README.md, THIRD-PARTY.txt, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/OpenDistroSecurityDeprecationHandler.java, src/test/java/com/amazon/opendistroforelasticsearch/security/HttpIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/resources/log4j2-test.properties
Tests:
All Unit Tests Have Passed
Integration Tests Passes
=>  Support for Elasticsearch 6.6.2

README.md
Fix artifact Id.
```
[root@4d35d3779771 elasticsearch]# bin/elasticsearch-plugin install -b com.amazon.opendistroforelasticsearch:opendistro_security:0.8.0.0
-> Downloading com.amazon.opendistroforelasticsearch:opendistro_security:0.8.0.0 from maven central
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission /proc/sys/net/core/somaxconn#plus read
* java.lang.RuntimePermission accessClassInPackage.com.sun.jndi.ldap
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessClassInPackage.sun.nio.ch
* java.lang.RuntimePermission accessClassInPackage.sun.security.x509
* java.lang.RuntimePermission …
```
=> Fix Maven Artifact Id in README

securityconfig/elasticsearch.yml.example
https://github.com/opendistro-for-elasticsearch/security/issues/41
=> Correcting config parameter name in example config

plugin-descriptor.properties, pom.xml
- Support for Elasticsearch 7.1
- No major changes
- Version upgrade in pom file
- All Unit Tests Passed
=> Support for Elasticsearch 7.1

plugin-descriptor.properties, pom.xml
* Support for Elasticsearch 7.1
* No major changes
* Version upgrade in pom file
=> Support for Elasticsearch 7.1 (#64)

src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java
Log the information of the first challenge authentication method for debugging authentication configuration error.
=> add log information for configuration error

src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java
Reverts opendistro-for-elasticsearch/security#79
=> Revert "add log information for configuration error"

pom.xml, securityconfig/roles.yml, securityconfig/roles_mapping.yml
Ran unit tests jenkins and all passed.
=> Adding Kibana readonly role

pom.xml
=> Bumping subversion 1.1.0.1

opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
Update subversion tags.
[INFO]
[WARNING] Tests run: 207, Failures: 0, Errors: 0, Skipped: 22
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ opendistro_security ---
[INFO] Building jar: /Opendistro/security/target/opendistro_security-1.1.0.2.jar
[INFO]
[INFO] --- git-commit-id-plugin:2.2.6:validateRevision (validate-the-git-infos) @ opendistro_security ---
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:test-jar (default) @ opendistro_security ---
[INFO] Building jar: /Opendistro/security/target/opendistro_security-1.1.0.2-tests.jar
[INFO]
[INFO] Installing /Opendistro/security/target/opendistro_security-1.1.0.2.jar to …
=> Bumping subversion 1.1.0.2

securityconfig/elasticsearch.yml.example, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityIndexSearcherWrapper.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/OpenDistroProtectedIndexAccessEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ReflectionHelper.java, src/test/java/com/amazon/opendistroforelasticsearch/security/protected_indices/ProtectedIndicesTests.java, src/test/resources/config_protected_indices.yml, src/test/resources/internal_users_protected_indices.yml, src/test/resources/roles_mapping_protected_indices.yml, src/test/resources/roles_protected_indices.yml
Back porting PR #126 to opendistro-0.9
```
[INFO] 
[INFO] 
[WARNING] Tests run: 132, Failures: 0, Errors: 0, Skipped: 4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14:45 min
[INFO] Finished at: 2019-09-06T09:25:49-07:00
[INFO] ------------------------------------------------------------------------
```
```
[INFO] 
[INFO] 
[WARNING] Tests run: 551, Failures: 0, Errors: 0, Skipped: 5
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:34 …
```
=> Protected index 0.9

securityconfig/elasticsearch.yml.example, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityIndexSearcherWrapper.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/OpenDistroProtectedIndexAccessEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ReflectionHelper.java, src/test/java/com/amazon/opendistroforelasticsearch/security/protected_indices/ProtectedIndicesTests.java, src/test/resources/config_protected_indices.yml, src/test/resources/internal_users_protected_indices.yml, src/test/resources/roles_mapping_protected_indices.yml, src/test/resources/roles_protected_indices.yml
Back porting PR #126 to opendistro-0.10
```
[INFO] 
[INFO] 
[WARNING] Tests run: 132, Failures: 0, Errors: 0, Skipped: 4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:51 min
[INFO] Finished at: 2019-09-06T10:34:58-07:00
[INFO] ------------------------------------------------------------------------
```
```
[INFO] 
[INFO] 
[WARNING] Tests run: 551, Failures: 0, Errors: 0, Skipped: 5
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:27 …
```
=> Protected index 0.10

opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
Update subversion tags.
[INFO]
[WARNING] Tests run: 132, Failures: 0, Errors: 0, Skipped: 4
[INFO]
[INFO]
[INFO] Building jar: /Opendistro/security/target/opendistro_security-0.10.0.2.jar
[INFO]
[INFO]
[INFO] Building jar: /Opendistro/security/target/opendistro_security-0.10.0.2-tests.jar
[INFO]
[INFO] Installing /Opendistro/security/target/opendistro_security-0.10.0.2.jar to …
=> Bumping subversion 0.10.0.2

opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
Update subversion tags.
[INFO]
[WARNING] Tests run: 132, Failures: 0, Errors: 0, Skipped: 4
[INFO]
[INFO]
[INFO] Building jar: /Opendistro/security/target/opendistro_security-0.9.0.3.jar
[INFO]
[INFO]
[INFO] Building jar: /Opendistro/security/target/opendistro_security-0.9.0.3-tests.jar
[INFO]
[INFO] Installing /Opendistro/security/target/opendistro_security-0.9.0.3.jar to …
=> Bumping subversion 0.9.0.3

plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/http/netty/OpenDistroSecuritySSLNettyHttpServerTransport.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java
Support for Opendistro-1.2
Run UT result:
[INFO]
[INFO]
[WARNING] Tests run: 174, Failures: 0, Errors: 0, Skipped: 22
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ opendistro_security ---
[INFO] Building jar: /Opendsitro/tc-security-1.2-3/security/target/opendistro_security-1.2.0.0.jar
[INFO]
[INFO] --- git-commit-id-plugin:2.2.6:validateRevision (validate-the-git-infos) @ opendistro_security ---
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:test-jar (default) @ opendistro_security ---
[INFO] Building jar: /Opendsitro/tc-security-1.2-3/security/target/opendistro_security-1.2.0.0-tests.jar
[INFO]
[INFO] Installing …
=> Support for ES 7.2.0

opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
Update pom file and release notes.
[INFO]
[WARNING] Tests run: 128, Failures: 0, Errors: 0, Skipped: 4
[INFO]
[INFO]
[INFO] Building jar: /Opendistro/security/target/opendistro_security-0.9.0.4.jar
[INFO]
[INFO]
[INFO] Building jar: /Opendistro/security/target/opendistro_security-0.9.0.4-tests.jar
[INFO]
[INFO] Installing /Opendistro/security/target/opendistro_security-0.9.0.4.jar to …
=> Bumping subversion 0.9.0.4

opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
[INFO]
[WARNING] Tests run: 203, Failures: 0, Errors: 0, Skipped: 22
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ opendistro_security ---
[INFO] Building jar: /Opendistro/security/target/opendistro_security-1.2.1.0.jar
[INFO]
[INFO] --- git-commit-id-plugin:2.2.6:validateRevision (validate-the-git-infos) @ opendistro_security ---
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:test-jar (default) @ opendistro_security ---
[INFO] Building jar: /Opendistro/security/target/opendistro_security-1.2.1.0-tests.jar
[INFO]
[INFO] Installing /Opendistro/security/target/opendistro_security-1.2.1.0.jar to /root/.m2/repository/com/amazon/opendistroforelasticsearch/opendistro_security/1 …
=> Support for ES 7.2.1

src/main/java/com/amazon/opendistroforelasticsearch/security/NonValidatingObjectMapper.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationLoaderSecurity7.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/SecurityDynamicConfiguration.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java
Instead of using security_admin tool, use validate and migrate APIs to do the migration.
=> Fixing configuration migration in version upgrade

.github/workflows/ci.yml, README.md
Integrating CI workflow with Github actions.
This workflow will be triggered for any pull request or push to master branch.
Workflow will run only after it is merged to master. 
Tasks which will be implemented in future PRs
- Checkstyle enforcement
Tasks not implemented yet due to approvals
- Codecov code coverage with Jacoco 
Testing:
https://github.com/sujithvm/security/commit/45ce53e2122ab37862a5a1f0e3719360d9795a47/checks?check_suite_id=354132934
=> CI workflow with Github Actions

.github/workflows/ci.yml, README.md, pom.xml
Add support for code coverage using codecov
=> Add support for codecov coverage

opendistro-elasticsearch-security.release-notes, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuthTokenProcessorAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/Endpoint.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/FlushCacheApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityConfigAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityRestApiActions.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantsApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/support/Utils.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AccountValidator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/CredentialsValidator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/InternalUsersValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluatorTest.java, src/test/resources/restapi/internal_users.yml, tools/install_demo_configuration.sh
Support for Elasticsearch 7.4.2
- New API to fetch and update account details (currently used for password update)
- Fix bug in demo install script to correctly configure when deb/rpm installs are present
=> Update 1.4.0.0 release branch

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuthTokenProcessorAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/Endpoint.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/FlushCacheApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityConfigAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityRestApiActions.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantsApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/support/Utils.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AccountValidator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/CredentialsValidator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/InternalUsersValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluatorTest.java, src/test/resources/restapi/internal_users.yml
=> Add Account API to enable users to change their own password

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuthTokenProcessorAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/Endpoint.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/FlushCacheApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityConfigAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityRestApiActions.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantsApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/support/Utils.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AccountValidator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/CredentialsValidator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/InternalUsersValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluatorTest.java, src/test/resources/restapi/internal_users.yml
Backporting change password api
=> Opendistro 1.2

pom.xml
Reference: https://central.sonatype.org/pages/requirements.html
=> Add url to pom.xml for maven central uploads

src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java
* Tested with ODFE7.4
* Sanity tested for security plugin
=> Removed OpenSSL for 7.4

.github/workflows/cd.yml, .github/workflows/ci.yml, build.gradle
- Create deploy to S3 bucket and invalidate cloud front distribution (zip, deb and rpm) 
- Create github draft release (need to update release notes) 
- Upload to workflow artifacts
=> Fix 7.5.2 version in build gradle and add CD workflow

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
opendistro-1.3 version bump from 1.3.0.1 to 1.3.0.2
=> opendistro-1.3 version bump from 1.3.0.1 to 1.3.0.2

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
opendistro-1.4 version bump from 1.4.0.0 to 1.4.0.1
=> opendistro-1.4 version bump from 1.4.0.0 to 1.4.0.1

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
*Description of changes:* Bumping version
=> Version bump 1.5.0.1

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
*Description of changes:* Bumping version to 0.9.0.6
=> Version bump 0.9.0.6

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
*Description of changes:* Bumping version to 1.0.0.5
=> Version bump 1.0.0.5

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
*Description of changes:* Bumping opendistro-1.2 version 
=> Version bump 1.2.1.2

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
*Description of changes:* Bumping version
=> Version bump 0.10.1.1

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java
Code for checking permission match was very contrived and hidden a big performance problem we have spotted in our installation for log analytics.
In short getResolvedIndexPattern method is very costly as it goes to ElasticSearch Metadata store takes the tree map of _all_ of indices/aliases and elaborately filters things out, then it proceeds to extract aliases and more. 
In the original code this method is called for every matching index times every index pattern. In our system we have long series of rotated indices so it might be why we have triggered this problem.
Another optimization is to avoid creating temporary hash sets with complicated logic and translate the whole code to a combination of a few nested matchAll + matchAny algorithms.
Does it all matter ? Yes, in our case …
=> [Optimization] Implement faster version of implies type perm

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/support/SnapshotRestoreHelper.java, src/test/java/com/amazon/opendistroforelasticsearch/security/http/proxy/HTTPExtendedProxyAuthenticatorTest.java
=> Support ES 7.6.1

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV6.java
ES 6.x security plugin model is supported by ES 7.x security plugin in read-only mode. Implemented similar optimization as what was done for 7.x security model
=> [Optimization] Port faster version of implies type perm (00da48ae557c00719cd5ed947d87e40344989c41) to 6.x security model

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
Refactoring and micro-optimizations part of:
https://github.com/opendistro-for-elasticsearch/security/pull/258
=> Refactor Resolved class, drop unused fields and simplify logic

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/Hashed.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
=> Security 1.4.0.2 changes

.github/workflows/cd.yml, .github/workflows/ci.yml, build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/Hashed.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
=> Security 1.1.0.6 changes 

.github/workflows/cd.yml, .github/workflows/ci.yml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/Hashed.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
=> Cherry pick commits from master to 1.6 branch

.github/workflows/cd.yml, .github/workflows/ci.yml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/Hashed.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
=> Cherry pick commits from master to 1.5 branch

.github/workflows/ci.yml, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
=> Cherry pick commits from master to 1.4 branch

.github/workflows/ci.yml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/Hashed.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
=> Cherry pick commits from master to 1.3 branch

.github/workflows/cd.yml, .github/workflows/ci.yml, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/SSLAuditlogTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java
=> Cherry pick commits from master to 0.9 branch

.github/workflows/cd.yml, .github/workflows/ci.yml, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/SSLAuditlogTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java
=> Cherry pick commits from master to 0.10 branch

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
Changes:
- Fix for updating password without deleting roles
=> Security 0.10.1.2 changes

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
=> Security 0.9.0.7 changes

.github/workflows/ci.yml, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/SSLAuditlogTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java
=> More cherry pick commits from master to 1.6 branch

.github/CODEOWNERS
*Issue #, if available: n/a
*Description of changes: utilize [CODEOWNERS](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)
=> Use CODEOWNERS to automate PR review requests

.github/workflows/cd.yml, .github/workflows/ci.yml, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/SSLAuditlogTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java
=> More cherry pick commits from master to 1.1 branch 

.github/CODEOWNERS
=> Fixed CODEOWNERS

README.md
* Updating feature description post repo merging 
* Grouping them under categories.
=> Updating readme post Advanced Module repo deprication

.github/CODEOWNERS, .github/workflows/cd.yml, .github/workflows/ci.yml
=> Backport CODEOWNERS and CI changes to 1.5

.github/CODEOWNERS, .github/workflows/cd.yml, .github/workflows/ci.yml
=> Backport CODEOWNERS and CI changes to 0.9

.github/CODEOWNERS, .github/workflows/cd.yml, .github/workflows/ci.yml
=> Backport CODEOWNERS and CI changes to 1.6

src/main/assemblies/plugin.xml, src/main/assemblies/securityadmin-standalone.xml
Backport of PR: https://github.com/opendistro-for-elasticsearch/security/pull/386
=> Changing file permissions for securityconfig and tools

src/main/assemblies/plugin.xml, src/main/assemblies/securityadmin-standalone.xml
Cherry picked from commit 5f28e80
*Description of changes:* Backport of PR #386 
=> Changing file permissions for securityconfig and tools.

README.md
=> [DONT REVIEW] Testing a automated workflow in a test branch "backport"

README.md
=> [Dont merge] Testing a PR workflow in a separate branch

src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java
*Issue #, if available: Avoid changing logger configuration during tests
*Description of changes:
=> Do not shutdown logger context during Node close

build.gradle, opendistro-elasticsearch-security.release-notes, plugin-descriptor.properties, pom.xml
Supporting ES: 7.6.1 (same as plugin version 1.6.0.0)
Changes:
- Implemented APIs and datamodel to configure nodes_dn dynamically #445 (backported from master #362)
- Performance improvement by memorizing results of resolveIndexPatterns for Bulk requests (backported from master #309)
- Performance improvement by implementing faster version of implies type perm #302
- Enabled limited OpenSSL support
- Changed file permissions for securityconfig and tools #387
- Fixed bug which caused user to lose roles on account password update #333
- Refactored to use Greenrobot EventBus #445 (backported from master #370)
- Refactored Resolved class, dropped unused fields and simplified logic (backported from master #310)
- Refactored audit logging related classes #445 (backported from master #303, #445, …
=> Version bump 1.7.0.0

build.gradle
1.8 branch needs to be updated with the latest changes from the master
=> Sync 1.8 branch with master

build.gradle
=> Use 'elasticsearch' for the group during rpm/deb installation (pull from master)

src/main/java/com/amazon/opendistroforelasticsearch/security/support/Base64Helper.java, src/test/java/com/amazon/opendistroforelasticsearch/security/support/Base64HelperTest.java
- introduced SafeObjectOutputStream to catch unauthorized serializations
- introduced Base64HelperTest
=> Refactor Base64Helper class

plugin-security.policy, src/main/java/com/amazon/opendistroforelasticsearch/security/support/Base64Helper.java
=> Check for substitute permissions before attempting to use SafeObjectOutputStream

src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java
There are some typos in this file so I modified it from "reqested" to "requested"
*Issue #, if available: Some typos are exist.
*Description of changes: Modified it from "reqested" to "requested"
=> Fix typo in DefaultOpenDistroSecurityKeyStore.java

build.gradle, plugin-descriptor.properties, pom.xml
=> Support ES 7.7.1

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityFlsDlsIndexSearcherWrapper.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ReflectionHelper.java
=> Avoid using reflection to instantiate OpenDistroSecurityFlsDlsIndexSearcherWrapper

src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigHelper.java
Use case: If you want to include new config file (say audit.yml for audit logging configuration) to a cluster (which already contains opendistro index), then it loads new config file to an existing index.
Current behavior:
- If opendistro index does not exist (run CreateIndexRequest)
- Create a new index 
- Load the security config files
- if opendistro index exists (run CreateIndexRequest)
- throw exception and skips trying to load any security config files
Proposed behavior:
- check if opendistro index exists (run GetIndexRequest)
- if does not exist, create index using CreateIndexRequest
- try to load any security config into the index using IndexRequest with optype set to Create for put if absent behavior
- if doc already exists (throw VersionConflictEngineException) do nothing as …
=> Implement put if absent behavior for security config

build.gradle, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ClusterInfoHolder.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationLoaderSecurity7.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/SnapshotRestoreHelper.java, src/main/java/com/amazon/opendistroforelasticsearch/security/tools/OpenDistroSecurityAdmin.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/BasicAuditlogTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java
Upgrade ES version to 7.8.0 and plugin version to 1.9.0
=> Upgrade ES to 7.8.0

pom.xml
Changed the maven endpoint URL used for deployement
=> Update Maven endpoint URL

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java
- `clusterService.state().metaData().hasConcreteIndex(opendistrosecurityIndex)` checks if index exists with a cached copy and it incorrectly determines index is absent especially when the cluster bootstraps. 
- Removed the above check as its incorrectly functioning.
- added a try, catch around index creation to capture index/resource exists exception
- Updated log statements 
- Same behavior as we currently have
=> Remove the faulty index exists check and have more predictable behavior

release-notes/opendistro-for-elasticsearch.security.release-notes-1.9.0.0.md
=> Update release notes for v1.9.0.0

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditCategory.java, src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java
=> AuditConfig and AuditCategory minor refactoring

src/main/java/com/amazon/opendistroforelasticsearch/security/DefaultObjectMapper.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceConfig.java
=> Support "true" and "false" String to boolean conversion in DefaultObjectMapper.getOrDefault()

README.md
Fix 404 when clicking on link in Readme to navigate to Opendistro documentation
=> fix broken link to security configuration page

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java
*Description of changes:* Fixed failing NodesDnApiTest#testNodesDnApi test
=> Fix failing NodesDnApiTest#testNodesDnApi

pom.xml
=> Upgrade Apache CXF to 3.2.14

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuditApiAction.java
- Using TypeReference is giving a runtime error which is not when run as part of unit test process.
```
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
at java.security.AccessController.checkPermission(AccessController.java:897) ~[?:?]
at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
at java.lang.Class.checkMemberAccess(Class.java:2847) ~[?:?]
at java.lang.Class.getDeclaredConstructors(Class.java:2355) ~[?:?]
```
- Issue does not occur in 7.7.x, 7.8.x https://github.com/opendistro-for-elasticsearch/security/blob/master/src/main/java/com/amazon/opendistroforelast …
=> Fix readonly type reference read

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/PatchableResourceApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigFactory.java, src/test/java/com/amazon/opendistroforelasticsearch/security/OpendistroSecurityRolesTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/resources/restapi/roles.yml
*Description of changes:* Cherry pick changes for opendistro_security_roles fixes.
=> Opendistro 1.8

pom.xml
=> Upgrade Apache Kafka Client to 2.5.0

pom.xml
- upgrade Apache Commons Codec to 1.14
- upgrade Apache Santuario to 2.2.0
=> Upgrade Onelogin Java SAML to 2.5.0

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AbstractAuditLog.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/BasicAuditlogTest.java
- Log request method also in the audit message eg: POST, PUT, GET, DELETE ...
- Minor refactor to consolidate logic for adding rest request info
- Added tests 
=> Add rest method to audit logging

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceConfig.java
PR #588 Included changes from PR #591  which was unintended. 
Reverting the changes
=> Revert unintended changes

pom.xml
=> Upgrade Bouncy Castle to 1.66

pom.xml, src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
- upgrade cryptacular to 1.1.4
=> Upgrade OpenSAML SAML Provider Implementations to 3.4.5

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opendistro-for-elasticsearch.security.release-notes-1.9.0.1.md
=> Change version to 1.9.0.1

pom.xml, src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
=> Backport to opendistro-1.7

pom.xml
=> Upgrade jackson-databind to 2.11.2

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigFactory.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModel.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV7.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/RoleMappings.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/SecurityDynamicConfiguration.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/RoleMappingsV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/RoleMappingsV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/OpendistroSecurityRolesTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/GetConfigurationApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantInfoActionTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/resources/restapi/roles.yml, src/test/resources/restapi/roles_mapping.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
=> Backport Opendistro 1.8

README.md
*Issue #, if available:*#610
Under the section "Features provided by Security", there is a subtitle "Audit/Complaince logging:". The word "Complaince" looks like a typo. This PR is to fix the typo.
=> Correct a typo in the Readme file.

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AuditValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessageTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuditApiActionTest.java
=> Backport Opendistro 0.10

pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/TracingTests.java
*Description of changes:* Encapsulate logic of `opendistro_security_action_trace` Logger
=> Refactor opendistro_security_action_trace logger

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AuditValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessageTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuditApiActionTest.java
=> Backport Opendistro 0.9

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AuditValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessageTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuditApiActionTest.java
=> Backport Opendistro 1.1

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AuditValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessageTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuditApiActionTest.java
=> Backport Opendistro 1.4

pom.xml, src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java, src/main/java/com/amazon/dlic/auth/http/saml/Saml2SettingsProvider.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java, src/test/java/com/amazon/dlic/auth/http/saml/MockSamlIdpServer.java
=> Backport to opendistro-1.8

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/ThreadPoolConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditCategory.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/compliance/ComplianceConfigTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfigFilterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfigSerializeTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/ThreadPoolConfigTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditCategoryTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessageTest.java
=> Add copyright headers

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AbstractAuditLog.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditlogTest.java
- Check enabled/disabled for all categories for REST & Transport
- Added unit tests 
=> Enabled or disable for all categories

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditLogImpl.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
=> Pulling latest changes to opendistro-1.9

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/WhitelistApiTest.java
Do not expose exception details in responses as it may contain code & line references.
=> Remove exception details from responses

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
(cherry picked from commit a4f7645f01f7e9e9e6e5265415e64cfed869370d)
=> Backport: opendistro-1.4 - Remove exception details from responses

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/WhitelistApiTest.java
(cherry picked from commit 0ad31b04f6666b4b9d1e66926f0a13fc4e211989)
=> Backport: opendistro-1.9 - Remove exception details from responses (#667)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
(cherry picked from commit a4f7645f01f7e9e9e6e5265415e64cfed869370d)
=> Backport: opendistro-1.8 - Remove exception details from responses

build.gradle, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityFlsDlsIndexSearcherWrapper.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/http/OpenDistroSecurityHttpServerTransport.java, src/main/java/com/amazon/opendistroforelasticsearch/security/http/OpenDistroSecurityNonSslHttpServerTransport.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/http/netty/OpenDistroSecuritySSLNettyHttpServerTransport.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLNettyTransport.java, src/test/java/com/amazon/opendistroforelasticsearch/security/http/proxy/HTTPExtendedProxyAuthenticatorTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/plugin/UserInjectorPlugin.java
=> Support ES 7.9.0

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opendistro-for-elasticsearch.security.release-notes-1.10.0.0.md
=> Add release notes. Change version to 1.10.0.0.

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
(cherry picked from commit a73967242bcb8aa0d92d59e3c2682e60b4bd75d7)
=> Adding onelogin loadXML util helper to prevent XXE attacks

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opendistro-for-elasticsearch.security.release-notes-1.9.0.2.md
=> Change version to 1.9.0.2

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/BasicAuditlogTest.java
(cherry picked from commit c6c53e8b7221e85998a3d1e0b4642f8c66edf680)
=> Backport opendistro-0.10

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/BasicAuditlogTest.java
(cherry picked from commit c6c53e8b7221e85998a3d1e0b4642f8c66edf680)
=> Backport opendistro-0.9

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/BasicAuditlogTest.java
(cherry picked from commit c6c53e8b7221e85998a3d1e0b4642f8c66edf680)
=> Backport opendistro-1.9

src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/rest/OpenDistroSecuritySSLCertsInfoAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/rest/OpenDistroSecuritySSLReloadCertsAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLCertsInfoActionTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLReloadCertsActionTests.java
=> Adding copyright to cert reload files

pom.xml
https://github.com/opendistro-for-elasticsearch/opendistro-infra/issues/251
This PR is to update pom.xml to support ODFE 1.10.1
=> Update pom.xml to support ODFE 1.10.1

pom.xml
=> Upgrade Apache CXF to 3.4.0

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java, src/test/resources/saml/metadata.xml
(cherry picked from commit f223ba66810db516b3a1569481b02c6b0a0aa005)
=> Removing newline whitespace from metadata content

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6Test.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7Test.java
=> Backport to opendistro-1.9

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6Test.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7Test.java
=> Backport to opendistro-1.6

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6Test.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7Test.java
=> Backport to opendistro-1.5

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6Test.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7Test.java
=> Backport to opendistro-1.4

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6Test.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7Test.java
=> Backport to opendistro-1.3

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6Test.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7Test.java
=> Backport to opendistro-1.2

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6Test.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7Test.java
=> Backport to opendistro-1.0

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6Test.java, src/test/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7Test.java
=> Backport to opendistro-1.1

pom.xml
=> Generate SHA-512 checksum for opendistro_security .zip only (exclude securityadmin-standalone)

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opendistro-for-elasticsearch-security.release-notes-1.11.0.0.md
Preparing for ODFE 1.11.0.0 release
=> Change version to 1.11.0.0

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/DualModeSSLHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLNettyTransport.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/util/SSLConnectionTestResult.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/util/SSLConnectionTestUtil.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/util/TLSUtil.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/test/java/com/amazon/opendistroforelasticsearch/security/EncryptionInTransitMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/DualModeSSLHandlerTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/util/SSLConnectionTestUtilTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/util/TLSUtilTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java
* Adding SSL dual mode support for SSLOnly
(cherry picked from commit 27f33fb)
Co-authored-by: Vengadanathan Srinivasan <vengadan@amazon.com>
=> Adding support for SSL dual mode (#712)

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java
Backport of: Add user & roles to the thread context
Backport of: Add user & roles to the thread context
=> Backport of: Add user & roles to the thread context

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/PrivilegesInterceptorImpl.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluatorResponse.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesInterceptor.java, src/test/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/multitenancy/test/MultitenancyTests.java
=> Backport to opendistro-0.9

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/PrivilegesInterceptorImpl.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluatorResponse.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesInterceptor.java, src/test/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/multitenancy/test/MultitenancyTests.java
=> Backport to opendistro-0.10

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/PrivilegesInterceptorImpl.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluatorResponse.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesInterceptor.java, src/test/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/multitenancy/test/MultitenancyTests.java
=> Backport to opendistro-1.10

pom.xml
=> Upgrade junit to 4.13.1

src/main/resources/static_config/static_roles.yml
updating static_roles.yml
removing some cluster permissions
removing some cluster permissions
=> updating static_roles.yml

securityconfig/elasticsearch.yml.example, securityconfig/roles.yml, tools/install_demo_configuration.sh
Added system index configuration for reporting and notification plugin
Added default roles configuration required for reporting functionality
Updated demo config and example with above system index configurations
=> Security configuration for reporting and notification plugins

legacy/securityconfig_v6/roles.yml, src/main/resources/static_config/static_roles.yml, src/test/resources/cache/roles.yml, src/test/resources/legacy/securityconfig_v6/migration/roles.yml, src/test/resources/legacy/securityconfig_v6/roles.yml, src/test/resources/multitenancy/roles.yml, src/test/resources/roles.yml
*Description of changes:* 
Removing unnecessary permission from security configuration and test resources. 
=> Security configuration cleanup for static and test resources

legacy/securityconfig_v6/roles.yml, src/main/resources/static_config/static_roles.yml, src/test/resources/cache/roles.yml, src/test/resources/legacy/securityconfig_v6/roles.yml, src/test/resources/multitenancy/roles.yml, src/test/resources/roles.yml
Security configuration cleanup for static and test resources (#838 #841)
(cherry picked from commit b65b547d3f21e2318497b040bf97f57e5d109d0d and b65b547d3f21e2318497b040bf97f57e5d109d0d)
=> Security configuration cleanup for static and test resources (#838 #841)

legacy/securityconfig_v6/roles.yml, src/main/resources/static_config/static_roles.yml, src/test/resources/cache/roles.yml, src/test/resources/legacy/securityconfig_v6/migration/roles.yml, src/test/resources/legacy/securityconfig_v6/roles.yml, src/test/resources/multitenancy/roles.yml, src/test/resources/roles.yml
Security configuration cleanup for static and test resources  #838 #841
Cherry picked from commit b65b547d3f21e2318497b040bf97f57e5d109d0d and b65b547d3f21e2318497b040bf97f57e5d109d0d
=> Security configuration cleanup for static and test resources #838 #841

legacy/securityconfig_v6/roles.yml, src/main/resources/static_config/static_roles.yml, src/test/resources/cache/roles.yml, src/test/resources/legacy/securityconfig_v6/migration/roles.yml, src/test/resources/legacy/securityconfig_v6/roles.yml, src/test/resources/multitenancy/roles.yml, src/test/resources/roles.yml
Security configuration cleanup for static and test resourcesa (#838 #841)
(cherry picked from commit b65b547d3f21e2318497b040bf97f57e5d109d0d and b65b547d3f21e2318497b040bf97f57e5d109d0d)
=> Security configuration cleanup for static and test resourcesa (#838 #841)

legacy/securityconfig_v6/roles.yml, src/main/resources/static_config/static_roles.yml, src/test/resources/cache/roles.yml, src/test/resources/legacy/securityconfig_v6/migration/roles.yml, src/test/resources/legacy/securityconfig_v6/roles.yml, src/test/resources/multitenancy/roles.yml, src/test/resources/roles.yml
Security configuration cleanup for static and test resources #841 
Cherry picked from commit b65b547d3f21e2318497b040bf97f57e5d109d0d and b65b547d3f21e2318497b040bf97f57e5d109d0d
=> Security configuration cleanup for static and test resources #841 

legacy/securityconfig_v6/roles.yml, src/main/resources/static_config/static_roles.yml, src/test/resources/cache/roles.yml, src/test/resources/legacy/securityconfig_v6/roles.yml, src/test/resources/multitenancy/roles.yml, src/test/resources/roles.yml
Security configuration cleanup for static and test resources #838  #841
Cherry picked from commit b65b547 and b65b547
=> Security configuration cleanup for static and test resources #838 #841 

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auth/UserInjector.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/Base64Helper.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/test/java/com/amazon/opendistroforelasticsearch/security/TransportUserInjectorIntegTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auth/UserInjectorTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilterTest.java, src/test/resources/roles_transport_inject_user.yml
*Supports user injection for transport requests:*
=> Support user injection for transport requests

build.gradle, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/DlsFlsFilterLeafReader.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/DlsFlsRequestValve.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/DlsFlsValveImpl.java, src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTermsGetter.java, src/test/java/com/amazon/opendistroforelasticsearch/security/TransportClientIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/dlsfls/CustomFieldMaskedTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/dlsfls/FieldMaskedTest.java
=> Support ES 7.10.0

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opendistro-for-elasticsearch-security.release-notes-1.12.0.0.md
=> Change version to 1.12.0.0

.github/workflows/cd.yml
=> Upgrade github CD action to using Environment Files

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java
=> Refactor getUserInfoString

release-notes/opendistro-for-elasticsearch-security.release-notes-1.12.0.0.md
=> Update 1.12 release notes

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/test/java/com/amazon/opendistroforelasticsearch/security/IndexIntegrationTests.java
=> Catch and respond invalid_index_name_exception when an index with invalid name is mentioned

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java
(cherry picked from commit f382a820ad8512c878a1eaa85bf604e2d4aa4b7d)
=> Fix for java.io.OptionalDataException that is caused by changes to User object after it is put on thread context. (#869)

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
=> Use StringJoiner instead of (Immutable)List builder

.github/pull_request_template.md
Creating template for pull request.
*Issue #, if available:* ~None~ 
Creating template for pull request. It will add pull request intake form for Security plugin.  Idea behind creating this template is for asking community members to provide as much details as possible about changes. 
Please suggest any additional/missing questions for this template. 
=> Pull request intake form (PR template)

.github/pull_request_template.md
Maintenance
2. __Github Issue # or roaddmap entry, if available:__
N/A
Fixing some typos and formatting 
Template is shown in every PR and has some typos
5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screenshot if avaialble_)
No change in behavior
6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manaual testing_) 
No change to code
7. __TO-DOs, if any:__ (_Please describe pending items and provide github issues# …
=> Fix typos in template

src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auth/UserInjector.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/Base64Helper.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auth/UserInjectorTest.java
1. __Category:__ bug fix
2. __Github Issue # or roaddmap entry, if available:__
3. __Description of changes:__ 
4. __Why these changes are required?__ support for mixed cluster
5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screenshot if avaialble_)
6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manaual testing_) 
7. __TO-DOs, if any:__ (_Please describe pending items and provide github issues# for each of them)
By submitting this pull request, I confirm that you can use, modify, copy, and …
=> Replace InjectedUser with User during serialization

pom.xml
1. __Category:__ Maintenance
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> Upgrade Bouncy Castle to 1.67

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java
*Add user and roles to the thread context*
(cherry pick from ca90ce9)
*Adding requested tenant to the thread context transient info for consumption*
(cherry picked from commit 7131b6a)
*Fix for java.io.OptionalDataException that is caused by changes to User object after it is put on thread context*
(cherry picked from commit f382a82)
*Use StringJoiner instead of (Immutable)List builder*
(cherry picked commit from b710ac7)
=> Add user & roles to the thread context  (#798)

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
Refactoring
N/A
- Currently whenever we access Resolved class members, we return a new unmodified list creating new objects. Some of these class functions are accessed a number of times.
- Avoid creating new objects every time getter is called.
- No changes in behavior
6. __Testing done:__ (_Please provide details of testing done: Unit …
=> Optimize creating new collection objects in IndexResolverReplacer

pom.xml
=> Backport to opendistro-1.11

src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/util/TLSUtilTests.java
Maintenance 
Replacing writeByte with writeShort in TLSUtilTests to avoid the test failures on CI.
No behavior changes. …
=> Replace writeByte with writeShort in TLSUtilTests

.github/workflows/ci.yml
1. __Category:__  Maintenance
3. __Description of changes:__ enable github codeql analysis
By submitting this pull request, I confirm that you can use, modify, copy, …
=> Integrate Github CodeQL Analysis into CI

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java
1. __Category:__ Enhancement/Maintenance
1. __Github Issue # or road-map entry, if available:__
1. __Description of changes:__ Implement `SystemIndexPlugin` interface
1. __Why these changes are required?__ Comply with ES system indices
1. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
1. __Testing done:__ UT
1. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)
1. __Is it backport from master branch?__ (_If yes, please add backport PR # and commits #_)
=> Support for ES system index

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java
1. __Category:__ Bug fix
2. __Github Issue # or road-map entry, if available:__ #879
3. __Description of changes:__ include only modified config CType into `ConfigUpdateRequest`
4. __Why these changes are required?__ it is not necessary to reload configs not modified as part of PATCH request
5. __What is the old behavior before changes and new behavior after changes?__ all config CTypes are reloaded (even ones that were not modified/updated)
6. __Testing done:__ UT
7. __TO-DOs, if any:__ 
=> ConfigUpdateRequest should include only updated CType

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.11)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.9)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.8)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.10)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.7)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.6)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.5)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.4)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.3)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.2)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.1)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
=> ConfigUpdateRequest should include only updated CType (backport to opendistro-1.0)

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
(cherry picked from commit a629421fe4cf207d5d13613370211d2d28a578c4)
8. __Is it backport from master branch?__ (_If yes, …
=> Using SAML subject_key and roles_key in the HTTPSamlAuthenticator

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/HttpIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/IntegrationTests.java, src/test/resources/internal_users.yml, src/test/resources/roles_bulk.yml, src/test/resources/roles_mapping.yml
- Enhancement (performance)
- N/A
- Short circuit bulk requests if tenant is not specified (default tenant)
- Skip index resolution
- Only evaluation that is done at top level is checking if the user has privileges to perform the request. Other evaluations are done in lower level in BulkShardRequest
- Performance improvement 
6. __Testing …
=> Short circuit privilege evaluation for bulk requests without index resolution

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
Maintenance
N/A
- Creating list even if index is null. 
- Cleanup
- Don't create object unnecessarily
Unit test
N/A
8. …
=> Cleanup single shard request index check

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
1. __Category:__ Refactoring
1. __Github Issue # or road-map entry, if available:__
1. __Description of changes:__ drop serializable from Resolved and refactor Resolved.Builder to use ImmutableSet.Builder
1. __Why these changes are required?__ improve code maintainability
1. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
1. __Testing done:__ UT
1. __TO-DOs, if any:__ 
1. __Is it backport from master branch?__ 
=> Refactor Resolved

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
Refactoring
Combine 2 different log messages of no cluster-level permission
Avoid redundant log messages and keep the log messages consistent in the class.
No behavior changes.
UT
7. __TO-DOs, if any:__ (_Please describe …
=> Combine log messages of no cluster-level permission

build.gradle, plugin-descriptor.properties, pom.xml
Maintenance
Support ES 7.10.2
ODFE 1.13 is required to support ES 7.10.2
UT
8. __Is it backport …
=> Support ES 7.10.2

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.0.0.md
Maintenance
Pump version to 1.13
Prepare for release 1.13
UT
8. __Is it backport from master …
=> Bump version to 1.13

.github/workflows/ci.yml, .github/workflows/release-drafter.yml, CONTRIBUTING.md, README.md
Maintenance
Update Github actions and files to use main branch.
This is a part of switching from master branch to main branch.
No changes in behavior.
UT 
7. __TO-DOs, if any:__ (_Please describe pending items and provide …
=> Updating Github actions and files to use main branch.

.github/pull_request_template.md
Maintenance
Add the Linux Foundation's Developer Certificate of Origin in pull request template
Add the Linux Foundation's Developer Certificate of Origin in pull request template
UT
7. __TO-DOs, if …
=> Add the Linux Foundation's Developer Certificate of Origin in pull request template

build.gradle
Maintenance
#1026
Change the build configuration for deb package and rename the folder of artifacts.
The current configuration will not support arm64
No changes in bahavior.
UT
7. __TO-DOs, if any:__ (_Please describe …
=> Change the build configuration for deb package and rename the folder of artifacts.

release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.0.0.md
Maintenance
Update release notes 1.13
Release 1.13 requires updated release notes.
UT
8. __Is it …
=> Update release notes 1.13

build.gradle
Maintenance
Fix release version to make it consistent with other odfe plugins
To make it consistent with other odfe plugins
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of …
=> Fix release version

securityconfig/elasticsearch.yml.example, securityconfig/roles.yml, tools/install_demo_configuration.sh
Bug fix
2. __Description of changes:__
Mismatch of action name and system index name between async search plugin and security plugin.
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, …
=> Fixed async search action names and system index

release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.0.0.md
Maintenance
Update releaes notes 1.13 with a new PR merged
Keep release notes up-to-date.
No changes in behavior.
UT
8. …
=> Update releaes notes 1.13

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/HttpIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/IntegrationTests.java, src/test/resources/internal_users.yml, src/test/resources/roles_bulk.yml, src/test/resources/roles_mapping.yml
Maintenance
Optimization
Unit testing
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and …
=> Backport opendistro-1.11

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV6.java, src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java, src/test/java/com/amazon/opendistroforelasticsearch/security/HttpIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/IntegrationTests.java, src/test/resources/internal_users.yml, src/test/resources/roles_bulk.yml, src/test/resources/roles_mapping.yml
Maintenance
N/A
Optimizations
Performance improvements
Unit tests
N/A …
=> Backport opendistro-1.4

release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.1.0.md
Maintenance
Update release notes for 1.13.1.0 release
1.13.1.0 release
No changes in bahavior
UT
8. __Is it backport from …
=> Update release notes 1.13.1

.github/workflows/ci.yml, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ClusterInfoHolder.java
Maintenance
- Consume OpenSearch 1.0.0-alpha1 tag to stablize the build
- MINOR: Remove a unused import from ClusterInfoHolder.java
Stablize the build with a stable upstream.
UT
7. __TO-DOs, if …
=> Consume OpenSearch 1.0.0-alpha1

.github/workflows/cd.yml, README.md, build.gradle, plugin-descriptor.properties, pom.xml, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/main/java/com/amazon/opendistroforelasticsearch/security/tools/AuditConfigMigrater.java, tools/install_demo_configuration.sh
Maintenance
- Rename prefix of plugin artifacts from `opendistro` to `opensearch` 
- Rename prefix of plugin folder name from `opendistro` to `opensearch`
- Change the plugin version from `1.15.0.0` to `1.0.0.0-beta1`
- Change the license header in build.gradle file
Migrate to OpenSearch
6. __Testing done:__ …
=> Change name and version of plugin

.github/workflows/ci.yml, README.md, build.gradle, plugin-descriptor.properties, pom.xml
Maintenance
Consume the latest version OpenSearch 1.0.0-alpha2
Make security plugin compatible with the latest version of OpenSearch
UT
7. __TO-DOs, if any:__ (_Please describe pending items and …
=> Build with OpenSearch 1.0.0-alpha2

.github/workflows/ci.yml, pom.xml
Maintenance
Built security plugin with the latest version of OpenSearch 1.0.0-beta1
Make security plugin support the latest version of OpenSearch 1.0.0-beta1
UT
7. __TO-DOs, if any:__ (_Please …
=> Build security plugin with OpenSearch 1.0.0-beta1

README.md, build.gradle, tools/install_demo_configuration.sh
Maintenance
Fix some echo messages and anchor links.
Echo messages should be consistent with OpenSearch naming convention.
Anchor links need to be fixed to accommodate the repo movement.
UT & Manual …
=> Fix echo messages and anchor links

release-notes/opensearch-security.release-notes-1.0.0.0-beta1.md
=> Update release note for OpenSearch Security Plugin 1.0.0.0-beta1

pom.xml
Maintenance
- `json-smart-2.3` is introduced by `json-path-2.4`
-  Upgrading `json-smart` to `2.4.2`. 
`json-smart` needs to be upgraded to `2.4.2` because of [this issue](https://github.com/netplex/json-smart-v1/issues/7).
6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration …
=> Force the version of json-path 2.4.0

src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java
- Bug
- N/A
- Removed redundant `isEmpty` check which is covered by `isNullOrEmpty`
- `escapedKid` cannot be null at the check as it is covered in `isNullOrEmpty` 
- Retaining log line and not publishing any key id in the logs
- Discovered issue in testing/code scan and recommended to use java equals in place of operator equals 
- No …
=> Remove redundant isEmpty check and incorrect string equals operator

securityconfig/opensearch.yml.example, securityconfig/whitelist.yml, tools/install_demo_configuration.sh
Documentation
Rename settings from opendistro_security to plugins.security in following files
`securityconfig/opensearch.yml.example`
`securityconfig/whitelist.yml`
`tools/install_demo_configuration.sh`
7. __TO-DOs, if …
=> Rename documents and demo for settings

.github/release-notes-drafter-config.yml, build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opensearch-security.release-notes-1.0.0.0-rc1.md
Maintenance
- Bump plugin version to 1.0.0.0-rc1
- Create release notes for 1.0.0.0-rc1
- Fix the url used in release notes drafter
1.0.0.0-rc1 Release
UT
7. __TO-DOs, if any:__ (_Please describe …
=> Bump version to rc1, create release notes and fix the url used in release notes drafter

README.md, securityconfig/internal_users.yml, src/main/java/org/opensearch/security/rest/DashboardsInfoAction.java, src/main/java/org/opensearch/security/support/ModuleType.java, src/main/resources/static_config/static_action_groups.yml
=> Dashboards rename related changes

.github/CODEOWNERS, release-notes/opensearch-security.release-notes-1.0.0.0-rc1.md
Maintenance
Change the owner in CODEOWNERS file
Migrate to OpenSearch
No changes in bahavior
UT
8. __Is it backport from …
=> Fix CODEOWNERS file

.github/workflows/ci.yml
Maintenance
Build [OpenSearch 1.0 branch](https://github.com/opensearch-project/OpenSearch/tree/1.0) on CI
OpenSearch cut a new branch 1.0 that is stable and will not have new features added.
UT
7. …
=> Build OpenSearch 1.0 branch on CI

tools/install_demo_configuration.sh
Maintenance
Rename opendistro_security to plugins.security
Manual testing
8. __Is it backport from main branch?__ (_If …
=> Fix install_demo_configuration.sh

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
Bug fix
e.g.
before:
'admin' role will be compared to the 'admin ' role and found to be equal.
after:
'admin' role is not equal to 'admin ' role.
UTs
7. __TO-DOs, if any:__ (_Please describe pending items and provide …
=> Do not trim SAML roles

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
=> [opendistro-1.13][backport] Do not trim SAML roles

.github/workflows/cd.yml, .github/workflows/ci.yml
=> Use JDK 14 for CI and CD (#1226)

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
Maintenance
Backport for #1207 
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits …
=> [opendistro-0.9][backport] Do not trim SAML roles

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
=> [opendistro-0.10][backport] Do not trim SAML roles

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
=> [opendistro-1.1][backport] Do not trim SAML roles

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
=> [opendistro-1.8][backport] Do not trim SAML roles

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
=> [opendistro-1.10][backport] Do not trim SAML roles

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
(cherry picked from commit 2ecb088a1ac58bd1ac4a0c1100492bc1566b9be7)
Maintenance
8. __Is it backport …
=> [opendistro-1.9][backport] Do not trim SAML roles

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
(cherry picked from commit 2ecb088a1ac58bd1ac4a0c1100492bc1566b9be7)
Maintenance
8. __Is it backport …
=> [opendistro-1.11][backport] Do not trim SAML roles

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
=> [opendistro-1.4][backport] Do not trim SAML roles

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/IndexBaseConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-0.9

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/IndexBaseConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-0.10

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.13

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.12

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.11

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.10

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.9

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.8

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.7

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.4

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153) and (#1154) to branch opendistro-1.1

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=>  Backport issue(#1153) and (#1154) to branch opendistro-1.3

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java
Yes,
- #517 and commit hash is …
=> Backport issue(#517) to branch opendistro-1.3

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153), (#1154) and (#517) to branch opendistro-1.2

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153), (#1154) and (#517) to branch opendistro-1.5

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/ConfigurationRepository.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/SlowIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/invalid_config/config.yml
Backporting
Yes, 
- #1154  and …
=> Backport issue(#1153), (#1154) and (#517) to branch opendistro-1.6

src/test/java/org/opensearch/security/AdvancedSecurityMigrationTests.java
Maintenance
Move `AdvancedSecurityMigrationTests.java` to opensearch directory
Fix the namespace to follow OpenSearch naming convention
UT
7. __TO-DOs, if any:__ (_Please describe pending items and …
=> Move AdvancedSecurityMigrationTests.java to opensearch directory

pom.xml
1. __Category:__ 
Maintenance
https://github.com/opensearch-project/security/issues/1208
upgrade CXF to v3.4.3
According to https://github.com/opensearch-project/.github/edit/main/SECURITY.md , I'm not supposed to say.
`mvn package` on my local machine
8. __Is it backport from main branch?__ (_If yes, please add …
=> upgrade CXF to v3.4.3

pom.xml
=> Bump httpclient version from 4.5.3 to 4.5.13

src/main/resources/static_config/static_action_groups.yml
Adding static action group for data-stream management related actions.
https://github.com/opensearch-project/security-dashboards-plugin/issues/782
Added action group in the list of static action groups.
So that user can directly use this action group to enable data-stream management related permissions.
User had to manually create such …
=> Add static action group for managing data streams

.github/CODEOWNERS
=> Fix CODEOWNERS file (opensearch-project#1193)

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/SSLTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) and issue(#1057) to branch opendistro-1.12

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) to branch opendistro-1.13

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) and issue(#1057) to branch opendistro-1.7

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) and issue(#1057) to branch opendistro-1.11

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=>  Backport issue(#1156) and issue(#1057) to branch opendistro-1.8

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) and issue(#1057) to branch opendistro-1.9

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=>  Backport issue(#1156) and issue(#1057) to branch opendistro-0.9

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=>   Backport issue(#1156) and issue(#1057) to branch opendistro-0.10

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) and issue(#1057) to branch opendistro-1.4

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=>  Backport issue(#1156) and issue(#1057) to branch opendistro-1.1

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) and issue(#1057) to branch opendistro-1.5

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opensearch-security.release-notes-1.0.0.0.md
=> Bump version to 1.0.0.0 and create release notes

.github/workflows/ci.yml, build.gradle, pom.xml, release-notes/opensearch-security.release-notes-1.0.0.0.md
=> Build on OpenSearch 1.0.0

src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java, src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
Bug fix
#1095 
Send parallel put/delete requests
before: 
returns
`{"status":"INTERNAL_SERVER_ERROR","message":"Error [internalusers]: version conflict, ......`
after: 
returns
`{"status":"CONFLICT","message":"[internalusers]: version conflict, ......`
6. __Testing done:__ (_Please provide details of testing done: Unit testing, …
=> Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) and issue(#1057) to branch opendistro-1.6

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java, src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java, src/test/resources/security_passive/action_groups.yml, src/test/resources/security_passive/audit.yml, src/test/resources/security_passive/config.yml, src/test/resources/security_passive/internal_users.yml, src/test/resources/security_passive/nodes_dn.yml, src/test/resources/security_passive/roles.yml, src/test/resources/security_passive/roles_mapping.yml, src/test/resources/security_passive/tenants.yml, src/test/resources/security_passive/whitelist.yml
=> Backport issue(#1156) and issue(#1057) to branch opendistro-1.0

src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
=> Fix race condition on async test for PR #1158

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-0.9][backport] Return HTTP 409 if get parallel put request 

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-0.10][backport] Return HTTP 409 if get parallel put request 

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.0][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.1][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.4][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.2][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.8][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.10][backport] Return HTTP 409 if get parallel put request 

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.11][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.12][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.13][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
=> [opendistro-1.9][backport] Return HTTP 409 if get parallel put request

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/resources/restapi/actiongroup_null_array_element.json, src/test/resources/restapi/nodesdn_null_array_element.json, src/test/resources/restapi/roles_null_array_element_allowed_actions.json, src/test/resources/restapi/roles_null_array_element_cluster_permissions.json, src/test/resources/restapi/roles_null_array_element_index_patterns.json, src/test/resources/restapi/roles_null_array_element_index_permissions.json, src/test/resources/restapi/roles_null_array_element_masked_fields.json, src/test/resources/restapi/roles_null_array_element_tenant_permissions.json, src/test/resources/restapi/rolesmapping_null_array_element_backend_roles.json, src/test/resources/restapi/rolesmapping_null_array_element_hosts.json, src/test/resources/restapi/rolesmapping_null_array_element_users.json, src/test/resources/restapi/users_null_array_element.json
=> [opendistro-1.13][backport] Add validation for null elements in JSON array (#1157)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/resources/restapi/actiongroup_null_array_element.json, src/test/resources/restapi/nodesdn_null_array_element.json, src/test/resources/restapi/roles_null_array_element_allowed_actions.json, src/test/resources/restapi/roles_null_array_element_cluster_permissions.json, src/test/resources/restapi/roles_null_array_element_index_patterns.json, src/test/resources/restapi/roles_null_array_element_index_permissions.json, src/test/resources/restapi/roles_null_array_element_masked_fields.json, src/test/resources/restapi/roles_null_array_element_tenant_permissions.json, src/test/resources/restapi/rolesmapping_null_array_element_backend_roles.json, src/test/resources/restapi/rolesmapping_null_array_element_hosts.json, src/test/resources/restapi/rolesmapping_null_array_element_users.json, src/test/resources/restapi/users_null_array_element.json
=> [opendistro-1.12][backport] Add validation for null elements in JSON array (#1157)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/resources/restapi/actiongroup_null_array_element.json, src/test/resources/restapi/nodesdn_null_array_element.json, src/test/resources/restapi/roles_null_array_element_allowed_actions.json, src/test/resources/restapi/roles_null_array_element_cluster_permissions.json, src/test/resources/restapi/roles_null_array_element_index_patterns.json, src/test/resources/restapi/roles_null_array_element_index_permissions.json, src/test/resources/restapi/roles_null_array_element_masked_fields.json, src/test/resources/restapi/roles_null_array_element_tenant_permissions.json, src/test/resources/restapi/rolesmapping_null_array_element_backend_roles.json, src/test/resources/restapi/rolesmapping_null_array_element_hosts.json, src/test/resources/restapi/rolesmapping_null_array_element_users.json, src/test/resources/restapi/users_null_array_element.json
=> [opendistro-1.11][backport] Add validation for null elements in JSON array (#1157)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/resources/restapi/actiongroup_null_array_element.json, src/test/resources/restapi/nodesdn_null_array_element.json, src/test/resources/restapi/roles_null_array_element_allowed_actions.json, src/test/resources/restapi/roles_null_array_element_cluster_permissions.json, src/test/resources/restapi/roles_null_array_element_index_patterns.json, src/test/resources/restapi/roles_null_array_element_index_permissions.json, src/test/resources/restapi/roles_null_array_element_masked_fields.json, src/test/resources/restapi/roles_null_array_element_tenant_permissions.json, src/test/resources/restapi/rolesmapping_null_array_element_backend_roles.json, src/test/resources/restapi/rolesmapping_null_array_element_hosts.json, src/test/resources/restapi/rolesmapping_null_array_element_users.json, src/test/resources/restapi/users_null_array_element.json
=> [opendistro-1.10][backport] Add validation for null elements in JSON array (#1157)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/resources/restapi/actiongroup_null_array_element.json, src/test/resources/restapi/nodesdn_null_array_element.json, src/test/resources/restapi/roles_null_array_element_allowed_actions.json, src/test/resources/restapi/roles_null_array_element_cluster_permissions.json, src/test/resources/restapi/roles_null_array_element_index_patterns.json, src/test/resources/restapi/roles_null_array_element_index_permissions.json, src/test/resources/restapi/roles_null_array_element_masked_fields.json, src/test/resources/restapi/roles_null_array_element_tenant_permissions.json, src/test/resources/restapi/rolesmapping_null_array_element_backend_roles.json, src/test/resources/restapi/rolesmapping_null_array_element_hosts.json, src/test/resources/restapi/rolesmapping_null_array_element_users.json, src/test/resources/restapi/users_null_array_element.json
=> [opendistro-1.9][backport] Add validation for null elements in JSON array (#1157)

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/NodesDnApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java, src/test/resources/restapi/actiongroup_null_array_element.json, src/test/resources/restapi/nodesdn_null_array_element.json, src/test/resources/restapi/roles_null_array_element_allowed_actions.json, src/test/resources/restapi/roles_null_array_element_cluster_permissions.json, src/test/resources/restapi/roles_null_array_element_index_patterns.json, src/test/resources/restapi/roles_null_array_element_index_permissions.json, src/test/resources/restapi/roles_null_array_element_masked_fields.json, src/test/resources/restapi/roles_null_array_element_tenant_permissions.json, src/test/resources/restapi/rolesmapping_null_array_element_backend_roles.json, src/test/resources/restapi/rolesmapping_null_array_element_hosts.json, src/test/resources/restapi/rolesmapping_null_array_element_users.json, src/test/resources/restapi/users_null_array_element.json
=> [opendistro-1.8][backport] Add validation for null elements in JSON array (#1157)

.github/workflows/cd.yml
=> Fix wrong indentation in CD

.github/workflows/ci.yml, CONTRIBUTING.md
(Cherry picked from commit dc291c2345cdb9885d7b99dff835df08bc3b15fd) …
=> Updating Github actions and files to use main branch. (#1023)

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditLogImpl.java, src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/routing/AuditMessageRouter.java
=> Opendistro 1.7 bp

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/resources/static_config/static_action_groups.yml, src/test/java/com/amazon/opendistroforelasticsearch/security/ResolveAPITests.java, src/test/resources/action_groups.yml, src/test/resources/action_groups_packaged.yml
=> [opendistro-1.11][backport] Add support for ResolveIndexAction handling (#1312) 

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/main/resources/static_config/static_action_groups.yml, src/test/java/com/amazon/opendistroforelasticsearch/security/ResolveAPITests.java, src/test/resources/action_groups.yml, src/test/resources/action_groups_packaged.yml
=> [opendistro-1.13][backport] Add support for ResolveIndexAction handling (#1312)

.github/workflows/cd.yml
Maintenance
Checkout OpenSearch to after Cache
- To fix CD workflow
- To be consistent with [CI](https://github.com/opensearch-project/security/blob/main/.github/workflows/ci.yml)
[CD …
=> Checkout OpenSearch after Cache in CD

src/main/java/com/amazon/dlic/auth/ldap/backend/LDAPAuthorizationBackend.java
1. __Category:__ Bug fix
2. __Github Issue:__
- #985 (same symptoms)
When authenticating users against an LDAP directory that demand StartTLS
connections, the security plugin does not issue a StartTLS command to
upgrade the connection, leading to authentication failures.
The code use the ldaptive library to communicate with LDAP, but does not
use the same API as the one shown in the official ldaptive
documentation.  When used against an LDAP directory that demand
StartTLS, the examples of ldaptive perform the StartTLS upgrade
transparently and the communication with the directory is successful.
Update the code to use the same ldaptive API as the one of the working
examples.  This unbreak LDAP authentification when StartTLS is required.
As a bonus, remove the …
=> Fix LDAP authentication when using StartTLS

pom.xml
=> Upgrade CXF to v3.4.4

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opensearch-security.release-notes-1.0.1.0.md
Maintenance
- Built security plugin on OpenSearch 1.0.0
- Installed security plugin on OpenSearch 1.0.0
8. __Is it …
=> Bump version to 1.0.1.0

.github/workflows/cd.yml, .github/workflows/ci.yml, build.gradle, plugin-descriptor.properties, pom.xml
Maintenance
- Built security plugin with OpenSearch 1.1.0
- Installed security plugin on OpenSearch 1.1.0
- [CD run](https://github.com/cliu123/security/runs/3406281257?check_suite_focus=true)
7. __TO-DOs, if any:__ …
=> Upgrade OpenSearch version to 1.1.0

build.gradle, plugin-descriptor.properties, pom.xml
Signed-off-by: dblock <dblock@dblock.org>
Maintenance
N/A
Incremented version to 1.1.0.0-SNAPSHOT.
Main is building against OpenSearch 1.1 and is no longer a 1.0.
N/A
```
mvn -B clean package
```
7. __TO-DOs, if any:__ …
=> Incremented version to 1.1.0.0-SNAPSHOT.

securityconfig/opensearch.yml.example
Documentation 
None
Remove protected indices usage from sample configuration. Protected indices configuration has never been used or recommened for OpenSearch. 
To avoid user confusion. 
This is doc change.
Not applicable. 
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for …
=> Remove alerting and ism indices from protected indices usage in sample configuration

.github/workflows/ci.yml, plugin-descriptor.properties, pom.xml
Signed-off-by: dblock <dblock@dblock.org>
Maintenace
Build against OpenSearch 1.1.0-SNAPSHOT.
8. __Is it backport from …
=> Build against OpenSearch 1.1.1-SNAPSHOT.

securityconfig/opensearch.yml.example, securityconfig/roles.yml, tools/install_demo_configuration.sh
Enhancement
https://github.com/opensearch-project/cross-cluster-replication/issues/97
Added replication specific roles and system index to the configuration
These changes are required to have pre-created replication roles and 
system index to be added as part of security configuration.
N/A
6. __Testing done:__ (_Please provide details of …
=> Added replication specific roles and system index to the configuration

src/main/java/org/opensearch/security/configuration/DlsFlsRequestValve.java, src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java, src/main/java/org/opensearch/security/filter/SecurityFilter.java, src/test/java/org/opensearch/security/dlic/dlsfls/CCReplicationTest.java, src/test/resources/dlsfls/roles_ccreplication.yml
Enhancement 
N/A
These changes are required for the the replication use-case to block replication on indices with dls/fls enabled for user/role.
Before this change, DLS/FLS are not honored for replication transport actions.
After this changes, replication actions throw security exception
6. __Testing done:__ (_Please provide details of …
=> Handled DLS/FLS/Field masking for replication actions

src/main/java/org/opensearch/security/auth/RolesInjector.java, src/main/java/org/opensearch/security/filter/SecurityFilter.java, src/main/java/org/opensearch/security/support/ConfigConstants.java, src/main/java/org/opensearch/security/transport/SecurityInterceptor.java, src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java, src/test/java/org/opensearch/security/auth/RolesInjectorTest.java, src/test/java/org/opensearch/security/ccstest/CrossClusterSearchTests.java
- Enhancement
N/A
- Extended role injection support for cross cluster requests.
- Added audit logs for role injection
- Extends role injection for cross cluster requests
- Added Integration tests and tested locally
7. …
=> Extended role injection support for cross cluster requests

src/main/java/org/opensearch/security/filter/SecurityFilter.java, src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java, src/main/java/org/opensearch/security/privileges/PrivilegesEvaluatorResponse.java, src/main/java/org/opensearch/security/support/ConfigConstants.java, src/main/java/org/opensearch/security/transport/SecurityInterceptor.java, src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java, src/test/java/org/opensearch/security/RolesInjectorIntegTest.java, src/test/java/org/opensearch/security/RolesValidationIntegTest.java
New feature
https://github.com/opensearch-project/security/issues/1337
Added assume role support for the plugins - #1337 
These changes are required for picking-up specified roles associated with an user.
Added Integration …
=> Added changes to support validation of security roles for plugins

securityconfig/elasticsearch.yml.example, securityconfig/roles.yml, tools/install_demo_configuration.sh
Added replication specific roles and system index to the configuration
(cherry picked from commit 39e3c28762eafaffd2498f6024216d86026aa0c0)
Maintenance
[Backport] Added replication specific roles and system index to the configuration
https://github.com/opensearch-project/security/pull/1408
6. __Testing done:__ (_Please provide details of …
=> [Backport] Added replication specific roles and system index to the configuration

release-notes/opensearch-security.release-notes-1.1.0.0.md
Maintenance
OpenSearch 1.1.0 release
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and …
=> Create release notes 1.1.0.0

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/DlsFlsRequestValve.java, src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/DlsFlsValveImpl.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/test/java/com/amazon/opendistroforelasticsearch/security/RolesInjectorIntegTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/dlsfls/CCReplicationTest.java, src/test/resources/dlsfls/roles_ccreplication.yml
[Backport] Handled DLS/FLS/Field masking for Cross cluster replication
(chrerry-pick 534fffe0e6cf2b33b9abcbc6508e98fc2d077a3d)
Maintenance
[Backport] Handled DLS/FLS/Field masking for Cross cluster replication
PR: https://github.com/opensearch-project/security/pull/1330
PR: https://github.com/opensearch-project/security/pull/1330
6. …
=> [Backport] Handled DLS/FLS/Field masking for Cross cluster replication

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluatorResponse.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/test/java/com/amazon/opendistroforelasticsearch/security/RolesValidationIntegTest.java
Enhancement, Maintenance
https://github.com/opensearch-project/security/pull/1367/
Added changes to support validation of security roles for plugins 
https://github.com/opensearch-project/security/pull/1367/
https://github.com/opensearch-project/security/pull/1367/
6. __Testing done:__ (_Please provide details of testing done: Unit …
=> [Backport] Added changes to support validation of security roles for plugins 

.github/workflows/cd.yml, .github/workflows/ci.yml, pom.xml, release-notes/opensearch-security.release-notes-1.1.0.0.md
Maintenance
- Building OpenSearch on new branch 1.1
- Changing <scm><tag> per [this comment](https://github.com/opensearch-project/security/pull/1429/files#r698832926)
- Triggering [CD](https://github.com/opensearch-project/security/pull/1430#discussion_r698910605) on any tags for the new release tag `1.1.0.0` to be created.
6. __Testing …
=> Switch opensearch from 1.x to 1.1

src/main/java/com/amazon/opendistroforelasticsearch/security/auth/RolesInjector.java, src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java, src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java, src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java, src/test/java/com/amazon/opendistroforelasticsearch/security/RolesInjectorIntegTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/auth/RolesInjectorTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/ccstest/CrossClusterSearchTests.java
Extended role injection support for cross cluster requests
(cherry picked from commit 4b1664419dfc09f500896a3ffaa4664741d01d01)
Enhancement,  Maintenance
Extended role injection support for cross cluster requests
(cherry picked from commit 4b1664419dfc09f500896a3ffaa4664741d01d01)
https://github.com/opensearch-project/security/pull/1195 …
=> [Backport] Extended role injection support for cross cluster requests

.github/dco.yml
Enhancement
Closes #1463 
Added DCO check to repository
See https://github.com/opensearch-project/project-meta/issues/17
No DCO checks on PR
N/A
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github …
=> Adding DCO check to repo

.github/workflows/ci.yml, build.gradle, plugin-descriptor.properties, pom.xml
Maintenance
N/A
Incremented version to 1.2.0.0-SNAPSHOT
Keep current with project versions
N/A
```
mvn -B clean package
```
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of …
=> Incremented version to 1.2.0.0-SNAPSHOT

pom.xml
Maintenance
Related to PR #1464 
Moved SNAPSHOTS maven repo to project level. It was previously at profile level, so it wouldn't be used when not applying profile `advanced`.
Maven commands not applying the `advanced` profile don't use SNAPSHOTS repo
Not use SNAPSHOTS repo when not in …
=> Moved SNAPSHOTS repo to project level

.github/workflows/cd.yml, build.gradle, plugin-descriptor.properties, pom.xml
Maintenance
#1459 
* Update the OpenSearch core dependency version to 1.2.0
* No longer building OpenSearch core artifact in CD workflow
OpenSearch 1.2.0 release readiness
* Compiled security plugin on OpenSearch core …
=> Update OpenSearch core dependency version to 1.2.0

securityconfig/opensearch.yml.example, securityconfig/roles.yml, tools/install_demo_configuration.sh
Signed-off-by: Joshua Li <joshuali925@gmail.com>
1. __Category:__  New feature
2. __Github Issue # or road-map entry, if available:__ https://github.com/opensearch-project/trace-analytics/issues/178
- Add cluster permissions for [observability plugin](https://github.com/opensearch-project/trace-analytics/tree/main/opensearch-observability)
- Add `.opensearch-observability` index as system index
- Observability plugin will be released in 1.2
Add new cluster permissions and system index
6. …
=> Add observability permissions and index

src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java, src/test/java/org/opensearch/security/PrivilegesEvaluationTest.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml
(cherry-picked from commit [5a9935a](https://github.com/opensearch-project/security/commit/5a9935a08f12444012a36985361ef942f933a56d))
7. __TO-DOs, if any:__ (_Please …
=> [backport] [opensearch 1.1] fix to include hidden indices when resolving wildcards

src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java, src/test/java/org/opensearch/security/PrivilegesEvaluationTest.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml
(cherry-picked from commit [5a9935a](https://github.com/opensearch-project/security/commit/5a9935a08f12444012a36985361ef942f933a56d))
7. __TO-DOs, if any:__ (_Please …
=> [backport] [opensearch 1.0] fix to include hidden indices when resolving wildcards

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/PrivilegesEvaluationTest.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml
=> [backport][opendistro-1.13] fix to include hidden indices when resolving wildcards

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/PrivilegesEvaluationTest.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml
=> [backport][opendistro-1.12]fix to include hidden indices when resolving wildcards

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/PrivilegesEvaluationTest.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml
=> [backport][opendistro-1.10]fix to include hidden indices when resolving wildcards

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/PrivilegesEvaluationTest.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml
=> [backport][opendistro-1.9]fix to include hidden indices when resolving wildcards

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/PrivilegesEvaluationTest.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml
=> [backport][opendistro-1.8]fix to include hidden indices when resolving wildcards

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/PrivilegesEvaluationTest.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml
=> [backport][opendistro-1.11]fix to include hidden indices when resolving wildcards

securityconfig/roles.yml
Signed-off-by: Amit Galitzky <amgalitz@amazon.com>
Maintenance
N/A
Adding new AD validate detector action to AD read access permissions. 
Adding new AD top anomalies result action to AD read access permissions.
Two new APIs are being added too AD during this release. 
* Validation API should have AD read access in order to execute all the correct validation checks for AD creation.
* Top anomaly results API for high-cardinality anomly results also needs to have AD read …
=> Add AD validate, multi-category results API permissions to AD read access

release-notes/opensearch-security.release-notes-1.2.0.0.md
=> Create 1.2.0.0 release notes

release-notes/opensearch-security.release-notes-1.2.0.0.md
Maintenance
N/A
Updated release notes with copyright notices PR 
8. __Is …
=> Updated release notes for 1.2 with copyright updates

pom.xml
(cherry picked from commit e341bd5)
Maintenance
8. __Is it backport …
=> [opendistro-1.13][backport] Upgrade json-smart from 2.4.2 to 2.4.7 

pom.xml
Maintenance
8. __Is it backport from main branch?__ (_If yes, please add …
=> Bumping log4j to 2.11.2

release-notes/opensearch-security.release-notes-1.2.1.0.md
8. __Is it backport from main branch?__ (_If yes, please add backport PR # …
=> Release notes for 1.2.1

pom.xml, release-notes/opensearch-security.release-notes-1.2.1.0.md
=> Cherrypick changes for 1.2.1 release

build.gradle, plugin-descriptor.properties, pom.xml
Upgrading log4j to 2.15.0 and bumping plugin version to 1.2.1
Bug fix / Maintenance
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each …
=> Released version 1.2.1 with log4j 2.15.0

release-notes/opensearch-security.release-notes-1.2.1.0.md
Updating release notes for 1.2.1
Maintenance …
=> Updated release notes for 1.2.1

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opensearch-security.release-notes-1.2.2.0.md
Cherry-picked from 3e01690
Update to version 1.2.2 with log4j 2.16.0
Maintenance
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and …
=> Update to version 1.2.2 with log4j 2.16.0

build.gradle, plugin-descriptor.properties, pom.xml
Coming from https://github.com/opensearch-project/opensearch-build/issues/1365.
=> Incremented version to 1.2.3.

build.gradle
Updating dependency check on OpenSearch core to 1.2.3
Maintenance
By …
=> Updated check on OpenSearch Core to 1.2.3

pom.xml, src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java, src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java, src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
Signed-off-by: Palash Hedau <phhedau@amazon.com>
Bug Fix
Update CXF version to 3.4.5 …
=> Update CXF version to 3.4.5

pom.xml
#1548 
8. __Is it backport from main branch?__ (_If yes, please add …
=> Bump log4j-core to 2.17.1

DEVELOPER_GUIDE.md, README.md
Improved documentation with more details for getting started with the project. Fixed some broken links.
Documentation
Better developer/user experience
No behavior changes
N/A
N/A
=> Improved readme and developer guide

pom.xml
(cherry-picked from commit 63558a1) …
=> [backport] Bump log4j-core to 2.17.1

.github/workflows/backport.yml, DEVELOPER_GUIDE.md
Signed-off-by: Jason <hsiang@amazon.com>
https://github.com/opensearch-project/security/issues/1507
=> Add auto backport functionality to security plugin

release-notes/opensearch-security.release-notes-1.2.4.0.md
Adding release notes for version `1.2.4.0`
* Category: Maintenance
N/A
N/A
=> Release notes for 1.2.4.0

pom.xml
Signed-off-by: Darshit Chanpura <dchanp@amazon.com>
Upgrades Kafka and spring-kafka-test jar versions
* Enhancement
* Failing Whitesource check
https://github.com/opensearch-project/security/issues/1564
=> Upgrades Kafka version and Spring-kafka-test version to latest suggested by whitesource

tools/install_demo_configuration.sh
Adds sign-off commit signature.
=> Revert "Add ssl script (#1530)"

.gitignore
Add git ignore for VScode IDE settings
=> Add git ignore for VScode IDE settings

securityconfig/roles.yml, tools/install_demo_configuration.sh
Signed-off-by: Yaliang Wu <ylwu@amazon.com>
Rebase and backport https://github.com/opensearch-project/security/commit/3638c6ff89d3260da625b328a0b95f1596b03e5c from https://github.com/opensearch-project/security/pull/1654
Security team, please help close this PR https://github.com/opensearch-project/security/pull/1655
=> [Backport 1.3] configure ML reserved roles and system indices (#1654)

build.gradle
Signed-off-by: Sayali Rohidas Gaikawad <gaiksaya@amazon.com>
Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.
=> Incremented version to 1.3.2.

.github/workflows/plugin_install.yml, build.gradle
Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.
=> Change 2.0-alpha1 to 2.0-rc1.

.github/workflows/ci.yml, bwc-test/build.gradle
=> Remove checked-in zip files

build.gradle
Backport PR for this PR: #1806 
* Resolves #1802 
=> Updates dependency vulnerabilities versions in 1.3

securityconfig/internal_users.yml
* Category: Documentation
* Why these changes are required?  The documentation was incomplete and confusing to some.
* What is the old behavior before changes and new behavior after changes?  Same behavior, but better documentation for users transitioning from ODfE to Opensearch.
https://github.com/opensearch-project/security/issues/1766
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/       OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
=> More thorough and explicit user examples

release-notes/opensearch-security.release-notes-1.3.2.0.md
Followed the process used by #1772 to create the release notes
=> Release notes for 1.3.2

release-notes/opensearch-security.release-notes-1.3.1.0.md
(cherry picked from commit 1d40b807c9eefe78946127c10dd1fa025a431d2d)
1.3.1 release notes
* Category : Documentation
Forward-port PR #1713 and/or commits 1d40b807c9eefe78946127c10dd1fa025a431d2d
=> Add 1.3.1 release notes (#1713)

build.gradle
Fixes CVE-2022-22970 found in `org.springframework:spring-core:5.3.19`
* Resolves #1840
=> Update `org.springframework:spring-core` to `5.3.20`

.github/ISSUE_TEMPLATE/config.yml
Update support link on github issues
Here is the link in the new issue UX that is updated with this change.
=> Update support link

build.gradle
https://github.com/opensearch-project/opensearch-build/issues/2101
https://github.com/opensearch-project/opensearch-build/issues/2101
=> Version Increment to 1.3.3 OpenSearch release

src/test/java/org/opensearch/security/auditlog/compliance/ComplianceAuditlogTest.java, src/test/java/org/opensearch/security/auditlog/integration/TestAuditlogImpl.java
_Backporting this from 2.x branch_
We were seeing test failures where on higher end computers there would
be duplicate audit messages for the index mapping creation.  Then when
run inside GitHub Actions there would only be 2 messages.  This doesn't
look like an overt product issue, overlogging of requests, but the test
case was not handling it well. Also improved the failure message response
for faster future debugging.
(cherry picked from commit 1904db559960fca9d87e334172017c412f3e3d0e)
Co-authored-by: Peter Nied <petern@amazon.com>
For more information on following Developer Certificate of Origin and signing off your commits, …
=> testComplianceEnable supports variable number of audit messages (#1920) (#1924)

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.2.0.md
Create release notes and bump version to 1.13.2.0
Maintenance
=> Bump version and create release notes for 1.13.2.0

release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.2.0.md
Removes unwanted language from release notes.
Maintenance
=> Remove cherry picked from release notes for 1.13.2.0

build.gradle, plugin-descriptor.properties, pom.xml, release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.1.1.md
Rename next version of the release from 1.13.2.0 to 1.13.1.1
Maintenance
=> Renamed version from 1.13.2.0 to 1.13.1.1

build.gradle
In order to generate correct `.deb` and `.rpm` artifacts this version number increment is required.
manual testing
=> Increments minor patch version number in build.gradle

bwc-test/build.gradle, bwc-test/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties
Update to Gradle 7.5
Closes https://github.com/opensearch-project/security/issues/1962
N/A
=> Update to Gradle 7.5

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java, src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java, src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
=> Backport cluster evaluation permissions #1885 to 2.0

release-notes/opensearch-security.release-notes-2.2.0.0.md
Add release notes for 2.2.0.0 release
Maintenance
https://github.com/opensearch-project/security/issues/1969
=> Add release notes for 2.2.0.0 release

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java, src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java, src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
=> backport cluster evaluation permissions #1885 to 1.3

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java, src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java, src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
=> backport cluster evaluation permissions #1885 to 1.x

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
Backport of #1885 to `opendistro-1.13`
=> backport cluster evaluation permissions #1885 to opendistro-1.13

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java, src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java, src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
=> backport cluster evaluation permissions #1885 to 1.2

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java, src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java, src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
=> backport cluster evaluation permissions #1885 to 1.1

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java, src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java, src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
=> backport cluster evaluation permissions #1885 to 1.0

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java, src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java, src/test/java/com/amazon/opendistroforelasticsearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
Backport of #1885 to `opendistro-1.11`
=> backport cluster evaluation permissions #1885 to `opendistro-1.11`

release-notes/opensearch-security.release-notes-2.2.0.0.md
Add release changes into release notes for 2.2.0.0 including bug fix for OptionalDataException issue.
Maintenance
=> Update release notes for 2.2.0.0

src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java
* Resolves: https://github.com/opensearch-project/security/issues/2015
=> Updates matcher to use hasItem

bwc-test/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties
Update Gradle to 7.5.1
N/A
N/A
=> Update Gradle to 7.5.1

build.gradle
Increment 1.3 branch to 1.3.5
Maintenance
https://github.com/opensearch-project/opensearch-build/issues/2348
=> Increment version to 1.3.5

.github/workflows/ci.yml, build.gradle, bwc-test/build.gradle
Increments the version of `opensearch-security` to 2.3.0.0
Maintenance
https://github.com/opensearch-project/security/issues/1969
=> Increment version to 2.3.0.0

release-notes/opensearch-security.release-notes-1.3.5.0.md
Adding release note for 1.3.5
* Resolve https://github.com/opensearch-project/opensearch-build/issues/2348
=> Adding release notes for 1.3.5

release-notes/opensearch-security.release-notes-2.3.0.0.md
Signed-off-by: Chang Liu <lc12251109@gmail.com>
* Why these changes are required? 2.3.0 release
https://github.com/opensearch-project/security/issues/2063
UTs
=> Add 2.3.0.0 release notes

release-notes/opensearch-security.release-notes-2.3.0.0.md
Correct the release date in 2.3.0.0 release notes
=> Correct release date to 2022-09-15

build.gradle
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 1.3.6 for the upcoming release. 
Part of https://github.com/opensearch-project/opensearch-build/issues/2650
=> Increment version to 1.3.6

build.gradle
Update Kafka version to fix security vulnerability(#2095)
[[List any issues this PR will resolve]
](https://github.com/opensearch-project/security/issues/2095)
=> Upgrade Kafka Client to 3.0.2

release-notes/opensearch-security.release-notes-1.3.6.0.md
Signed-off-by: Vinayak Kothari <vkothar@amazon.com>
Release Notes 1.3.6
Documentation
*
=> Release notes 1.3.6

build.gradle
Address CVE-2022-42889 by updating commons-text
Closes https://github.com/opensearch-project/security/issues/2176
N/A
=> Address CVE-2022-42889 by updating commons-text

src/integrationTest/java/org/opensearch/security/IndexOperationsHelper.java, src/integrationTest/java/org/opensearch/security/SearchOperationTest.java, src/integrationTest/java/org/opensearch/test/framework/matcher/ClusterMatchers.java, src/integrationTest/java/org/opensearch/test/framework/matcher/DeleteResponseMatchers.java, src/integrationTest/java/org/opensearch/test/framework/matcher/GetIndexResponseContainsIndicesMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/GetMappingsResponseContainsIndicesMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/GetSettingsResponseContainsIndicesMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/IndexExistsMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/IndexMappingIsEqualToMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/IndexResponseMatchers.java, src/integrationTest/java/org/opensearch/test/framework/matcher/IndexSettingsContainValuesMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/IndexStateIsEqualToMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulClearIndicesCacheResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulCloseIndexResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulCreateIndexResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulDeleteResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulOpenIndexResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulResizeResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulUpdateResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/UpdateResponseMatchers.java
Signed-off-by: Kacper Trochimiak <kacper.trochimiak@eliatra.com>
* Category Integration Tests
The PR adds tests related to the following operations: index, update and delete. Ignored test cases are related to bugs which have been already reported
For more information on following Developer Certificate of Origin and signing off your …
=> add index, update, delete operation tests

src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
Signed-off-by: Hailong Cui <ihailong@amazon.com>
https://github.com/opensearch-project/security/issues/2035
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/ …
=> fix duplicate check

build.gradle
Backports Commit #2163 into 2.x.
=> [Backport 2.x] Patch bump for scala dependency

.github/workflows/plugin_install.yml, bwc-test/build.gradle
=> Upgrading versions in missing places

src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java, src/test/java/org/opensearch/security/DataStreamIntegrationTests.java, src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java, src/test/java/org/opensearch/security/PitIntegrationTests.java, src/test/java/org/opensearch/security/securityconf/impl/v7/IndexPatternTests.java, src/test/resources/internal_users.yml, src/test/resources/roles.yml, src/test/resources/roles_mapping.yml
Backport of https://github.com/opensearch-project/security/commit/f7cc569c9d3fa5d5432c76c854eed280d45ce6f4 to 2.x
=> [Backport 2.x] Fix issues with datastream backing indexes

.github/workflows/plugin_install.yml, tools/install_demo_configuration.bat
Backport of https://github.com/opensearch-project/security/pull/2161 to 1.3
=> [Backport 1.3] Add install_demo_configuration Batch script for Windows

.github/workflows/ci.yml, .github/workflows/plugin_install.yml, bwc-test/build.gradle
=> Bumps versions in remaining files

.github/workflows/ci.yml, .github/workflows/plugin_install.yml, bwc-test/build.gradle
=> Create pull request/2.4.1 snapshot

.github/actions/start-opensearch-with-one-plugin/action.yml, .github/workflows/plugin_install.yml
Modify reusable action to support workflow call acrossing repositories
Refactoring
* Related: https://github.com/opensearch-project/security-dashboards-plugin/issues/1228
* Related: https://github.com/opensearch-project/security-dashboards-plugin/pull/1212
=> Modify reusable action to support workflow call acrossing repositories

release-notes/opensearch-security.release-notes-2.4.1.0.md
Adds release notes for 2.4.1.0
Maintenance
=> Add 2.4.1.0 release notes

release-notes/opensearch-security.release-notes-1.3.7.0.md
Add release notes for 1.3.7.0
Maintenance
=> Add release notes for 1.3.7.0

src/integrationTest/java/org/opensearch/security/PointInTimeOperationTest.java, src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java, src/integrationTest/java/org/opensearch/test/framework/matcher/DeletePitContainsExactlyIdsResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/GetAllPitsContainsExactlyIdsResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/PitResponseMatchers.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulCreatePitResponseMatcher.java, src/integrationTest/java/org/opensearch/test/framework/matcher/SuccessfulDeletePitResponseMatcher.java
Signed-off-by: Kacper Trochimiak <kacper.trochimiak@eliatra.com>
Integration tests for PIT operations added.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develo …
=> Pit operations tests

src/integrationTest/java/org/opensearch/security/http/AnonymousAuthenticationTest.java
Signed-off-by: Kacper Trochimiak <kacper.trochimiak@eliatra.com>
Integration tests for anonymous auth added.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develo …
=> Anonymous authentication tests

.github/workflows/plugin_install.yml, build.gradle
Incremented version to 1.3.8
Maintenance
=> [1.3] Increment version to 1.3.8

tools/audit_config_migrater.bat, tools/hash.bat, tools/securityadmin.bat
Backport 8ccad5c7d2653fda12acabc1b94afe2b3d9a99dd from #2371
=> [Backport 1.X] Update tool scripts to run in windows (#2371)

.github/workflows/plugin_install.yml, tools/install_demo_configuration.bat, tools/install_demo_configuration.sh
Backport https://github.com/opensearch-project/security/pull/2401 to 2.5
=> [Backport 2.5]  Revert "Windows Install Action Fix"

.github/workflows/plugin_install.yml, tools/install_demo_configuration.bat, tools/install_demo_configuration.sh
Backport https://github.com/opensearch-project/security/pull/2401 to 2.4
=> [Backport 2.4] Revert "Windows Install Action Fix"

.github/workflows/plugin_install.yml, tools/install_demo_configuration.bat, tools/install_demo_configuration.sh
Backport https://github.com/opensearch-project/security/pull/2401 to 2.x
=> [Backport 2.x] Revert "Windows Install Action Fix"

build.gradle
=> Upgrade spotbugs to version 5.0.14

src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java, src/main/java/org/opensearch/security/support/ConfigHelper.java
=> [Backport 1.x] Fix lost privileges during auto initializing of the index

src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java, src/main/java/org/opensearch/security/support/ConfigHelper.java
=> [Backport 2.x] Fix lost privileges during auto initializing of the index (#2498)

README.md
=> Update README.md to add slack badge and announcement

build.gradle
Gradle plugin updates (spotless, ospackage)
N/A
=> Gradle plugin updates (spotless, ospackage)

.github/CODEOWNERS, .github/workflows/auto-release.yml, .github/workflows/plugin_install.yml, build.gradle, release-notes/opensearch-security.release-notes-1.3.9.0.md, securityconfig/config.yml, src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java, src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java, src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java, src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/TestJwts.java, tools/install_demo_configuration.bat, tools/install_demo_configuration.sh
There have been several backport changes that did not make it into the 1.x branch.  This pull request aligns both branches.
See https://github.com/opensearch-project/security/compare/1.3...peternied:security:1.x-merged-from-1.3 for how this branch differs from the 1.3 branch.
=> Sync 1.x with 1.3 branch

CONTRIBUTING.md
Taking over from #2593 from @shanilpa, adding starting tenets to our CONTRIBUTIN.md file.
=> Adding tenets to CONTRIBUTING.md

release-notes/opensearch-security.release-notes-2.8.0.0.md
Add release notes for 2.8.0
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation]
Maintenance
* Relate https://github.com/opensearch-project/security/issues/2785
=> [Backport 2.8] Add release notes for 2.8.0

release-notes/opensearch-security.release-notes-2.8.0.0.md
Update 2.8 release notes for security backend
Maintenance
* Relate https://github.com/opensearch-project/security/issues/2785
=> [Backport 2.8] Update 2.8 release notes for security backend

release-notes/opensearch-security.release-notes-2.8.0.0.md
Add release notes for 2.8.0
[Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation]
Maintenance
* Relate https://github.com/opensearch-project/security/issues/2785
=> Add release notes for 2.8.0

TRIAGING.md
Update the triaging guidelines to include open PR status check, and review of all "security" labelled issues in the project. 
=> Update triaging guidelines

release-notes/opensearch-security.release-notes-1.3.11.0.md
=> Add release notes for 1.3.11

release-notes/opensearch-security.release-notes-1.3.11.0.md
I missed the month when updating the release date for the 1.3.11 release notes. 
=> 1.3 Update release date

build.gradle, plugin-security.policy, src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
Backport 9a72355cbf37972ce1b9d12918e2a3e7c5023d80 from #2901
=> [Backport 1.x] Bump BouncyCastle from jdk15on to jdk15to18 (#2901)

config/roles.yml
Add connector read only API to security plugin
NA
No
NA
=> Add readonly API to security plugin

build.gradle
Bump org.glassfish.jaxb:jaxb-runtime and org.glassfish.jaxb:txw2
Maintenance
=> Bump org.glassfish.jaxb:jaxb-runtime and org.glassfish.jaxb:txw2 to 2.3.8

build.gradle
Moved `mavenLocal` to top which is required for compatibility check to pass with core changes. 
Part of https://github.com/opensearch-project/security/issues/2915
=> Changed maven repo location for compatibility check

release-notes/opensearch-security.release-notes-2.9.0.0.md
=> [2.9] Add release notes for 2.9.0.0

.github/workflows/plugin_install.yml, build.gradle
Move 2.x to OpenSearch 2.10.0-SNAPSHOT
N/A
=> Move 2.x to OpenSearch 2.10.0-SNAPSHOT

scripts/integtest.sh
Update default version of common-utils used by the integ tests for 2.x
Maintenance
=> [2.x] Update common utils version for integ tests

build.gradle
Maintenance
https://advisories.aws.barahmand.com/advisories/GMS-2023-1246
=> Bump the version of `kafka` and `spring-kafka-test` (CVE Related)

release-notes/opensearch-security.release-notes-1.3.12.0.md
Add release notes for 1.3.12.0
Documentation
=> Add release notes for 1.3.12.0

src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
After the upgrade of JJWT from https://github.com/opensearch-project/security/pull/3092, the JWT Integration Tests in security-dashboards-plugin started failing. See details on: https://github.com/opensearch-project/security-dashboards-plugin/issues/1555
The output from the tests in Github actions was not very revealing, but @RyanL1997 pointed out that when running the test locally after creating a local distro of core + security plugin with 2.x it would output a permissions error:
```
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485) ~[?:?]
at java.security.AccessController.checkPermission(AccessController.java:1068) ~[?:?]
at …
```
=> [2.x] Fix permission issue when creating JWTParser after jjwt upgrade

ARCHITECTURE.md, README.md
As we are expanding the features in the Security Plugin we are capturing how those features work in our service architecture.  For this set of changes I'm documenting how plugins, extensions with OnBehalfOf tokens, and Extension with service accounts interact with the cluster.
Bonus added a table of contents
=> [Docs] Add flows for OBO and Service Account

plugin-security.policy, src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
Backport https://github.com/opensearch-project/security/pull/3289 to 2.x
=> [Backport 2.x] Fix permissions issues while reading keys in PKCS#1 format

DEVELOPER_GUIDE.md
Getting OpenSearch version from gradle properties.
Backport from PR #3457.
=> [Backport 1.x] Get OpenSearch version from gradle properties.

release-notes/opensearch-security.release-notes-2.11.0.0.md
=> Updates 2.11 release notes

build.gradle, src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java, src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java, src/main/java/org/opensearch/security/util/KeyUtils.java, src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java, src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java
=> [Backport 2.x] Bump jjwt_version from 0.11.5 to 0.12.3 (#3536)

src/integrationTest/java/org/opensearch/security/ResourceFocusedTests.java, src/integrationTest/java/org/opensearch/security/rest/CompressionTests.java, src/integrationTest/java/org/opensearch/test/framework/AsyncActions.java, src/integrationTest/resources/log4j2-test.properties
(cherry picked from commit 1ad8cf480cd31d2fd10fdb16e974816cb64fe0a8)
=> [Backport 2.x][Refactor] Improve asynchronous test cases format (#3601)

build.gradle
=> Bumps spotbugs-gradle-plugin to 5.2.3

src/test/java/org/opensearch/security/TransportUserInjectorIntegTest.java
Fix flaky tests in TransportUserInjectorIntegTest by removing reliance on a static variable that makes the test unpredictable. This instead adds a setting in the UserInjectorPlugin and relies on each node that has the plugin installed to supply this setting when instantiating the node.
Test Fix
- Fixes https://github.com/opensearch-project/security/issues/3729 …
=> Switch UserInjectorPlugin to use reliable per-instance settings

build.gradle
Reverts opensearch-project/security#3801
=> Revert "Upgrade logback-classic to address CVE CVE-2023-6378"

.github/workflows/ci.yml, src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java, src/integrationTest/java/org/opensearch/test/framework/cluster/SearchRequestFactory.java, src/test/java/org/opensearch/security/SlowIntegrationTests.java
* Category Test fix
- Resolves https://github.com/opensearch-project/security/issues/3423
=> Enable windows platform for integration tests cases

build.gradle
Bump missing libraries between main and 2.x.
=> [Backport 2.x] Bump missing libraries

build.gradle
Resolve logback-classic to 1.2.13
Backport of: https://github.com/opensearch-project/security/pull/3823
=> [Backport 2.x] Resolve logback-classic to 1.2.13

.github/workflows/ci.yml
Reverts opensearch-project/security#3860
=> Revert "Bump actions/download-artifact from 3 to 4"

config/roles.yml
Description
Adds permission for a new Get Workflow Step API. https://github.com/opensearch-project/flow-framework/pull/394
=> Add permission for get workflow step

.github/workflows/ci.yml, src/integrationTest/java/org/opensearch/test/framework/matcher/SearchHitContainsFieldWithValueMatcher.java
- Improve error message logging on mismatch in search response.  
```
Suite: Test class org.opensearch.security.DlsIntegrationTests
2> java.lang.AssertionError: 
Expected: Search hit with index <5> should contain field "artist"" with value equal to ""yes"
but: Unexpected match in SearchResponse {"took":101,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":6,"relation":"eq"},"max_score":null,"hits":[{"_index":"first-test-index","_id":"INDEX_1_S1","_score":null,"_source":{"artist":"First artist","lyrics":"Very deep subject","stars":1,"genre":"rock","title":"Magnum Opus"},"sort":["INDEX_1_S1"]},{"_index":"first-test-index","_id":"INDEX_1_S2","_score":null,"_source":{"artist":"String","lyrics":"Once upon a …
```
=> Add additional logging around `testShouldSearchAll` tests

src/main/java/org/opensearch/security/util/ratetracking/HeapBasedRateTracker.java, src/test/java/org/opensearch/security/auth/limiting/HeapBasedRateTrackerTest.java
HeapBasedRateTracker uses time provider to allow simluating of time in unit tests
- Resolves https://github.com/opensearch-project/security/issues/2193
=> HeapBasedRateTracker uses time provider to allow simluating of time in unit tests

release-notes/opensearch-security.release-notes-1.3.15.0.md
Adds release notes for 1.3.15 release
=> [1.3] Add release notes for 1.3.15 release

config/roles.yml, release-notes/opensearch-security.release-notes-2.13.0.0.md, src/integrationTest/java/org/opensearch/security/DoNotFailOnForbiddenTests.java
Manually backport #4151 and add DNFOF exception to fix tests. 
=> Backport 2.13 Manually backport 4151 (ML roles refactor)

src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
* Why these changes are required?: Need to add a new system index for ML commons for 2.13
* What is the old behavior before changes and new behavior after changes?: No behavior change other than supporting a new system index
N/A
Verified CIs pass
=> Add new stop words system index

.github/workflows/ci.yml, build.gradle
Backport dc8bd61a8df01b32805ddde0b6f6c6010eeca5cf from #4178
- Related 4178
=> [Backport 2.x] Remove Pom task dependencies rewrite (#4178)

.github/workflows/ci.yml
Upgrade codecov/codecov-action to v4
* Category
Maintenance
=> Upgrade codecov/codecov-action to v4

release-notes/opensearch-security.release-notes-1.3.16.0.md
=> Adds 1.3.16.0 release notes

build.gradle, src/main/java/org/opensearch/security/configuration/MaskedField.java, src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
Replace Bouncy Castle Blake2bDigest in MaskedField.
Changes are backwards compatible.
No documentation changes are required.
Resolves https://github.com/opensearch-project/security/issues/4212
Backwards compatibility confirmed by existing tests.
=> Replace bouncy castle blake2b

build.gradle
[Backport 2.x] Bump open_saml_version from 4.3.0 to 4.3.2 (#4239)
=> [Backport 2.x] Bump open_saml_version from 4.3.0 to 4.3.2 (#4239)

build.gradle, src/main/java/org/opensearch/security/tools/SecurityAdmin.java
Manually bumped `commons-cli` to 1.8.0
=> Bump commons-cli to 1.8.0

build.gradle, src/main/java/org/opensearch/security/tools/SecurityAdmin.java
=> [Backport 2.x] Bump commons-cli to 1.8.0

release-notes/opensearch-security.release-notes-1.3.17.0.md
=> Adds 1.3.17.0 release notes

build.gradle
Backport 2b5a811de599f7c7fc2ca2b9246e57fd6cfaf33b from #4501
=> [Backport 2.x] Bump kafka_version from 3.7.0 to 3.7.1 (PR #4501)

build.gradle
Backport 055a07d6af0fe4bd277228fc497190d174bdca42 from #4531
=> [Backport 2.x] Bump org.checkerframework:checker-qual from 3.44.0 to 3.45.0

src/integrationTest/java/org/opensearch/security/FlsAndFieldMaskingTests.java
Backport 08d3a6cedc737b82b31aa03e80748dcef698a33d from #4548
Fixes failing tests in FlsAndFieldMaskingTests. 
The tests `flsWithIncludesRulesIncludesFieldMappersFromPlugins` and `testFlsOnAClosedAndReopenedIndex` both used the REST API to create an identical test user. However, the test which executes second would get a 200 Ok REST status instead a 201 Created REST status, as the `PUT` would operate on a resource that already exists. 
This caused the test to fail.
This moves the user to the global user definition of the test.
* Category: Test fix
* Why these changes are required? - The test failed before
* What is the old behavior before changes and new behavior after changes? - None …
=> [Backport 2.x] Fixed test failures in FlsAndFieldMaskingTests (#4548)

config/roles.yml
Manually backport #4151
This PR never got backported to 2.x originally so fixing that. 
=> [Backport 2.x] Refactor and update existing ml roles

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
Backport https://github.com/opensearch-project/security/pull/4605/commits/b3e067bdf0096a8f4c76249b5b5f2996f7bf5c01 from https://github.com/opensearch-project/security/pull/4605
=> [Backport 2.x] Refactor security provider instantiation

build.gradle
Backport 240d72d14927f60bc0746ecd8b673be8e6640b8e from #4620
=> [Backport 2.x] Bump org.checkerframework:checker-qual from 3.45.0 to 3.46.0

release-notes/opensearch-security.release-notes-2.17.0.0.md
Add release notes for 2.17 release
Maintenance
Release 2.17
Nothing
None
No
No
None …
=> Add release notes for 2.17

gradle/wrapper/gradle-wrapper.properties
=> Bump gradle to 8.10.2

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java, src/main/java/org/opensearch/security/ssl/SslContextHandler.java, src/main/java/org/opensearch/security/ssl/SslSettingsManager.java, src/main/java/org/opensearch/security/support/ConfigConstants.java, src/test/java/org/opensearch/security/ssl/CertificatesRule.java, src/test/java/org/opensearch/security/ssl/SslSettingsManagerReloadListenerTest.java, src/test/java/org/opensearch/security/ssl/config/JdkSslCertificatesLoaderTest.java, src/test/resources/log4j2-test.properties
Backoport c22002a5313fa2cc265b43c2177ecc2357ad0701 from #4880
=> [Backport 2.x] Add support for certificates hot reload (#4880)

build.gradle
Update commons-io to 2.18.0 to address [CVE-2024-47554](https://nvd.nist.gov/vuln/detail/CVE-2024-47554)
Maintenance
=> [1.3] Update commons-io to 2.18.0

build.gradle
=> Bumps guava to 33.4.0-jre

gradle/wrapper/gradle-wrapper.properties, gradlew
=> Bump gradle to 8.13

release-notes/opensearch-security.release-notes-3.0.0.0-alpha1.md
=> Adds 3.0.0-alpha1 release notes

build.gradle, src/main/java/org/opensearch/security/compliance/ComplianceConfig.java, src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java, src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java, src/test/java/org/opensearch/security/configuration/ConfigurationRepositoryTest.java
Backport of https://github.com/opensearch-project/security/pull/5206
=> [Backport 2.x] Improve coverage: Adding tests for ConfigurationRepository class (#5206)

src/main/java/org/opensearch/security/privileges/ActionPrivileges.java
This change moves the matching of index patterns from role configuration entries to a higher level during the construction of StatefulIndexPrivileges instances. This avoids that index pattern matching is repeated for each permission that is sourced from the role configuration. On clusters with many indices, this can provide a very significant performance improvement. In a simple micro benchmark (see comment below), we could observe computation times that showed a 85% reduction compared to the original code.
* Why these changes are required? For clusters with many indices and roles, runtime of index matching gets very significant.
* What is the old behavior before changes and new behavior after changes? No behavioral change
- Existing unit and integration tests
By …
=> [3.1 Backport] Optimized runtime behavior of index matching during StatefulIndexPrivileges construction

CHANGELOG.md, src/main/java/org/opensearch/security/securityconf/impl/CType.java, src/test/java/org/opensearch/security/SecurityAdminIEndpointsTests.java
=> [Backport 3.1] Fix Mixed Cluster Config Update Bug

release-notes/opensearch-security.release-notes-2.19.3.0.md
Release notes.
N/A
N/A
~~- [ ] New functionality includes testing~~
~~- [ ] New functionality has been documented~~
~~- [ ] New Roles/Permissions have a corresponding security dashboards plugin PR~~
~~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md)~~
~~- [ ] Commits are signed per the DCO using --signoff~~
=> 2.19.3 release notes 

CHANGELOG.md, build.gradle
=> Bumps spotbugs to 6.2.4 and checkstyle to 11.0.0

.github/dependabot.yml
Ensure dependabot can monitor libs/opensaml/
Maintenance
=> Ensure dependabot can monitor libs/opensaml/
