src/integrationTest/java/org/opensearch/security/api/DashboardsInfoTest.java
src/integrationTest/java/org/opensearch/security/api/DashboardsInfoWithSettingsTest.java
src/main/java/org/opensearch/security/rest/DashboardsInfoAction.java

Companion Security Dashboards Plugin PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/1503
This modifies the /dashboardsinfo endpoint to include the `plugins.security.restapi.password_validation_error_message` setting or the default message of "Password should be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit, and one special character.". The purpose of adding this to the endpoint is to utilize this message when rendering both the password edit component and password reset component to include the proper message.
Bug Fix
https://github.com/opensearch-project/security-dashboards-plugin/issues/1501
By submitting …

Add password message to /dashboardsinfo endpoint

---

build.gradle
src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/main/java/com/amazon/dlic/auth/http/saml/Saml2SettingsProvider.java
src/main/java/com/amazon/dlic/auth/http/saml/SamlHTTPMetadataResolver.java
src/test/java/com/amazon/dlic/auth/http/saml/MockSamlIdpServer.java

Bump SAML libs
- OpenSAML to version 4.3.0
- One login SAML to 2.9.0

Bump SAML libs

---

build.gradle
src/integrationTest/java/org/opensearch/test/framework/log/LogCapturingAppender.java
src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java

Removed commons-collections 3.2.2
Reasons:
- it is not supported anymore 
- there were only 2 places where it used:   
-  Class `LogCapturingAppender` - replaced `CircularFifoBuffer` with guava `EvictingQueue` 
- `ResolvedIndicesProvider` - replace `MultyKey` with the custom one 

Remove commons-collections 3.2.2

---

.github/dependabot.yml

Add dependandabot yaml file. Dependandabot should check dependencies weekly and create commits with "dependabot:" prefix
https://github.com/opensearch-project/security/issues/2933

Add dependandabot yml file

---

build.gradle

The eventbus artifact was moved in `org.greenrobot:eventbus-java` instead `org.greenrobot:eventbus`. This PR is a replacement for https://github.com/opensearch-project/security/pull/2961

Bump eventbus to 3.3.1

---

build.gradle

[Backport 2.x] Resolve CVE-2023-2976 by forcing use of Guava 32.0.1 (#2937)

---

build.gradle

[Backport 2.x] Bump org.glassfish.jaxb:jaxb-runtime and org.glassfish.jaxb:txw2 to 2.3.8 (#2977)

---

build.gradle
src/main/java/org/opensearch/security/compliance/FieldReadCallback.java

Bump JSON libraries to latest versions:
- `jjwt-api` - to 0.11.5
- `json-flattener` -0.16.4
- `zjsonpatch` - 0.4.14
- `json-path` -2.8
- `json-smart` - 2.4.11
Regarding `json-flattener` I have a question. All functionality which we use in our case can be replaced with such class:
```java
package org.opensearch.security.compliance;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import org.apache.kafka.common.protocol.types.Field;
import org.opensearch.core.common.Strings;
import org.opensearch.security.DefaultObjectMapper;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import …
```

Bump JSON libs

---

build.gradle

(cherry picked from commit 9599155caad2d3c72a1b999ea4b7cab999e6ef93)
Backport #2976 to 2.x

[Backport 2.x] Bump guava to 32.1.1-jre (#2976)

---

build.gradle

Use version of log4j from core's buildSrc/version.properties
* Category
Maintenance

[2.x] Use version of log4j from core's buildSrc/version.properties

---

scripts/integtest.sh

- Resolve #3010 
- Resolves #3011

[2.9] Updates common-utils version in integ test script

---

.github/actions/create-bwc-build/action.yaml
bwc-test/build.gradle

The BWC Tests are not currently referring to a SNAPSHOT version when running testclusters which causes the distribution downloader to look for release or release-candidate versions of the minimum distribution as @saratvemulapalli describes [here](https://github.com/opensearch-project/OpenSearch/pull/8731#issuecomment-1639032164). This PR appends `-SNAPSHOT` to the versions supplied to testclusters to instruct testclusters to download a SNAPSHOT which will always have the most up-to-date changes included.
Test fix
https://github.com/opensearch-project/security/issues/3020
For more …

Use SNAPSHOT in bwc tests to run tests with latest commits

---

build.gradle

This combines 4 dependabot PRs into one. I created a PR because the dependabot PRs cannot be synchronized with main to get the latest build fixing PR.
This change includes:
- bump com.netflix.nebula.ospackage from 11.1.0 to 11.3.0
- bump org.checkerframework:checker-qual from 3.5.0 to 3.36.0
- bump com.nulab-inc:zxcvbn from 1.7.0 to 1.8.0
- bump com.google.errorprone:error_prone_annotations from 2.3.4 to 2.20.0
- bump org.apache.camel:camel-xmlsecurity from 3.14.2 to 3.21.0
Maintenance
For more information on following Developer Certificate of Origin and signing off your commits, …

Update ospackage, checker-qual, zcxvbn and error_prone_annotations, camel-xmlsecurity

---

config/roles.yml

Adds cluster permissions for alerting workflows to alerting roles
**`alerting_read_access`** role is mapped additionally to 
**`'cluster:admin/opensearch/alerting/workflow/get'`** and **`cluster:admin/opensearch/alerting/workflow_alerts/get'`**
**`alerting_ack_alerts`** is mapped to **'cluster:admin/opendistro/alerting/workflow_alerts/*`**  and **'cluster:admin/opendistro/alerting/chained_alerts/*'**
These roles are merged in https://github.com/opensearch-project/common-utils/blob/main/src/main/kotlin/org/opensearch/commons/alerting/action/AlertingActions.kt#L9-L20 …

add workflow cluster permissions to alerting roles

---

TRIAGING.md

Documents what different labels are used during triage and what they mean.
- Resolves https://github.com/opensearch-project/security/issues/3022

Triage label guidelines

---

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
src/main/java/org/opensearch/security/auditlog/impl/RequestResolver.java
src/main/java/org/opensearch/security/dlic/rest/api/PatchableResourceApiAction.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java

Adapt MediaType library change in core
Refactoring
* Relate https://github.com/opensearch-project/OpenSearch/pull/8636

Adapt MediaType library change in core

---

src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/main/java/org/opensearch/security/support/ConfigHelper.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/dlic/rest/validation/RequestContentValidatorTest.java
src/test/java/org/opensearch/security/test/helper/file/FileHelper.java

There are multiple PRs in core affecting the security plugin that the security plugin needs to adapt to.
- https://github.com/opensearch-project/OpenSearch/pull/7792
- https://github.com/opensearch-project/OpenSearch/pull/8826
- https://github.com/opensearch-project/OpenSearch/pull/8668
I am opening a Draft PR that includes a fix for the Lucene-related test failures which was caused by https://github.com/opensearch-project/OpenSearch/pull/7792
Resolves: https://github.com/opensearch-project/security/issues/3064

Fix build after Lucene upgrade and breaking XContentFactory changes

---

src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/main/java/org/opensearch/security/support/ConfigHelper.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/test/helper/file/FileHelper.java

Backport https://github.com/opensearch-project/security/pull/3069 to 2.x

[Backport 2.x] Fix build after Lucene upgrade and breaking XContentFactory changes (#3069)

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java

Remove static reference/initialization of localNode variable inside security plugin, to fix `No user found..` errors caused due to mismatching localNode values in test. 

Remove static local-node reference

---

build.gradle

Manually re-creating dependabot's [PR](https://github.com/opensearch-project/security/pull/3042) off of the latest changes from main which has build fixes.
Is there a way we can open PRs with main at the push of a button?

bump com.github.wnameless.json:json-base from 2.4.0 to 2.4.1

---

build.gradle
src/main/java/org/opensearch/security/ssl/util/SSLConnectionTestUtil.java
src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java
src/test/java/org/opensearch/security/ssl/util/SSLConnectionTestUtilTests.java

Update guava to address [CVE-2023-2976](https://www.cve.org/CVERecord?id=CVE-2023-2976).
Seems like this has been resolved for 2.x so this PR is for the 1.3 branch.
https://github.com/opensearch-project/security/issues/2940

[1.3] Update guava to address CVE-2023-2976

---

.github/workflows/backport.yml

There have been improvements including adding a label to a pull request when any backport on it has failed.
- Related https://github.com/VachaShah/backport/pull/8

Update backport version for failure labels

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
src/main/java/org/opensearch/security/auditlog/impl/RequestResolver.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/auth/UserInjector.java
src/main/java/org/opensearch/security/configuration/SecurityIndexSearcherWrapper.java
src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/PermissionsInfoAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
src/main/java/org/opensearch/security/http/XFFResolver.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/rest/SecurityInfoAction.java
src/main/java/org/opensearch/security/securityconf/ConfigModel.java
src/main/java/org/opensearch/security/securityconf/ConfigModelV6.java
src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
src/test/java/org/opensearch/security/InitializationIntegrationTests.java
src/test/java/org/opensearch/security/auditlog/helper/MockAuditMessageFactory.java
src/test/java/org/opensearch/security/auditlog/impl/IgnoreAuditUsersTest.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterInfo.java
src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java

Backport 56172cdb2671432621dadb6b9990c0c5d8039686 from #3091

[Backport 2.x] Fix imports for TransportAddress

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
src/main/java/org/opensearch/security/auditlog/impl/RequestResolver.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/auth/UserInjector.java
src/main/java/org/opensearch/security/configuration/SecurityIndexSearcherWrapper.java
src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/PermissionsInfoAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
src/main/java/org/opensearch/security/http/XFFResolver.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluator.java
src/main/java/org/opensearch/security/rest/SecurityInfoAction.java
src/main/java/org/opensearch/security/securityconf/ConfigModel.java
src/main/java/org/opensearch/security/securityconf/ConfigModelV6.java
src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
src/test/java/org/opensearch/security/InitializationIntegrationTests.java
src/test/java/org/opensearch/security/auditlog/helper/MockAuditMessageFactory.java
src/test/java/org/opensearch/security/auditlog/impl/IgnoreAuditUsersTest.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterInfo.java
src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java

This PR fixed `TransportAddress` imports after core refactor in [#9073](https://github.com/opensearch-project/OpenSearch/pull/9073)

Fix import for TransportAddress after core refactor #9073

---

src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java
src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/main/java/org/opensearch/security/ssl/util/ExceptionUtils.java
src/main/java/org/opensearch/security/support/HTTPHelper.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java

Edge Cases Of OBO Token Usage: 
New feature
* Resolve https://github.com/opensearch-project/security/issues/2891

[Feature/Extension] Restrict OBO token's usage for certain endpoints

---

.github/dependabot.yml

Limit dependabot from automatically creating major version increments
- Related https://github.com/opensearch-project/security/pull/3107

Limit dependabot from automatically creating major version increments

---

src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java

Remove log spam for files that are cleaned up

Remove log spam for files that are cleaned up

---

.github/workflows/ci.yml

Switch CodeQL to assemble artifacts using the same build as the rest of CI
- Bump CodeQL action version from v1 to v2
- Resolves https://github.com/opensearch-project/security/issues/3131

Switch CodeQL to assemble artifacts using the same build as the rest of CI

---

.github/workflows/backport.yml

Only run the backport job on merged pull requests
From the GitHub Action log, we'd see an error about branch_name not being used, and the error that backports should only run on merged PRs.  This should reduce noisy failures in our logs.
```
Warning: Unexpected input(s) 'branch_name', valid inputs are ['body_template', 'files_to_skip', 'github_token', 'head_template', 'label_pattern', 'labels_template', 'title_template', 'failure_labels']
Run VachaShah/backport@v[2](https://github.com/opensearch-project/security/actions/runs/5802658423/job/15729398925?pr=3132#step:3:2).2.0
Error: Error: For security reasons, this action should only run on merged PRs.
```
Example [[workflow failure]](https://github.com/opensearch-project/security/actions/runs/5802658423/job/15729398925?pr=3132), see more …

Only run the backport job on merged pull requests

---

scripts/integtest.sh

(cherry picked from commit 46989b57d9cdf969be9473d1ca6bcb61c7923135)
Backports #3122 

[Backport 2.x] Updates integTestRemote task to dynamically fetch common-utils version from build.gradle (#3122)

---

.github/dependabot.yml

Automatically update GitHub Actions dependencies with dependabot.  Noticed this was possible when I was reading the notice around CodeQL's v1 deprecation, [[codeql-action-v1-is-now-deprecated]](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/#can-i-use-dependabot-to-help-me-with-this-upgrade).

Automatically update GitHub Actions dependencies with dependabot

---

.github/workflows/ci.yml

CodeQL is throwing errors when run inside of branches created by dependabot requests.  Also we've had issue with a flood of CI checks that were redudant when inspecting pull request check results.  This should limit the 'doubling' up unless you are making a pull request from a fork's main branch.

Only run CI on push for 'official' branches

---

src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java

Remove hostmapping from create OBO endpoint
new feature
* Relate #3000 

[Feature/Extension] Remove hostmapping from create OBO endpoint.

---

src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
src/test/resources/dlsfls/roles.yml
src/test/resources/dlsfls/roles_mapping.yml

Backport https://github.com/opensearch-project/security/pull/3136 to 2.x

[Backport 2.x] Fix Document GET with DLS terms query (#3136)

---

.github/actions/create-bwc-build/action.yaml
.github/actions/run-bwc-suite/action.yaml
.github/workflows/ci.yml
.github/workflows/code-hygiene.yml
.github/workflows/plugin_install.yml

Disable gradlew build cache to ensure most up-to-date dependencies
We suspect that we are seeing the snapshot build of opensearch be cached in some circumstances and not cached in others that is creating a mix of build failures that are hard to interpret.
Follow up issue to revisit and potentially renable this setting https://github.com/opensearch-project/security/issues/3185
- Related https://github.com/opensearch-project/security/issues/3185

[Build Break] Disable gradlew build cache to ensure most up-to-date dependencies

---

.github/actions/create-bwc-build/action.yaml
.github/actions/run-bwc-suite/action.yaml
.github/workflows/ci.yml
.github/workflows/code-hygiene.yml
.github/workflows/plugin_install.yml

Backport 5e8f12c from #3186.
Disable gradlew build cache to ensure most up-to-date dependencies
We suspect that we are seeing the snapshot build of opensearch be cached in some circumstances and not cached in others that is creating a mix of build failures that are hard to interpret.
Follow up issue to revisit and potentially renable this setting https://github.com/opensearch-project/security/issues/3185
- https://github.com/opensearch-project/security/issues/3185
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of- …

[Backport 2.x][Build Break] Disable gradlew build cache to ensure most up-to-date dependencies

---

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java

Backport https://github.com/opensearch-project/security/pull/3094 to 1.x

[Backport 1.x] Reverse order of setUserInfoInThreadContext and addSecurityRoles to resolve ConcurrentModificationException on bulk request (#3094)

---

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java

Backport https://github.com/opensearch-project/security/pull/3094 to 1.3

[Backport 1.3] Reverse order of setUserInfoInThreadContext and addSecurityRoles to resolve ConcurrentModificationException on bulk request (#3094)

---

src/main/java/org/opensearch/security/DefaultObjectMapper.java

If Jackson can't parse JSON body it throws `IOException` which contains the whole request body including hashes, passwords and so on. This property was added in 2.9 version, so the body will be excluded from logs. Instead, Jackson adds `UNKNOWN` for the source and provides the property name it can't parse.
So exception now looks like that:
```java
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "password" (class org.opensearch.security.securityconf.impl.v7.InternalUserV7), not marked as ignorable (10 known properties: "opendistro_security_roles", "enabled", "backend_roles", "service", "attributes", "reserved", "hidden", "description", "hash", "static"])
at [Source: UNKNOWN; line: 1, column: 299] (through reference chain: …
```

Exclude sensitive info from the jackson serialization stacktraces

---

src/main/java/org/opensearch/security/dlic/rest/validation/CredentialsValidator.java

Reacting to changes from the backport of https://github.com/opensearch-project/OpenSearch/pull/9262. 
This reason the main branch of Security is not encountering these errors is because the affected class was removed in https://github.com/opensearch-project/security/pull/2900 and the change has not been backported yet.
@willyborankin are you planning to backport https://github.com/opensearch-project/security/pull/2900?
Maintenance …

[2.x] React to Compressor changes from core from #9262

---

codecov.yml

Adding code coverage exclusions on files that are creating code coverage measurement issues.
- Related https://github.com/opensearch-project/security/issues/3137
Will be checking the codecov output on this PR and expect it to come back clean.  Might need to iterate a couple times to make sure the max threshold % amount is correct.

Add code coverage exclusions on false positives

---

.github/dependabot.yml

Prefixes the dependabot commit message with `[2.x]` for PRs against the 2.x branch.
Maintenance

[2.x] Add [2.x] to dependabot commit message

---

.github/dependabot.yml

Adds dependabot.yml to 1.x branch. This PR adds dependabot.yml directly to 1.x branch. With all of the dependabot PRs against main, labels like `backport 2.x`, `backport 1.x` and `backport 1.3` must be added to the PR in order to trigger backport bot to backport the PR to the respective branches. This process is manual and causes drifts between release branches if the labels are not added to the PR.
I am creating a PR to add dependabot.yml directly in 2.x and 1.x to keep all of the release branches up to date. 
The PR against 1.x includes an automatic label of `backport 1.3` so that 1.x and 1.3 can stay synchronized.
Maintenance
By submitting this pull request, I confirm that my contribution …

[1.x] Add dependabot.yml

---

.github/workflows/ci.yml

Noticed in several results of
https://github.com/opensearch-project/security/actions/runs/5978371801/job/16220344142?pr=3123 that the code coverage upload had failed silently, and the annotations make it look like many tests were not executed.  Since in this job there were 9 failures at the same time, adding retry mechanism as well to prevent blind restarting of workflows.
Solution sourced from this stackoverflow question "How to automatically retry github action jobs on failure?" [1]
- [1] https://stackoverflow.com/questions/71574593/how-to-automatically-retry-github-action-jobs-on-failure
For more information on following Developer Certificate of Origin and signing off your …

Retry code coverage upload on failure

---

src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/OnBehalfOfConfig.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/integrationTest/resources/config.yml
src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/auth/internal/NoOpAuthenticationBackend.java
src/main/java/org/opensearch/security/authtoken/jwt/EncryptionDecryptionUtil.java
src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModel.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV6.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/org/opensearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/org/opensearch/security/securityconf/impl/v7/ConfigV7.java
src/main/java/org/opensearch/security/ssl/util/ExceptionUtils.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/user/AuthCredentials.java
src/main/java/org/opensearch/security/util/KeyUtils.java
src/test/java/org/opensearch/security/authtoken/jwt/EncryptionDecryptionUtilsTest.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java
src/test/resources/restapi/securityconfig_nondefault.json

Merge OBO Authentication into 'main' branch
New Feature
**Major Components:**
- `JwtVendor`: assemble the jwt based OBO token.
- `OnBehalfOfAuthenticator`: the authentication backend for validate OBO Token
- `CreateOnBehalfOfTokenAction`: the endpoint of creation of OBO Token
**Major Testing Components:**
- `JwtVendorTest`: Unit tests for JwtVendor
- `OnBehalfOfAuthenticatorTest`: Unit tests for OBO authentication backend
- `OnBehalfOfAuthenticationTest`: Integration test for OBO issuing endpoints
* Resolve #2945 
* Resolve https://github.com/opensearch-project/security/issues/3177
* Relate #2573  …

OnBehalfOf authenticator and token generator

---

.github/workflows/ci.yml

Backport of d7d7f626042a42626bacd25de4af178b8dc37e18 from #3242
(cherry picked from commit d7d7f626042a42626bacd25de4af178b8dc37e18)

[Backport 2.x] Retry code coverage upload on failure (#3242)

---

.github/actions/run-bwc-suite/action.yaml
.github/workflows/ci.yml
bwc-test/build.gradle
bwc-test/src/test/java/SecurityBackwardsCompatibilityIT.java

Opening up a PR to describe the issues faced with BWC tests with the security plugin installed and solicit feedback.
Thanks to the work that @scrawfor99 did in [core](https://github.com/opensearch-project/OpenSearch/pull/8900) to supply security settings to testClusters to be able to run the initial wait for cluster yellow checks with a URL that includes the right protocol (`https` when security is enabled) along with a username and password to authenticate the request.
I ran into 4 hurdles to get this to run:
1. Initially the cluster didn't form. After a lot of frustration, I ended up finding that by supplying `network.bind_host` and `network.publish_host` to both 127.0.0.1 it resolved the issue. These could probably be combined into a single `network.host`, but I chose to keep them …

Enable security for bwc tests

---

src/main/java/org/opensearch/security/DefaultObjectMapper.java
src/main/java/org/opensearch/security/NonValidatingObjectMapper.java

Same as https://github.com/opensearch-project/security/pull/3195.
Excluded sensitive info for java stacktrace:
- YAML object mapper as well
- NonValidatingObjectMapper
- defaulOmittingObjectMapper
More details see https://github.com/FasterXML/jackson-core/wiki/JsonParser-Features#misc-other

Prevent raw request body as output in serialization error messages

---

build.gradle
src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RolesApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionRequestContentValidatorTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesApiActionRequestContentValidatorTest.java
src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java

After RFC 6901 was introduced
and the implementation was added to Jackson,
there is no need to keep the `com.jayway.jsonpath:json-path` library in our source code,
so we can replace current validation with Jackson's `JsonPointer` class.
Besides added missing tests for:
- `RoleRequestContentValidator`
- `AuditRequestContentValidator`
https://github.com/opensearch-project/security/issues/3245

[Refactor] Remove json-path from deps and use JsonPointer instead

---

src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RolesMappingApiAction.java
src/main/java/org/opensearch/security/dlic/rest/validation/EndpointValidator.java
src/test/java/org/opensearch/security/dlic/rest/api/AbstractApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/InternalUsersApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/validation/EndpointValidatorTest.java

The resent refactoring of the REST APIs: https://github.com/opensearch-project/security/pull/3123 introduce a regression in how roles-mapping verification has worked before. 
The old solution verified only hidden roles both for internal users and roles mapping, while new was too strict and forbid to do it for both.
This PR fixes the problem and uses the same logic as it was before. 
- In case of roles-mapping it verifies only a role associated with it that the role is not hidden.      
- In case of internal users it verifies that a role is not hidden and roles-mapping associated with the role is mutable
So verification was split and added to the corresponding ActionApi class which is more convenient as it was before.
Tests for such functionality were added as well.  
By submitting this …

[BUG] Fix roles verification for roles mapping and internal users

---

build.gradle
src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RolesApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionRequestContentValidatorTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesApiActionRequestContentValidatorTest.java
src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java

Backport 14574dd108cefbd634ab5af8e5f13dba00a5681f from #3262

[Backport 2.x] [Refactor] Remove json-path from deps and use JsonPointer instead #3262 

---

build.gradle

Use version of org.apache.commons:commons-lang3 defined in core
https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/version.properties#L42
Fixes issue seen on spotless upgrade PR against 2.x: https://github.com/opensearch-project/security/pull/3298
Maintenance

Use version of org.apache.commons:commons-lang3 defined in core

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/3306 to 2.x

[Backport 2.x] Use version of org.apache.commons:commons-lang3 defined in core

---

build.gradle
plugin-security.policy
src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java

Netty has logic to use the BouncyCastlePemReader if BouncyCastle is located on the class path. The BouncyCastle provider loaded properly in netty, but was failing to read the private key with permissions issues that failed silently. With netty, if one PemReader fails they will fall back to the next which is only capable of reading keys in the PKCS#8 format. 
The regression in PKCS#1 keys happened when bouncycastle was upgraded from jdk15on to jdk15to18.
This PR adds permissions to ensure that netty can read the PKCS#1 keys.
This PR also cleans up the policy file to have a single entry for `permission java.util.PropertyPermission "*","read,write";` because the other entries are redundant.
Open Questions:
- There is a test in SSLTest to ensure PKCS#1 keys can be read. Why did that test not …

Fix permissions issues while reading keys in PKCS#1 format

---

src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/RolesMapping.java

Add integration test case for OBO hostmapping
Test Enhancement
* Resolve https://github.com/opensearch-project/security/issues/3222

[Feature/Extension] Add integration test case for OBO hostmapping

---

build.gradle

Manual backports of https://github.com/opensearch-project/security/pull/3295 and https://github.com/opensearch-project/security/pull/3293 to 2.x
The automatic backport PRs are stale and I don't have a way to update them via Github UI.
- https://github.com/opensearch-project/security/pull/3298
- https://github.com/opensearch-project/security/pull/3304

[Backport 2.x] bump com.diffplug.spotless to 6.21.0 and com.github.wnameless.json:json-base to 2.4.2

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/http/SecurityHttpServerTransport.java
src/main/java/org/opensearch/security/http/SecurityNonSslHttpServerTransport.java
src/main/java/org/opensearch/security/ssl/OpenSearchSecuritySSLPlugin.java
src/main/java/org/opensearch/security/ssl/http/netty/SecuritySSLNettyHttpServerTransport.java
src/test/java/org/opensearch/security/test/plugin/UserInjectorPlugin.java
src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java

Maintenance
* Relate https://github.com/opensearch-project/OpenSearch/pull/9415

Add tracer for getHttpTransports

---

.github/workflows/ci.yml

Seeing a ton of CI failures due to code coverage upload failures.  I'd like to fix this - but I'd rather keep the builds flowing in until we have a better solution.
E.g: https://github.com/opensearch-project/security/actions/runs/6153593099/job/16697726519?pr=3339
- Related https://github.com/opensearch-project/security/issues/2649

Disable codecov from failing CI if there is an upload issue

---

.github/workflows/maven-publish.yml

Backport bec360afd7973c7acff8e92e34906d241c72affd from #3370

[Backport 2.x] dependabot: bump aws-actions/configure-aws-credentials from 3 to 4

---

build.gradle

Backpor 660e2da1fada1fcf949233a79bfddb2adb280e45 from #3366

[Backport 2.x] dependabot: bump org.springframework:spring-beans from 5.3.29 to 5.3.30

---

build.gradle

Backport 283c3be8244dff5d6efc19ec10e82e81098dee4f from #3368

[Backport 2.x] dependabot: bump org.apache.ws.xmlschema:xmlschema-core from 2.3.0 to 2.3.1

---

src/main/java/org/opensearch/security/auth/BackendRegistry.java

Change warning message No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic' to trace
- Resolves #3273

Change log message from warning to trace on WWW-Authenticate challenge

---

.github/workflows/auto-release.yml
.github/workflows/backport.yml

Backport of https://github.com/opensearch-project/security/pull/3395 to `2.x`

[Backport] [2.x] dependabot: bump tibdex/github-app-token from 2.0.0 to 2.1.0 (#3395)

---

build.gradle

Backport https://github.com/opensearch-project/security/commit/b52e762bc449f67d5332a9702040c0f18b2eb986 from https://github.com/opensearch-project/security/pull/3390

[Backport 2.x] dependabot: bump org.springframework:spring-core from 5.3.29 to 5.3.30

---

build.gradle

Backport https://github.com/opensearch-project/security/commit/9caa098a52c1e155889d70a80127f92b25ac8a35 from https://github.com/opensearch-project/security/pull/3391

[Backport 2.x] dependabot: bump org.gradle.test-retry from 1.5.4 to 1.5.5

---

src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/AuditApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/legacy/LegacySecurityConfigApiActionTests.java

Change routs for audit and security configuration PUT methods. 
The previous configuration used the `{name}` parameter which is confusing since `config` the only allowed value for this parameter. This PR changes routes' configuration and removes useless validation for them.  
Note: We do not need to change documentation for endpoints and keep backward compatibility. e.g. Audit endpoint  https://opensearch.org/docs/latest/security/access-control/api/#audit-logs
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-orig …

[Refactor] Change HTTP routes for Audit and Config PUT methods  

---

build.gradle

Backport https://github.com/opensearch-project/security/commit/826bdebc8c1c017868f5226191e9ff419e42642f from https://github.com/opensearch-project/security/pull/3393

[Backport 2.x] dependabot: bump com.google.errorprone:error_prone_annotations from 2.21.1 to 2.22.0

---

.github/workflows/automatic-merges.yml

Allow for automatic merging of dependabot changes after checks pass
- Related https://github.com/opensearch-project/OpenSearch/issues/10211

Allow for automatic merging of dependabot changes after checks pass

---

plugin-security.policy

Backport to 1.x from #3289
We did not do it, while 1.x version has the same problem as 2.x branch. Moved only permissions.

[Backport 1.x] Fix permissions issues while reading keys in PKCS#1 format

---

src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/org/opensearch/security/util/AuthTokenUtils.java
src/test/java/org/opensearch/security/authtoken/jwt/AuthTokenUtilsTest.java

Setup auth token utils for obo
Enhancement, New feature
* Resolve https://github.com/opensearch-project/security/issues/3238

[Enhancement] Setup auth token utils for obo

---

src/integrationTest/java/org/opensearch/security/IpBruteForceAttacksPreventionTests.java
src/integrationTest/java/org/opensearch/security/IpBruteForceAttacksPreventionWithDomainChallengeTests.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/auth/HTTPAuthenticator.java
src/main/java/org/opensearch/security/http/HTTPBasicAuthenticator.java
src/main/java/org/opensearch/security/http/HTTPClientCertAuthenticator.java
src/main/java/org/opensearch/security/http/HTTPProxyAuthenticator.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/main/java/org/opensearch/security/http/proxy/HTTPExtendedProxyAuthenticator.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
src/test/java/org/opensearch/security/auth/limiting/AddressBasedRateLimiterTest.java
src/test/java/org/opensearch/security/auth/limiting/UserNameBasedRateLimiterTest.java
src/test/java/org/opensearch/security/cache/DummyHTTPAuthenticator.java

* Category: Refactoring
Prior to this change, the ip auth failure listener was not called upon challengeAuthenticator check invocation, which caused AddressBasedRateLimiter to not be invoked. With this change AddressBasedRateLimiter will be invoked upon multiple wrong requests from an ip
- Resolves https://github.com/opensearch-project/security/issues/2686
Integration Testing (Adds a new test to verify the change)
When cluster was setup with Basic http challenge:
<details>
<summary>Before:</summary>
```console
java.lang.AssertionError: Expected status code is '401', but was '200'. Response body '{
"user" : "User [name=simple-user-2, backend_roles=[], requestedTenant=null]",
"user_name" : "simple-user-2",
"user_requested_tenant" : null,
"remote_address" : "127.0.0.3:54025",
"backend_roles" …
```

Refactors reRequestAuthentication to call notifyIpAuthFailureListener before sending the response to the channel

---

config/roles.yml
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
src/test/java/org/opensearch/security/securityconf/SecurityRolesPermissionsTest.java
src/test/resources/restapi/internal_users.yml
src/test/resources/restapi/roles.yml
src/test/resources/restapi/roles_mapping.yml

Instead of setting `SECURITY_UNSUPPORTED_RESTAPI_ALLOW_SECURITYCONFIG_MODIFICATION` settings to update security configuration using `PATCH` or `PUT` a new permission was added: `restapi:admin/config/update`.
So far I decided to keep this flag as it is due to a backward compatibility and log a deprecation message that these settings will be removed in the future. Maybe it is better to remove it completely.
Besides, added the missed test for `SecurityConfigApiAction`
https://github.com/opensearch-project/security/issues/2577 …

Support security config updates on the REST API using permission

---

src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java

Update custom serialization min supported version, should be 2.11.0 since the features backport [1] was merged.
- [1] https://github.com/opensearch-project/security/pull/3444 
- Resolves https://github.com/opensearch-project/security/issues/3456
⚠️ I will be bypassing approval to merge this change to unblock the pipeline as soon as all of the `backward-compatibility*` tests have passed.

[Build Break] Update custom serialization min supported version

---

tools/hash.sh

* Redirect deprecation messages to stderr to differentiate between the two streams to make debugging and troubleshooting more efficient.
- Resolves #2485  

Redirect deprecation messages to stderr.

---

config/roles.yml
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SecurityConfigApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
src/test/java/org/opensearch/security/securityconf/SecurityRolesPermissionsTest.java
src/test/resources/restapi/internal_users.yml
src/test/resources/restapi/roles.yml
src/test/resources/restapi/roles_mapping.yml

Backport e4a1b77e9259c019a8ef4728495260468954d6af from #3264

[Backport 2.x] Support security config updates on the REST API using permission (#3264)

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/ssl/OpenSearchSecuritySSLPlugin.java
src/main/java/org/opensearch/security/ssl/transport/SecuritySSLNettyTransport.java

Add tracer to fix the breaking issue.
- #3462

Add tracer to Transport

---

.github/workflows/automatic-merges.yml

With this change version increment PRs can be automatically merge by opensearch-trigger-bot.
- Resolves: #3408

Adds opensearch trigger bot to discerning merger list to allow automatic merges

---

src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java

Backport fb82bbbfcc133fa4ae0bba227c881f7a6ebbe7bd from #3467

[Backport 2.x] Add missing license header (#3467)

---

build.gradle

Checkstyle is already declare in  [plugins](https://github.com/opensearch-project/security/blob/87520741566eaa4ea609441a1f53f3cef4a9674c/build.gradle#L65), not need for extra line.
#3355 

Remove Checkstyle redundant implementation.

---

.github/workflows/automatic-merges.yml

Backports #3474 via commit 999339e7ea3043f6be9342685b7e7c70b5dd55ae
Since the original file was not present in 1.3 line, this PR adds the file too. (Essentially backports https://github.com/opensearch-project/security/pull/3408 as well)

[Backport 1.3] Adds opensearch trigger bot to discerning merger list to allow automatic merges (#3474)

---

.github/workflows/automatic-merges.yml

Backports #3474 via commit 999339e7ea3043f6be9342685b7e7c70b5dd55ae)
Not sure why manual backport was required as there were no conflicts

[Backport 2.11] Adds opensearch trigger bot to discerning merger list to allow automatic merges (#3474)

---

build.gradle

Bump snappy-java to address the following potential vulnerabilities.
https://www.cve.org/CVERecord?id=CVE-2023-43642
https://www.cve.org/CVERecord?id=CVE-2023-34453
https://www.cve.org/CVERecord?id=CVE-2023-34454
https://www.cve.org/CVERecord?id=CVE-2023-34455
A similar change has already been pushed into the 2.x branches so this is effectively a backport.
https://github.com/opensearch-project/security/pull/3435
Manually built and ran the security plugin according to the [developer guide](https://github.com/opensearch-project/security/blob/1.3/DEVELOPER_GUIDE.md#building).
For more information on following Developer Certificate of Origin and signing off your commits, please …

Bump snappy-java to address CVE

---

DEVELOPER_GUIDE.md

- Related to https://github.com/opensearch-project/security/issues/3415

[2.11] Updates developer guide to reflect admin:admin changes

---

.github/workflows/automatic-merges.yml

Backports #3474 via commit 999339e7ea3043f6be9342685b7e7c70b5dd55ae
Not sure why automatic backport failed as there were no conflicts

[Backport 2.x] Adds opensearch trigger bot to discerning merger list to allow automatic merges (#3474)

---

.github/actions/start-opensearch-with-one-plugin/action.yml
.github/workflows/plugin_install.yml
DEVELOPER_GUIDE.md
tools/install_demo_configuration.bat
tools/install_demo_configuration.sh

Reverts
- #3493
- #3490 
- #3414
Due to build breaks, we are reverting all changes related to admin:admin password change from 2.11
- Resolves https://github.com/opensearch-project/security/issues/3511

[Reverts] Demo configuration script requires admin password

---

.github/workflows/automatic-merges.yml

Backports #3474  via commit 999339e7ea3043f6be9342685b7e7c70b5dd55ae
Since the original file was not present in 1.3 line, this PR adds the file too. (Essentially backports https://github.com/opensearch-project/security/pull/3408 as well)

[Backports 1.x] Adds opensearch trigger bot to discerning merger list to allow automatic merges (#3474)

---

DEVELOPER_GUIDE.md

* Replaced the asterisk symbol to prevent potential confusion when naming folders. In a later section of the document, the asterisk symbol is reintroduced and should be used accordingly.
* Added `-p` to `mkdir` command to allow it to create subfolders if needed.

Get OpenSearch version from gradle properties

---

build.gradle

Unblocks CI on main by resolving the following:
```console
* What went wrong:
Execution failed for task ':integTestRemote'.
> Could not resolve all dependencies for configuration ':testRuntimeClasspath'.
> Conflicts found for the following modules:
- com.google.errorprone:error_prone_annotations between versions 2.22.0 and 2.10.0
- org.checkerframework:checker-qual between versions 3.38.0 and 3.19.0
```
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.m …

Fixes CI failure due to dependency conflicts

---

DEVELOPER_GUIDE.md

- Replaced the asterisk symbol to prevent potential confusion when naming folders. In a later section of the document, the asterisk symbol is reintroduced and should be used accordingly.
- Added `-p` to `mkdir` command to allow it to create subfolders if needed.
Backport from PR #3457.

[Backport 2.x] Get OpenSearch version from gradle properties.

---

src/main/java/org/opensearch/security/configuration/PrivilegesInterceptorImpl.java
src/test/java/org/opensearch/security/multitenancy/test/MultitenancyTests.java
src/test/resources/multitenancy/roles_mapping.yml
src/test/resources/multitenancy/roles_tenants.yml

When tenants were considered readonly an deny list was used, this could be prone to error, switch to an allow list instead.  Added tests to confirm prevent and new state.
(cherry picked from commit 0914f8ce51d25203a2a5dd9ba133d82e10cfed45)

[Backport 2.x] For read-only tenants filter with allow list

---

src/main/java/org/opensearch/security/configuration/PrivilegesInterceptorImpl.java
src/test/java/org/opensearch/security/multitenancy/test/MultitenancyTests.java
src/test/resources/multitenancy/roles_mapping.yml
src/test/resources/multitenancy/roles_tenants.yml

When tenants were considered readonly an deny list was used, this could be prone to error, switch to an allow list instead.  Added tests to confirm prevent and new state.
(cherry picked from commit 4e962f22a39b22ee4dd7619bfee72544aaae61b0)

[Forwardport 1.x] For read-only tenants filter with allow list

---

.github/workflows/auto-release.yml

Before this change release notes workflow required release notes to be present in tag, with this change release notes will not need to be backported. They can be but will not need to be.

Updates auto release notes workflow to fetch notes from main

---

src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java

Code coverage of OBO Authentication
Enhancement
* Resolve https://github.com/opensearch-project/security/issues/3101

Code coverage of OBO Authentication

---

src/integrationTest/java/org/opensearch/test/framework/testplugins/AbstractRestHandler.java
src/main/java/org/opensearch/security/dlic/rest/validation/EndpointValidator.java
src/test/java/org/opensearch/security/dlic/rest/api/AccountApiActionConfigValidationsTest.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiActionValidationTest.java

Backports https://github.com/opensearch-project/security/pull/3467 via fb82bbbfcc133fa4ae0bba227c881f7a6ebbe7bd
Manual backport is required to address white space conflicts in relevant files

[Backport 2.11] Add missing license header (#3467)

---

src/main/java/org/opensearch/security/filter/DelegatingRestHandler.java
src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
src/test/java/org/opensearch/security/filter/DelegatingRestHandlerTests.java
src/test/java/org/opensearch/security/filter/SecurityRestFilterUnitTests.java

Utilizes the DelegatingRestHandler from the companion core PR to ensure that the security plugin delegates to implementations of the wrapped Rest Handler.
Bug fix
https://github.com/opensearch-project/security/issues/3422

Use DelegatingRestHandler to delegate to the original handler

---

build.gradle

- Remove an unused JVM setting for integration tests
- Fixed an issue where you couldn't run non-resource tests unless you had CI_ENVIRONMENT set to normal on your machine (Already fixed in main)
- Fixed an issue where code coverage was always run after tests completed (Already fixed in main)
- Related https://github.com/opensearch-project/security/pull/3388

Minor comments follow up for integration tests

---

src/integrationTest/java/org/opensearch/security/CrossClusterSearchTests.java

Reverts opensearch-project/security#3526 as the exit criteria was not satisfied.

Revert "Refactors CrossClusterSearchTests to fix flaky behavior"

---

src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java

Add Input Validation for generate obo token endpoint
Enhancement
* Resolve https://github.com/opensearch-project/security/issues/3558
* Relate https://github.com/opensearch-project/security/issues/2573
Integration Test

[Enhancement] Input Validation for generate obo token endpoint

---

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
src/main/java/org/opensearch/security/filter/SecurityRequest.java
src/main/java/org/opensearch/security/filter/SecurityRequestChannelUnsupported.java
src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
src/main/java/org/opensearch/security/filter/SecurityRestUtils.java
src/main/java/org/opensearch/security/ssl/http/netty/Netty4HttpRequestHeaderVerifier.java
src/test/java/org/opensearch/security/filter/SecurityRestUtilsTests.java

This PR removes some duplication in the Netty4HttpRequestHeaderVerifier around the `/_plugins/_security/api/authtoken` endpoint and also abstracts the logic for where authentication is skipped into helper methods.
Maintenance

[Cleanup] Remove duplication in Netty4HttpRequestHeaderVerifier

---

.github/dependabot.yml

Removes prefix from dependabot's commit message since it is removed when generating releases notes ultimately.

Removes prefix from dependabot's commit message

---

.github/workflows/automatic-merges.yml

Bumps [peternied/discerning-merger](https://github.com/peternied/discerning-merger) from 2 to 3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/peternied/discerning-merger/releases">peternied/discerning-merger's releases</a>.</em></p>
<blockquote>
<h2>v3 Release</h2>
<ul>
<li>Allows specifying how the merge is performed, with default of 'squash' method</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/peternied/discerning-merger/commit/07eafb14c195a2c23b291f6b008a686589cfb545"><code>07eafb1</code></a> Support passing merge type</li>
<li>See full diff in <a href="https://github.com/peternied/discerning-merger/compare/v2...v3">compare view</a></li>
</ul>
</details> …

Bump peternied/discerning-merger from 2 to 3

---

src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/resources/config.yml
src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/auth/HTTPAuthenticator.java
src/main/java/org/opensearch/security/auth/internal/NoOpAuthenticationBackend.java
src/main/java/org/opensearch/security/authtoken/jwt/EncryptionDecryptionUtil.java
src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModel.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV6.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/org/opensearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/org/opensearch/security/securityconf/impl/v7/ConfigV7.java
src/main/java/org/opensearch/security/ssl/util/ExceptionUtils.java
src/main/java/org/opensearch/security/user/AuthCredentials.java
src/main/java/org/opensearch/security/util/AuthTokenUtils.java
src/main/java/org/opensearch/security/util/KeyUtils.java
src/test/java/org/opensearch/security/authtoken/jwt/AuthTokenUtilsTest.java
src/test/java/org/opensearch/security/authtoken/jwt/EncryptionDecryptionUtilsTest.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java
src/test/resources/restapi/securityconfig_nondefault.json

Backport feature OnBehalfOf Authentication into `2.x` branch
New feature
* Relate #3555 
_For completely resolve the above issue, we still need to backport #3421 into `2.x` branch. However, since that change also includes something unrelated to OBO Auth, we will backport that separately._
Unit Tests + Integration Tests included

[Backport 2.x] Feature OnBehalfOf Authentication

---

build.gradle
src/test/java/org/opensearch/security/dlic/dlsfls/AbstractDlsFlsTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/RenameFieldResponseProcessorTest.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterConfiguration.java
src/test/resources/dlsfls/roles_flsdls_rename_processor.yml
src/test/resources/dlsfls/roles_mapping_flsdls_rename_processor.yml

Adds FLS/DLS tests for RenameFieldResponseProcessor
* Category Enhancement
* Why these changes are required? Testing to ensure the RenameFieldResponseProcessor complies with FLS/DLS security
* What is the old behavior before changes and new behavior after changes? No difference
#2890
Is this a backport? If so, please add backport PR # and/or commits #: No, but it does need to be backported.
N/A
> ## Draft PR for `RenameFieldResponseProcessor` FLS/DLS …

Add RenameFieldResponseProcessor FLS/DLS tests

---

src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/auth/HTTPAuthenticator.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java

Switch to `supportsImpersonation` check for http auth backend + wrap JwtParserBuilder with `doPrivileged`
Reference to @cwperks's [comment](https://github.com/opensearch-project/security/pull/3563#discussion_r1365539239):
>As a default implementation the authDomain could have:
>
>```
>default boolean supportsImpersonation() { return true; }
>```
>
>and any authDomain that does not support it can override:
>
>```
>@Override
>public boolean supportsImpersonation() { return false; }
>```
Enhancement
* Related https://github.com/opensearch-project/security/pull/3563
It has already been included in `2.x`  …

[Forwardport main] Switch to `supportsImpersonation` check for http auth backend and add Privileged Action for `JwtParserBuilder `

---

build.gradle
checkstyle/checkstyle.xml
src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeyProvider.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetProvider.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetRetriever.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SelfRefreshingKeySet.java
src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/main/java/org/opensearch/security/authtoken/jwt/KeyPaddingUtil.java
src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/MockIpdServer.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SelfRefreshingKeySetTest.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SingleKeyHTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/TestJwk.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/TestJwts.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
src/test/java/org/opensearch/security/authtoken/jwt/KeyPaddingUtilTest.java

Switch from `org.apache.cxf.rs.security.jose` to `com.nimbusds.jose.jwk`.
* Relate https://github.com/opensearch-project/security/issues/3267
* Resolve https://github.com/opensearch-project/security/issues/3555

[Backport 2.x] Switch from `org.apache.cxf.rs.security.jose` to `com.nimbusds.jose.jwk`.

---

src/integrationTest/java/org/opensearch/security/ResourceFocusedTests.java
src/integrationTest/java/org/opensearch/security/rest/CompressionTests.java
src/integrationTest/java/org/opensearch/security/rest/GzipTests.java
src/main/java/org/opensearch/security/http/SecurityNonSslHttpServerTransport.java
src/main/java/org/opensearch/security/ssl/http/netty/Netty4ConditionalDecompressor.java
src/main/java/org/opensearch/security/ssl/http/netty/SecuritySSLNettyHttpServerTransport.java

Resolves an issue with decompression that can lead to concurrent gzipped requests failing. This removes the `@Sharable` annotation from the `Netty4ConditionalDecompressor` and creates a new instance of the decompressor on channel initialization.
`Netty4ConditionalDecompressor` is an `HttpContentDecompressor` which is a subclass of `HttpContentDecoder` - a stateful handler. Netty docs on `@Sharable` annotation: https://netty.io/4.0/api/io/netty/channel/ChannelHandler.Sharable.html
Bug fix
- https://github.com/opensearch-project/OpenSearch/issues/10802
Tested by running OpenSearch w fluentbit and Merge_Log on. See files below which can reproduce the issue from the linked error.
I opened this PR …

Use new instance of Decompressor on channel initialization

---

src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java

HTTPJwtAuthenticator fails initialization of JwtParser due to InvocationTargetException when calling jwtParserBuilder.build().
This is causing API calls with JWT token to fail.
It is root cause of failures identified in https://github.com/opensearch-project/security-dashboards-plugin/pull/1617 and only exists in 2.12.0
I verified manually by running `jwt_auth.test.ts` and making curl calls that this behavior works as expected on `main` and `2.11`
- Unblocks https://github.com/opensearch-project/security-dashboards-plugin/pull/1617
Manual Testing.
Spin up a 2.x cluster without this change & run jwt_auth.test.ts. They would fail with ```TimeoutError: Waiting for at least one element to be located By(xpath, //*[@id="osdOverviewPageHeader__title"])
Wait timed out after 15011msError: Waiting …
```

Wraps HTTPJwtAuthenticator jwtParserBuilder.build call with access controller to prevent AccessControlException

---

src/integrationTest/java/org/opensearch/security/DefaultConfigurationTests.java
src/integrationTest/java/org/opensearch/security/SecurityConfigurationTests.java
src/integrationTest/java/org/opensearch/security/http/CertificateAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java
src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java

I was doing some inspection around the OBO feature and noticed some items to clean up.
Unit + Integration tests

OnBehalfOf tokens odds and ends

---

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java

Fixes bug where the SAMLAuthenticator expects the provided key to be base64 encoded otherwise it would cause saml-authenticator initialization to fail.
Front-end tests pass exchange-key in URL encoded format. Another solution to this would be to remove `getDecoder()` completely. This works and I've tested it locally as well.
I proceed with the approach to remove decoding as that was the state prior to library change.
The tests didn't catch this because they use `abc` as exchange_key. I've updated it to reflect the exchange key used in front-end tests: `6aff3042-1327-4f3d-82f0-40a157ac4464`. 
Backport of this PR will unblock frontend CI
- Resolves: https://github.com/opensearch-project/security/issues/3604
Existing tests.
By submitting this …

Remove unneeded decoding from AuthTokenProcessorHandler

---

.github/workflows/ci.yml
src/integrationTest/java/org/opensearch/security/CrossClusterSearchTests.java

This change addresses an issue that can arise when setting up two clusters at the same time whereby, port mismatches can occur as outlined in issue #3425. However, after much testing this issue does not appear to be tied to this integration test or it could be related to a windows environment issue.
* Category: Test fix
* Why these changes are required? : No changes are to be merged except the removal of @ignore given the findings of this tests. The integration test for CrossClusterSearchTests appears to have been fixed with unrelated changes to the main branch. 
* What is the old behavior before changes and new behavior after changes? : All the changes listed below except remove the commit that removes @ignore stemmed from an error on my end [please dismiss it] due to an issue in my …

Re-enables CrossClusterSearchTests

---

.github/dependabot.yml

Backports https://github.com/opensearch-project/security/pull/3548 via https://github.com/opensearch-project/security/commit/2e7c3616d8f1325cb62be51af84e23da6a0f081d
Manual backport was needed since there were conflicts in the commit message between main and 2.x

[Backport 2.x] Removes prefix from dependabot's commit message (#3548)

---

src/integrationTest/java/org/opensearch/security/ResourceFocusedTests.java
src/integrationTest/java/org/opensearch/security/rest/CompressionTests.java
src/integrationTest/java/org/opensearch/test/framework/AsyncActions.java
src/integrationTest/resources/log4j2-test.properties

Improve asynchronous test cases format
- Created AsyncActions to help generate and collect results
- Use of CountDownLatch to trigger requests to run concurrently
- Shrunk existing test cases by 2.7 times
- Follow up to some outstanding feedback from https://github.com/opensearch-project/security/pull/3583

[Refactor] Improve asynchronous test cases format

---

.github/dependabot.yml

Backports #3548 via 2e7c3616d8f1325cb62be51af84e23da6a0f081d
Manual backport was needed since there were conflicts in the commit message between main and 1.x

[Backport 1.x] Removes prefix from dependabot's commit message (#3548)

---

src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java

Change info message with jwtString to trace.
JWT tokens is sensitive information and should not be logged on info level.

Change log message with jwtString from INFO to TRACE

---

src/integrationTest/java/org/opensearch/security/http/ServiceAccountAuthenticationTest.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/privileges/SecurityIndexAccessEvaluator.java
src/main/java/org/opensearch/security/user/User.java
src/test/java/org/opensearch/security/IntegrationTests.java
src/test/java/org/opensearch/security/UserServiceUnitTests.java
src/test/resources/internal_users.yml

Limit service account permission
Enhancement
* Resolve https://github.com/opensearch-project/security/issues/3201

Limit service account permission

---

bwc-test/gradle/wrapper/gradle-wrapper.properties
bwc-test/gradlew
gradle/wrapper/gradle-wrapper.properties
gradlew

Update to Gradle 8.4
- Related https://github.com/opensearch-project/OpenSearch/issues/10334
N/A

Update to Gradle 8.4

---

build.gradle
bwc-test/gradle/wrapper/gradle-wrapper.properties
bwc-test/gradlew
gradle/wrapper/gradle-wrapper.properties
gradlew

Backport of https://github.com/opensearch-project/security/pull/3638 to `2.x`

[Backport] [2.x] Update to Gradle 8.4 (#3638)

---

.github/workflows/ci.yml
.github/workflows/integration-tests.yml
.github/workflows/plugin_install.yml

Add Java 11/17/21 matrix for plugin install, test and integration test checks
Part  of https://github.com/opensearch-project/OpenSearch/issues/10334
N/A

Add Java 11/17/21 matrix for plugin install, test and integration test checks

---

src/integrationTest/java/org/opensearch/security/DefaultConfigurationTests.java
src/integrationTest/java/org/opensearch/security/SecurityConfigurationTests.java
src/integrationTest/java/org/opensearch/security/http/CertificateAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/http/ServiceAccountAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java
src/main/java/org/opensearch/security/authtoken/jwt/ExpiringBearerAuthToken.java
src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/main/java/org/opensearch/security/identity/SecurityTokenManager.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/privileges/SecurityIndexAccessEvaluator.java
src/main/java/org/opensearch/security/securityconf/impl/SecurityDynamicConfiguration.java
src/main/java/org/opensearch/security/user/User.java
src/main/java/org/opensearch/security/user/UserFilterType.java
src/main/java/org/opensearch/security/user/UserService.java
src/test/java/org/opensearch/security/IntegrationTests.java
src/test/java/org/opensearch/security/UserServiceUnitTests.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java
src/test/java/org/opensearch/security/identity/SecurityTokenManagerTest.java
src/test/resources/internal_users.yml

Backport Service Accounts into 2.x
New feature
* Resolve https://github.com/opensearch-project/security/issues/3557
PRs:
* Relate #3607 
* Relate #2786 
* Relate #3538 
* Relate #3593 

[Backport 2.x] Backport Service Accounts into 2.x

---

src/main/java/org/opensearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/org/opensearch/security/securityconf/impl/v7/ConfigV7.java
src/test/java/org/opensearch/security/SlowIntegrationTests.java
src/test/java/org/opensearch/security/securityconf/impl/v6/ConfigV6Test.java
src/test/java/org/opensearch/security/securityconf/impl/v7/ConfigV7Test.java

Fixes test failures seen in multiple PRs:
- https://github.com/opensearch-project/security/actions/runs/6739586788/job/18321350189?pr=3637
```
org.opensearch.security.SlowIntegrationTests > testDelayInSecurityIndexInitialization FAILED
java.lang.AssertionError: Expected IOException here due to red cluster state
at __randomizedtesting.SeedInfo.seed([BD5A8547B6467745:994D254B5D5310AA]:0)
at org.junit.Assert.fail(Assert.java:89)
at org.opensearch.security.SlowIntegrationTests.testDelayInSecurityIndexInitialization(SlowIntegrationTests.java:228)
```
and
```
1> org.opensearch.OpenSearchException: Settings for signing key is missing. Please specify at least the option signing_key with a shared secret.
1> 	at org.opensearch.security.authtoken.jwt.JwtVendor.createJwkFromSettings(JwtVendor.java:81) …
```

OnBehalfOf tokens feature is disabled by default

---

src/integrationTest/java/org/opensearch/security/http/AsyncTests.java
src/integrationTest/java/org/opensearch/security/http/BasicAuthTests.java
src/integrationTest/java/org/opensearch/test/framework/AsyncActions.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java

Opening a PR that adds a test to ensure that requests during a cache invalidation succeed and fail if any unsuccessful status code is detected. This is related to adding an automated test for https://github.com/opensearch-project/security/issues/1961
I'm currently encountering a couple of issues and am able to reproduce a separate concurrency error, but not the OptionalDataException.
This test will fail if both of these PRs are reverted:
- https://github.com/opensearch-project/security/pull/1970
- https://github.com/opensearch-project/security/pull/2765
When the above 2 PRs are reverted, the test case fails with:
```
Caused by: org.opensearch.OpenSearchException: Instance User [name=admin, backend_roles=[admin], requestedTenant=null] of class class org.opensearch.security.user.User is not …
```

Validate requests are not impacted during security cache invalidation

---

src/integrationTest/java/org/opensearch/security/http/AsyncTests.java
src/integrationTest/java/org/opensearch/security/http/BasicAuthTests.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java

Backport https://github.com/opensearch-project/security/commit/850b7dc959024f3868d4e874d10eb1ebbd605ee6 from https://github.com/opensearch-project/security/pull/3637.

[Backport 2.x] Validate requests are not impacted during security cache invalidation

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/3657 to `2.x`

[Backport] [2.x] Bump org.apache.httpcomponents:fluent-hc from 4.5.13 to 4.5.14 (#3657)

---

build.gradle
src/integrationTest/java/org/opensearch/test/framework/testplugins/AbstractRestHandler.java
src/main/java/org/opensearch/security/dlic/rest/validation/EndpointValidator.java
src/test/java/org/opensearch/security/dlic/rest/api/AccountApiActionConfigValidationsTest.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiActionValidationTest.java

Reverts 2 PRs added after the 2.11.0 release that should not be in the 2.11.1 release:
- https://github.com/opensearch-project/security/pull/3486
- https://github.com/opensearch-project/security/pull/3480
https://github.com/opensearch-project/security/issues/3650

[2.11] Revert PRs added to 2.11 that are not part of 2.11.1 release

---

plugin-security.policy
src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/saml/SamlHTTPMetadataResolver.java
src/main/java/org/opensearch/security/opensaml/integration/CleanerFactory.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityX509CRLBuilder.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityX509CRLImpl.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityX509CertificateBuilder.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityX509CertificateImpl.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityXMLObjectProviderInitializer.java

In order to exclude `permission org.opensearch.secure_sm.ThreadPermission "modifyArbitraryThread";` we must use the dedicated `cleaners` thread factory in `OpenSearch`. Since `OpenSAML` packages are sealed it it impossible to replace `CleanerSupport` class with our own solution. Instead we have to change configuration of how such objects should be parsed. There are only 2 classes in the library which use `CleanerSupport`:
- `X509CertificateImpl`
- `X509CRLImpl` 
This fix uses the same solution as in `OpenSAML` and replaces `CleanerSupport` with our custom implementation `CleanerFactory`.
#2989
For more information on following Developer Certificate of Origin and signing off …

Integrates OpenSAML 4.3 with SAML authenticator

---

.github/workflows/ci.yml

Fix the association of code coverage results with source code.  You'll have seen how this was broken because we stopped getting the comment on PRs with coverage information.  My apologies for breaking this in the most recent change to centralized the CC runs.
- Resolves https://github.com/opensearch-project/security/issues/2649
✅ Inspection CC report on this PR, see [[link]](https://github.com/opensearch-project/security/pull/3668#issuecomment-1802489151). …

Fix the association of code coverage results with source code 

---

src/main/java/org/opensearch/security/httpclient/HttpClient.java
src/test/java/org/opensearch/security/httpclient/HttpClientTest.java
src/test/resources/auditlog/endpoints/routing/configuration_valid.yml

Allow adding URLs to the OpenSearch cluster with support for both http:// and https:// for external logs.
- #3321 
Tested using *RouterTest.java* and manual testing.

Allow adding URL to the cluster

---

.github/workflows/ci.yml
.github/workflows/integration-tests.yml
.github/workflows/plugin_install.yml

Backport of https://github.com/opensearch-project/security/pull/3641 to `2.x`

[Backport] [2.x] Add Java 11/17/21 matrix for plugin install, test and integration test checks (#3641)

---

build.gradle
src/main/java/org/opensearch/security/filter/NettyAttribute.java
src/main/java/org/opensearch/security/filter/SecurityResponse.java
src/test/java/org/opensearch/security/filter/SecurityRestUtilsTests.java

This PR runs the License Header check with the checkstyle CI check to ensure that PRs contain licenses on top of new files. This PR also adds the license on 2 files where its missing today.
Maintenance
- Resolves https://github.com/opensearch-project/security/issues/3471
- Resolves https://github.com/opensearch-project/security/issues/3691

Run precommit checks before checkstyle task

---

src/integrationTest/java/org/opensearch/security/IndexOperationsHelper.java
src/integrationTest/java/org/opensearch/security/http/AsyncTests.java
src/integrationTest/java/org/opensearch/security/http/BasicAuthTests.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/matcher/ClusterMatchers.java
src/integrationTest/java/org/opensearch/test/framework/matcher/IndexStateIsEqualToMatcher.java
src/main/java/org/opensearch/security/user/User.java
src/test/java/org/opensearch/security/auditlog/compliance/RestApiComplianceAuditlogTest.java

This change backports #1970 in order to fix the OptionalDataException issue encountered on the 1.3.x line. 
The original change did not have any tests but #3637 added tests, so I backported those as well and the changes required to support them. This resulted in changes to the TestSecurityConfig.User class, the addition of a IndexStateIsEqualToMatcher and User.java. 
- Resolves #3531
- Backports #1970 
- Backports https://github.com/opensearch-project/security/pull/3637
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifica …

[Backport 1.3] Prevent OptionalDataException from User data structures

---

src/main/java/org/opensearch/security/tools/democonfig/Certificates.java
src/main/java/org/opensearch/security/tools/democonfig/ExecutionEnvironment.java
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java

Adds 4 config lines that were missed in the original PR: https://github.com/opensearch-project/security/blob/deff84265cd22badf9cca02a3240aeb000acb439/tools/install_demo_configuration.sh#L384C1-L388C1

Adds missing default security config lines when updating opensearch.yml

---

src/test/java/org/opensearch/security/auditlog/compliance/RestApiComplianceAuditlogTest.java

Considering what is tested - the auto log events that are creating when a test cluster starts up.  This isn't a useful test case, removing.
- Resolves #3730

Removing flaky test case testAutoInit

---

.github/workflows/code-hygiene.yml
build.gradle

The Spotless Gradle Plugin brings in a transitive dependency on Eclipse Core Runtime 3.26.100.  That version is impacted by a CVE.
This forces the newest version, currently 3.29.0.  Note that newer versions than 3.26 require JDK17+ to run spotless.
Fixes #3688 

Force newer version of Eclipse core transitive dependency (resolves CVE-2023-4218)

---

build.gradle

Extracts `spring_version` to a variable so it can be re-used. This will cut down slightly on maintenance where dependabot can make multiple PRs to update this version.
Recent examples:
- https://github.com/opensearch-project/security/pull/3744
- https://github.com/opensearch-project/security/pull/3743
Maintenance

Add spring_version variable to have single instance of spring version

---

src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java

Makes sure that for response with a body they are returning the expected content type
- Related to https://github.com/opensearch-project/security/issues/3718

Validate content type of responses

---

src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java

Backports c30c084b911d00f94683bcccc0d1acd32461a001 from #3719

[Backport 2.x] Validate content type of responses (#3719)

---

src/test/java/org/opensearch/security/auditlog/compliance/RestApiComplianceAuditlogTest.java

Backport ca8aafe3ff75b1dbc39f4ed857d5c385e0025bcf from #3732.

[Backport 2.x] Removing flaky test case testAutoInit (#3732)

---

src/integrationTest/java/org/opensearch/security/SearchOperationTest.java
src/main/java/org/opensearch/security/httpclient/HttpClient.java
src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java

Bug fix. Shrink, or resize operations weren't properly evaluated. More in the task:  https://github.com/opensearch-project/security/issues/2141
https://github.com/opensearch-project/security/issues/2141

Shrink operation privileges evaluation

---

src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java
src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java

Performance Analyzer (PA) sets up a transport interceptor that [wraps a TransportChannel](https://github.com/opensearch-project/performance-analyzer/blob/main/src/main/java/org/opensearch/performanceanalyzer/transport/PerformanceAnalyzerTransportChannel.java#L147-L151). The security plugin has logic to [extract the inner channel](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java#L100-L103) so that the rest of SecuritySSLRequestHandler uses the original channel. There is logic before the inner channel extraction to determine whether to use JDK Serialization if the incoming message was received from a [node running OS <= 2.10](https://github.com/opensearch-project/security/blob/main/src/main/java/org/op …

Better support wrapping of TransportChannel

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/3784 to `2.x`

[Backport] [2.x] Bump commons-io:commons-io from 2.15.0 to 2.15.1 (#3784)

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/3786 to `2.x`

[Backport] [2.x] Bump com.diffplug.spotless from 6.23.0 to 6.23.3 (#3786)

---

build.gradle

Force resolve logback-classic to 1.3.12 to address https://github.com/advisories/GHSA-vmq6-5m68-f53m

Upgrade logback-classic to address CVE CVE-2023-6378

---

build.gradle

Bumps zookeeper to 3.9.1 to resolve: CVE-2023-44981
Bumps xmlsec to 2.3.4 to resolve: CVE-2023-44483
Bumps jackson-databind to match core: https://github.com/opensearch-project/OpenSearch/blob/1.3/buildSrc/version.properties#L11

[1.3] Resolve zookeeper, databind, xmlsec to address CVE

---

build.gradle
plugin-security.policy
src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/saml/Saml2SettingsProvider.java
src/main/java/com/amazon/dlic/auth/http/saml/SamlHTTPMetadataResolver.java
src/main/java/org/opensearch/security/opensaml/integration/CleanerFactory.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityX509CRLBuilder.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityX509CRLImpl.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityX509CertificateBuilder.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityX509CertificateImpl.java
src/main/java/org/opensearch/security/opensaml/integration/SecurityXMLObjectProviderInitializer.java
src/test/java/com/amazon/dlic/auth/http/saml/MockSamlIdpServer.java

Backported PRs:
- #2987
- #2927
- #3651
- #3690 
into 2.x

[Backport 2.x] Backport OpenSAML 4.3.0 to 2.x

---

release-notes/opensearch-security.release-notes-1.3.14.0.md

Add release notes for 1.3.14 release

[1.3] Add release notes for 1.3.14 release

---

src/main/resources/static_config/static_roles.yml

- https://github.com/opensearch-project/security/issues/3791

[BUG-3791] Adds missing permissions in logstash static role

---

src/integrationTest/java/org/opensearch/security/DefaultConfigurationTests.java
src/integrationTest/java/org/opensearch/security/DoNotFailOnForbiddenTests.java
src/integrationTest/java/org/opensearch/security/PointInTimeOperationTest.java
src/integrationTest/java/org/opensearch/security/SecurityConfigurationTests.java
src/integrationTest/java/org/opensearch/security/SslOnlyTests.java
src/integrationTest/java/org/opensearch/security/http/CommonProxyAuthenticationTests.java
src/integrationTest/java/org/opensearch/security/http/ExtendedProxyAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java

There was some question of what permissions around DNFOF applied to scenarios with the stats API, adding in test cases that confirm these APIs are behaving as expected.

Add do not fail on forbidden test cases around the stats API

---

src/integrationTest/java/org/opensearch/security/http/LdapAuthenticationTest.java
src/main/java/org/opensearch/security/user/User.java

Fixes an issue when a scroll context is created by an LDAP User. There is a subclass in the system for [LDAP Users](https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/auth/ldap/LdapUser.java) that in some circumstances can lead to issues with the scroll query. The issue is always reproducible when using rest impersonation to impersonate the LDAP User when authenticating as an internal user. 
See steps to reproduce the issue here: https://github.com/opensearch-project/security/issues/3582#issuecomment-1843560293
This PR includes a test that will fail if the fix within User.java is reverted. 
Bug fix
https://github.com/opensearch-project/security/issues/3582 …

Fix issue when scroll is created with LDAP user

---

.github/actions/start-opensearch-with-one-plugin/action.yml
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java

- Resolves https://github.com/opensearch-project/security/issues/3842
- automated tests

Renames initialAdminPassword to OPENSEARCH_INITIAL_ADMIN_PASSWORD to be compliant with opensearch naming convention

---

DEVELOPER_GUIDE.md
build.gradle
src/test/java/org/opensearch/security/SlowIntegrationTests.java
src/test/java/org/opensearch/security/util/Repeat.java
src/test/java/org/opensearch/security/util/RepeatRule.java

Explicitly adds a command after setup to create an index and wait for cluster green which produces the expected IOException.
The pseudo code of this test is:
1. Setup a cluster, but forbid allocating any shards so cluster is red
2. If cluster is red as expected, then remove the restriction on shard allocation and wait for cluster to turn green
3. Wait another 10s to ensure that the security index is initialized.
I believe this test is not succeeding, because the cluster is coming up as green initially since there is no data (and hence no shards) in the cluster. By adding an explicit command to create an index, the test ensures that the shards are not being allocated and cluster is indeed red. …

Fix flaky test SlowIntegrationTests.testDelayInSecurityIndexInitialization

---

build.gradle

Resolve logback classic to 1.2.13 for https://github.com/advisories/GHSA-gm62-rw4g-vrc4

[Backport 1.3] Bump Logback Classic to 1.2.13 (resolves CVE-2023-6481)

---

.github/actions/start-opensearch-with-one-plugin/action.yml
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/tools/democonfig/Installer.java
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
src/test/java/org/opensearch/security/tools/democonfig/InstallerTests.java
src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java
src/test/java/org/opensearch/security/tools/democonfig/util/NoExitSecurityManager.java

Storing an admin password in a text file that can be available to anyone that has access to config folder at any time could be potentially vulnerable. Although, originally added with the perception to support autonomous process to easily read from the config folder, we now only allow passing the admin password through environment variable as it is session-scoped. Further, we don't print the password to the logs to avoid any traces.
- Related to https://github.com/opensearch-project/security/issues/3847
- automated tests …

Removes support for txt file for specifying initial admin password and prevents password from being printed in the logs

---

config/roles.yml
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java

Adds 2 flow-framework related roles to the plugin: read only and fully access.
Adds flow-framework system indices to demo scripts as well.
manual testing of roles

Add flow framework system indices and roles

---

src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java

Resolves an issue with permissions in the SAML auth flow after merge of https://github.com/opensearch-project/security/pull/3671
This backports code from https://github.com/opensearch-project/security/pull/2987 that wraps the call to `instantiateAAA` in `AccessController.doPrivileged`. Expand the section below to see the stack trace with permissions error.
<details>
<summary>Permission issue stack trace</summary>
[2023-12-15T23:45:14,828][WARN ][o.o.s.s.ReflectionHelper ] [6c7e67b914eb] Unable to enable 'com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticator' due to java.lang.reflect.InvocationTargetException
[2023-12-15T23:45:14,832][ERROR][o.o.s.s.DynamicConfigModelV7] [6c7e67b914eb] Unable to initialize auth domain saml_auth_domain=AuthcDomain [http_enabled=true, transport_enabled=false, …

[2.x] Backport SAML permissions changes in DynamicConfigModelV7

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/3857 to `2.x`

[Backport] [2.x] Bump org.checkerframework:checker-qual from 3.40.0 to 3.42.0 (#3857)

---

.github/workflows/ci.yml

Backport of https://github.com/opensearch-project/security/pull/3859 to `2.x`

[Backport] [2.x] Bump github/codeql-action from 2 to 3 (#3859)

---

config/roles.yml
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java

Backports b996eb15640c56d657758a58279578e38c047202 from #3851

[Backport 2.x] Add flow framework system indices and roles (#3851)

---

.github/workflows/ci.yml

This PR fixes the CI / report-coverage check by using the corresponding upload artifact package. I verified this change by creating a PR on my local fork and checked that the artifacts are uploaded to the CI summary after the build is complete.
Maintenance
- https://github.com/opensearch-project/security/issues/3878
For more information on following Developer Certificate of Origin and signing off your commits, please …

Fix the CI / report-coverage check by switching to corresponding actions/upload-artifact@v4

---

src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java

Add deprecation check for `jwt_header` setting
- Related https://github.com/opensearch-project/security/issues/3886

Add deprecation check for `jwt_header` setting

---

build.gradle

Switched to more reliable OpenSearch Lucene snapshot location
- Resolves https://github.com/opensearch-project/security/issues/3597

Switched to more reliable OpenSearch Lucene snapshot location

---

src/integrationTest/java/org/opensearch/security/PointInTimeOperationTest.java

Re-enables 2 PIT integration tests that were previously disabled. This adds a @Before method to clean up all PITs created from previous test cases to ensure each test case runs pristinely.
Test fix
- https://github.com/opensearch-project/security/issues/3424 …

Re-enable disabled PIT integration tests

---

src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java

When the demo configuration script fails when no initial admin password is set, it does not provide helpful output telling the user how to set the initial admin password. This PR provides some helpful output indicating what variable the user should modify in order for the setup to succeed.
Changed test asserting output 

Improve messaging on how to set initial admin password

---

src/main/java/org/opensearch/security/filter/NettyAttribute.java
src/main/java/org/opensearch/security/filter/OpenSearchRequest.java
src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java

This is cherry-pick from https://github.com/opensearch-project/security/pull/3514 to use the channel properties instead of type-casting
Closes  https://github.com/opensearch-project/security/issues/3911
The change is covered by existing test suites

Refactor SSL handler retrieval to use HttpChannel / TranportChannel APIs instead of typecasting

---

src/main/java/org/opensearch/security/filter/NettyAttribute.java
src/main/java/org/opensearch/security/filter/OpenSearchRequest.java
src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java

Backport of https://github.com/opensearch-project/security/pull/3917 to `2.x`

[Backport] [2.x] Refactor SSL handler retrieval to use HttpChannel / TranportChannel APIs instead of typecasting (#3917)

---

src/integrationTest/java/org/opensearch/security/ConfigurationFiles.java
src/integrationTest/java/org/opensearch/security/SecurityAdminLauncher.java
src/integrationTest/java/org/opensearch/security/SecurityConfigurationBootstrapTests.java
src/integrationTest/java/org/opensearch/security/SecurityConfigurationTests.java
src/integrationTest/java/org/opensearch/security/api/CreateResetPasswordTest.java
src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/action/configupdate/TransportConfigUpdateAction.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/InitializationIntegrationTests.java
src/test/java/org/opensearch/security/configuration/ConfigurationRepositoryTest.java
src/test/java/org/opensearch/security/test/SingleClusterTest.java

- Backport of #3810 from 045d4ef8a5d9bb8470e03c1b4d7cc68847b986cb

[Backport 2.x] Allow TransportConfigUpdateAction when security config initialization has completed (#3810)

---

config/roles.yml

update security analytics roles with custom log type cluster permissions
Security Analytics Role enhancement
Custom Log Types were introduced in `2.10` but they were only available for `admin` users. This pr allows `non-admin` users to access custom log types.
For more …

Update security analytics roles to include custom log type cluster permissions

---

src/main/java/org/opensearch/security/securityconf/impl/SecurityDynamicConfiguration.java

Protect config object from concurrent modification issues
We've had rare reports of modification exceptions from customers around the config objects.  Using a lock object to protect the internal collection from modification on other threads and changing the behavoir of the getter to pass a copy of the collection instead of direct collection references.
- Resolves #3404

Protect config object from concurrent modification issues

---

src/main/java/org/opensearch/security/compliance/ComplianceConfig.java
src/test/java/org/opensearch/security/auditlog/compliance/ComplianceConfigTest.java
src/test/java/org/opensearch/security/auditlog/config/AuditConfigSerializeTest.java

There are some cases that use datetime that were causing code coverage fluctuations depending on when the tests are run, fixed this by adding a date provider and new unit tests.
- Related #3137
- New Issue #3950

Add test coverage for ComplianceConfig

---

src/main/java/org/opensearch/security/ssl/transport/SecuritySSLNettyTransport.java
src/test/java/org/opensearch/security/ssl/transport/SecuritySSLNettyTransportTests.java

This change increases code coverage for the SecuritySSLNettyTransport class. In the middle of 12/23, a few unit tests were added to give coverage to different parts of the class. This change builds on these existing changes. 
Box three of https://github.com/opensearch-project/security/issues/3137

Improve code coverage for SSLNettyTransport class

---

config/config.yml
src/integrationTest/java/org/opensearch/security/http/LdapAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/http/LdapTlsAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/AuthzDomain.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV6.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/org/opensearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/org/opensearch/security/securityconf/impl/v7/ConfigV7.java
src/main/java/org/opensearch/security/setting/DeprecatedSettings.java
src/test/java/org/opensearch/security/setting/DeprecatedSettingsTest.java
src/test/resources/restapi/invalid_config.json
src/test/resources/restapi/security_config.json
src/test/resources/restapi/securityconfig.json
src/test/resources/restapi/securityconfig_nondefault.json

Remove the transport_enabled setting in config.yml and its related code in DynamicConfigModelV6/7, ConfigV6/7, associated tests. Additionally add handlers in Config files to handle when transport_enabled is still used within the config.yml file while alerting the user with a message in startup that this setting can be safely removed from the config.
Enhancement
#3191 states that since the transport client has been removed, there is no need for the transport_enabled config and its related code to exist in the codebase, so this ticket removes that unnecessary code.
Nothing.
#3191 
Is this …

[Enhancement-3191] `transport_enabled` setting on an auth domain and authorizer may be unnecessary after transport client removal 

---

src/main/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/AuditApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/NodesDnApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RolesApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RolesMappingApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/TenantsApiAction.java

Coming from https://github.com/opensearch-project/opensearch-api-specification/pull/179 which flags a couple of false positives because of mismatched trailing slash.

Fix: remove unnecessary trailing slashes in APIs.

---

build.gradle

This PR bumps spotless to bump the transient dependency on org.eclipse.platform:org.eclipse.core.resources@3.18.100 -> org.eclipse.platform:org.eclipse.core.resources@3.19.100. In turn this should stop scanners from reporting the project as vulnerable to: https://nvd.nist.gov/vuln/detail/CVE-2023-4218. 
I was not able to easily move just the Eclipse dependency because it seems that the package causing the flagging org.eclipse.platform:org.eclipse.core.resources@3.18.100 does not have a straight path forward to the recommended versions listed on the CVE. However, https://security.snyk.io/package/maven/org.eclipse.platform:org.eclipse.core.resources/3.19.100 reports that this version should remove the issue while https://security.snyk.io/package/maven/org.eclipse.platform:org.eclipse.core.re …

Bump spotless (6.24.0 -> 6.25.0) to bump eclipse resources (3.18 -> 3.19) 

---

src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java

This PR adds a new DLS filtering test that checks for the union of different dls settings related to different roles attached to the same user.
Enhancement
These tests were previously not included, which makes testing bugs including the one in #2556 difficult. Adding this test makes it easy to recreate these bugs if they appear in the future. Additionally the data in these test cases matches the examples provided in the bug case so these tests were also used to determine if the bug in the ticket is actually happening. Since these two tests pass, I personally don't think this bug is reproducible.
* What is the old behavior before changes and new behavior after …

[BUG-2556] Add new DLS filtering test

---

config/roles.yml

Adding the default role for query insights plugin
Related issues and PRs
- https://github.com/opensearch-project/OpenSearch/issues/11186
- https://github.com/opensearch-project/OpenSearch/pull/11903
- https://github.com/opensearch-project/OpenSearch/pull/11904
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …

Admin role for Query insights plugin

---

config/roles.yml

We added a new API to the alerting plugin to support enhancements to the UI ([link](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesAction.kt#L13)). The enhancements allow users to configure per query, and per bucket monitors that can query remote clusters via the UI. Previously, such monitors could only be configured using devtools/API commands.
In addition, we added support for configuring cluster metrics monitors which can execute various API ([link to full list of supported API](https://opensearch.org/docs/latest/observing-your-data/alerting/per-cluster-metrics-monitors/#supported-apis)) against remote clusters. The new API is used by the frontend to also support creating these monitors via the UI.
* …

[Backport 2.12] v2.12 update roles.yml with new API for experimental alerting plugin feature #4027

---

config/roles.yml

We added a new API to the alerting plugin to support enhancements to the UI ([link](https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/action/GetRemoteIndexesAction.kt#L13)). The enhancements allow users to configure per query, and per bucket monitors that can query remote clusters via the UI. Previously, such monitors could only be configured using devtools/API commands.
In addition, we added support for configuring cluster metrics monitors which can execute various API ([link to full list of supported API](https://opensearch.org/docs/latest/observing-your-data/alerting/per-cluster-metrics-monitors/#supported-apis)) against remote clusters. The new API is used by the frontend to also support creating these monitors via the UI.
* …

v2.12 update roles.yml with new API for experimental alerting plugin feature

---

build.gradle

This change adds an exclusion for the transitive logback-core dependency that the Security plugin was still using as a test dependency. 
This should resolve the flagging of CVE-2023-6378 even though we should not have been directly impacted. 

Add exlusion for logback-core to resolve CVE-2023-6378

---

build.gradle

Following: https://github.com/opensearch-project/OpenSearch/pull/12317 in core, this PR increases the version used for bouncycastle in the Security plugin. This is an attempt to correct the intermittent failures described here: [#3299](https://github.com/opensearch-project/security/issues/3299)

Update Bouncy Castle Version from *jdk15to18 to *jdk18on 

---

build.gradle

This change forces is a manual backport of the same type of change in #4049 . Instead of excluding the the logback-classic and logback-core transient dependencies we now just force them to be versions 1.2.13. This resolves CVE-2023-6378 

[Manual backport of #4049] Force logback to version 1.2.13 to resolve CVE-2023-6378

---

build.gradle

Manual backport `add96ad601ccf99b8420fe9dc95ece601357f8bd` from #4074

[Backport 2.x] Bump com.google.googlejavaformat:google-java-format from 1.19.1 to 1.20.0 (#4074)

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/ssl/util/SSLConfigConstants.java
src/test/java/org/opensearch/security/ssl/util/SSLConfigConstantsTest.java

Since TLSv1.1 was deprecated in 2021 (RFC [8996](https://datatracker.ietf.org/doc/html/rfc8996)) and new deprication message was added.
By default JDK 18 uses TLS 1.2 and latest stable 1.3

Add deprecate message that TLSv1 and TLSv1.1 support will be removed in the next major version

---

src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java

Logs details about the password validations done when demo clusters are created. The current message "Password $ADMIN_PASSWORD is weak. Please re-try with a stronger password." doesn't provide enough information communicate what the user needs to set the password to.
* See #4048 - to improve UX when creating test OpenSearch clusters by logging details on password requirements
* Before: OS 2.12 fails to start with message `Password sample@1029 is weak. Please re-try with a stronger password.`
* After: security plugin fails to start with message `Password weakpassword failed validation with error "Weak password". Please re-try with a minimum 8 character …

Log password requirement details in demo environment

---

build.gradle

Manual backport 493fe02b4ed64d54a02cbac63a5e28d3bdd3de0d and c73776d40e80ffc7b644829d204c4432b79011da from #4087

[Backport 2.x] Bump kafka_version from 3.5.1 to 3.7.0

---

src/main/java/org/opensearch/security/tools/democonfig/Installer.java
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java

This PR solves an edge case where someone is trying to load custom internal_users.yml onto a docker distribution while trying to use the demo configuration for setting up security in v2.12.0
* So distributions like Docker and HELM can load custom internal_users.yml with a hashed custom admin password that is not `admin` string.
* Unable to support internal_users.yml in HELM without a work-around. With this fix, no workaround is needed.
- Resolves #4098
- Resolves #3891
Automated testing
For more information on following Developer Certificate of …

Updates admin password string only if correct hash is present

---

build.gradle

Backport 9806699cc727489c8d46637986f7860e81ed7066 from #4123

[Backport 2.x] Bump org.awaitility:awaitility from 4.2.0 to 4.2.1 (#4123)

---

build.gradle

Backport 582d2cddbe3c23640370698647752b39ff58eed0 from #4126

[Backport 2.x] Bump com.google.errorprone:error_prone_annotations from 2.25.0 to 2.26.1 (#4126)

---

config/roles.yml
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java

This PR should add query assistant role and new ml system indices

Add query assistant role and new ml system indices

---

src/integrationTest/java/org/opensearch/security/http/RolesMappingTests.java

Adds a simple test to verify backend role to role mapping. There currently are not tests in the integrationTest framework around role mapping. I'm introducing this test fixture with a plan to expand this to test all forms of roles mapping like direct user mapping, backend role mapping, and_backend_role mapping and host mapping. 
Maintenance
Related: https://github.com/opensearch-project/security/issues/4084
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/C …

Add simple roles mapping integ test to test mapping of backend role to role

---

.github/workflows/ci.yml
build.gradle

The underlying issue associated with Pom validation was fixed in OpenSearch [1], this causes the 'hack' that was used to unblock pom generation in security to start causing problems in the distribution builds.
- [1] https://github.com/opensearch-project/OpenSearch/pull/12807
- Fixes https://github.com/opensearch-project/security/issues/4160
Added new CI test that executes the same job used by the distribution build and checks the expected artifacts exist

Remove Pom task dependenices rewrite

---

build.gradle
src/integrationTest/java/org/opensearch/security/AbstractDefaultConfigurationTests.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationMultiNodeClusterTests.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationMultiNodeClusterUseClusterStateTests.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationSingleNodeClusterTests.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationSingleNodeClusterUseClusterStateTests.java
src/integrationTest/java/org/opensearch/security/SecurityConfigurationBootstrapTests.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/securityconf/impl/SecurityDynamicConfiguration.java
src/main/java/org/opensearch/security/state/SecurityConfig.java
src/main/java/org/opensearch/security/state/SecurityMetadata.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/support/ConfigHelper.java
src/main/java/org/opensearch/security/support/SecurityIndexHandler.java
src/main/java/org/opensearch/security/support/YamlConfigReader.java
src/test/java/org/opensearch/security/configuration/ConfigurationRepositoryTest.java
src/test/java/org/opensearch/security/state/SecurityMetadataSerializationTestCase.java
src/test/java/org/opensearch/security/support/ConfigReaderTest.java
src/test/java/org/opensearch/security/support/SecurityIndexHandlerTest.java

Change the way how the security plugin initialize its configuration. 
The current solution uses poll to upload the default security configuration from each node in the cluster. As result it could lead to the races during initialization of the security index. 
To solve the problem with possible races the new solution uses cluster state and initializes the default configuration only on the management node and after that sends updated cluster state on all other nodes to load the configuration from the index.   
Initialization using cluster state makes things much more simpler and security admin shell script can be removed in the future.
the cluster state for the security plugin is this:
```json
"security": {
"created": "2024-02-27T15:44:44.194028751Z",
"configuration": {
"actiongroups": { …
```

Fix cluster default initialization #1

---

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/main/java/org/opensearch/security/action/onbehalf/CreateOnBehalfOfTokenAction.java
src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
src/main/java/org/opensearch/security/rest/DashboardsInfoAction.java
src/main/java/org/opensearch/security/rest/SecurityHealthAction.java
src/main/java/org/opensearch/security/rest/SecurityInfoAction.java
src/main/java/org/opensearch/security/rest/TenantInfoAction.java

Extracted route path prefixes into contants:
- `/_plugins/_security` - `PLUGIN_ROUTE_PREFIX`
- `/_opendistro/_security` - `LEGACY_PLUGIN_ROUTE_PREFIX`
- `/_plugins/_security/api` - `PLUGIN_API_ROUTE_PREFIX`
- `/_opendistro/_security/api` - `LEGACY_PLUGIN_API_ROUTE_PREFIX`
Same part of #4153 for simplicity of the final PR.

Extract route paths prefixes into constants

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/4193 to `2.x`

[Backport] [2.x] Bump io.dropwizard.metrics:metrics-core from 4.2.15 to 4.2.25 (#4193)

---

config/roles.yml

Add index permissions in query insights role to allow only users with permissions to access top n queries indices.
Related issue: https://github.com/opensearch-project/OpenSearch/issues/11296

Add index permissions for query insights exporters

---

.github/CODEOWNERS
MAINTAINERS.md

This PR moves Dave Lago from the codeowners file, and moves him from active to emeritus maintainer. We need confirmation from @davidlago somehow on making this change.
- Resolves #4234 
No
None

Move Dave Lago to emeritus

---

src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
src/test/java/org/opensearch/security/auditlog/impl/AuditMessageTest.java

This change fixes the bug https://github.com/opensearch-project/security/issues/1849. This change ensures audit logging logs a failed request if request body fails to match content-type header or required parameters.
This change is required to be consistent with user provided configuration of audit logging request body even for failed requests
Before this change, an invalid request (with invalid content or source type parameters) did not get audit_request_body even if request body audit logging is enabled by user because of improper exception handling. After this change, audit_request_body will be generated …

Handle exceptions for adding request body audit log if rest request is invalid

---

plugin-security.policy

[Backport 2.x] Add getProperty.org.bouncycastle.pkcs12.default to plugin-security.policy

---

src/integrationTest/java/org/opensearch/security/ResourceFocusedTests.java
src/integrationTest/java/org/opensearch/security/http/BasicAuthTests.java
src/main/java/org/opensearch/security/http/HTTPBasicAuthenticator.java

Included `Unauthorized` in the body of the challenge response to be consistent with the behavior from 2.10 and before.
* Category
Bug fix
- https://github.com/opensearch-project/security/issues/3803
- https://github.com/opensearch-project/security/issues/4214

Ensure that challenge response contains body

---

.github/workflows/maven-publish.yml
build.gradle

Adds the maven publish workflow for 1.3. This should start publishing plugin zips to the maven repo for consumption.
* Category
Enhancement
Failed backport - https://github.com/opensearch-project/security/issues/4281
Should start publishing zips to maven
https://github.com/opensearch-project/security/issues/4281
Backport of: https://github.com/opensearch-project/security/pull/2438
For more information on …

Add maven publish workflow for 1.3

---

build.gradle
src/main/java/org/opensearch/security/configuration/MaskedField.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java

Backport https://github.com/opensearch-project/security/pull/4275 to 2.x
Resolves https://github.com/opensearch-project/security/issues/4212
Tests confirm backwards compatibility

[Backport 2.x] Replace bouncy castle blake2b

---

.github/workflows/maven-publish.yml

After backporting the failed backport to publish snapshot to maven it seems not to work. After inspection again in main/2.x branches I saw it has a different syntax. That may have been added in subsequent PRs. This copies the same workflow to 1.3 branch to hopefully make it publish again. 

Fix syntax with the publish maven workflow

---

src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/support/SerializationFormat.java
src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
src/test/java/org/opensearch/security/support/Base64HelperTest.java
src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java

This change will prevent new clusters from using the 'custom serialization' format that was causing performance impact with customers in OpenSearch 2.11.
Background: the serialization changes from #2802 introduced issues where for certain serialization headers that were previously very small for over the wire transmission become much larger. The root cause of this was that the JDK serialization process was able to detect duplicate entries and then use an encoding format to make it compressible. Adding this logic into the serialization system from OpenSearch is non-trivial and is not being invested in.
- Related https://github.com/opensearch-project/security/pull/4264
- Related #2802
- Resolves https://github.com/opensearch-project/security/issues/4227
- Resolves …

[2.x] Use predictable serialization logic for transport headers

---

src/main/java/org/opensearch/security/configuration/SecurityIndexSearcherWrapper.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/securityconf/ConfigModelV6.java
src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/main/java/org/opensearch/security/securityconf/SecurityRoles.java
src/test/java/org/opensearch/security/securityconf/SecurityRolesPermissionsV6Test.java
src/test/java/org/opensearch/security/system_indices/SystemIndexPermissionEnabledTests.java

* Category: **Bug Fix**
* Why these changes are required? **User has `system:admin/system_index permission`, but cannot search documents in the custom system index.**
* What is the old behavior before changes and new behavior after changes? **It was modified to not return `EmptyFilterLeafReader` when the system index permission option is enable.**
- Resolves #4188 
- Update `SystemIndexPermissionEnabledTests.testSearchAsNormalUser`

System index permission grants reading access to documents in the index

---

src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/support/SerializationFormat.java
src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
src/test/java/org/opensearch/security/support/Base64HelperTest.java
src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java
src/test/java/org/opensearch/security/transport/SecuritySSLRequestHandlerTests.java

This change will prevent new clusters from using the 'custom serialization' format that was causing performance impact with customers in OpenSearch 2.11.
Background: the serialization changes from #2802 introduced issues where for certain serialization headers that were previously very small for over the wire transmission become much larger.  The root cause of this was that the JDK serialization process was able to detect duplicate entries and then use an encoding format to make it compressible.  Adding this logic into the serialization system from OpenSearch is non-trivial and is not being invested in. 
- Related #2802
- Resolves https://github.com/opensearch-project/security/issues/4227
- Resolves https://github.com/opensearch-project/security/issues/3776
BWC test should cover the …

Use predictable serialization logic for transport headers

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/4293 to `2.x`

[Backport] [2.x] Bump commons-codec:commons-codec from 1.16.1 to 1.17.0 (#4293)

---

src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/FlushCacheApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/MigrateApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/Responses.java
src/main/java/org/opensearch/security/dlic/rest/api/ValidateApiAction.java

Fixed spelling for the `internalSeverError` method in the `org.opensearch.security.dlic.rest.api.Responses` class

Fix spelling

---

src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
src/main/java/org/opensearch/security/support/SnapshotRestoreHelper.java

This PR fixes build errors caused by a recent change in Core where the _filderIndices()_ method got moved from SnapshotUtils to IndexUtils
#4312

fix build errors caused by filterIndices method being moved from SnapshotUtils to IndexUtils

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/4323 to `2.x`

[Backport] [2.x] Bump com.google.errorprone:error_prone_annotations from 2.27.0 to 2.27.1 (#4323)

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/4322 to `2.x`

[Backport] [2.x] Bump org.checkerframework:checker-qual from 3.42.0 to 3.43.0 (#4322)

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/4321 to `2.x`

[Backport] [2.x] Bump org.scala-lang:scala-library from 2.13.13 to 2.13.14 (#4321)

---

src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java

Fixed flaky integration tests, which were introduced in #4255. The node counter was defined as a global variable, as result it counted more nodes then an actual local cluster had.

Fix flaky tests

---

src/integrationTest/java/org/opensearch/security/api/AbstractApiIntegrationTest.java
src/integrationTest/java/org/opensearch/security/api/CertificatesRestApiIntegrationTest.java
src/integrationTest/java/org/opensearch/security/api/SslCertsRestApiIntegrationTest.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/api/CertificatesApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificateInfo.java
src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificateType.java
src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesActionType.java
src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesInfo.java
src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesInfoNodesRequest.java
src/main/java/org/opensearch/security/dlic/rest/api/ssl/CertificatesNodesResponse.java
src/main/java/org/opensearch/security/dlic/rest/api/ssl/TransportCertificatesInfoNodesAction.java

Introduce new endpoint:
- `_plugins/_security/api/certificates` 
- `_plugins/_security/api/certificates/{nodeId}`
which provides information about SSL certificates for each node in the cluster. The endpoint works only with Default key store but not with external key store.  
Path parameters:
- `nodeId` - (Optional, string) The names of particular nodes in the cluster to target. For example, `nodeId1,nodeId2`
Query string parameters:
- `cert_type` - (Optional, string) The SSL certificate type. Expected values are: `http`, `transport` and `all`. The default value is `all`
- `timeout` - node request timeout
HTTP Response:
```json
{
"_nodes" : {
"total" : 0,
"successful" : 0,
"failed" : 0
},
"cluster_name" : "...",
"nodes" : {
"..." : {
"name" : "...",
"certificates" : {
"http" : [{ …
```

[Fix #4280] Introduce new endpoint _plugins/_security/api/certificates

---

src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java
src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java

Related: https://github.com/opensearch-project/security/issues/3723
Currently OpenSearch doesn't support multiple audience for JWT authentication.
I want to pass the audience claims if `aud` value in JWT is at least one of the required audiences.
For example, If I set my OpenSearch security configuration for JWT like below.
I want to pass verification if there is either `project1` or `admin` audience in the JWT token.
This may be useful for some cases, like if someone need to access opensearch for all projects(project1, project2, ....) via `admin` aud.
```yaml
required_audience: project1,admin
```
Please confirm this concept positively.
Thanks in advance.
I added unit tests. …

Support multiple audience for jwt authentication

---

src/main/java/org/opensearch/security/auditlog/config/AuditConfig.java

This is a bugfix of a logging statement that has caused a lot of confusion for our customers.

Made sensitive header log statement more clear

---

build.gradle

Backport f0021823752e67b9310224160857ca38dc770dc4 from #4389.

[Backport 2.x]  Bump com.google.errorprone:error_prone_annotations from 2.27.1 to 2.28.0 (#4389)

---

src/main/java/org/opensearch/security/auth/UserInjector.java
src/test/java/org/opensearch/security/auth/UserInjectorTest.java

Enhances the parsing logic of user injection to support ipv6 addresses.
Bug fix
Issue: https://github.com/opensearch-project/security/issues/4177
Ipv6 IP addresses would throw a parsing error, now it doesn't
Fix: https://github.com/opensearch-project/security/issues/4177
No
Added unit test …

Add support for ipv6 ip address in user injection

---

src/integrationTest/java/org/opensearch/security/api/ActionGroupsRestApiIntegrationTest.java
src/main/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiActionValidationTest.java

Added validation for the action groups `type` key.
#4374 

Adds validation for the action groups type key

---

build.gradle
src/integrationTest/java/org/opensearch/security/FlsAndFieldMaskingTests.java
src/integrationTest/java/org/opensearch/test/framework/matcher/SearchHitDoesContainFieldMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/SearchResponseMatchers.java
src/main/java/org/opensearch/security/configuration/SecurityFlsDlsIndexSearcherWrapper.java

Remove static metaFields list and get version-specific values from core.
The new list obtained from core is: `[_ignored, _routing, _seq_no, _doc_count, _index, _nested_path, _data_stream_timestamp, _field_names, _source, _id, _version, _primary_term]`
This doesn't match the hardcoded list because it removes many of the deprecated fields from [META_FIELDS_BEFORE_7DOT8](https://github.com/opensearch-project/OpenSearch/blob/8883e62a8f3d862739250cff1eb8d3d18680cfa2/server/src/main/java/org/opensearch/index/mapper/MapperService.java#L204-L208) 
When using FLS Includes rules, this list is used as the starting point for all metaFields to include by default.
* Category
Bug fix
- https://github.com/opensearch-project/security/issues/4349
By submitting this pull request, I confirm that my …

Remove static metaFields list and get version-specific values from core

---

build.gradle
src/integrationTest/java/org/opensearch/security/api/AbstractApiIntegrationTest.java
src/integrationTest/java/org/opensearch/security/api/AccountRestApiIntegrationTest.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/auth/internal/InternalAuthenticationBackend.java
src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/SecurityRestApiActions.java
src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
src/main/java/org/opensearch/security/hasher/BCryptPasswordHasher.java
src/main/java/org/opensearch/security/hasher/PasswordHasher.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
src/main/java/org/opensearch/security/tools/Hasher.java
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
src/main/java/org/opensearch/security/user/UserService.java
src/test/java/org/opensearch/security/UserServiceUnitTests.java
src/test/java/org/opensearch/security/UtilTests.java
src/test/java/org/opensearch/security/auth/InternalAuthBackendTests.java
src/test/java/org/opensearch/security/dlic/rest/api/AbstractApiActionValidationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/AccountApiActionConfigValidationsTest.java
src/test/java/org/opensearch/security/dlic/rest/api/InternalUsersApiActionValidationTest.java
src/test/java/org/opensearch/security/hasher/BCryptPasswordHasherTests.java

Manual backport https://github.com/opensearch-project/security/commit/20c524ad994a9cc7d8757999f92f6d2fec6cb8ca from https://github.com/opensearch-project/security/pull/4381. 
Auto-merge failed due to slight differences in code between 2.x and main branches.

[Backport 2.x] Replace BouncyCastle's OpenBSDBCrypt use with password4j for password hashing and verification 

---

src/main/java/org/opensearch/security/filter/DelegatingRestHandler.java

Fix DelegatingRestHandlerTests
Caused by https://github.com/opensearch-project/OpenSearch/pull/13772
N/A

Fix DelegatingRestHandlerTests

---

src/integrationTest/java/org/opensearch/security/DoNotFailOnForbiddenTests.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/test/java/org/opensearch/security/privileges/PrivilegesEvaluatorUnitTest.java

This adds DNFOF support for Cat Aliases API. The behavior prior to this change is that cat alias API would fail with error: no permissions for [indices:admin/aliases/get], even with DNFOF is enabled. Now the behavior is that cat alias API will return the aliases with indices that you have access to. I added a DNFOF test show casing this behavior. 
Bug fix
Fix: #4413 
See description
Fix: #4413
No
Manual testing, added a test case, fixed a unit test
By submitting this pull request, I confirm that my contribution is made …

Add cat/alias support for DNFOF 

---

release-notes/opensearch-security.release-notes-2.15.0.0.md

Adds release notes for 2.15 release
Maintenace
Releasing version 2.15
No release notes, now there is
Fix: #4318 
No
None

Add 2.15 release notes

---

bwc-test/src/test/java/org/opensearch/security/bwc/SecurityBackwardsCompatibilityIT.java

Fixes flaky BWC test. Fixes #4445 
The test `SecurityBackwardsCompatibilityIT.testDataIngestionAndSearchBackwardsCompatibility` had a 1:100 chance to send empty bulk request bodies which would result in 400 Bad Request errors.
* Category: Test fix
* Why these changes are required? The CI was flaky
* What is the old behavior before changes and new behavior after changes? no behavioral change.
- #4445 

Fixed flaky BWC test.

---

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/privileges/ProtectedIndexAccessEvaluator.java

This code change is just in preparation for the change in #4380 as requested in https://github.com/opensearch-project/security/pull/4380#discussion_r1621325450 .
In the course of #4380 , the `SecurityRoles` class will be replaced by a new concept.  This PR already replaces the usages of `SecurityRoles` where no methods are used on it except the `getRoleNames()` method. This method call can be easily replaced by the `Set<String> mappedRoles`, which is computed by `PrivilegesEvaluator` before the `SecurityRoles` instance is created. This change elliminated the coupling of the interfaces that consume that information to the `SecurityRoles` class, thereby enhancing code quality.
* Category:  Refactoring
* Why these changes are required? The changes in #4380 will abolish the `SecurityRoles` …

Replaced uses of SecurityRoles by Set<String> mappedRoles where the SecurityRoles functionality is not needed

---

src/integrationTest/java/org/opensearch/security/AbstractDefaultConfigurationTests.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationMultiNodeClusterTests.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationMultiNodeClusterUseClusterStateTests.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationSingleNodeClusterTests.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationSingleNodeClusterUseClusterStateTests.java

`AbstractDefaultConfigurationTests` used `configurationFolder` as a constant as result all inherited tests could use the same config folder which can be cleaned unpredictably.

Fixes flaky integration tests

---

.github/actions/create-bwc-build/action.yaml
.github/workflows/ci.yml
.github/workflows/code-hygiene.yml
.github/workflows/integration-tests.yml
.github/workflows/maven-publish.yml
.github/workflows/plugin_install.yml
build.gradle
src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
src/main/java/org/opensearch/security/DefaultObjectMapper.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/dlic/rest/api/ConfigUpgradeApiAction.java
src/main/java/org/opensearch/security/hasher/BCryptPasswordHasher.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
src/main/java/org/opensearch/security/support/ConfigHelper.java
src/main/java/org/opensearch/security/support/SecurityIndexHandler.java
src/main/java/org/opensearch/security/util/KeyUtils.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java
src/test/java/org/opensearch/security/tools/democonfig/CertificateGeneratorTests.java
src/test/java/org/opensearch/security/tools/democonfig/InstallerTests.java
src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java
src/test/java/org/opensearch/security/tools/democonfig/util/NoExitSecurityManager.java

Set security plugin 3.0.0 baseline JDK version to JDK-21
Closes https://github.com/opensearch-project/security/issues/4407
N/A

Set security plugin 3.0.0 baseline JDK version to JDK-21

---

src/main/java/org/opensearch/security/configuration/SecurityIndexSearcherWrapper.java
src/test/java/org/opensearch/security/IndexIntegrationTests.java
src/test/java/org/opensearch/security/system_indices/AbstractSystemIndicesTests.java
src/test/java/org/opensearch/security/system_indices/SystemIndexPermissionEnabledTests.java
src/test/resources/system_indices/roles.yml

* Category : Bug Fix
* Why these changes are required? : There was an issue where documents could not be queried without system index permissions, even if the index was not a system index. This has been fixed.
- old : Documents could not be searched without system index permissions when `plugins.security.system_indices.permission.enabled` enabled
- new : Documents in normal indexes can always be searched regardless of system index permissions.
issue: https://github.com/opensearch-project/security/issues/4429 …

Check block request only if system index

---

src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/main/java/org/opensearch/security/securityconf/FlattenedActionGroups.java
src/main/java/org/opensearch/security/securityconf/impl/SecurityDynamicConfiguration.java
src/test/java/org/opensearch/security/securityconf/FlattenedActionGroupsTest.java

This code change is just in preparation for the change in #4380 as requested in https://github.com/opensearch-project/security/pull/4416#pullrequestreview-2106138499 .
This replaces the previous action group resolution algorithm done in ConfigModelV7 by a new one, which has a number of enhancements:
- The new implementation forms an independent class, enhancing testability and use in other components that will be introduced in #4380.
- The new implementation handles action group configurations containing loops gracefully. The old one would wind up StackOverflowErrors.
- The new one pre-computes the resolved action groups, thus enhancing the performance.
* Why these changes are required? - The changes in #4380 will no longer use ConfigModelV7 and thus need an …

New algorithm for resolving action groups

---

src/integrationTest/java/org/opensearch/security/api/TenantsRestApiIntegrationTest.java
src/main/java/org/opensearch/security/dlic/rest/api/TenantsApiAction.java

Added Tenants REST API test
partial fix #4166

Add Tenants REST API test and partial fix #4166

---

src/integrationTest/java/org/opensearch/security/DoNotFailOnForbiddenTests.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/test/java/org/opensearch/security/IntegrationTests.java

The special handling for `do_not_fail_on_forbidden` on cluster actions does not provide any benefits - rather it just causes some inconsistent behavior. See #4485 for the details.
This is part of the work done for #3870
* Category: Enhancement and bug fix
* Why these changes are required? - The present behavior is inconsistent and confusing. Additionally, it does unnecessary computations on index sets, which can potentially decrease action throughput
* What is the old behavior before changes and new behavior after changes? - Both clusters with `do_not_fail_on_forbidden` set to `true`  and to `false` will need the same set of privileges for multi actions and scroll actions. The need to specify `indices:data/read/mget`, `indices:data/read/msearch`, `indices:data/read/mtv`, …

Remove special handling for do_not_fail_on_forbidden on cluster actions

---

src/integrationTest/java/org/opensearch/security/FlsAndFieldMaskingTests.java
src/integrationTest/java/org/opensearch/test/framework/log/LogsRule.java
src/integrationTest/resources/log4j2-test.properties
src/main/java/org/opensearch/security/configuration/SecurityFlsDlsIndexSearcherWrapper.java

Fixes a NullPointerException that occurs on a Closed index request. This fixes an issue seen after the merge of https://github.com/opensearch-project/security/pull/4370 which made a change to get the list of metaFields from the mapperService in core. On close index requests, `indexService.mapperService()` can return null so the call to `indexService.mapperService().getMetadataFields()` throws an NPE.
This fix checks for Close index requests and handles the scenario accordingly. Closed indices are not searchable so there's no need to have a list of metaFields for a closed index.
> The close index API operation closes an index. Once an index is closed, you cannot add data to it or search for any data within the index.
Ref: https://opensearch.org/docs/latest/api-reference/index-apis/close-ind …

Fix NPE getting metaFields from mapperService on a close index request

---

config/roles.yml

Add the new api action names for security analytics threat intel project
Feature Issue: https://github.com/opensearch-project/security-analytics/issues/1117
By submitting this pull request, I …

Add security analytics threat intel action 

---

src/main/java/org/opensearch/security/tools/SecurityAdmin.java

Fixed typo in "Try running securityadmin.sh with -icl (but no -cl) and -nhnv (If that works you need to check your clustername as well as hostnames in your TLS certificates)", changed -cl to -cn as per: https://github.com/opensearch-project/security/issues/4376
Bug fix
-cl does not exist, so it was changed to the correct -cn
Nothing ideally
https://github.com/opensearch-project/security/issues/4376
No
For …

[BUG] Typo in securityadmin.sh hint

---

.github/pull_request_template.md

Signed-off-by: dblock <dblock@amazon.com>
(cherry picked from commit 4f3ea970914b7b70566e1ec7a73be49d4c8335c4)
Backports #4533 via 4f3ea970914b7b70566e1ec7a73be49d4c8335c4
Manual backport was required due to conflicts in the template. …

[Backport 2.x] Update PULL_REQUEST_TEMPLATE to include an API spec change in the checklist. (#4533)

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/configuration/DlsFilterLevelActionHandler.java
src/main/java/org/opensearch/security/configuration/DlsFlsRequestValve.java
src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/main/java/org/opensearch/security/filter/SecurityFilter.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluationContext.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluatorResponse.java

This change is in preparation for #3870 and #4380 .
This cuts off some parts from the quite big and monolithic method `PrivilegesEvaluator.evaluate()` into separate methods and modules.
This achieves several things:
- Better separation of concerns, thus better modularization and thus better understandability, re-usability and testability
- Computations of DLS/FLS privileges are done directly in the DLS/FLS valve code. Thus, if DLS/FLS valve is disabled, no DLS/FLS privileges are computed
- The new class `PrivilegesEvaluationContext` combines commonly needed information for privilege evaluation and thus allows to shorten the parameter lists of many methods in this context. For this PR, only the `PrivilegesEvaluator.evaluate()` method itself is changed, but further adaptions will follow up …

Separated DLS/FLS privilege evaluation from action privilege evaluation

---

release-notes/opensearch-security.release-notes-1.3.18.0.md

Add release notes for 1.3.18 release
Part of https://github.com/opensearch-project/opensearch-build/issues/4763
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#developer-certificate-of-or …

Add release notes for 1.3.18 release

---

src/integrationTest/java/org/opensearch/security/FlsAndFieldMaskingTests.java

Fixes failing tests in FlsAndFieldMaskingTests. 
The tests `flsWithIncludesRulesIncludesFieldMappersFromPlugins` and `testFlsOnAClosedAndReopenedIndex` both used the REST API to create an identical test user. However, the test which executes second would get a 200 Ok REST status instead a 201 Created REST status, as the `PUT` would operate on a resource that already exists. 
This caused the test to fail.
This moves the user to the global user definition of the test.
* Category: Test fix
* Why these changes are required? - The test failed before
* What is the old behavior before changes and new behavior after changes? - None
For more information on following Developer …

Fixed test failures in FlsAndFieldMaskingTests

---

build.gradle

Bump jose to 3.5.8 to address [CVE-2024-28752](https://nvd.nist.gov/vuln/detail/CVE-2024-28752)
Maintenance
[CVE-2024-28752](https://nvd.nist.gov/vuln/detail/CVE-2024-28752)
None
None
No
No
Existing tests pass
For …

Bump jose to address CVE

---

release-notes/opensearch-security.release-notes-1.3.18.0.md

Update the release notes for 1.3.18 for https://github.com/opensearch-project/security/pull/4549
Part of https://github.com/opensearch-project/opensearch-build/issues/4763 …

Update the release notes for 1.3.18

---

src/main/java/org/opensearch/security/filter/SecurityRestFilter.java

`Remove unnecessary return statements`
- clean up code
none …

[Chore] Remove unnecessary return statements

---

src/main/java/org/opensearch/security/privileges/SystemIndexAccessEvaluator.java

This PR fixes a compilation error after merge of https://github.com/opensearch-project/OpenSearch/pull/14750 in core which changes the method signature to SystemIndexRegistry.matchesSystemIndexPattern to accept a set to prevent having to convert between a set and array in SystemIndexAccessEvaluator.
Maintenance

Pass set to SystemIndexRegistry.matchesSystemIndexPattern

---

release-notes/opensearch-security.release-notes-2.16.0.0.md

Adds 2.16 release notes

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/tools/democonfig/Certificates.java
src/test/java/org/opensearch/security/tools/democonfig/CertificateGeneratorTests.java

This PR addresses a bug where mismatching demo certificate hashes caused the setting `plugins.security.allow_unsafe_democertificates` to not work as expected.
* Category : Bug fix
Without this PR, the setting `plugins.security.allow_unsafe_democertificates` will not work.
* Before: Cluster fails to not boot up when setting is set to true
* After: Cluster fails to boot up
- Resolves #4599 
Unit testing, Manual Testing …

Addresses a bug with `plugins.security.allow_unsafe_democertificates` setting

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java

Category (Refactoring)
Refactor call to add the BouncyCastleProvider in OpenSearchSecurityPlugin.java and any associated code.
Helps towards potential support of FIPS-compatible Bouncy Castle provider. This class does not exist in other providers.
Backwards compatible.
Resolves https://github.com/opensearch-project/security/issues/4583
Derived from and replaces https://github.com/opensearch-project/security/pull/4588 - please refer to it for additional context
Bulk Integration Test Github action
Run latest 3.x Core and OpenSearch Security plugin. Smoke tests (Indexing, searching, user creation, role creation, security admin script calls) run against both:
- JDK 17 - local
- JDK 21 - shipped with OS
By submitting this pull request, I confirm that my contribution is made under the terms of …

Refactor security provider instantiation

---

.github/pull_request_template.md

Updates template to notify user to remove `backport-failed` label from source PR when back-porting it manually
* To maintain a clean usage of `backport-failed` label to allow release-managers to track missing/failed backports correctly.

Update backport section of PR template

---

src/integrationTest/java/org/opensearch/security/api/CertificatesRestApiIntegrationTest.java
src/integrationTest/java/org/opensearch/security/api/InternalUsersRestApiIntegrationTest.java
src/main/java/org/opensearch/security/dlic/rest/api/CertificatesApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/org/opensearch/security/user/UserService.java

This change ensures that authtoken endpoint works to vend authtoken for `internalusers` API. 
The issue was root-caused to improperly handled [generateAuthToken()](https://github.com/opensearch-project/security/blob/808fe31f640a3543e358ff11365f3d76ae2385c1/src/main/java/org/opensearch/security/user/UserService.java#L264). This PR modifies the associated method and adds missing tests for `/authtoken` endpoint.
Also fixes a small issue where `timeout` parameter is not working as expected for certificates API.
- #4627
- integration testing
~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/D …

Fixes authtoken endpoint

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/4657 to `2.x`

[Backport 2.x] Bump org.junit.jupiter:junit-jupiter from 5.10.3 to 5.11.0 (#4657)

---

src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java

This was causing an error if the audit config was null and was posted to the event bus.
* Category: Bugfix
* Why these changes are required? An empty audit config causes the logs to be filled with an irrelevant error.
Old behavior:
Lots of errors when the audit config is missing
New behavior:
Audit config is set to the default when missing
#4315 
https://forum.opensearch.org/t/ava-lang-nullpointerexception-cannot-invoke-object-getclass-because-event-is-null/20821/
Is this a backport? No.
Do these changes introduce new permission(s) to be displayed in the static dropdown on the front-end? No.
None
For …

Handle the audit config being null

---

src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationTests.java
src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationWithUrlParamTests.java
src/integrationTest/java/org/opensearch/test/framework/JwtConfigBuilder.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/main/java/org/opensearch/security/util/KeyUtils.java
src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java

This change manually backports #4632
We had to manually backport this change because there are some differences in the support of list.getFirst() between main and 2.x. The JWT classes are also slightly different between the two versions. 

[Backport 2.x] Manually backport #4632 (Allow multiple signing keys to be provided)

---

.github/CODEOWNERS
MAINTAINERS.md

Moves @cliu123 to emeritus status.

Moves @cliu123 to emeritus status

---

.github/CODEOWNERS
MAINTAINERS.md

I have nominated, and maintainers have agreed to add Nils Bandener (@nibix) as a co-maintainer, who has kindly accepted.
Nils has made many valuable contributions and given insight into the OpenSearch Security repo over the last few years.
Notable code contributions from Nils include:
- New integrationTest framework: https://github.com/opensearch-project/security/pull/1967
- New algorithm for resolving action groups: https://github.com/opensearch-project/security/pull/4448
- Separated DLS/FLS privilege evaluation from action privilege evaluation: https://github.com/opensearch-project/security/pull/4490
- Remove special handling for do_not_fail_on_forbidden on cluster actions: https://github.com/opensearch-project/security/pull/4486
Nils has engaged in maintenance of the code base like …

Add Nils Bandener (Github: nibix) as a maintainer

---

.github/CODEOWNERS
MAINTAINERS.md

Backports #4667
Manual backport required due to conflicts in both files.

[Backport 1.x] Moves @cliu123 to emeritus status (#4667)

---

config/roles.yml

Add the new api action names for Alerts in Correlations Project
Feature Issue: https://github.com/opensearch-project/security-analytics/issues/988
No …

added API roles for correlationAlerts

---

.github/workflows/ci.yml

This reverts commit 359272ef4b3811ec794a1c8ac19e7dfcf42906f4.
This PR reverts a previous change that purportedly fixed the codecov-report CI check. After the PR was merged into main, I observed that the fix was not working as intended and had a false sense of fix because codecov upload works with tokenless uploads on forks.
While the change is a valid way to configure codecov/codecov-action@v4 according to the [README](https://github.com/codecov/codecov-action?tab=readme-ov-file#usage), there is an issue with the usage of `env` inside the `Wandalen/wretry.action@v3.5.0` action which is an action that automatically retries upload on failure. 
```
Warning: Unexpected input(s) 'env', valid inputs are ['action', 'command', 'with', 'current_path', 'steps_context', 'attempt_limit', …
```

Revert "Fix covereage-report workflow (#4683)"

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/identity/NoopPluginSubject.java

This PR fixes compilation issues due to a change in the IdentityPlugin interface introduced in https://github.com/opensearch-project/OpenSearch/pull/14630
There is a [PR open on this repo](https://github.com/opensearch-project/security/pull/4665) to implement the extension points as intended, but the PR will need some time for thorough review.
This PR is an interim change to ensure that the plugin compiles. The code is not currently used and guarded by the [identity feature flag](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/util/FeatureFlags.java#L88): `opensearch.experimental.feature.identity.enabled` 
The PluginSubject being introduced in this PR is a noop and simply stashes the ThreadContext.
* Category (Enhancement, New feature, …

Interim build fix for PluginSubject related changes

---

build.gradle

Backport 3319dd2b7b4d61eebfe2791921392d53c5d9eeda from #4695

[Backport 2.x] Bump com.google.errorprone:error_prone_annotations from 2.30.0 to 2.31.0

---

config/roles.yml

Adding new alerting comments security permissions to existing alerting plugin roles for new Alerting Comments feature: https://github.com/opensearch-project/alerting/pull/1561
* Category: Addition as part of new feature
* Why these changes are required?: to ensure proper and intended permissioning of comments in the alerting plugin
* What is the old behavior before changes and new behavior after changes?: before the changes, there was no way to specify what users and what roles had access to what comments. This change allows for that to happen.
Not a backport PR, but would like this PR backported to 2.15
Do these changes …

adding alerting comments security actions to roles.yml

---

build.gradle

Backported: 
- ch.qos.logback:logback-classic from 1.5.7 to 1.5.8 (7a73fd59dc36b8dca1a67928787a8a72f78ed36e from #4715)
- org.checkerframework:checker-qual from 3.46.0 to 3.47.0 (31cfd54a4166af232fb1d584720de29fc0620da0 from #4716)

[Backport 2.x] org.checkerframework:checker-qual and ch.qos.logback:logback-classic to new versions

---

config/roles.yml

Adding a few more index permissions for AD full access role. This is due to the fact we now make some additional calls during detector creation to get all necessary information from the remote clusters.
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/854 …

Adding index permissions for remote index in AD

---

config/roles.yml

Modifying the alerting ack alerts role to give full access to comments, as opposed to only access to view comments. …

changing comments permission for alerting_ack_alerts role

---

config/roles.yml

Backporting https://github.com/opensearch-project/security/pull/4719 to 2.17 …

[2.17 Backport] Adding index permissions for remote index in AD

---

config/roles.yml

Backporting https://github.com/opensearch-project/security/pull/4719 to 2.17 …

[2.x Backport] Adding index permissions for remote index in AD

---

src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
src/main/java/org/opensearch/security/filter/SecurityFilter.java
src/main/java/org/opensearch/security/support/Base64Helper.java
src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
src/test/java/org/opensearch/security/support/Base64HelperTest.java
src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java

This PR fixes multiple issue:
- https://github.com/opensearch-project/security/issues/4494
- https://github.com/opensearch-project/security/issues/4670
When upgrading from 2.11/2.12/2.13 to >= 2.14, there can be an issue when deserializing threadContext headers on the receiving node due to the transmitting node re-using the serialization format from a previous transport hop.
This was particularly seen in scenarios where there is a chain of transport hops, such as 2.14 (Coordinator node) -> 2.14 node -> 2.12 node
These scenarios can happen on ingestion during rolling upgrades where a replica shard may temporarily be on an older node than a primary shard.
This PR adds logic in the SecurityInterceptor to re-serialize the headers if they have previously been populated from a prior transport …

Add ensureCustomSerialization to ensure that headers are serialized correctly with multiple transport hops

---

src/test/java/org/opensearch/security/dlic/rest/api/InternalUsersApiActionValidationTest.java

While working on https://github.com/opensearch-project/security/pull/4546, I encountered weird behavior in InternalUsersApiActionValidationTest. Closer analysis revealed that the behavior came from the fact that the test erroneously parsed a roles mapping JSON config as `CType.ROLES` and not as `CType.ROLESMAPPING`.
I have now switched the config type to `CType.ROLESMAPPING`. 
This has a couple of consequences:
- The roles mapping config type does not have a `static` property, so it cannot be marked as such.
- This causes the behavior of one test to flip: `InternalUsersApiActionValidationTest.validateSecurityRolesWithImmutableRolesMappingConfig`, last assert.
Side note: To be honest, I am a bit confused by the test `validateSecurityRolesWithImmutableRolesMappingConfig` - why should have a …

Fixed use of rolesMappingConfiguration in InternalUsersApiActionValidationTest

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/auditlog/sink/AbstractInternalOpenSearchSink.java
src/main/java/org/opensearch/security/auditlog/sink/InternalOpenSearchDataStreamSink.java
src/main/java/org/opensearch/security/auditlog/sink/InternalOpenSearchSink.java
src/main/java/org/opensearch/security/auditlog/sink/SinkProvider.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/auditlog/sink/InternalOpensearchDataStreamSinkTest.java

This PR allows writing auditlogs to datastreams.
auditlog type "internal_opensearch" currently not supporting datatstreams. 
`java.lang.IllegalArgumentException: only write ops with an op_type of create are allowed in data streams
`
This PR changes the op_type to "create" for the "internal_opensearch" auditlogs, because audit logs should never be updated.
Datastreams only supporting "create" as op_type.
- https://github.com/opensearch-project/security/issues/3745
Tested manually: Security auditlog with and without datastreams

Support datastreams as an AuditLog Sink

---

src/integrationTest/java/org/opensearch/security/api/DefaultApiAvailabilityIntegrationTest.java
src/main/java/org/opensearch/security/dlic/rest/api/FlushCacheApiAction.java

Removes Get, Post, Put cache API routes, since only delete is used. This should not be backported to 2.x, and we should add a deprecation notice there as well (although these were never used anyway so the behavior should be consistent) …

Removes unused get/post/put cache endpoint

---

tools/audit_config_migrater.bat
tools/audit_config_migrater.sh
tools/hash.bat
tools/hash.sh
tools/securityadmin.bat
tools/securityadmin.sh

There was some recent engagement/concern from the community (for example @spapadop) about the deprecation of security admin script. Since there is no concrete plan to remove/replace it, we should remove the deprecation warning. We can add this back in if/when we decide to and have a viable alternative for the script. 
None
No
No
Script no longer prints the warning out …

Undeprecate securityadmin script

---

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java

Removes audit log entry of failed login for all SAML authentication since it will always re-request authentication
Fix: https://github.com/opensearch-project/security/issues/4608
No
No
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIB …

Remove failed login attempt for saml authenticator

---

.github/CODEOWNERS
MAINTAINERS.md

Backports #4667
Manual backport required due to conflicts in both files.

[Backport 1.3] Moves @cliu123 to emeritus status (#4667)

---

.github/CODEOWNERS
MAINTAINERS.md

Backports #4667
Manual backport required due to conflicts in both files.

[Backport 2.x] Moves @cliu123 to emeritus status (#4667)

---

src/integrationTest/java/org/opensearch/security/SystemIndexTests.java
src/main/java/org/opensearch/security/configuration/SecurityFlsDlsIndexSearcherWrapper.java
src/main/java/org/opensearch/security/configuration/SecurityIndexSearcherWrapper.java
src/main/java/org/opensearch/security/configuration/SystemIndexSearcherWrapper.java

Prevents reads on security system index registered through core
Fix: #4755 
No
No
Added unit test

Fix bug where admin can read system index

---

src/main/java/org/opensearch/security/support/SecurityUtils.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/UtilTests.java

Category (Bug fix)
Passwords provided as environment variables are always hashed using BCrypt even when configured to use something else. Authentication fails when using PBKDF2 .
Resolves https://github.com/opensearch-project/security/issues/4771
Initially found testing on a personal cluster. Confirmed fix works.
Included new test for PBKDF2 with PR.
Run Bulk Integration Tests.

Fix env var password hashing for PBKDF2

---

src/main/java/org/opensearch/security/dlic/rest/api/FlushCacheApiAction.java

Adds deprecation warning that GET/POST/PUT methods for cache endpoint is removed in version 3.0.0. 
None
No
No
None

Add deprecation warning for GET/POST/PUT cache

---

.github/CODEOWNERS
MAINTAINERS.md

I have nominated, and maintainers have agreed to add Derek Ho (@derek-ho) as a co-maintainer, who has kindly accepted.
Derek has made many valuable contributions and given insightful comments on reviews in many PRs over the last year.
Notable code contributions from Derek include:
- Add initial changes to expose an endpoint for auth failure listener get call: https://github.com/opensearch-project/security/pull/4641
- This change is a good example of an enhancement to the security plugin to deliver value to the community
- Add cat/alias support for DNFOF: https://github.com/opensearch-project/security/pull/4436
- Add support for ipv6 ip address in user injection: https://github.com/opensearch-project/security/pull/4399
- Use GHA derek-ho/start-opensearch for OpenSearch plugin install …

Add Derek Ho (github: derek-ho) as a maintainer

---

.github/workflows/ci.yml

Fixes #4801. 
Switches the upload of integration-tests artifacts from `upload-tartifact` to `actions/upload-artifact@v4`. This will also properly include the integration-tests coverage data.
* Category: CI fix
* Why these changes are required?  - test coverage data reported to codecov was incomplete
* What is the old behavior before changes and new behavior after changes? - none
Resolves #4801 
Test coverage gains visible in codecov: https://app.codecov.io/github/opensearch-project/security/commit/0976a9609e8e0efa8c2361372f73f592fdbb81a3/indirect-changes …

Fix codecov test coverage information for directory `integration-tests` 

---

.github/CODEOWNERS
MAINTAINERS.md

Moves @stephen-crawford to emeritus maintainer
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTIN …

Move Stephen to emeritus

---

build.gradle

Fix 'integTest' not called with test workflows during release. Adding an  'integTest' as an alias for `integrationTest` task.
Closes https://github.com/opensearch-project/security/issues/4805
`./gradlew integTest`

Fix 'integTest' not called with test workflows during release

---

src/main/java/org/opensearch/security/dlic/rest/api/RateLimitersApiAction.java

This PR fixes an issue on Delete scenarios for the new AuthFailureListener endpoints where the authfailurelistener is not found. This issue was found [here](https://github.com/opensearch-project/security/pull/4810#issuecomment-2411245121) and can lead to `Channel already closed` because its performing an internal config update request even if the corresponding auth failure listener is not found. This PR prevents the internal transport config update request from happening if the listener is not found.
Tested by adding [@RepeatRule](https://github.com/opensearch-project/security/pull/3763/files#r1419262032) on the failing test and ensuring that it passes 10x on a single run.
Bug fix
By …

Fix ChannelAlreadyClosed error in RateLimitersApiActionTest.testInvalidDeleteScenarios

---

bwc-test/src/test/java/org/opensearch/security/bwc/SecurityBackwardsCompatibilityIT.java
bwc-test/src/test/java/org/opensearch/security/bwc/Song.java

So far, the BWC test `SecurityBackwardsCompatibilityIT.testDataIngestionAndSearchBackwardsCompatibility()` did not ingest any documents, as the submitted bulk requests were invalid. 
The test already asserted that `_bulk` API calls returned a 200 OK HTTP status. However, this is not sufficient, as the `_bulk` API also returns a 200 status if processing of the bulk items fails.  Such failures are only reflected item-wise in the response body. This indeed happened, as the test erroneously serialized a string containing the JSON document again as JSON, creating a JSON string containing JSON. This was rejected by OpenSearch.
This is now fixed - additional assertions have been created to verify that the items of the bulk request are actually indexed.
Additionally, the DLS rules of the user …

Fixed bulk index requests in BWC tests and hardened assertions

---

src/main/java/org/opensearch/security/ssl/util/ExceptionUtils.java
src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
src/test/java/org/opensearch/security/ccstest/CrossClusterSearchTests.java

Updated the error message to understand what is the exact reason of error and renamed the API name to match the intention of API.
Resolves #4601
Ran the unit tests
- [ x] New functionality includes testing
- [ x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md)
- [ x] Commits are signed per the DCO using --signoff

Improve error message when a node with an incorrectly configured certificate attempts to connect

---

src/integrationTest/java/org/opensearch/security/StoredFieldsTests.java
src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java

This PR fixes a bug inside HashingStoredFieldVisitor to account for [stored_fields](https://opensearch.org/docs/latest/search-plugins/searching-data/retrieve-specific-fields/#searching-with-stored_fields) which are stored separately from `_source` in the backing index. This PR also adds integ tests to verify the correct behavior.
Bug fix

Fix issue in HashingStoredFieldVisitor with stored fields

---

src/integrationTest/java/org/opensearch/security/EncryptionInTransitMigrationTests.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/MinimumSecuritySettingsSupplierFactory.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/ssl/OpenSearchSecureSettingsFactory.java
src/main/java/org/opensearch/security/ssl/OpenSearchSecuritySSLPlugin.java

Companion core PR: https://github.com/opensearch-project/OpenSearch/pull/16387
Overrides a new method in the SecureTransportSettingsProvider interface to allow the security plugin to feed this value to core. This is required since the security plugin has a listener on cluster settings and allows this setting to be changed dynamically irrespective of the value in opensearch.yml
Bug fix
[latest-dual-mode.zip](https://github.com/user-attachments/files/17439395/latest-dual-mode.zip)
^ Attached above is a sample docker configuration for a 3 node cluster. node1 is commented out originally. All paths in the volumes are paths on my local machine and would need to change for a reproduction.
1. Apply …

Ensure that dual mode enabled flag from cluster settings can get propagated to core

---

src/main/java/org/opensearch/security/ssl/SslContextHandler.java
src/main/java/org/opensearch/security/ssl/config/SslParameters.java
src/main/java/org/opensearch/security/ssl/util/SSLConfigConstants.java
src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java

Adapts https://github.com/opensearch-project/security/pull/4752 to the changes introduced in https://github.com/opensearch-project/security/pull/4671.
Opening this up in Draft initially while additional testing is performed.
I also opened a [revert PR](https://github.com/opensearch-project/security/pull/4840) as well to solicit feedback from maintainers on which direction we should take to fix the CI failures.
Maintenance …

Adapt disable dn verification on cert reload changes to SSL refactor

---

src/main/java/org/opensearch/security/ssl/SslContextHandler.java
src/test/java/org/opensearch/security/ssl/CertificatesRule.java
src/test/java/org/opensearch/security/ssl/SslContextHandlerTest.java

Added validation of authority certificates prior to reloading the SSL context.

Add validation of authority certificates

---

src/integrationTest/java/org/opensearch/security/SystemIndexTests.java
src/main/java/org/opensearch/security/configuration/SecurityFlsDlsIndexSearcherWrapper.java
src/main/java/org/opensearch/security/configuration/SecurityIndexSearcherWrapper.java

This reverts commit 5cb4dd29d2b083025310f4918b5b121094b32cd5.
By submitting this pull request, I …

Revert "Fix bug where admin can read system index (#4774)"

---

src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java

Fixes issue in the JWT authenticator when parsing a claim that contains a list value. The existing parsing logic works as-is, but the problem arises when you try to use the parsed value in a DLS clause using the `${attr.jwt.claim}` syntax.
Bug fix
Resolves: https://github.com/opensearch-project/security/issues/4267

Fix issue with jwt attribute parsing of lists

---

src/main/java/org/opensearch/security/ssl/SslSettingsManager.java

Log `io.netty.internal.tcnative.SSLContext` availability warning only when OpenSSL is explicitly enabled but not available
Closes https://github.com/opensearch-project/security/issues/4881
The log is clean now , will be printed out if `SECURITY_SSL_HTTP_ENABLE_OPENSSL_IF_AVAILABLE` or `SECURITY_SSL_TRANSPORT_ENABLE_OPENSSL_IF_AVAILABLE` is enabled.

Log io.netty.internal.tcnative.SSLContext availability warning only when OpenSSL is explicitly enabled but not available

---

src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java

Reduces a log message in HttpJwtAuthenticator to debug level if the request cannot be authenticated with any of the configured signing keys.
If authentication fails across all configured authentication domains, there is a catch all warning message in BackendRegistry [here](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/BackendRegistry.java#L432-L436). This message in HttpJwtAuthenticator is redundant and can be reduced in severity since it is not an error in the application and expected behavior if a request is sent with a bad JWT. 
Maintenance
Resolves: https://github.com/opensearch-project/security/issues/4910 …

Reduce log level in HttpJwtAuthenticator if request cannot be authenticated

---

src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
src/test/java/org/opensearch/security/auditlog/compliance/ComplianceAuditlogTest.java

This PR ensures that the value of `log_request_body` is honored for the compliance logging. When using the compliance config, this PR will ensure that the document's source is audit logged in the `audit_request_body` when a document is first created, but otherwise it will not. When `write_log_diffs` is enabled, you can trace the full history of changes to documents on the tracked indices by looking for all events on the target index.
By default, the security index gets events audit logged so Compliant logging is a good feature to use to trace changes to the security configuration.
Enhancement
https://github.com/opensearch-project/security/issues/4534
By submitting this pull request, I confirm …

Honor log_request_body setting in compliance audit log

---

src/test/java/org/opensearch/security/auditlog/compliance/ComplianceAuditlogTest.java

Small follow-up to https://github.com/opensearch-project/security/pull/4832
This PR fixes a test inconsistency when running on the CI runner vs running the test locally. When running the test locally, I get an additional 2 audit messages in the audit log corresponding to the index being auto created on first document indexed
```
{"audit_cluster_name":"utest_n8_fnull_t353371380541833","audit_node_name":"node_utest_n8_fnull_t353371380541833_num1","audit_trace_task_id":"YhQ8bQAAQACC5F0XAAAAAA:104","audit_transport_request_type":"CreateIndexRequest","audit_category":"INDEX_EVENT","audit_request_origin":"REST","audit_node_id":"YhQ8bQAAQACC5F0XAAAAAA","audit_request_layer":"TRANSPORT","@timestamp":"2024-11-19T20:30:34.523+00:00","audit_format_version":4,"audit_request_privilege":"indices:admin/a …
```

Explicitly create index before ingesting document in ComplianceAuditlogTest.testWriteLogDiffsEnabledAndLogRequestBodyDisabled

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle to 8.11

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/ssl/SslContextHandler.java
src/main/java/org/opensearch/security/ssl/SslSettingsManager.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/ssl/CertificatesRule.java
src/test/java/org/opensearch/security/ssl/SslSettingsManagerReloadListenerTest.java
src/test/java/org/opensearch/security/ssl/config/JdkSslCertificatesLoaderTest.java
src/test/resources/log4j2-test.properties

Added support for certificates hot reload
#4427

Add support for certificates hot reload

---

build.gradle

[CVE-2024-38808] [1.3] Bump spring-framework dependency to 2.9.13

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/4958 to `2.x`

[Backport] [2.x] Bump org.checkerframework:checker-qual from 3.48.2 to 3.48.3 (#4958)

---

src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/test/java/org/opensearch/security/securityconf/impl/v7/IndexPatternTests.java

Creating this backport to explore a small optimization for the all_access role when evaluating index permissions in clusters with a large number of indices.
This PR is not a strategic fix like https://github.com/opensearch-project/security/pull/4898. https://github.com/opensearch-project/security/pull/4898 takes a holistic approach to optimize privilege evaluation for any type of role definition.
Performance improvement …

[2.x] Optimize privilege evaluation for index permissions across '*' index pattern (i.e. all_access role)

---

src/main/java/org/opensearch/security/ssl/config/SslCertificatesLoader.java
src/main/java/org/opensearch/security/ssl/util/SSLConfigConstants.java
src/test/java/org/opensearch/security/ssl/config/JdkSslCertificatesLoaderTest.java

The `KeyStore.getDefaultType()` method returns `JKS` by default for all `JDK` versions prior to `JDK 23`,
which switches the default to `PKCS12`. Since the refactored version uses
`KeyStore.getDefaultType()`, it could break backward compatibility with older `JDK` versions.
[JDK 21 docs](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/security/KeyStore.html#getDefaultType()) vs [JDK23 docs](https://docs.oracle.com/en/java/javase/23/docs/api/java.base/java/security/KeyStore.html#getDefaultType()) …

Set default value for key/trust store type as constant for JDK PKCS setup

---

src/main/java/org/opensearch/security/ssl/config/SslCertificatesLoader.java

Set the  `keystore_password` by default same as the `keystore_keypassword` setting
#4961

Fix SSL config for JDK PKCS setup

---

src/integrationTest/java/org/opensearch/security/DoNotFailOnForbiddenTests.java
src/test/java/org/opensearch/security/support/SafeSerializationUtilsTest.java

Fixes a flaky test: SafeSerializationUtilsTests#testCaching and resolves a gradle build error caused by missing syntax.

Adds a quick fix to flaky test and corrects run-time error

---

src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetRetriever.java
src/main/java/org/opensearch/security/auditlog/sink/WebhookSink.java
src/main/java/org/opensearch/security/httpclient/HttpClient.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/MockIpdServer.java
src/test/java/com/amazon/dlic/auth/http/saml/MockSamlIdpServer.java
src/test/java/org/opensearch/security/InitializationIntegrationTests.java
src/test/java/org/opensearch/security/auditlog/sink/SinkProviderTLSTest.java
src/test/java/org/opensearch/security/auditlog/sink/WebhookAuditLogTest.java
src/test/java/org/opensearch/security/test/AbstractSecurityUnitTest.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java

See please  https://github.com/opensearch-project/OpenSearch/pull/16757
See please https://github.com/opensearch-project/security/actions/runs/12813953884/job/35729309491?pr=5034
N/A
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUT …

Fix tests after Apache HttpClient5 / HttpCore5 update since those use deprecated APIs

---

.github/actions/run-bwc-suite/action.yaml
.github/workflows/integration-tests.yml

Fixes deprecation error on BWC action by moving to v4 for upload artifact. 
None
Existing tests pass

Move to upload artifact v4 for BWC action

---

src/main/java/org/opensearch/security/ssl/http/netty/Netty4HttpRequestHeaderVerifier.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java

Fix Netty4 header verifier inbound handler to deal with upgrade requests
Follow up on https://github.com/opensearch-project/security/pull/5035
N/A

Fix Netty4 header verifier inbound handler to deal with upgrade requests

---

src/main/java/org/opensearch/security/ssl/http/netty/Netty4HttpRequestHeaderVerifier.java

Backport of https://github.com/opensearch-project/security/pull/5045 to `2.x`

[Backport] [2.x] Fix Netty4 header verifier inbound handler to deal with upgrade requests (#5045)

---

config/roles.yml

For PR - https://github.com/opensearch-project/anomaly-detection/pull/1401, add ingest pipeline and indices related permissions for anomaly_full_access role. 
[Please provide details of testing …

add ingest pipeline and indices related permissions for anomaly_full_access role

---

config/roles.yml

Backporting this pr into 2.x branch - https://github.com/opensearch-project/security/pull/5065
By …

[Backport 2.x] add ingest pipeline and indices related permissions for anomaly_full_access role

---

src/test/java/org/opensearch/security/ccstest/RemoteReindexTests.java

Test fix to replace usage of a deprecated setting

Use non-deprecated `reindex.remote.allowlist` setting

---

src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/main/java/org/opensearch/security/user/User.java

Fix https://github.com/opensearch-project/security/issues/4441
Previously, since the fields were ```Collections.synchronizedSet()``` /``Collections.synchronizedMap()`` - explicit synchronization is required (see https://github.com/opensearch-project/security/issues/4642#issue-2465496301) 
By switching to ``CopyOnWriteArraySet`` and ``ConcurrentHashMap``, we get lock-free reads, safe iteration without explicit synchronization. 
However, CopyOnWriteArraySet can lead to memory overhead - should be minimal as updates/writes are expected to be …

[2.x] Avoid ConcurrentModificationException for User class fields

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java

Fix SSL hot reload settings
#5115

Fix ssl hot reload settings

---

src/main/java/org/opensearch/security/dlic/rest/validation/PasswordValidator.java

Small PR that makes sure that the set of valid values for `plugins.security.restapi.password_score_based_validation_strength` matches the public documentation at https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/security-settings/
Bug fix

Add 'good' as a valid value for plugins.security.restapi.password_score_based_validation_strength

---

src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/test/java/org/opensearch/security/dlic/dlsfls/FlsExistsFieldsTest.java

Update `DlsFlsFilterLeafReader` to reflect Apache Lucene 10 APIs changes in the `FilterTermsEnum`
Follow up on https://github.com/opensearch-project/security/pull/5053 and concretely this workaround https://github.com/opensearch-project/security/pull/5053/files#r1950155753 …

Update DlsFlsFilterLeafReader to reflect Apache Lucene 10 APIs changes

---

.github/workflows/plugin_install.yml

Current step generates names as password which may not be strong enough for future CI given that we require a strong password now.
- CI

Replaces password generator step to a secure password generator action

---

.github/workflows/plugin_install.yml

Backports #5153 
(cherry picked from commit 88036909c46230a3d743f2e7fc9cb71b7ca31594)

[Backport 2.x] Replaces password generator step to a secure password generator action (#5153)

---

src/main/java/org/opensearch/security/tools/democonfig/Installer.java
src/test/java/org/opensearch/security/tools/democonfig/InstallerTests.java

A bug was discovered in Installer.java while working on #5016, where the version matcher string matched everything after `opensearch-security`. WIth #5016 introducing packages like `opensearch-security-client` and `openserch-secrurity-common` the version matcher spewed out `common-3.0.0.0` instead out `3.0.0.0`. This PR fixes it to only spew out the version along with qualifier and snapshot string.
unblocks #5016 
Unit tests

Fixes version matcher string in demo config installer

---

src/main/java/org/opensearch/security/rest/DashboardsInfoAction.java

Update deprecation message for _opendistro/_security/kibanainfo API
The security repo has lingering usages of the terms opendistro and kibana, these will be removed in 4.0
For https://github.com/opensearch-project/security/issues/5092 & https://github.com/opensearch-project/security/issues/5097
* What is the old behavior before changes and new behavior after changes? Update of log line on using deprecated API.
```
2025-03-07 08:37:03 opensearch[data_0][transport_worker][T#4] DEPRECATION RestController:123 - [_opendistro/_security/kibanainfo] is a deprecated endpoint path. Please use _plugins/_security/dashboardsinfo instead.
``` …

nit: Update deprecation message for _opendistro/_security/kibanainfo API

---

config/roles.yml

This change adds an additional permission to  index_management_full_access role in config/roles.yml. 
This permission is needed to execute the newly added "stop_replication action" added in index-management plugin - https://github.com/opensearch-project/index-management/pull/1198
Related to https://github.com/opensearch-project/index-management/issues/726
For more information on following Developer Certificate of Origin and signing off your commits, please …

Adding stop-replication permission to index_management_full_access

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/5161 to `2.x`

[Backport] [2.x] Bump org.mockito:mockito-core from 5.15.2 to 5.16.0 (#5161)

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/5162 to `2.x`

[Backport] [2.x] Bump org.checkerframework:checker-qual from 3.49.0 to 3.49.1 (#5162)

---

build.gradle

Bumps spring to fix cve-2024-38827
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#develop …

Bump spring version to fix cve-2024-38827

---

src/integrationTest/java/org/opensearch/security/InternalAuditLogTest.java
src/integrationTest/java/org/opensearch/security/rest/AuthZinRestLayerTests.java
src/integrationTest/java/org/opensearch/test/framework/audit/AuditMessagePredicate.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
src/main/java/org/opensearch/security/support/ConfigConstants.java

Currently we do not get request body to audit log, as requests are already authenticated in header verifier level, which does not have access to request body.
SecurityRestFilter has the whole RestRequest object, but it does not authenticate it again. Also, it does not authorize the request if the route is not a named one. The idea here is to do logGrantedPrivileges call even if we do not authorize. This way we will get the request body to audit log.
[[BUG] audit_request_body missing for REST since 2.11
](https://github.com/opensearch-project/security/issues/4094) …

Log request body to audit logs

---

src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/main/java/org/opensearch/security/privileges/dlsfls/AbstractRuleBasedPrivileges.java
src/main/java/org/opensearch/security/privileges/dlsfls/DocumentPrivileges.java

This PR fixes the logic for determining whether a role is unrestricted with regards to FLS/DLS/FieldMasking restrictions. A role is considered unrestricted if the respective `fls:`, `dls:`, or `masked_fields:` portions are either an empty list or left out of the role definition altogether.
The gist of the problem is that we bypass the [FlsDlsValveImpl if a role has no restrictions](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java#L147-L153), but we are not computing whether a role has no restrictions correctly because we are resolving to concrete indices for cluster actions and then applying the default of `{"match_none": {}}` to any resolvable indices such as `.opendistro_security`.
There was a bug seen in …

Fix logic for determining if a role has no DLS/FLS/FieldMasking restrictions

---

build.gradle

`bouncycastle` was removed from the gradle version catalog in https://github.com/opensearch-project/OpenSearch/pull/17507/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87df.
This PR sets the same version inline in security's build.gradle file
Maintenance

Add bouncycastle version directly in build.gradle

---

src/integrationTest/java/org/opensearch/security/InternalAuditLogTest.java
src/integrationTest/java/org/opensearch/security/rest/AuthZinRestLayerTests.java
src/integrationTest/java/org/opensearch/test/framework/audit/AuditMessagePredicate.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
src/main/java/org/opensearch/security/support/ConfigConstants.java

Signed-off-by: Timo Olkkonen <timo.olkkonen@reaktor.com>
Co-authored-by: Timo Olkkonen <timo.olkkonen@reaktor.com>
Co-authored-by: Andrey Pleskach <ples@aiven.io>
(cherry picked from commit 00204dd49ae555856f13a319dd805e69a29c8ee2)
Currently we do not get request body to audit log, as requests are already authenticated in header verifier level, which does not have access to request body.
SecurityRestFilter has the whole RestRequest object, but it does not authenticate it again. Also, it does not authorize the request if the route is not a named one. The idea here is to do logGrantedPrivileges call even if we do not authorize. This way we will get the request body to audit log.
[[BUG] audit_request_body missing for REST since 2.11 …

[Backport 2.x] Log request body to audit logs (#5071)

---

src/integrationTest/java/org/opensearch/security/rest/AuthZinRestLayerTests.java
src/integrationTest/java/org/opensearch/test/framework/audit/AuditMessagePredicate.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
src/main/java/org/opensearch/security/support/ConfigConstants.java

Currently we do not get request body to audit log, as requests are already authenticated in header verifier level, which does not have access to request body.
SecurityRestFilter has the whole RestRequest object, but it does not authenticate it again. Also, it does not authorize the request if the route is not a named one. The idea here is to do logGrantedPrivileges call even if we do not authorize. This way we will get the request body to audit log.
[[BUG] audit_request_body missing for REST since 2.11
](https://github.com/opensearch-project/security/issues/4094)
This is a backport from [5199](https://github.com/opensearch-project/security/pull/5199)
I removed changes to InternalAuditLogTest from this one, as it is not in 2.19 branch and I only fixed a flaky test in order to get my …

[Backport 2.19] Log request body to audit logs (#5071) (#5199)

---

build.gradle

Follow-up for https://github.com/opensearch-project/security/pull/5206#discussion_r2012742870
Java 21 as default- https://github.com/opensearch-project/security/blob/main/build.gradle#L98-L99
Maintenance
Maintenance
[Please provide details of testing done: unit testing, …

nit: remove java version check for reflection args in build.gradle

---

build.gradle
src/main/java/org/opensearch/security/compliance/ComplianceConfig.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
src/test/java/org/opensearch/security/configuration/ConfigurationRepositoryTest.java

Improve coverage: Adding tests for ConfigurationRepository class
Maintenance
https://github.com/opensearch-project/security/issues/3255
NA
https://github.com/opensearch-project/security/issues/3255
[Please provide details of testing done: unit testing, integration testing …

Improve coverage: Adding tests for ConfigurationRepository class

---

src/integrationTest/java/org/opensearch/security/InternalAuditLogTest.java

Refactor InternalAuditLogTest to use Awaitility
This test had flakiness that was fixed in https://github.com/opensearch-project/security/pull/5071. I'm creating this small PR to refactor this to use Awaitility instead which is a good utility to wait for a particular result in a test.
Test fix

Refactor InternalAuditLogTest to use Awaitility

---

src/main/java/org/opensearch/security/dlic/rest/api/MigrateApiAction.java

This PR creates a small update to the migrate API to ensure that every securityconfig has a `_meta` header when using the v7 models.
This PR is needed to resolve a known migration issue from 2.19 -> 3.0 if any of the security config types in the index are missing the `_meta` portion, but are known to be up to date.
Bug fix
Resolves: https://github.com/opensearch-project/security/issues/5191
1. Manually delete the `_meta` portion of one of the yaml files before booting up a cluster.
2. Run the migrate API and ensure that it responds: `{"status":"OK","message":"Migration completed."}`
Run the migrate API with: `curl -XPOST https://admin:myStrongPassword123\!@localhost:9200/_plugins/_security/api …

[2.19] Ensure that all ctypes contain _meta header in migrate API

---

src/integrationTest/java/org/opensearch/security/privileges/ActionPrivilegesTest.java
src/main/java/org/opensearch/security/privileges/ActionPrivileges.java

This fixes the issue reported in #5216. In the case that a cluster has aliases defined on backing indices of data streams, the creation of the stateful rule would fail with an `IllegalArgumentException`. 
This is because data stream backing indices are not supposed to be included in the stateful index privilege object. Via the aliases, however, they sneaked in anyway. We are now filtering these indices out.
This is mostly just a cosmetic problem as privilege evaluation will continue via slower fall back code paths. However, the logs will show an `IllegalArgumentException` stack trace for each update of the index meta data on the cluster.
* Category
* Bugfix
* Fixes log spam
* No …

Fixed IllegalArgumentException when building stateful index privileges

---

src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java

Fixes
```
2025-04-01 13:19:40 opensearch[data_0][get][T#3] WARN  RunnerThreadGroup:570 - Uncaught exception in thread: Thread[#301,opensearch[data_0][get][T#3],5,TGRP-FlsFmIntegrationTests]
java.lang.AssertionError: null
at __randomizedtesting.SeedInfo.seed([756AD321ED0B3FEE]:0) ~[?:?]
at org.opensearch.action.termvectors.TermVectorsWriter.writeTermWithDocsAndPos(TermVectorsWriter.java:213) ~[opensearch-3.0.0-beta1-SNAPSHOT.jar:3.0.0-beta1-SNAPSHOT]
at org.opensearch.action.termvectors.TermVectorsWriter.setFields(TermVectorsWriter.java:139) ~[opensearch-3.0.0-beta1-SNAPSHOT.jar:3.0.0-beta1-SNAPSHOT]
at org.opensearch.action.termvectors.TermVectorsResponse.setFields(TermVectorsResponse.java:414) ~[opensearch-3.0.0-beta1-SNAPSHOT.jar:3.0.0-beta1-SNAPSHOT]
at …
```

DlsFlsFilterLeafReader::termVectors implementation causes assertion errors for users with FLS/FM active

---

src/integrationTest/java/org/opensearch/security/http/ServiceAccountAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/privileges/dlsfls/FlsFmIntegrationTests.java
src/integrationTest/java/org/opensearch/test/framework/TestData.java
src/integrationTest/java/org/opensearch/test/framework/TestIndex.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/integrationTest/java/org/opensearch/test/framework/matcher/RestDocumentMatchers.java
src/integrationTest/java/org/opensearch/test/framework/matcher/RestMatchers.java

At the moment, the FLS/FM functionality is lacking test coverage. This is especially evident in the class `DlsFlsFilterLeafReader`: https://app.codecov.io/gh/opensearch-project/security/blob/main/src%2Fmain%2Fjava%2Forg%2Fopensearch%2Fsecurity%2Fconfiguration%2FDlsFlsFilterLeafReader.java
This PR introduces a new integration test with the goal to increase test coverage. It uses a test matrix of:
- different users with different FLS/FM configs
- different operations like get, search, aggregation, terms vectors
* Category: Test enhancement
* What is the old behavior before changes and new behavior after changes?: No changes
Is this a backport? If so, please add backport PR # and/or …

More tests for FLS and field masking

---

.github/CODEOWNERS
MAINTAINERS.md

I have nominated and maintainers have agreed to add @shikharj05 as a co-maintainer of the security repo.
@shikharj05 has made many valuable contributions and given insightful comments on reviews and GH issues over the last few years.
Shikhar is an avid PR reviewer and has reviewed a total of 127 PRs (including open and closed) - a great quality of a maintainer :).
See all PRs where Shikhar has engaged as a commenter: https://github.com/opensearch-project/security/pulls?q=is%3Apr+commenter%3Ashikharj05
Some notable PR reviews include:
- Replace BouncyCastle's OpenBSDBCrypt use with password4j for password hashing and verification: https://github.com/opensearch-project/security/pull/4381
- Add support for ipv6 ip address in user injection: …

Add Shikhar Jain (GH: shikharj05) as a maintainer

---

bwc-test/build.gradle
plugin-security.policy
src/main/java/org/opensearch/security/ssl/OpenSearchSecureSettingsFactory.java
src/main/java/org/opensearch/security/tools/democonfig/CertificateGenerator.java
src/main/java/org/opensearch/security/tools/democonfig/DefaultExitHandler.java
src/main/java/org/opensearch/security/tools/democonfig/ExitHandler.java
src/main/java/org/opensearch/security/tools/democonfig/Installer.java
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java
src/test/java/org/opensearch/security/http/OnBehalfOfAuthenticatorTest.java
src/test/java/org/opensearch/security/tools/democonfig/CertificateGeneratorTests.java
src/test/java/org/opensearch/security/tools/democonfig/InstallerTests.java
src/test/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurerTests.java

This PR fixes a compilation issue after merge of https://github.com/opensearch-project/OpenSearch/pull/17796 which altered the [SecureSettingsFactory](https://github.com/opensearch-project/OpenSearch/pull/17796/files#diff-f51de3d6462ad0f2d3dbde0f929571b25a4319e7675c3d90d2b413ede93ddf45) interface in core.
This PR is not a replacement for https://github.com/opensearch-project/security/pull/5152. This is a PR in the interim to fix compilation issues, but the actual implementation will be provided in https://github.com/opensearch-project/security/pull/5152
This PR also contains changes from https://github.com/opensearch-project/security/pull/5262
Maintenance
- Resolves …

Fix compilation issue after Secure gRPC PR (#17796) merged into core

---

.github/workflows/plugin_install.yml
build.gradle

Remove beta1 qualifier
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#developer-certifica …

Remove beta1 qualifier

---

src/integrationTest/java/org/opensearch/security/privileges/dlsfls/FieldPrivilegesTest.java
src/integrationTest/java/org/opensearch/security/privileges/dlsfls/FlsFmIntegrationTests.java
src/integrationTest/java/org/opensearch/test/framework/TestData.java
src/integrationTest/java/org/opensearch/test/framework/matcher/RestDocumentMatchers.java
src/integrationTest/java/org/opensearch/test/framework/matcher/RestMatchers.java
src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/main/java/org/opensearch/security/privileges/dlsfls/FieldPrivileges.java
src/main/java/org/opensearch/security/privileges/dlsfls/FlsDocumentFilter.java
src/main/java/org/opensearch/security/privileges/dlsfls/FlsStoredFieldVisitor.java

This fixes and cleans up DlsFlsFilterLeafReader logic related to field mappins based on PointValues and object valued attributes.
- Integration testing

Corrections in DlsFlsFilterLeafReader regarding PointVales and object valued attributes

---

.github/workflows/dependabot_pr.yml
CHANGELOG.md

Fixing  [dependabot](https://github.com/apps/dependabot) broken pull_request workflow for changelog update 
For GitHub Actions workflows initiated by Dependabot (github.actor == "dependabot[bot]") using the pull_request, pull_request_review, pull_request_review_comment, and push events:
secrets are inaccessible , which cause
Dependabot_pr worklow is faling with error : [Error: Input required and not supplied: app_id](https://github.com/opensearch-project/security/actions/runs/14965211943/job/42033842830)
ref : https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
For workflows that are triggered by the pull_request_target event, the GITHUB_TOKEN is granted read/write repository permission and secrets
https://github.com/opensearch-project/security/pull/5326
Do …

fixing dependabot changelog pull_request workflow

---

CHANGELOG.md
src/integrationTest/java/org/opensearch/security/SecuritySettingsTests.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/rest/SecurityHealthAction.java
src/main/java/org/opensearch/security/support/SecuritySettings.java

This PR registers a cluster settings listener for the `plugins.security.cache.ttl_minutes` setting that will allow it to be changed dynamically.
Updating this setting will not persist across reboots and this will only last as long as the OpenSearch process remains up. To update this setting more permanently requires modifying the setting in `opensearch.yml`
Enhancement
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#developer-certificate-of-o …

Register cluster settings listener for `plugins.security.cache.ttl_minutes`

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/support/SnapshotRestoreHelper.java
src/test/java/org/opensearch/security/configuration/ConfigurationRepositoryTest.java

Bug fix: Fixing stale cache issue post snapshot restore
Currently when a snapshot is restored on a domain including security index, the security index is updated but the in memory cache is not updated or reloaded with data from security index. Due to this AuthNZ for API requests and dashboard access is incorrect. It can either provide access when it shouldn't or deny access when it shouldn't
This change address this issue by adding a listener to index shard update events which reloads the cache with data from security index. This ensures cache is always updated when security index is updated
[[Bug] Stale cache post snapshot restore](https://github.com/opensearch-project/security/issues/5308)
- Tested with a local snapshot repository. Took a snapshot of current security index data. Made …

Bug fix: Fixing stale cache issue post snapshot restore

---

src/integrationTest/java/org/opensearch/security/privileges/dlsfls/FlsFmIntegrationTests.java
src/integrationTest/java/org/opensearch/test/framework/TestData.java
src/integrationTest/java/org/opensearch/test/framework/TestIndex.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/matcher/RestDocumentMatchers.java
src/integrationTest/java/org/opensearch/test/framework/matcher/RestMatchers.java
src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/main/java/org/opensearch/security/configuration/SecurityFlsDlsIndexSearcherWrapper.java

This fixes and cleans up DlsFlsFilterLeafReader logic related to field mappins based on PointValues and object valued attributes.
Backport of https://github.com/opensearch-project/security/pull/5303
Integration tests

[Backport 2.19] Corrections in DlsFlsFilterLeafReader regarding PointVales and object valued attributes

---

CHANGELOG.md
scripts/build.sh

Prevents sample plugin from being assembled when using build.sh for assemble workflow.
Reference: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/3.1.0/latest/linux/arm64/tar/builds/opensearch/manifest.yml …

Fixes assemble workflow failure during Jenkins build

---

CHANGELOG.md

Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation) - Documentation
Adding CHANGELOG for commit `33ec6600`([PR](https://github.com/opensearch-project/security/pull/5307))

Adding CHANGELOG for commit 33ec6600

---

.github/workflows/link-checker.yml
.lycheeignore

This workflow is already present across many repos in the OpenSearch project, but its missing from this repo.
This PR adds a PR check to ensure that links in the codebase resolve successfully. 
Maintenance
Resolves: https://github.com/opensearch-project/security/issues/5347

Add workflow using lychee to ensure that links in documentation files resolve

---

.github/dependabot.yml

The dependabot-changelog-helper GHA expects the `dependabot` label on dependabot PRs. Currently the `Update the changelog` step in `dependabot_pr.yml` workflow is failing silently bc this label is absent
```
Run dangoslen/dependabot-changelog-helper@v4
Label 'dependabot' not found in pull request labels
```
ref: https://github.com/opensearch-project/security/actions/runs/15109843244/job/42484278169?pr=5345
Maintenance …

Automatically add dependabot label to dependabot PRs

---

.github/workflows/dependabot_pr.yml

This PR fixes the error seen on https://github.com/opensearch-project/security/actions/runs/15144109381/job/42575432746?pr=5352
```
Run stefanzweifel/git-auto-commit-action@v5
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v5/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_FILE_PATTERN: .
INPUT_BRANCH value: dependabot/gradle/org.springframework.kafka-spring-kafka-test-3.3.6
From https://github.com/opensearch-project/security
* [new branch]      1.0                -> origin/1.0
* [new branch]      1.1                -> origin/1.1
* [new branch]      1.2                -> origin/1.2
* [new branch]      1.3                -> origin/1.3
* [new branch]      1.x                -> origin/1.x
* [new branch]      2.0                -> origin/2.0 …
```

Fix dependabot_pr workflow

---

src/main/java/org/opensearch/security/ssl/config/KeyStoreConfiguration.java
src/test/java/org/opensearch/security/ssl/CertificatesRule.java
src/test/java/org/opensearch/security/ssl/CertificatesUtils.java
src/test/java/org/opensearch/security/ssl/SslContextHandlerTest.java

Added additional unit test for the https://github.com/opensearch-project/security/issues/4949 issue

Additional unit test for #4949 

---

CHANGELOG.md
src/integrationTest/java/org/opensearch/security/privileges/TenantPrivilegesTest.java
src/main/java/org/opensearch/security/configuration/PrivilegesInterceptorImpl.java
src/main/java/org/opensearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/privileges/PrivilegesInterceptor.java
src/main/java/org/opensearch/security/privileges/TenantPrivileges.java
src/main/java/org/opensearch/security/rest/SecurityInfoAction.java
src/main/java/org/opensearch/security/rest/TenantInfoAction.java
src/main/java/org/opensearch/security/securityconf/ConfigModel.java
src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
src/main/java/org/opensearch/security/securityconf/impl/SecurityDynamicConfiguration.java
src/test/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluatorTest.java

This change applies the principles used for the optimized privilege evaluation feature (#4380) also for tenant privileges. This should fix the performance issues observed in #5342 and #5129.
* Category: Enhancement 
* Why these changes are required? The old implementation had severe performance issues on clusters with many tenants
* What is the old behavior before changes and new behavior after changes? No behavioral changes.
Fixes #5342 
Fixes #5129
- New unit tests
- Existing integration tests
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTIN …

Optimized tenant privilege evaluation

---

CHANGELOG.md
config/roles.yml
src/main/java/org/opensearch/security/tools/democonfig/SecuritySettingsConfigurer.java

Adds search-relevance related roles to the plugin: 
- read only
- full access.
Adds search-relevance system indices to demo scripts:
- `.plugins-search-relevance-experiment`
- `.plugins-search-relevance-judgment-cache`
This is a new feature for 3.1 release, no backfort
N/A

Integrate search-relevance functionalities with security plugin

---

CHANGELOG.md
config/roles.yml

Add forecast roles and indices; format roles.yml
* Added `forecast_read_access` and `forecast_full_access` roles in `config/roles.yml` to support the forecasting feature.
* Registered forecasting system indices within the AD plugin: [TimeSeriesAnalyticsPlugin.java](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/timeseries/TimeSeriesAnalyticsPlugin.java#L1722)](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/java/org/opensearch/timeseries/TimeSeriesAnalyticsPlugin.java#L1722).
* Formatted `config/roles.yml` using `check-permissions-order.js` to satisfy code hygiene CI requirements; this formatting affected the `ltr` role but did not change any actual content
Is this a backport? If so, please add backport PR # and/or …

Add forecast roles and permissions

---

CHANGELOG.md
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
src/main/java/org/opensearch/security/filter/SecurityFilter.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
src/test/java/org/opensearch/security/configuration/ClusterInfoHolderTest.java
src/test/java/org/opensearch/security/filter/SecurityFilterTests.java
src/test/java/org/opensearch/security/privileges/PrivilegesEvaluatorUnitTest.java
src/test/java/org/opensearch/security/privileges/RestLayerPrivilegesEvaluatorTest.java

If security index is not created during node bootup and if any API call is made we receive generic error `OpenSearch Security is not initialized`. Security index may not be created for various number of reasons but commonly seen due to master not initialized. To ease the debugging and fixing the issue, adding more details to error statement and possible cause will help. This PR starts with one of the possible cause, it can be extended in future appropriately
Future adding few debug lines to ease debugging during issues
Maintenance
Easing debugging and fixing error 
To minic the scenario added this setting in opensearch.yml `node.roles: [data, ingest]` to have no master node. Then made API …

Easing debugging for security not initialized error

---

config/roles.yml
release-notes/opensearch-security.release-notes-3.1.0.0.md

* adds required permission for creating a cross-cluster forecaster
No.
No, it doesn't. …

add missing cluster:monitor permission

---

src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java

Backporting to 3.0
This getter is necessary for anyone building a custom plugin on top of OS security plugin and wants to do some analysis on originalRequested field.

[Backport 3.0] Added getter for originalRequest field in IndexResolverReplacer.Resovled

---

src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java

Backporting to 3.1
This getter is necessary for anyone building a custom plugin on top of OS security plugin and wants to do some analysis on originalRequested field.

[Backport 3.1] Added getter for originalRequest field in IndexResolverReplacer.Resovled

---

.github/workflows/maven-publish.yml
build.gradle
bwc-test/build.gradle
sample-resource-plugin/build.gradle
spi/build.gradle

Update the Maven Snapshots publish URL in accordance with the recent Sonatype migration. 
https://central.sonatype.org/publish/publish-portal-snapshots/
We have stored the `onepassword` token in this repo secrets and new credentials for Sonatypes username & password have been stored in `onepassword`.  These credentials will be exported as env variables which used by maven publish.
Part of a campaign issue https://github.com/opensearch-project/opensearch-build/issues/5551 …

Update the maven snapshot publish endpoint and credential

---

.github/workflows/dependabot_pr.yml
CHANGELOG.md

Updates changelog layout to be in-line with the guideline stated here:
https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md

Updates Changelog structure to adhere to opensearch release-notes guideline

---

CHANGELOG.md
src/main/java/org/opensearch/security/ssl/OpenSearchSecureSettingsFactory.java

Implementing the `SecureHttpTransportParameters` provider APIs, introduced by https://github.com/opensearch-project/OpenSearch/pull/18572
Towards https://github.com/opensearch-project/OpenSearch/issues/18559
For more information on following Developer Certificate of …

Provide SecureHttpTransportParameters to complement SecureTransportParameters counterpart

---

CHANGELOG.md
src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/OnBehalfOfConfig.java
src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/main/java/org/opensearch/security/authtoken/jwt/claims/JwtClaimsBuilder.java
src/main/java/org/opensearch/security/authtoken/jwt/claims/OBOJwtClaimsBuilder.java
src/main/java/org/opensearch/security/http/OnBehalfOfAuthenticator.java
src/main/java/org/opensearch/security/identity/SecurityTokenManager.java
src/main/java/org/opensearch/security/securityconf/impl/v7/ConfigV7.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
src/test/java/org/opensearch/security/identity/SecurityTokenManagerTest.java
src/test/java/org/opensearch/security/securityconf/impl/v7/ConfigV7Test.java

This is a small refactor ahead of https://github.com/cwperks/security/pull/56 to make the JWTVendor more flexible. Currently the JWTVendor is tailor made for On-Behalf-Of tokens, but will be re-used for API Tokens and needs more flexibility. This PR adds a notion of a JWTClaimsBuilder to build the claims set for different types of tokens issued by the security plugin. This PR adds an OBOJwtClaimsSetBuilder for building the claims set of an OBO token.
It also has a small refactor of `onoEnabled` -> `enabled` since its clear in context what the variable is enabling.
Maintenance
For …

Refactor JWT Vendor to take a claims builder and rename oboEnabled to enabled

---

build.gradle

Align BC FIPS versions with those used in OpenSearch core.

Align BounceCastle FIPS and password4j versions with those used in OpenSearch core

---

CHANGELOG.md
build.gradle

CVE-2025-53864:
Bump nimbus-jose-jwt 9.48 -> 10.0.2
CVE-2025-48734
Bump checkstyle 10.3.3 -> 10.26.1
Additionally forcing plexus-utils:3.1.1 to resolve dependency conflict with new checkstyle version (wants 3.3.0).
Above CVEs.
N/A
~~- [ ] New functionality includes testing~~
~~- [ ] New functionality has been documented~~
~~- [ ] New Roles/Permissions have a corresponding security dashboards plugin PR~~
~~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md)~~
~~- [ ] Commits are signed per the DCO using --signoff~~
For more information on following Developer Certificate of Origin …

[2.19] Fix CVE-2025-53864, CVE-2025-48734

---

CHANGELOG.md
src/integrationTest/java/org/opensearch/security/support/WildcardMatcherTest.java
src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
src/main/java/org/opensearch/security/rest/SecurityWhoAmIAction.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java
src/main/java/org/opensearch/security/support/WildcardMatcher.java
src/main/java/org/opensearch/security/transport/DefaultInterClusterRequestEvaluator.java
src/test/java/org/opensearch/security/UtilTests.java

Backport from #5470 
While researching https://github.com/opensearch-project/security/issues/5464 we found that the string matching algorithm used by WildcardMatcher does significantly more comparisons than necessary for simple cases.
This PR does not change the matching algorithm, but it introduces special cases for the most common patterns: "prefix*" and "*contains*". In a simple micro benchmark, we found that these optimizations can reduce the runtime required for matching large amounts of strings by 30% (see comments for micro benchmark code).
Additionally, this PR removes unused methods from WildcardMatcher and improves test coverage.
* Category Enhancement
* Why these changes are required? For clusters with many indices and roles, runtime of …

[3.1 Backport] Optimizations and simplifications for WildcardMatcher

---

CHANGELOG.md
src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/test/java/org/opensearch/security/dlic/dlsfls/StarTreeDlsFlsTest.java
src/test/resources/dlsfls/internal_users_startree.yml
src/test/resources/dlsfls/roles_mapping_startree.yml
src/test/resources/dlsfls/roles_startree.yml

Restricts usage of star tree index when DLS/FLS/FieldMasking restrictions are applied for user for a particular index.
As part of this PR , we set the `StarTreeQueryContext` to null when DLS/FLS/FieldMasking restrictions are present, so that the query falls back to the default aggregations behavior. We'll just skip using star tree for optimizations.
Do these changes introduce new permission(s) to be displayed in the static …

Restricting star tree index for users with DLS/FLS/FieldMasking restrictions

---

CHANGELOG.md
src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationNestedClaimsTests.java
src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationTests.java
src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationWithUrlParamTests.java
src/integrationTest/java/org/opensearch/security/http/JwtAuthorizationHeaderFactory.java
src/integrationTest/java/org/opensearch/test/framework/JwtConfigBuilder.java
src/main/java/org/opensearch/security/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/main/java/org/opensearch/security/auth/http/jwt/HTTPJwtAuthenticator.java
src/test/java/org/opensearch/security/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
src/test/java/org/opensearch/security/auth/http/jwt/keybyoidc/TestJwts.java

This PR abstracts the `subject ` configuration from jwt-backed auth backends to handle a list as config to get sub within nested claims of a JWT payload.
Enhancement of https://github.com/opensearch-project/security/pull/5355
Resolves https://github.com/opensearch-project/security/issues/5430
Supported Nested claims 
```
Standard structure with top-level subject:
{
"sub": "Leonard McCoy",
"aud": "TestAudience",
"iss": "TestIssuer",
"roles": "role1,role2"
}
Standard structure with top-level subject with nested structures for roles:
{
"sub": "Leonard McCoy",
"aud": "TestAudience",
"iss": "TestIssuer",
"attributes": {
"roles": "role1,role2"
}
}
Nested subject under attributes:
{
"aud": …
```

Handle subject in nested claim for JWT auth backends

---

src/main/java/org/opensearch/security/filter/SecurityFilter.java
src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/filter/SecurityRestFilterTests.java

* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation) 
Refactoring
In this [PR](https://github.com/opensearch-project/security/pull/5496) we added support to check if a user has access using query param `has_permission_check`. Changing to `perform_permission_check` (sounds more appropriate) 
Do these changes introduce new permission(s) to be displayed in the static dropdown on the front-end? If so, please open a draft PR in the security …

Update query param name to check if a user has access to call an API

---

src/integrationTest/java/org/opensearch/security/RolloverTest.java
src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java

Fixes the interpretation of the target index param in rollover requests.
* Why these changes are required? The target index param was incorrectly considered.
* What is the old behavior before changes and new behavior after changes? No changes
- Updated integration test

Fixed index resolution for rollover requests

---

CHANGELOG.md
src/main/java/org/opensearch/security/ssl/transport/SPIFFEPrincipalExtractor.java
src/test/java/org/opensearch/security/ssl/transport/SPIFFEPrincipalExtractorTest.java

* Category: Feature
As an OpenSearch cluster operator, I want to be able to use existing [SPIFFE](https://spiffe.io/) X509-SVID (https://github.com/spiffe/spiffe/blob/main/standards/X509-SVID.md) identities for node and admin authentication, so that I do not have to setup dedicated workload PKI infrastructure for OpenSearch.
Default behavior is unchanged, this adds an additional implementation of the `PrincipalExtractor` class that may be utilized via the existing `plugins.security.ssl.transport.principal_extractor_class` configuration parameter.
Unit tests in `org.opensearch.security.ssl.transport.SPIFFEPrincipalExtractorTest`
Manually tested in a running cluster over the past few …

Add SPIFFEPrincipalExtractor

---

src/integrationTest/java/org/opensearch/security/ParentChildRelationTests.java
src/main/java/org/opensearch/security/configuration/DlsFilterLevelActionHandler.java
src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
src/main/java/org/opensearch/security/util/ParentChildrenQueryDetector.java
src/test/java/org/opensearch/security/util/ParentChildrenQueryDetectorTest.java

If we detect parent/child queries, we switch the DLS mode to use the FilterLeafReader
Backport from https://github.com/opensearch-project/security/pull/5528
- integration testing

[Backport 2.19] Use FilterLeafReader based DLS for parent/child queries

---

gradle/wrapper/gradle-wrapper.properties
src/integrationTest/java/org/opensearch/security/grpc/GrpcClientAuthNoneTests.java
src/integrationTest/java/org/opensearch/security/grpc/GrpcClientAuthOptionalTests.java
src/integrationTest/java/org/opensearch/security/grpc/GrpcClientAuthRequireTests.java
src/integrationTest/java/org/opensearch/security/grpc/GrpcHelpers.java

Pending core change: https://github.com/opensearch-project/OpenSearch/pull/18915
gRPC transport is moving out of experimental in core. Settings in ITs need to reflect this change.
N/A
Unit/Integration tests
Testing plugin install step locally with the following:
```
export SNAP_VERSION=3.2.0
export PLAT=darwin
export REPOS_DIR=<security and OS repos path>
export OS_REPO=${REPOS_DIR}OpenSearch
export SEC_REPO=${REPOS_DIR}security
export SEC_TAR=${SEC_REPO}/build/distributions/opensearch-security-${SNAP_VERSION}.0-SNAPSHOT.zip
export OS_INSTALL=${OS_REPO}/distribution/archives/${PLAT}-tar/build/install …
```

Bump gradle to 8.14.3 and move gRPC transport out of experimental

---

CHANGELOG.md
src/main/java/org/opensearch/security/ssl/transport/SecuritySSLRequestHandler.java
src/main/java/org/opensearch/security/transport/SecurityInterceptor.java
src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java
src/test/java/org/opensearch/security/transport/SecurityInterceptorTests.java

With introduction of stream transport in OpenSearch (https://github.com/opensearch-project/OpenSearch/pull/18722), there could be multiple responses for a transport request, thus security plugin need to ensure the headers are injected for each response. Currently, stream transport is only available for node-node communication. 
The new flight based stream transport doesn't use DirectChannel for local node, thus this PR also addresses bypassing optimization done for local node. 
- Manually tested using scripts here -  https://gist.github.com/rishabhmaurya/f714a87ac775a70b0632c5e9e9ea15f4 
- Unit tests …

Integration of security with stream transport

---

CHANGELOG.md
sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/resource/ShareApiTests.java
sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/resource/TestUtils.java
spi/src/main/java/org/opensearch/security/spi/resources/sharing/Recipients.java
spi/src/main/java/org/opensearch/security/spi/resources/sharing/ShareWith.java
spi/src/test/java/org/opensearch/security/spi/resources/ShareWithTests.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/support/Utils.java
src/main/java/org/opensearch/security/privileges/ResourceAccessEvaluator.java
src/main/java/org/opensearch/security/resources/ResourceAccessHandler.java
src/main/java/org/opensearch/security/resources/ResourceSharingIndexHandler.java
src/main/java/org/opensearch/security/resources/api/share/ShareAction.java
src/main/java/org/opensearch/security/resources/api/share/ShareRequest.java
src/main/java/org/opensearch/security/resources/api/share/ShareResponse.java
src/main/java/org/opensearch/security/resources/api/share/ShareRestAction.java
src/main/java/org/opensearch/security/resources/api/share/ShareTransportAction.java
src/test/java/org/opensearch/security/resources/ResourceAccessHandlerTest.java

Adds a new `/share` API to support sharing of resources by dashboard component. It supports three methods:
1. GET `/_plugins/_security/api/resource/share` - requires two query params `?resource_id=<id>&resource_type=<name>` to be present.
1. fetches the current sharing information for the requested resource
2. PUT `/_plugins/_security/api/resource/share` 
```json
{
"resource_id": "%s",
"resource_type": "%s",
"share_with": {
"%s" : {
"users": ["%s"]
}
}
}
```
1. Creates or update (overrides) any existing sharing information.
3. PATCH `/_plugins/_security/api/resource/share`
```json
{
"resource_id": "%s",
"resource_type": "%s",
"add": {
%s
},
"revoke": {
%s
}
}
``` 
1. Patches existing sharing info:
1. `add` block contains information of entities and levels at which to share
2. `revoke` …

[Resource Sharing] Adds a Share API to fetch and update sharing information

---

CHANGELOG.md
libs/opensaml/build.gradle

Unblocks 3.0 build by addressing CVE-2024-47554
https://github.com/opensearch-project/opensearch-build/issues/5595#issuecomment-3177822911

Remove `commons-io` and `commons-lang3` maven metadata from being shaded in opensaml jar

---

build.gradle
spi/build.gradle

This PR updates the Gradle build files to fix compatibility with Gradle 9.
The current syntax using `$System.env.VARIABLE_NAME` for accessing environment variables is not compatible with Gradle 9.
This format is used in this repository for Sonatype credentials for SNAPSHOT publication. This fails with under Gradle 9.
```gradle
credentials {
username = "$System.env.SONATYPE_USERNAME"
password = "$System.env.SONATYPE_PASSWORD"
}
```
See [example failed workflow here](https://github.com/opensearch-project/opensearch-remote-metadata-sdk/actions/runs/17023398832/job/48255946880#step:5:74).
Update to use the `System.getenv()` method instead:
```gradle
credentials {
username = System.getenv("SONATYPE_USERNAME")
password = System.getenv("SONATYPE_PASSWORD")
}
```
Example fix which restored …

fix: Update System.env syntax for Gradle 9 compatibility

---

CHANGELOG.md
sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/resource/MigrateApiTests.java
sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/resource/SecurityDisabledTests.java
sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/resource/TestUtils.java
sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/secure/SecurePluginTests.java
sample-resource-plugin/src/main/java/org/opensearch/sample/resource/actions/transport/SearchResourceTransportAction.java
spi/src/main/java/org/opensearch/security/spi/resources/sharing/ResourceSharing.java
src/main/java/org/opensearch/security/resources/ResourceIndexListener.java
src/main/java/org/opensearch/security/resources/ResourceSharingIndexHandler.java

This change updates the `fetchAccessibleResourceIds` method in `ResourceSharingIndexHandler` to search the **resource index** directly instead of the `*-sharing` index.
* **Category**: Enhancement
* **Why these changes are required?**
Previously, we only searched the resource sharing index (`*-sharing`) and derived principals from `share_with`. This required scripts and runtime fields to flatten recipients, adding overhead. This PR also keeps track of `principals` in each resource document, we can query this field directly to determine visibility. Principals are of the form: `user:{username}`, `role:{rolename}`, `backend:{backend_role_name}`. `user:*` will be used as the convention for making a resource publicly visible.
Keeping track of `principals` in the resource document improves:
* …

[Resource Sharing] Keep track of list of`all_shared_principals` for which sharable resource is visible for searching

---

.github/workflows/plugin_install.yml

Backport the windows plugin_install fix from https://github.com/opensearch-project/security/pull/5579 to 2.19

[Backport 2.19] Fix plugin install GH workflow for Windows

---

build.gradle
src/integrationTest/java/org/opensearch/security/grpc/GrpcClientAuthNoneTests.java
src/integrationTest/java/org/opensearch/security/grpc/GrpcHelpers.java

Update test only dependency to maintain compatibility with opensearch protobufs 0.13.0.
PR updating protobuf schema on main: https://github.com/opensearch-project/OpenSearch/pull/19007
N/A
IT updates

Bump test only protobuf to 0.13.0

---

src/integrationTest/java/org/opensearch/security/TlsHostnameVerificationTests.java
src/integrationTest/java/org/opensearch/test/framework/certificate/TestCertificates.java
src/integrationTest/resources/log4j2-test.properties
src/main/java/org/opensearch/security/ssl/OpenSearchSecureSettingsFactory.java
src/main/java/org/opensearch/security/ssl/SslContextHandler.java

This fixes TLS endpoint identification
* Category: Bugfix
- Integration test

Fixed TLS endpoint identification by SAN

---

CHANGELOG.md
src/main/java/org/opensearch/security/auth/http/jwt/AbstractHTTPJwtAuthenticator.java

This PR is a simple change to forgo logging `Failed to get roles from JWT claims with roles_key '${roles_key}'. Check if this key is correct and available in the JWT payload.` if the `roles_key` is configured with an empty list.
Bug fix
Resolves https://github.com/opensearch-project/security/issues/5634

Fix JWT log spam when JWT authenticator is configured with an empty list for roles_key

---

CHANGELOG.md
sample-resource-plugin/src/integrationTest/java/org/opensearch/sample/resource/feature/enabled/ApiAccessTests.java
sample-resource-plugin/src/main/java/org/opensearch/sample/resource/actions/transport/SearchResourceTransportAction.java
sample-resource-plugin/src/main/java/org/opensearch/sample/resource/actions/transport/UpdateResourceTransportAction.java
src/main/java/org/opensearch/security/resources/ResourceIndexListener.java
src/main/java/org/opensearch/security/resources/ResourceSharingIndexHandler.java

AD saw test failure during CI run which was result of `all_shared_principals` field being removed from the document on update request. This PR fixes it by prevent such scenarios and explicitly updating `all_shared_principals` on index-requests masked as updates.
https://github.com/opensearch-project/anomaly-detection/pull/1546
Search Request after updates would fail.
Manual + Automated

[Bug Fix] Handles resource updates which otherwise may wipe out all_shared_principals

---

src/integrationTest/java/org/opensearch/security/TlsHostnameVerificationTests.java
src/integrationTest/java/org/opensearch/test/framework/certificate/TestCertificates.java
src/integrationTest/resources/log4j2-test.properties
src/main/java/org/opensearch/security/ssl/OpenSearchSecureSettingsFactory.java
src/main/java/org/opensearch/security/ssl/SslContextHandler.java

This fixes TLS endpoint identification
* Category: Bugfix
Backport from https://github.com/opensearch-project/security/pull/5647
- Integration test

[2.19 Backport] Fixed TLS endpoint identification by SAN

---

libs/opensaml/build.gradle

This PR ensures that the security repo shows as not affected by any known CVEs by forcing dependency resolution in `libs/opensaml`. Forcing dependency resolution in this library will not have any effect because the classes from all of these jars will be excluded from the final shadow jar that this lib produces. This PR is merely to make sure its not flagged during scanning. 
Maintenance
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security/blob/main/CONTRIBUTING.md#develope …

Force dep resolution in libs/opensaml even though classes are excluded from shadow
