README.md

This plugin supports the modern OpenID Connect (OIDC) protocol, not the older XML-based OpenID 2.0 protocol. This PR updates the README to clarify this.
Ideally, references in code would also be updated to refer to “OIDC” instead of just “OpenID”, but that’s likely to be a breaking change.

Clarify OpenID Connect (OIDC) support

---

src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java

Description of changes:
The security plugin assumes that transport channel is always of a particular type. The performance analyzer plugin wraps the transportChannel into a different object and this breaks the transport plugin. This change retrieves the underlying transportChannel via reflection.

Handle overridden Transport channels.

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auth/internal/InternalAuthenticationBackend.java
src/test/java/com/amazon/opendistroforelasticsearch/security/HttpIntegrationTests.java
src/test/resources/internal_users.yml

After impersonating a user using the `opendistro_security_impersonate_as` header, all of my document-level-security rules that relied on user attributes exploded.
Additionally, the attributes were not visible on a query to `_opendistro/_security/authinfo` - user name, roles, etc... all looked right, but `custom_attribute_names` was empty.
This pull request includes a unit test that checks for this behavior, along with a fix so that user attributes are handled the same way roles are on impersonation.
Closes #22.

Handle attributes when impersonating user

---

securityconfig/roles.yml

This change defines 3 new default read only roles to easily allow integration with the [opendistro alerting plugin](https://github.com/opendistro-for-elasticsearch/alerting)
The three roles are as follows:
- **alerting_view_alerts**: Allows a user to view alerts. No monitors or destinations, also does not allow users of this role to acknowledge alerts.
- **alerting_crud_alerts**: Allows a user to view and acknowledge alerts. User cannot view monitors or destinations.
- **alerting_full_access**: Provides full functionality of the alerting plugin.
Testing done manually using a single user for each role.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

Predefined roles for alerting.

---

securityconfig/roles.yml

Reverts opendistro-for-elasticsearch/security#88
- Reverting due to incompatible yml format

Revert "Predefined roles for alerting."

---

securityconfig/roles.yml

Fix for alerting roles since with security plugin v1.0 the format has changed. The roles still have the same permissions as [this pr](https://github.com/opendistro-for-elasticsearch/security/pull/88).
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

Alerting roles fix

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java

Run unit test result:
[INFO]
[WARNING] Tests run: 174, Failures: 0, Errors: 0, Skipped: 22
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:jar (default-jar) @ opendistro_security ---
[INFO] Building jar: /root/Opendistro/tc-security-plugin-1.1/security/target/opendistro_security-1.1.0.0.jar
[INFO]
[INFO] --- git-commit-id-plugin:2.2.6:validateRevision (validate-the-git-infos) @ opendistro_security ---
[INFO]
[INFO] --- maven-jar-plugin:3.1.1:test-jar (default) @ opendistro_security ---
[INFO] Building jar: /root/Opendistro/tc-security-plugin-1.1/security/target/opendistro_security-1.1.0.0-tests.jar
[INFO]
[INFO] Installing /root/Opendistro/tc-security-plugin-1.1/security/target/opendistr …

Fix security configuration on OD-1.1

---

pom.xml
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java

Run unit test result:
[INFO]
[WARNING] Tests run: 99, Failures: 0, Errors: 0, Skipped: 4
[INFO]
[INFO]
[INFO] Building jar: /home/Opendistro/tc-security-0.9/security/target/opendistro_security-0.9.0.1.jar
[INFO]
[INFO]
[INFO] Building jar: /home/Opendistro/tc-security-0.9/security/target/opendistro_security-0.9.0.1-tests.jar
[INFO]
[INFO] Installing /home/Opendistro/tc-security-0.9/security/target/opendistro_security-0.9.0.1.jar …

Fix security configuration naming on OD-0.9

---

pom.xml
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java

Unit test results:
[INFO]
[WARNING] Tests run: 99, Failures: 0, Errors: 0, Skipped: 4
[INFO]
[INFO]
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/3.2.0/maven-archiver-3.2.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-archiver/3.2.0/maven-archiver-3.2.0.pom (4.3 kB at 718 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.2.0/maven-shared-utils-3.2.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/3.2.0/maven-shared-utils-3.2.0.pom (4.9 kB at 1.2 MB/s)
Downloading from central: …

Fix security configuration naming on OD-0.10

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java
src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java
src/test/resources/config_disable_all.yml

Currently, if you disable basic auth and anonymous auth, open distro index in uninitialized. This is a real problem when we have just an injected_user enabled. In a case like this, doing any API call would return a 503 - internal service error, with a cryptic message of "OpenDistro Index not Initialized". We would like to initialize the index if injected_user is enabled. This way, even if the authentication fails, you will get something that makes sense, like a 401 UNAUTHORIZED with a message of Authentication Finally failed.
Ran tests -> 
[WARNING] Tests run: 11, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 106.662 s - in com.amazon.opendistroforelasticsearch.security.IndexIntegrationTests
[INFO]
[INFO]
[WARNING] Tests run: 175, Failures: 0, Errors: 0, Skipped: 6 …

Initialize opendistro index if injected user enabled

---

securityconfig/roles.yml

This change defines 3 new default read only roles to easily allow integration with the opendistro alerting plugin
The three roles are as follows:
1. **alerting_view_alerts**: Allows a user to view alerts. No monitors or destinations, also does not allow users of this role to acknowledge alerts.
1. **alerting_crud_alerts**: Allows a user to view and acknowledge alerts. User cannot view monitors or destinations.
1. **alerting_full_access**: Provides full functionality of the alerting plugin.
```
[WARNING] Tests run: 11, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 175.457 s - in com.amazon.opendistroforelasticsearch.security.IndexIntegrationTests
[INFO] 
[INFO] 
[WARNING] Tests run: 99, Failures: 0, Errors: 0, Skipped: 4
[INFO] 
[INFO] 
[INFO] --- …
```

Predefined roles for alerting ODFE 0.10

---

securityconfig/roles.yml

This change defines 3 new default read only roles to easily allow integration with the opendistro alerting plugin
The three roles are as follows:
1. **alerting_view_alerts**: Allows a user to view alerts. No monitors or destinations, also does not allow users of this role to acknowledge alerts.
1. **alerting_crud_alerts**: Allows a user to view and acknowledge alerts. User cannot view monitors or destinations.
1. **alerting_full_access**: Provides full functionality of the alerting plugin.
```
lucaswin$ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] …
```

Predefined roles for alerting ODFE 0.9

---

opendistro-elasticsearch-security.release-notes
plugin-descriptor.properties
pom.xml

Update pom file, plugin-descriptor.properties, and release notes.
[INFO]
[WARNING] Tests run: 128, Failures: 0, Errors: 0, Skipped: 4
[INFO]
[INFO]
[INFO] Building jar: /Opendistro/security/target/opendistro_security-0.10.0.3.jar
[INFO]
[INFO]
[INFO] Building jar: /Opendistro/security/target/opendistro_security-0.10.0.3-tests.jar
[INFO]
[INFO] Installing /Opendistro/security/target/opendistro_security-0.10.0.3.jar to …

Bumping subversion 0.10.0.3

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java
src/main/java/com/amazon/opendistroforelasticsearch/security/http/proxy/HTTPExtendedProxyAuthenticator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ModuleType.java
src/test/java/com/amazon/opendistroforelasticsearch/security/http/proxy/HTTPExtendedProxyAuthenticatorTest.java

This PR introduces and extended proxy authenticator to allow proxies to pass additional user attributes that can be consumed when using document level security.  Configured like:
```
http:
xff:
enabled: true
remoteIpHeader: 'x-forwarded-for'
trustedProxies: '.*'
internalProxies: '.*'
authc:
authentication_domain_proxy:
enabled: true
order: 0
http_authenticator:
challenge: false
type: extended-proxy
config:
user_header: 'x-proxy-remote-user'
attr_header_prefix: 'x-proxy-ext-'
authentication_backend:
type: noop
```
This allows a trusted proxy to provide request headers:
```
x-proxy-ext-namespace: foo
x-proxy-ext-namespace: bar
x-proxy-ext-bu: makemoney
```
that are made available as user attributes:
```
attr.proxy.namespace: foo,bar
attr.proxy.bu: makemoney
```

extended proxy authenticator to pass additional attributes via header

---

plugin-descriptor.properties
pom.xml
src/main/java/com/amazon/opendistroforelasticsearch/security/action/configupdate/ConfigUpdateAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/configupdate/ConfigUpdateNodeResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/configupdate/ConfigUpdateRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/configupdate/ConfigUpdateRequestBuilder.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/configupdate/ConfigUpdateResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/configupdate/TransportConfigUpdateAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/whoami/TransportWhoAmIAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/whoami/WhoAmIAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/whoami/WhoAmIRequest.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/whoami/WhoAmIRequestBuilder.java
src/main/java/com/amazon/opendistroforelasticsearch/security/action/whoami/WhoAmIResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/PermissionsInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/KibanaInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/OpenDistroSecurityHealthAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/OpenDistroSecurityInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/http/netty/ValidatingDispatcher.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/rest/OpenDistroSecuritySSLInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/tools/OpenDistroSecurityAdmin.java
src/main/resources/static_config/static_roles.yml
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenSSLTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/plugin/UserInjectorPlugin.java

Changes:
1. Minor changes to reflect ES API changes.
2. Removing support of OpenSSL for Java 12+
This means: 
1. For java versions before 12, the behavior stays the same.
2. For java 12+, we use JDK SSL, and if the user enables OpenSSL with Java 12+, we give a message saying that we don't support OpenSsl with Java12+ and continue to use JDK SSL
Tested with Java 1.8, 11 & 12

Getting ready for opendistro-1.4 release

---

tools/install_demo_configuration.sh

In `install_demo_configuration.sh` was hardcoded the default directory
`/usr/share/elasticsearch`, this won't work if elasticsearch is
installed on a custom location (or if it used from the tar.gz for
testing).
Using the `BASE_DIR` variable we can get more flexibility from the script.

Use BASE_DIR in demo install script

---

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuthTokenProcessorAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/Endpoint.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/FlushCacheApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityConfigAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/OpenDistroSecurityRestApiActions.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantsApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/support/Utils.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AccountValidator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/CredentialsValidator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/InternalUsersValidator.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluatorTest.java
src/test/resources/restapi/internal_users.yml

Add new REST endpoint `_opendistro/_security/api/account`.
- GET request to get basic information of the signed-in user
```
Sample request:
GET _opendistro/_security/api/account
Sample response:
{
"user_name" : "test",
"is_reserved" : false,
"is_hidden" : false,
"is_internal_user" : true,
"user_requested_tenant" : "__user__",
"backend_roles" : [ ],
"custom_attribute_names" : [ ],
"tenants" : {
"test" : true
},
"roles" : [
"own_index"
]
}
```
- PUT request to update the credentials of the user.
```
Sample request:
PUT _opendistro/_security/api/account
{
"current_password" : "old-pass",
"password" : "new-pass"
}
Sample response:
{
"status": "OK",
"message":"'test' updated."
}
```
Supporting PR in security-kibana-plugin: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/p …

Add Account API to enable users to change their own password

---

plugin-descriptor.properties
pom.xml

bump plugin for ES v6.8.6
blocked by https://github.com/opendistro-for-elasticsearch/security-ssl/pull/23

bump plugin for ES v6.8.6

---

src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java

- Fix was already added for opendistro-1.2 
https://github.com/opendistro-for-elasticsearch/security/blob/opendistro-1.2/src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/CredentialsValidator.java#L67

Add tests for changing roles without password

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditCategory.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/RequestResolver.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/routing/AuditMessageRouter.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/helper/MockAuditMessageFactory.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditCategoryTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/DisabledCategoriesTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/routing/FallbackTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/routing/PerfTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/routing/RouterTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/routing/RoutingConfigurationTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/sink/KafkaSinkTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/sink/SinkProviderTLSTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/sink/WebhookAuditLogTest.java

Changes:
- Pull out AuditCategory from AuditMessage 
- Use EnumSet for all categories instead of List of Strings 
No new functionality added.
Fixes: https://github.com/opendistro-for-elasticsearch/security/issues/323

AuditLog: Refactor to use AuditCategory enum

---

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java

Introduce per request resolve mask, this allows us to bypass the whole resolveIndexPatterns+builder.add combo
if multiple writes in one request go to the same alias/index. This is the common case in bulk indexing.
Split off from a bigger PR focused on solving perf problem with indexing to long chians of indices with a write alias to one of them.
https://github.com/opendistro-for-elasticsearch/security/pull/258

[Optimization] Memoize results of resolveIndexPatterns for Bulk requests

---

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AccountValidator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/Hashed.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java

Bug:
- Updating user hash was replacing the entire entry causing it to lose the roles attached to it directly from internal users api.
- Not returning bad request when both password and hash are not provided or empty

Fix updating password hash without replacing the entry

---

.github/workflows/ci.yml

As security plugin dropped support for openssl, it is no longer necessary to have it installed and configured during unit and integration tests.

OpenSSL is no longer required for unit/integration tests

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Upgrade checkout action to v2 to fix "fatal: reference is not a tree" issue

---

src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/SSLAuditlogTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java

*Issue #, if available: N/A
*Description of changes: Some unit tests start ES cluster(s). It is necessary to stop them.

Ensure that all clusters started during unit tests are stopped

---

.github/workflows/ci.yml

OPENDISTRO_SECURITY_TEST_OPENSSL_OPT should be set to `true` to make openssl optional. I missed it in d5b14637.

set OPENDISTRO_SECURITY_TEST_OPENSSL_OPT back to true during unit tests

---

src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java
src/test/java/com/amazon/opendistroforelasticsearch/security/TaskTests.java

The X-Opaque-Id header, when provided on the HTTP request header, would cause security plugin throws an exception. When a search request comes in, the security plugin stashes the context, hoping to start with a brand new, empty one, and re-insert headers in a whitelist (mostly security plugin headers). X-Opaque-Id is whitelisted too and re-inserted to the header. However, when we stash context, ES leaves out everything except X-Opaque-id. Thus, when we re-insert X-Opaque-id, we get exception indicating an X-Opaque-id is already present. This PR removes X-Opaque-Id from the security plugin's whitelisted headers.
This PR also fixes a test related to X-Opaque-Id: previously, it won't expose the bug, now it will.
Testing done:
- manually verified the fix mitigates …

Fix the security plugin so that we can use X-Opaque-Id

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auth/internal/InternalAuthenticationBackend.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityIndexSearcherWrapper.java
src/main/java/com/amazon/opendistroforelasticsearch/security/http/XFFResolver.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigFactory.java

*Issue #, if available: n/a
*Description of changes: publish/subscribe event bus is more flexible and will require less changes in the future. Please see [Event Bus](https://github.com/google/guava/wiki/EventBusExplained)

Migrate dynamic config from listener pattern to publish/subscribe event bus

---

pom.xml
src/main/java/com/amazon/opendistroforelasticsearch/security/auth/BackendRegistry.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auth/internal/InternalAuthenticationBackend.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityIndexSearcherWrapper.java
src/main/java/com/amazon/opendistroforelasticsearch/security/http/XFFResolver.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigFactory.java

*Issue #, if available: #369
*Description of changes: Guava EventBus implementation tries to find all possible Subscribers and requires "accessDeclaredMembers" runtime permission for all classes that the object being registered with the EventBus inherits from. That includes `java.lang.Object` that is available in multiple protection domains and for some domains ES does not grant the necessary permission. Instead of Guava, we may use an alternate implementation.

Switch from Guava EventBus to Greenrobot EventBus

---

src/main/assemblies/plugin.xml
src/main/assemblies/securityadmin-standalone.xml

*Issue #, if available:* 
*Description of changes:* Updated securityconfig yml file permissions to disable files being world-readable and executable by default.

Changing file permissions for securityconfig files

---

.github/workflows/cd.yml
.github/workflows/ci.yml

- Run maven in batch mode during Github workflows
- Cache artifacts on Github for faster CI builds

Run maven in batch mode during Github workflows

---

securityconfig/elasticsearch.yml.example
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/IgnoreAuditUsersTest.java

`opendistro_security.audit.enable_request_details` is not valid anymore.
I tried with ODFE 1.6.0 and ES gives the following error:
```
[2020-04-10T16:52:22,592][ERROR][o.e.b.Bootstrap          ] [data01] Exception
java.lang.IllegalArgumentException: unknown setting [opendistro_security.audit.enable_request_details] did you mean any of [opendistro_security.audit.enable_rest, opendistro_security.audit.enable_transport, opendistro_security.audit.log_request_body]?
```

Remove invalid option.

---

src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java
src/test/java/com/amazon/opendistroforelasticsearch/security/TaskTests.java

Backporting commit c3609481326ced46980d4ce698635d6da6ae62c4

[Backport] Fix the security plugin so that we use X-Opaque-Id (#349)

---

src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java
src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenSSLTest.java

Enable limited OpenSSL support

---

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrateApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ValidateApiAction.java

Fix routes in master

---

build.gradle

- Update gradle build script to enforce ES 7.7.0
- Use file permission from maven assembly for RPM and DEB

Update gradle build script to enforce ES 7.7.0

---

build.gradle

After installation 'elasticsearch' user that is used to run ES does not have read access to the plugin configuration files.

Use 'elasticsearch' for the group during rpm/deb installation

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/compliance/ComplianceConfigTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilterTest.java

- Removing immutable indices from compliance config as immutable indices changes the behavior of request handling and should not be impacted by enabling/disabling compliance config.
- There is testImmutableIndex test which passes. Migrated ComplianceConfigTest to OpenDistroSecurityFilterTest

Remove immutable indices from compliance config

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceConfig.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/compliance/ComplianceConfigTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfigFilterTest.java

- Moving compliance ignore users from audit config to compliance config as thats the correct place for this setting to exist. 
- Migrated all the tests

Move compliance ignore users from audit config to compliance config

---

plugin-security.policy

…licy
Issue: https://github.com/opendistro-for-elasticsearch/security/issues/489
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/security/issues/489
*Description of changes:* This permission is needed to enable StartTLS for LDAP. See http://www.docjar.com/docs/api/com/sun/jndi/ldap/ext/package-index.html

Grant access to all packages under com.sun.jndi

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceIndexingOperationListenerImpl.java

- IndexModule is called per index. 
- Current behavior, at the time it is called for index, checks for compliance write is enabled for the index. If not enabled at that time, then it creates an empty listener and will not check for compliance write updates and the index documents will be unaudited. 
- Change is creating index listener for a given index and check with the latest compliance write value at that time.

Create indexing operation listener for every index module call

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/DlsFlsFilterLeafReader.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/MaskedField.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityFlsDlsIndexSearcherWrapper.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/Salt.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/RolesValidator.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/compliance/ComplianceConfigTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/configuration/SaltTest.java

Changes:
- Removing salt from ComplianceConfig as it is not reloaded as part of it. Enabling/Disabling compliance for audit logging should not change the field anonymization behavior. 
- Refactored the salt usage into a separate FLS configuration class (inner class of DlsFlsConfig which could store other DlsFls configurations)
- Moved all the associated tests. 
- OpenDistroSecurityFlsDlsIndexSearcherWrapper was called per index, so the config had to be injected down from top level into DlsFlsFilterLeafReader (where its being used) to avoid being created everytime

Refactor salt from compliance config into Salt class

---

src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java

*Issue #, if available:* #376
When Authorization header includes "Basic" it can't be JWT token, so we don't need to try to parse it as JWT.

Avoid using Basic Authorization header as JWT token

---

src/main/resources/static_config/static_action_groups.yml

*Issue #, if available:*  https://github.com/opendistro-for-elasticsearch/security/issues/536
Removing static ILM action groups and refactoring other action groups to be consistent 

Removing static ILM action groups

---

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigFactory.java
src/test/java/com/amazon/opendistroforelasticsearch/security/OpendistroSecurityRolesTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java
src/test/resources/restapi/roles_mapping.yml
src/test/resources/roles.yml
src/test/resources/roles_mapping.yml

Earlier the InternalUsers API was filtering out all hidden/reserved roles. 
We will just restrict it to hidden/reserved roles associated via rolesmapping. This will ensure behaviour of rolesmapping and internalusers API is the same.
Tested via unit tests and manually with opendistro-1.9.0.0 - 
RolesMapping API
* Add a new user
curl -XPUT -H "Content-type: application/json"  --cacert root-ca.pem --key kirk-key.pem --cert kirk.pem -d "{ \"password\": \”XXXX\"}" https://localhost:9200/_opendistro/_security/api/internalusers/testuser
* Associate with reserved rolesmapping - super admin (should pass)
| => curl -XPUT -H "Content-type: application/json"  --cacert root-ca.pem --key kirk-key.pem --cert kirk.pem -d "{ \"users\": [\"kibanaserver\", …

Removing hidden/reserved roles added via rolesmapping

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/AuditLog.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/NullAuditLog.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditLogImpl.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/BasicAuditlogTest.java

- Currently on REST layer if user does not have access to Opendistro APIs then MISSING_PRIVILEGES is posted.
- Posting corresponding GRANTED_PRIVILEGES if user has role access to Opendistro APIs

Log granted privileges on REST layer if has access to opendistro APIs

---

src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/OpenDistroSecurityIndexSearcherWrapper.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/PermissionsInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RestApiPrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/OpenDistroSecurityInfoAction.java

*Description of changes:* There is no need to check remote TransportAddress for null before calling `PrivilegesEvaluator.mapRoles(...)`

Remove unnecessary check of remote address for null

---

src/main/java/com/amazon/dlic/auth/http/saml/Saml2SettingsProvider.java

*Issue #, if available:* #617
*Description of changes:* call to `com.onelogin.saml2.settings.SettingsBuilder.build()` requires "org.apache.xml.security.ignoreLineBreaks" property write permission in OneLogin SAML Java toolkit since version 2.4.0

Fix AccessControlException during HTTPSamlAuthenticator initialization.

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModel.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/RoleMappings.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/SecurityDynamicConfiguration.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/RoleMappingsV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/RoleMappingsV7.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/GetConfigurationApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantInfoActionTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java

Opendistro 1.3

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModel.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/RoleMappings.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/SecurityDynamicConfiguration.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/RoleMappingsV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/RoleMappingsV7.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/GetConfigurationApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantInfoActionTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java

Opendistro 1.2

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModel.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/RoleMappings.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/SecurityDynamicConfiguration.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/RoleMappingsV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/RoleMappingsV7.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/GetConfigurationApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantInfoActionTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java

Opendistro 1.0

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModel.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/RoleMappings.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/SecurityDynamicConfiguration.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/RoleMappingsV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/ConfigV7.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/RoleMappingsV7.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/GetConfigurationApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantInfoActionTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java

Opendistro 1.1

---

securityconfig/config.yml
src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/PatchableResourceApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/GetConfigurationApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantInfoActionTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java
src/test/resources/restapi/securityconfig_tenantinfo.json

Opendistro 0.9

---

securityconfig/config.yml
src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/PatchableResourceApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/rest/TenantInfoAction.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/GetConfigurationApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/TenantInfoActionTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java
src/test/resources/restapi/securityconfig_tenantinfo.json

Opendistro 0.10

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessageTest.java

- Cleanup header filtering logic. Creating two maps in one flow. 
- Input can be immutable map hence making a map clone (retaining behavior)
- Using wildcard pattern
- Added tests 

Clean up rest and transport header filtering

---

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AuditValidator.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuditApiActionTest.java

- Addresses #324 to fail on invalid categories in the request.
- Not all the audit categories are valid for REST transport layer
- Fails with 400 bad request if invalid categories are passed

Fail on invalid rest and transport categories

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AbstractAuditLog.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditlogTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/BasicAuditlogTest.java

- Removing hard coded check for transport cluster & index monitor actions
- Retaining internal actions to be ignored
- Updated tests

Remove cluster monitor check from audit transport check

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/config/AuditConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/compliance/ComplianceConfig.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AuditApiActionTest.java

- Currently non-default values are ignored in serialization based on Java defaults because of which during deserialization the defaults are reset causing different values to be used. 
- For eg: if /config/audit/log_request_body is false, then it is not stored during serialization and during the deserialization, since the value is not stored, the default is reset to false.
- `JsonInclude.Include.NON_NULL` will store all non-null & non-default values also
- Added test 

Add non-null to store even non-default values in serialization

---

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java

… convertToString util helper
*Description of changes:* Replaced DocumentBuilderFactory with onelogin util to prevent XXE attacks. Onelogin util has checks for XXE attacks. See - https://github.com/onelogin/java-saml/blob/master/core/src/main/java/com/onelogin/saml2/util/Util.java#L335-L409

Using onelogin util helper instead of DocumentBuilderFactory

---

src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java

Create new instance of `MockSamlIdpServer` for every unit test to avoid dependency on its state between tests.

Fix unit tests failures in HTTPSamlAuthenticatorTest

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditLogImpl.java

*Description of changes:* In unit tests relying on shutdown hook leads to the memory leak as more and more hooks are added every time `AuditLogImpl` is constructed.

Close AuditLog while closing OpenDistroSecurityPlugin and unregister shutdown hook when closing AuditLogImpl.

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/integration/BasicAuditlogTest.java

- Currently 3 APIs may contain plaintext passwords which may be audit logged
- /_opendistro/_security/api/account
- /_opendistro/_security/api/internalusers
- /_opendistro/_security/api/user 
- Redact if any of the above requests contain request body (primarily PUT/PATCH) but want to consider possibility of customer accidentally supplying the plain text password for GET requests
- Replace with `__SENSITIVE__` so that customer knows some content is redacted 
- Added tests

Redact request body for APIs that may contain plaintext password

---

build.gradle

A community user found a bug in the links stated in package descriptions. check the post [here](https://discuss.opendistrocommunity.dev/t/unable-to-setup-apt-repo-for-opendistro-in-our-org/3124)
Fix the download and document link in package description. Not sure if it needs to be changed anywhere else in this repo.

Fix download and doc link in the package description

---

build.gradle
plugin-descriptor.properties
pom.xml

Update elasticsearch dependency to 7.9.1.
*Testing:*
Ran `OPENDISTRO_SECURITY_TEST_OPENSSL_OPT=true mvn -B test` (same as what the ci workflow does).
Test results: `Tests run: 926, Failures: 0, Errors: 0, Skipped: 28`

Bump elasticsearch version to 7.9.1

---

build.gradle
plugin-descriptor.properties
release-notes/opendistro-for-elasticsearch-security.release-notes-1.10.1.0.md

Update plugin version to 1.10.1.0 and add release notes.
*Testing:*
Ran OPENDISTRO_SECURITY_TEST_OPENSSL_OPT=true mvn -B test (same as what the ci workflow does).
Test results: Tests run: 926, Failures: 0, Errors: 0, Skipped: 28

Bump to 1.10.1.0 and add release notes

---

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
src/test/resources/saml/metadata.xml

Currently if you set metadata xml content with a new line at the beginning of the file the security plugin is not able to read the XML content .
Did the following test on master branch. Add lines to start and end of saml/metadata.xml, also lines in between tags.
Run 
```
mvn -Dtest=HTTPSamlAuthenticatorTest#testMetadataBody test
- Without trim (FAIL)
[ERROR] Errors: 
[ERROR] com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticatorTest.testMetadataBody(com.amazon.dlic.auth.http.saml.HTTPSamlAuthenticatorTest)
[ERROR]   Run 1: HTTPSamlAuthenticatorTest.testMetadataBody:212 » Runtime …
```

Removing newline whitespace from metadata content

---

pom.xml

Exclude jakarta.activation-api library from CXF transient dependencies to avoid conflict with jakarata.activation

---

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/InternalUsersApiAction.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/PatchableResourceApiAction.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AccountApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java

- Change status of hidden resources to NOT_FOUND
- Currently some places return NOT_FOUND, FORBIDDEN and also BAD_REQUEST for hidden resources.
- Consolidate all resource writeable validation checks
- Update tests
Using components from previous PR https://github.com/opendistro-for-elasticsearch/security/pull/716 

Consolidate writeable resource validation check

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditLogImpl.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/routing/AuditMessageRouter.java

Fix IllegalStateException that is raised when AuditLogImpl.close() is called from ES Bootstrap shutdown hook.

---

securityconfig/roles.yml
tools/install_demo_configuration.sh

For https://github.com/opendistro-for-elasticsearch/alerting/issues/6
1. Add alerting plugin config and alerts indices to `system_indices`
2. Add default alerting roles

Demo config for plugins security and default alerting roles

---

src/main/java/com/amazon/opendistroforelasticsearch/security/http/HTTPProxyAuthenticator.java
src/test/java/com/amazon/opendistroforelasticsearch/security/http/proxy/HTTPExtendedProxyAuthenticatorTest.java

Fix missing trim when parsing roles in proxy authenticator

Fix missing trim when parsing roles in proxy authenticator

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/DualModeSSLHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLNettyTransport.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/util/SSLConnectionTestResult.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/util/SSLConnectionTestUtil.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/util/TLSUtil.java
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java
src/test/java/com/amazon/opendistroforelasticsearch/security/EncryptionInTransitMigrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/DualModeSSLHandlerTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/util/SSLConnectionTestUtilTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/ssl/util/TLSUtilTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java

- Adding SSL dual mode support for SSLOnly
(cherry picked from commit 27f33fb)
Co-authored-by: Vengadanathan Srinivasan <vengadan@amazon.com>

Adding SSL dual mode support for SSLOnly

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/PrivilegesInterceptorImpl.java
src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluatorResponse.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesInterceptor.java
src/test/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilterTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/multitenancy/test/MultitenancyTests.java

*Description of changes:* Create explicit `CreateIndexRequest` if index or alias does not exist instead of relying on auto index create ES functionality.

When replacing .kibana index with multi-tenant index, create index with alias if one already does not exist

---

securityconfig/roles.yml
tools/install_demo_configuration.sh

*Issue https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/195*
Moving AD indices to system index and defining pre-defined roles for Anomaly Detection plugin users.

Demo Config : Adding AD Indices to system index and creating pre-defined roles

---

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v6/InternalUserV6.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/MigrationTests.java

Unrecognized field "password" exception gets thrown out during migrating from 6.x to 7.x.
This PR is to fix the logic handling empty password in migration.
*Related PRs:*
Some of the review comments are in this old PR - https://github.com/opendistro-for-elasticsearch/security/pull/809

Fix empty password issue in upgrade from 6x to 7x

---

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/CredentialsValidator.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/AbstractRestApiUnitTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java

*Issue #, if available:* 
Given that Kibana and ES don't allow login with empty password, it'd make sense to deny empty password in internal user creation.
This PR is to add the validation to deny empty password in internal user creation.

Reject empty password in internal user creation

---

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java
src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java

Adding requested tenant to the thread context transient info for consumption
Why this change is required?
When transport action is invoked, thread context has information related to user and roles. this change adds tenant along with user and roles to consume by plugins. This helps plugin getting user requested tenant for its operation (like filing data based on tenant) without making another "authinfo" call.
Tests:
mvn test tested on 7.9.1.
Validated that the common-utils:User.parse() does not break with this change

Adding requested tenant to the thread context transient info for consumption

---

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java

```
org.elasticsearch.transport.RemoteTransportException: [][][indices:admin/aliases/get]
Caused by: org.elasticsearch.ElasticsearchException: java.io.OptionalDataException
at com.amazon.opendistroforelasticsearch.security.support.Base64Helper.deserializeObject(Base64Helper.java:185) ~[?:?]
at com.amazon.opendistroforelasticsearch.security.auditlog.impl.AbstractAuditLog.getUser(AbstractAuditLog.java:626) ~[?:?]
at com.amazon.opendistroforelasticsearch.security.auditlog.impl.AbstractAuditLog.logMissingPrivileges(AbstractAuditLog.java:234) ~[?:?]
at com.amazon.opendistroforelasticsearch.security.auditlog.impl.AuditLogImpl.logMissingPrivileges(AuditLogImpl.java:187) ~[?:?]
at com.amazon.opendistroforelasticsearch.security.auditlog.AuditLogSslExceptionHandler.logError( …
```

Fix for java.io.OptionalDataException that is caused by changes to User object after it is put on thread context.

---

.github/release-notes-drafter-config.yml

ODFE release notes standards require the headers to be at level 3(`###`), but by default, release notes drafter generates headers at level2(`##`)
This PR is to add a replacer to replace level 2 headers with level 3.

Add a replacer to release-notes-drafter-config

---

src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java

1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_): Enhancement
2. __Github Issue # or roaddmap entry, if available:__: N/A
In HTTPSamlAuthenticator am using SAML roles_key and subject_key as the JWT roles_key and subject_key. This will ensure that while logging/retrieving subject_key and roles_key we are using the SAML key for SAML auth instead of the JWT key.
These will improve logging for SAML.
5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screenshot if avaialble_)
6. __Testing done:__ (_Please provide details …

Using SAML subject_key and roles_key in the HTTPSamlAuthenticator

---

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java
src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java

_Enhancement
2. __Github Issue # or roaddmap entry, if available:__
Cherry-pick of commit (#850, #864, #869, #877)
Cherry-pick of commit (#850, #864, #869, #877)
Adding requested tenant to the thread context transient user info
When plugin gets the transport call, additional tenant info will be part of thread context
This change is required to support tenant for plugin metadata (Currently Report plugin filters data based on user tenant)
5. __What is the old behavior before changes and new behavior after changes?__ (_Please …

Adding requested tenant to the thread context transient user info for consumption (#850)

---

src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java

- Refactoring
- N/A
- Rolesmapping is loaded from the index. For every request, we are creating same wildcard matchers and iterating over them https://github.com/opendistro-for-elasticsearch/security/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java#L209 
- Use HashSet instead of TreeSet (O(1) vs O(log n) for add, remove, contains) and we are not taking any advantage of ordering
- Optimize creating wildcard …

Optimize by avoid creating wildcard matchers for every request 

---

.github/workflows/cd.yml
README.md
dev/scan_veracode.sh
pom.xml

Maintenance
Rename .zip file from opendistro_security to opendistro-security to comply with [ODFE artifacts naming convention](https://quip-amazon.com/gmuHA2uDtWHV/ODFE-artifact-naming-convention)
The [naming convention tracker ](https://quip-amazon.com/7fg8AqP9aMzM/ODFE-artifact-naming-convention-tracker#s:QFO9CAXScUB;QFO9CAPb1Xh) requires security plugin to rename the zip file.
5. __What is the old behavior before changes and new behavior after changes?__ (_Please add …

Rename security plugin artifacts from opendistro_security to opendistro-security

---

securityconfig/elasticsearch.yml.example
securityconfig/roles.yml
tools/install_demo_configuration.sh

Issue #, if available:
Description of changes:
Added system index configuration for notebooks plugin
Added default roles configuration required for notebooks functionality
Updated demo config and example with above system index configurations
The changes are similar to #836 

Add security configuration for Kibana Notebooks

---

src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/sink/WebhookAuditLogTest.java

Try using another port 8088 for running the webhook test

---

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java
src/test/java/com/amazon/opendistroforelasticsearch/security/HttpIntegrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/IntegrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/sink/WebhookAuditLogTest.java
src/test/resources/internal_users.yml
src/test/resources/roles_bulk.yml
src/test/resources/roles_mapping.yml

Maintenance
Backporting changes
Unit testing
N/A
8. __Is it backport from master branch?__ (_If yes, please add backport …

Backport Opendistro 1.8

---

securityconfig/roles.yml

Maintenance
N/A
Add new AD search task action to AD read access
Search AD task action should be part of AD read access.
We add new API to search AD task.
No change to actual source. No additional testing needed.
7. …

add AD search task permission to ad read access

---

src/main/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentials.java
src/test/java/com/amazon/opendistroforelasticsearch/security/cache/CachingTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/user/AuthCredentialsTests.java

Fixes #873.
Description of changes:
This PR fixes the `AuthCredentials` class to correctly consider two `AuthCredentials` equal if they have the same username and both instances have null passwords. Before this PR, if both instances had null passwords, they would be considered not equal, causing them to never be cached. This fixes caching for backends using anonymous authentication.

Fix AuthCredentials equality

---

securityconfig/elasticsearch.yml.example

Documentation / Sample config 
Community Question: https://github.com/opendistro-for-elasticsearch/security/issues/1007 
Sample yml configuration for password strength rules.
To provide sample configuration to users who want to setup password strength rules for internal users 
N.A
6. __Testing done:__ (_Please provide details of testing …

Sample configuration for password strength rules

---

pom.xml
release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.0.0.md

Maintenance
1. Revert back the renaming of jar file.
2. Update release notes 1.13 to keep it up-to-date.
1. Revert back the renaming of jar file.
2. Update release notes 1.13 to keep it up-to-date.
No changes in behavior. …

Revert back the renaming of jar file and update release notes 1.13

---

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV6.java
src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/ConfigModelV7.java
src/test/java/com/amazon/opendistroforelasticsearch/security/HttpIntegrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/IntegrationTests.java
src/test/resources/internal_users.yml
src/test/resources/roles_bulk.yml
src/test/resources/roles_mapping.yml

Maintenance
Optimization
Unit testing
NA
8. __Is it backport from main branch?__ (_If yes, please add backport PR # and …

backport opendistro-1.1

---

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
src/test/java/com/amazon/opendistroforelasticsearch/security/IntegrationTests.java

Fix for "java.lang.IllegalArgumentException: The array of keys must not be null" for "_cat/health" requests

---

build.gradle
plugin-descriptor.properties
pom.xml
release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.1.0.md

Maintenance
Bump version to 1.13.1.0
Release 1.13.1.0
UT
8. __Is it backport from main branch?__ …

Bump version to 1.13.1.0

---

src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java
tools/install_demo_configuration.sh

Co-Authored-By: Vincenzo De Naro Papa <vincenzo.denaropapa@gmail.com>
Maintenance
#208
Remove sample code adding excessive change to ES cluster configuration
And remove such setting in test code to reflect such behavior
Reduce confusion and prevent altering configuration that is unrelated to the plugin
Old behavior: …

 Remove code setting the value for cluster.routing.allocation.disk.threshold_enabled

---

securityconfig/elasticsearch.yml.example

This commit updates the documentation for the snapshot restore settings in the example elasticsearch configuration file.
From what I have gathered from testing and [reading the code](https://github.com/opendistro-for-elasticsearch/security/blob/v1.11.0.0/src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java#L112) I concluded that the docs were out of date. By default normal users _can_ restore snapshot if they have sufficient priviliges which is contrary to what the documentation said before this commit.
Thought that it might be worth an update as to not confuse other people when they are reading the example configuration for elasticsearch security plugin :slightly_smiling_face:
By submitting this pull request, I confirm that …

Update docs on snapshot restore settings

---

src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
src/test/java/com/amazon/opendistroforelasticsearch/security/IndexIntegrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/sink/WebhookAuditLogTest.java

Bug fix
#718 
When an index with invalid name is mentioned, instead of returning `invalid_index_name_exception` security plugin throws `security_exception`, which misleads users.
**Old behavior:** When an index with invalid name is mentioned, security plugin throws `security_exception`
**New bahavior** Returning …

Backport to opendistro-1.0

---

src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessage.java
src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/support/Utils.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/compliance/RestApiComplianceAuditlogTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/auditlog/impl/AuditMessageTest.java

- BCrypt hashes of internal users may be considered sensitive
- If auditing security index and doc is internalusers then redact all BCrypt hashes with `__HASH__` 
- Added separate methods for adding request body for security index configs as check is already done and not penalizing non security config logs 
- Changed type of convertStructuredMapToBytes to `Map<String, ?>` as used by Elasticsearch
- Updated tests 

Redact BCrypt security config internal hashes from audit logs

---

src/main/java/com/amazon/opendistroforelasticsearch/security/tools/Hasher.java

change the Java helper for cli reference for hash.sh
helper for this function is set to display "usage: hasher.sh [-env <name environment variable>] [-p <password>]" 
while it refers to hash.sh
https://github.com/opendistro-for-elasticsearch/security/blob/main/tools/hash.sh
1. __Category:__ Bug fix
change the Java helper for cli reference for hash.sh that was previously reference to hasher.sh
misleading usage helper for the hash.sh cli
6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing …

[Fix][Usage][Hasher] wrong file reference hash.sh

---

src/main/resources/static_config/static_roles.yml

Enhancement
N/A
Allows OpenSearch Dashboards server to access its indices with default `kibanaserver` role
Lack of required permissions granted to `kibanaserver` role renders OpenSearch Dashboards unusable
Old behavior: `kibanaserver` role does not have access to index patterns `.opensearch_dashboards` nor its derivatives
New behavior: …

Allow opensearch server to access its new index

---

.github/workflows/ci.yml

Maintenance
Build security plugin on top of 1.x branch.
The 1.x is the stable branch with new fixes on OpenSearch core.
UT
7. __TO-DOs, if any:__ (_Please describe pending items and provide Github …

Build plugin on top of 1.x branch of OpenSearch core

---

src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/test/java/org/opensearch/security/SlowIntegrationTests.java

__NOTE__: This commit has been moved from opendistro repo to opensearch. The manual test was done using docker in opendistro. Docker testing is currently unavailable in opensearch so did not perform a manual test here yet.
1. __Category:__ Bug fix
3. __Description of changes:__ In the plugin bootstrap logic, when the security index is being populated (if empty) from the static files, currently the health check on the index is done after populating the data - and if the index is red, the population of data fails and the plugin perpetually fails all the non-super admin rest requests unless a manual intervention is done. This usually involves …

Delay the security index initial bootstrap when the index is red

---

.github/workflows/ci.yml
build.gradle
pom.xml

Maintenance
- Build OpenSearch 1.0.0-rc1 on CI.
- Make security plugin compatible with OpenSearch 1.0.0-rc1.
OpenSearch release 1.0.0-rc1
UT
7. __TO-DOs, if any:__ (_Please describe pending items and …

Add build.version_qualifier and make security plugin compatible with OpenSearch 1.0.0-rc1

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/ssl/transport/SSLConfig.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/support/SecuritySettings.java
src/test/java/org/opensearch/security/EncryptionInTransitMigrationTests.java

Refactoring
Add fallback for the `Dynamic` setting `opendistro_security_config.ssl_dual_mode_enabled`
UT
8. __Is it …

Add fallback for opendistro_security_config.ssl_dual_mode_enabled

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Use JDK 14 for CI and CD

---

plugin-security.policy
src/main/java/org/opensearch/security/support/Base64Helper.java
src/main/java/org/opensearch/security/user/User.java

bug fix 
2. __Github Issue # or road-map entry, if available:__ #1259
3. __Description of changes:__ To be backward compatible it is necessary to preserve wire protocol between nodes. Changing package names caused wire protocol incompatibility. To restore compatibility, we can replace package names during serialization and restore them back during deserialization.
4. __Why these changes are required?__ to support mixed cluster during rolling upgrade
6. __Testing …

Replace opensearch class names with opendistro class names during serialization and restore them back during deserialization

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java
src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java
src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java
src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java
src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java
src/test/resources/security_passive/action_groups.yml
src/test/resources/security_passive/audit.yml
src/test/resources/security_passive/config.yml
src/test/resources/security_passive/internal_users.yml
src/test/resources/security_passive/nodes_dn.yml
src/test/resources/security_passive/roles.yml
src/test/resources/security_passive/roles_mapping.yml
src/test/resources/security_passive/tenants.yml
src/test/resources/security_passive/whitelist.yml

 Backport issue(#1156) and issue(#1057) to branch opendistro-1.10

---

release-notes/opensearch-security.release-notes-1.0.0.0.md

Consolidate the release notes for RC1 and GA

---

src/main/java/com/amazon/opendistroforelasticsearch/security/OpenDistroSecurityPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/configuration/CompatConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/filter/OpenDistroSecurityFilter.java
src/main/java/com/amazon/opendistroforelasticsearch/security/setting/OpenDistroDynamicSetting.java
src/main/java/com/amazon/opendistroforelasticsearch/security/setting/TransportPassiveAuthSetting.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/OpenDistroSecuritySSLPlugin.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSSLConfig.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLRequestHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/transport/OpenDistroSecuritySSLTransportInterceptor.java
src/main/java/com/amazon/opendistroforelasticsearch/security/support/ConfigConstants.java
src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityInterceptor.java
src/main/java/com/amazon/opendistroforelasticsearch/security/transport/OpenDistroSecurityRequestHandler.java
src/main/java/com/amazon/opendistroforelasticsearch/security/user/User.java
src/test/java/com/amazon/opendistroforelasticsearch/security/AdvancedSecurityMigrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/InitializationIntegrationTests.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/AbstractSecurityUnitTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/SingleClusterTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterConfiguration.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/cluster/ClusterHelper.java
src/test/resources/security_passive/action_groups.yml
src/test/resources/security_passive/audit.yml
src/test/resources/security_passive/config.yml
src/test/resources/security_passive/internal_users.yml
src/test/resources/security_passive/nodes_dn.yml
src/test/resources/security_passive/roles.yml
src/test/resources/security_passive/roles_mapping.yml
src/test/resources/security_passive/tenants.yml
src/test/resources/security_passive/whitelist.yml

 Backport issue(#1156) and issue(#1057) to branch opendistro-1.2

---

pom.xml

Signed-off-by: C.J. Jameson <cjcjameson@gmail.com>
1. __Category:__ 
maintenance
n/a
`mvn package` warns...
[WARNING] Some problems were encountered while building the effective model for org.opensearch:opensearch-security:jar:1.0.0.0-rc1
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
make it easier to …

Fix maven build ${version} deprecation warning

---

src/main/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/validation/AbstractConfigurationValidator.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/dlic/rest/api/UserApiTest.java
src/test/resources/restapi/actiongroup_null_array_element.json
src/test/resources/restapi/nodesdn_null_array_element.json
src/test/resources/restapi/roles_null_array_element_allowed_actions.json
src/test/resources/restapi/roles_null_array_element_cluster_permissions.json
src/test/resources/restapi/roles_null_array_element_index_patterns.json
src/test/resources/restapi/roles_null_array_element_index_permissions.json
src/test/resources/restapi/roles_null_array_element_masked_fields.json
src/test/resources/restapi/roles_null_array_element_tenant_permissions.json
src/test/resources/restapi/rolesmapping_null_array_element_backend_roles.json
src/test/resources/restapi/rolesmapping_null_array_element_hosts.json
src/test/resources/restapi/rolesmapping_null_array_element_users.json
src/test/resources/restapi/users_null_array_element.json

[opendistro-1.0][backport] Add validation for null elements in JSON array (#1157)

---

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
src/main/resources/static_config/static_action_groups.yml
src/test/java/org/opensearch/security/ResolveAPITests.java
src/test/resources/action_groups.yml
src/test/resources/action_groups_packaged.yml

Bug fix
https://github.com/opendistro-for-elasticsearch/security/issues/893
https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/598
Fix requests hitting `_resolve` endpoint failed with `403 forbidden` error due to accessing indices without proper permission. By re-configuring the logic in code, requests that were to return `403` will now success with `200` and not permitted indices will be filtered from its result.
Additional code added to unit tests and configuration ensures such …

Add support for ResolveIndexAction handling

---

.github/workflows/cd.yml

Build OpenSearch in CD workflow in order to build security plugin

---

src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/NodesDnApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

Bug fix
Currently `checkNullElementsInArray()` unit test only checks for the error code and it will pass even if request fails for a different reason. We need to check the error message to make sure that the message is also what we expect.
To make sure that the test is not passing if the request fails for a different reason.
In the new …

Update `checkNullElementsInArray()` unit test to check both error message and error code instead of only checking the error code

---

.github/workflows/ci.yml
CONTRIBUTING.md
README.md

(Cherry picked from commit dc291c2345cdb9885d7b99dff835df08bc3b15fd) …

Updating Github actions and files to use main branch. (#1023)

---

securityconfig/roles.yml

Signed-off-by: Ravi Thaluru <ravi1092@gmail.com>
Adding a new full access role for IndexManagement plugin so users who want to manage all indices, create policies, create rollups, create transforms can use the deafult role. 
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same …

Adding the default role for IM plugin

---

src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
src/test/java/org/opensearch/security/PrivilegesEvaluationTest.java
src/test/resources/internal_users.yml
src/test/resources/roles.yml

Bug fix
- Modified class `IndexResolverReplacer` to expand to, and consider hidden indices as well when resolving wildcards.
- Added test `PrivilegesEvaluationTest` to verify that the issue is present, and to verify the fix
`index.hidden` indicates whether the index should be hidden by default. Hidden indices are not returned by default when using a wildcard expression. This behavior is controlled per request through the use of the `expand_wildcards` parameter. Possible …

Fix to include hidden indices when resolving wildcards

---

build.gradle
plugin-descriptor.properties
pom.xml
release-notes/opensearch-security.release-notes-1.2.2.0.md

I copied the changes that were done [here](https://github.com/opensearch-project/security/commit/fac75a8592c4f4a50284ef8ae392278ff03ee924) but incremented the plugin version to 1.2.2 and updated log4j to 2.16.0.
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; …

Update to version 1.2.2 with log4j 2.16.0

---

release-notes/opensearch-security.release-notes-1.2.3.0.md

Adding release notes for 1.2.3 with the new log4j 2.17.0 upates
Maintenance

Added release notes for 1.2.3

---

build.gradle
plugin-descriptor.properties
pom.xml

Version bump to 1.3.0.0
Maintenance

Version bump to 1.3.0.0

---

pom.xml
release-notes/opensearch-security.release-notes-1.2.3.0.md

Added release notes for 1.2.3 (cherry-picked from d8c3dcf)
Bump log4j-core from 2.16.0 to 2.17.0 (cherry-picked from 118e951)
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Maintenance

Bump log4j-core to 2.17.0 and added 1.2.3.0 release notes

---

pom.xml
src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticator.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java

Bug Fix
Update CXF version to 3.4.5
To correctly parse JWT with escaped characters …

 Update CXF version to 3.4.5

---

.github/workflows/cd.yml
.github/workflows/ci.yml

This fix is coming from a particular workaround [here](https://github.com/apache/iotdb/pull/3122/files) to [this issue](https://github.community/t/maven-connection-timed-out/129040)
Maintenance
https://github.com/apache/iotdb/issues/3121
CI times out occasionally
6. __Testing done:__ (_Please …

Fix to prevent timeouts in GitHub actions

---

.github/workflows/cd.yml
.github/workflows/ci.yml
build.gradle
plugin-descriptor.properties
pom.xml

Maintenance
N/A
Bumping version to 1.2.4.0
Next iteration
8. __Is it …

Version bump to 1.2.4.0

---

.github/workflows/ci.yml
pom.xml
src/test/java/com/amazon/dlic/auth/ldap/LdapBackendTest.java
src/test/java/com/amazon/dlic/auth/ldap/LdapBackendTestNewStyleConfig.java
src/test/java/com/amazon/dlic/auth/ldap2/LdapBackendTestNewStyleConfig2.java
src/test/java/com/amazon/dlic/auth/ldap2/LdapBackendTestOldStyleConfig2.java
src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
src/test/java/org/opensearch/security/ssl/SSLTest.java

Adds 8, 11 and 14 to the CI matrix
Modifies UTs to drop TLSv1 and add TLSv1.2 instead
* Category: Maintenance
* Why these changes are required? Because opensearch claims compatibility for 8, 11 and 14
* What is the old behavior before changes and new behavior after changes? N/A
#1502 
Manually tested all the changes on my fork.

Modifying UTs and CI to add support for Java 8, 11 and 14

---

pom.xml

Signed-off-by: Darshit Chanpura <dchanp@amazon.com>
* Maintenance
* To fix the security vulnerability introduced by jjwt version 0.10.5 as desribed in this [issue](https://github.com/opensearch-project/security/issues/1587)
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …

Bumping jjwt version to fix dependency vulnerability created by jjwt

---

pom.xml

Signed-off-by: Darshit Chanpura <dchanp@amazon.com>
Updates outdated guava dependency. This issue was opened by whitesource as part of version compatibility/vulnerability check. But the version suggested by whitesource was an android toolkit, and hence this PR was opened to update to it to Java toolkit `30.1.1-jre`.
* Enhancement
* White-source suggested
https://github.com/opensearch-project/security/issues/1565
Manual testing
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTI …

Updates guava dependency to latest stable version suggested by whitesource

---

tools/audit_config_migrater.bat
tools/audit_config_migrater.sh
tools/hash.bat
tools/hash.sh
tools/securityadmin.bat
tools/securityadmin.sh

Add support for OPENSEARCH_JAVA_HOME
Closes https://github.com/opensearch-project/security/issues/1600
The scripts have been tested under Windows / Linux

Add support for OPENSEARCH_JAVA_HOME

---

pom.xml

Excluding velocity from dependencies as it is not used and it has security vulnerabilities (see #1605)
* Category: Maintenance
Fixes #1605 
Build locally. Will make sure all ITs pass.
- N/A New functionality includes testing
- N/A New functionality has been documented

Exclude velocity 1.7 from OpenSAML dependency

---

.github/workflows/ci.yml

Always run the checks on any push or pull request no matter the target.
Following the example from https://github.com/opensearch-project/opensearch-build/blob/bddbc06dd5ee6b67d3be3230cab922a083d4f15a/.github/workflows/python-tests.yml#L4
- Resolves #1614 

Always run the checks on any push or pull request no matter the target

---

MAINTAINERS.md

Updating practices for maintainers

Updating practices for maintainers

---

build.gradle

Add 'opens' for java.io libraries to unblock build
----
Background on JDK visibility changes over time, and why this is needed
> If you cannot obtain or deploy newer versions of tools and libraries, then there are two command-line options that enable you to grant access to specific internal APIs for older versions of tools and libraries:
> 
> [--add-exports](https://docs.oracle.com/en/java/javase/17/migrate/migrating-jdk-8-later-jdk-releases.html#GUID-2F61F3A9-0979-46A4-8B49-325BA0EE8B66): If you have an older tool or library that needs to use an internal API that has been strongly encapsulated, then use the --add-exports runtime option. You can also use --add-exports at compile time to access the internal APIs.
> [--add-opens](https://docs.oracle.com/en/java/javase/17/migrate/migrating-jd …

Add 'opens' for java.io libraries to unblock build

---

.github/workflows/ci.yml
build.gradle

Add jacoco report and pass the location to codecov
- Resolves #1612 

Add jacoco report and pass the location to codecov

---

src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java

Bug fix
2. __Why these changes are required?__ 
This is how to set a different separator for the roles attribute that comes on the SAML assertion.
3. __What is the old behavior before changes and new behavior after changes?__
Now if the setting is spelled correctly according to the documentation it will be picked up, if there is a conflicting typo'ed spelling it will be only used if the correctly spelled setting is not present.
Built off of the changes by @cliu123 in #1024 
- Resolves #969 
Added unit tests to cover correct setting, and legacy setting
For more information …

Fix the settings of roles_seperator

---

build.gradle

[#1633]
- Built security plugin 1.3.0.0
- Installed security plugin 1.3.0.0 on OpenSearch 1.3.0 …

Remove '-SNAPSHOT' from opensearch.version in plugin descriptor

---

src/test/java/org/opensearch/security/filter/SecurityFilterTest.java

Add test to make sure exception causes aren't sent to callers
* Related to #1632

Add test to make sure exception causes aren't sent to callers

---

.github/workflows/ci.yml

Switch gradle to info logging for improved test debugging
- Originally included in https://github.com/opensearch-project/security/pull/1632

Switch gradle to info logging for improved test debugging

---

.github/workflows/ci.yml

Removed artifacts step as they were never used and the martix of jdk
release would override them (saves couple minutes from check runtime)
- Originally included in https://github.com/opensearch-project/security/pull/1632

Remove artifact step from CI workflow

---

build.gradle

After migrating from maven to gradle, the build script for security in OpenSearch-build was broken.  We could not use the default script and had to make modifications, see https://github.com/opensearch-project/opensearch-build/pull/1631
Built locally with opensearch-build 1.3.0 manifest, see https://github.com/opensearch-project/opensearch-build#building-from-source

Use standard opensearch.version property

---

build.gradle

* Why these changes are required? `netty-tcnative-2.0.25.Final` does not support ARM64.
* What is the old behavior before changes and new behavior after changes? No behavior changes
#1647
Compile and UTs

Remove netty-tcnative dependency to unblock security plugin build on ARM64

---

.gitignore

* Why these changes are required? `plugin-descriptor.properties` is not needed in version contol.
* What is the old behavior before changes and new behavior after changes? No behavior changes
#1650
Not a backport
- Tested on local: `plugin-descriptor.properties` is not captured by Git.
- UTs …

Make Git ignore plugin-descriptor.properties file

---

securityconfig/roles.yml
tools/install_demo_configuration.sh

Signed-off-by: Yaliang Wu <ylwu@amazon.com>
This PR is to configure ML reserved roles and system indices. This is to replace the old PR https://github.com/opensearch-project/security/pull/1308
New feature
We need to release new ML plugin in 1.3
We add two new reserved roles for ML plugin.
We add two new system indices for ML plugin.
Test done on local single node cluster and on multi-node cluster on EC2. …

configure ML reserved roles and system indices

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/action/configupdate/ConfigUpdateNodeResponse.java
src/main/java/org/opensearch/security/action/configupdate/ConfigUpdateResponse.java
src/main/java/org/opensearch/security/filter/SecurityRestFilter.java
src/main/java/org/opensearch/security/rest/SecurityConfigUpdateAction.java
src/main/java/org/opensearch/security/rest/SecurityWhoAmIAction.java
src/main/java/org/opensearch/security/support/WildcardMatcher.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/SecurityAdminIEndpointsTests.java
src/test/java/org/opensearch/security/SecurityAdminInvalidConfigsTests.java
src/test/java/org/opensearch/security/SecurityAdminMigrationTests.java
src/test/java/org/opensearch/security/SecurityAdminTests.java
src/test/java/org/opensearch/security/auditlog/sink/SinkProviderTLSTest.java
src/test/java/org/opensearch/security/auditlog/sink/WebhookAuditLogTest.java

* Category = Maintenance
Check description in: https://github.com/opensearch-project/security/issues/1578
https://github.com/opensearch-project/security/issues/1578
Testing done: 
- unit testing
- manual tests

securityadmin: Replace TransportClient by RestHighLevelClient

---

build.gradle

There is a copy of the admin tools that are produced on build but are
not consumed or distributed as part of this project.  Until we have
documentation and/or tooling that uses this we should remove it from the
project.
By removing this file the security plugin to remove its custom build logic from OpenSearch-build, [see]( https://github.com/opensearch-project/opensearch-build/issues/1631#issuecomment-1042471356).
Searched through opensearch.org, this repository, and the security-dashboards-plugin repo for references to these stand alone tools. …

Remove standalone admin tools zip file

---

.github/workflows/ci.yml

With the current checkstyle settings the build is done, but it doesn't
prevent changes from being merged that contain checkstyle violations.
We need to revisit these as a whole, **saving 3 minutes of build time** per
leg until this work has been done.
See https://github.com/opensearch-project/security/issues/1659

Disable checkstyle until rules are enforced

---

.github/workflows/ci.yml
src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java

Removes Java-17 support from CI matrix as the expected behavior is that 1.3 will fail for Java-17. Refer this discussion more details: https://github.com/opensearch-project/job-scheduler/pull/130

Remove java17 from 1.3 build matrix

---

release-notes/opensearch-security.release-notes-1.3.0.0.md

Adds release notes for 1.3.0.0
* Category - Maintenance

Adds release notes for 1.3.0.0

---

release-notes/opensearch-security.release-notes-1.3.0.0.md

Backports release notes for 1.3.0.0
See the PR to main : #1671 
* Category - Maintenance

[Backport]Adds release notes for 1.3.0.0 (#1671)

---

src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/test/java/org/opensearch/security/dlic/dlsfls/CCReplicationTest.java

Fixed rest status for the replication action failure with DLS/FLS
and updated test cases to capture status code
Signed-off-by: Sai Kumar <karanas@amazon.com>
* Why these changes are required? Latest commit changed the status in https://github.com/opensearch-project/security/pull/1541
* What is the old behavior before changes and new behavior after changes? Error code was `403` instead of `500`
https://github.com/opensearch-project/cross-cluster-replication/issues/340
unit testing
For more information on …

Fixed rest status for the replication action failure with DLS/FLS

---

build.gradle

Fixes https://www.whitesourcesoftware.com/vulnerability-database/CVE-2020-36518

Update to most recent verson of jackson-databind

---

.github/workflows/ci.yml

* Why these changes are required? The step builds security plugin but does not run tests. The step name is misleading.
#1684
UTs
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-orig …

Correct the step name in CI

---

plugin-security.policy
src/main/java/org/opensearch/security/support/Base64Helper.java
src/main/java/org/opensearch/security/user/User.java

This PR being reverted is one of the things that would be broken by JDK17. JDK17 support got postponed to 2.0 because we'd like to keep the commits like this one being reverted to support rolling upgrade from ODFE/ES versions to OpenSearch 1.x. But in 2.0, we can revert them to unblock JDK17 since we won't need to support rolling upgrade directly from ODFE/ES versions to OpenSearch 2.0. The upgrade path ODFE -> OpenSearch 1.x -> OpenSearch 2.0 will still be retained.
This reverts commit 4abbafc1f49f8ba392538102132876a58e1f9a75.
#1653
UT
For more information on following Developer Certificate of Origin and signing off your commits, …

Revert "Replace opensearch class names with opendistro class names during serialization and restore them back during deserialization (#1278)"

---

build.gradle

This reverts commit 260f5403daa5abb5f58174ccdd12d8da0a72780e.
* Why these changes are required? OpenSearch core 1.3.0 does not have this version update.
UT

Revert "Update to most recent verson of jackson-databind (#1679) (#1693)"

---

build.gradle

- UTs
- Manual Testing:
1. Install security plugin 1.4.0.0 on OpenSearch 1.4.0-SNAPSHOT
2. Start OpenSearch cluster
3. Cat indices:
```
HTTP/1.1 200 OK
Warning: 299 OpenSearch-1.3.1-SNAPSHOT-01c99f761603dc8a63795c17d132a9cdbaedb5a8 "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"
content-type: text/plain; charset=UTF-8
content-length: 77
green open .opendistro_security QaZBpKzWRI-T73ul2rS8FA 1 0 9 0 60.1kb 60.1kb
```
By submitting this pull request, I confirm that my contribution is made under …

Bump plugin version to 1.3.1.0 and OpenSearch dependency version to 1.3.1

---

build.gradle

Move to version 2.0.0.0
Keeping the default OpenSearch build version to 1.3.0 until we have
resolved the breaking changes from core.

Move to version 2.0.0.0

---

.github/workflows/plugin_install.yml
build.gradle

Added a new check to build, install, and run the security plugin with the demo configuration script.
This was built heavily borrowing from https://github.com/opensearch-project/security-dashboards-plugin/blob/main/.github/workflows/integration-test.yml
* Resolves https://github.com/opensearch-project/security/issues/1641
Automatically runs as part of PR and PUSH Github actions

Add CI check for demo script

---

.github/workflows/ci.yml
.github/workflows/plugin_install.yml
build.gradle

* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation) Enhancement
* Why these changes are required? OpenSearch 2.0.0 does not support JDK 8
#1669
UT

Remove JDK8 from CI

---

.github/workflows/ci.yml
.github/workflows/plugin_install.yml
build.gradle
gradle.properties

A single file is referenced and read for version settings, updated
the build scripts and test script to read from this file.
Added functionality and tests for build.version_qualifier parameter
* Resolves https://github.com/opensearch-project/security/issues/1676
Added a new job that verifies the built artifact name correspond to the parameters passed to gradle

Centralize version settings

---

src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java

Fixes a broken test for testing EC algo which uses an unsupported curve in JDK 17
* Resolves #1620 
Gradle test script

Fixes broken test due to unsupported EC using JDK-17

---

.github/workflows/ci.yml
gradle/wrapper/gradle-wrapper.properties

Upgrade to Gradle 7
Remove CI work around that are no longer needed
* Resolves https://github.com/opensearch-project/security/issues/1505

Upgrade to Gradle 7

---

src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java
src/test/resources/dlsfls/roles.yml
src/test/resources/dlsfls/roles_mapping.yml

Fixes an issue in Document Level Security (DLS) by improving how the min_doc_count parameter is handled. The previous behavior returns keys for aggregations with 0 matches when min_doc_count is passed as 0, regardless of whether there are actually 0 matches or matches are not visible due to DLS rules. With this fix, we throw an error message if min_doc_count is passed as 0 and DLS rules are present for that index.
UTs
For more information on following …

Fix min_doc_count handling when using Document Level Security

---

release-notes/opensearch-security.release-notes-1.3.1.0.md

* Why these changes are required? 1.3.1 release
UTs

Add 1.3.1 release notes

---

src/test/java/org/opensearch/security/test/AbstractSecurityUnitTest.java

Sleep statements should rarely be used, instead apis should allow for
blocking/non-blocking calling patterns.  Attempting to remove and clean
up these statements to speed up PR workflows.
Github Action workflows for this repo were 75+ minutes, with this change 40 minutes. **47% reduction in time.**

Speeding up tests

---

src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
src/test/java/org/opensearch/security/DataStreamIntegrationTests.java
src/test/resources/roles.yml

Signed-off-by: Sandesh Kumar <sandeshkr419@gmail.com>
* Security plugin is not able to invalidate non-permitted data-stream (get/delete/stats) requests sent using wild-card expressions. 
This is because the list of 'allIndices' in 'ResolvedIndicesProvider' class does not has the resolved names of data streams. If the 'allIndices' variable when resolved, is empty -> leads the authorization to succeed as there are no eligible index patterns to block the request. 
In this change, we add the the names of resolved data streams to 'allIndices' so data stream names also can get resolved. 
Suppose the indices are as follows in a OS cluster.
```
kusandes@a483e789b681 ~ …
```

Fix data-stream name resolution for wild-cards

---

build.gradle

Attempted workaround for a jar hell conflict in OpenSearch 2.0.0, confirming that tests can still run and pass as expected
* Resolves https://github.com/opensearch-project/OpenSearch/issues/2590
* Resolves https://github.com/opensearch-project/security/issues/1687
By running in the installation workflow, we can see if the security plugin load or create other unexpected issues.

Remove explict dependency on jackson-databind

---

.gitignore

IntelliJ compilation outputs `out/` directory that is not needed for version control.
UTs

Make Git ignore out/ directory

---

build.gradle

Currently, CI log only gives a number of failing tests, but there is no easy way to find out what tests actually failed.
With this change, CI log summarizes a list of all failing tests, which facilitates test failure investigation.
Old behavior:
```
2022-04-01T07:19:55.2791783Z 1133 tests completed, 13 failed, 46 skipped
```
New bahavior:
```
2022-04-01T06:09:12.2380647Z Failed tests for opensearch-security:
2022-04-01T06:09:12.2381069Z [org.opensearch.security.HttpIntegrationTests::testTenantInfo]
2022-04-01T06:09:12.2381586Z …
```

List out test failures in CI log

---

src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java

For each node in the cluster we were removing and then sleeping for
250ms.  There is an API that we can wait on to be sure the node has
closed or at least take action if the closure wasn't successful.
For the usage, which is cleaning up all nodes, switching to a best
effort mode that could wait the same 250ms or return faster.
~Tested in this PR's workflow, new runtime is 25 minutes down from 40, a 40% reduction in runtime.~
Tested in this PR's workflow, new runtime is 25 minutes, seeing this amount of time hit during other runs.  While it might not provide a giant boost, I still think its worthwhile to avoid unreasoned sleeps.
For more information on following Developer …

Remove sleep when waiting for node close

---

.github/workflows/ci.yml
.github/workflows/plugin_install.yml
build.gradle
gradle.properties
src/main/java/org/opensearch/security/compliance/ComplianceIndexingOperationListenerImpl.java
src/main/java/org/opensearch/security/compliance/FieldReadCallback.java
src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/test/java/org/opensearch/security/TracingTests.java
src/test/java/org/opensearch/security/auditlog/impl/TracingTests.java
src/test/java/org/opensearch/security/dlic/dlsfls/CustomFieldMaskedComplexMappingTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsNestedTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/FlsExistsFieldsTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/FlsFieldsTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/FlsFieldsWcTest.java

Upgrade to opensearch 2.0.0 alpha1

---

src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
src/test/java/org/opensearch/security/auditlog/integration/BasicAuditlogTest.java
src/test/java/org/opensearch/security/auditlog/integration/TestAuditlogImpl.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java

I have been tracking test failures with testRestMethod very often
showing failures.  My theory is that the execution environment can
impact the order of operations sometimes causing the audit log not to
contain messages before it is checked.
Adding a new method `doThenWaitForMessages(...)` this ensures the
log queue is fresh, the triggering action completes, and the expected
number of messages were recieved.  There is a second long time window
that allows for the messages to be flushed, this is likely more than
enough - if the messages are recieved the count down latch immediately
continues execution so the tests will not wait if they are ready to
proceed.
While this new method is much more reliable not all tests were
encountering such issues, so I've keep the original convention.  This …

Add signal/wait model for TestAuditlogImpl

---

DEVELOPER_GUIDE.md
build.gradle
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/tools/AuditConfigMigrater.java
tools/install_demo_configuration.sh

Updates the folder structure created during build to follow the suggested structure.
* Category - Maintenance
1. "Before"
```
OpenSearch
│
└─── plugins
│     │
└─── opensearch-security
│          │   
└─── securityconfig
|               │   
└─── *.yml
```
2. After:
```
OpenSearch
│
└─── config
│     │
└─── opensearch-security
│          │   
└─── *.yml
```
* Resolves #1673 

Updates the folder structure for build artifacts

---

release-notes/opensearch-security.release-notes-2.0.0.0-rc1.md

How to repeat:
* `git checkout origin/2.0`
* `git log --pretty=format:"* %s" --since=3-11-2022 > release-notes/opensearch-security.release-notes-2.0.0.0-rc1.md`
* Manually organize file sections
* Add Date / Version section (copy + modify from previous release)
* Enhancements/Bug fixes/Maintenance
* Replace pull request ids with full urls via regex
* Find: `\(#(\d+)\)$`
* Replace: `([#$1](https://github.com/opensearch-project/security/pull/$1))`
* Commit with these steps / modified with additional details
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main …

Generate release notes for 2.0.0

---

build.gradle
config/checkstyle/sun_checks.xml

To aid in detection and removal of non-inclusive terms, adding a
checkstyle error when they are detected.  When we are ready to remove
all these terms from the codebase we will set these checks to error
level.
* Related to https://github.com/opensearch-project/security/issues/1664
Since all errors are ignored by default, now the checkstyle output is much easier to parse, here is an example of the output with this change.
```
...
[ant:checkstyle] [WARN] /local/home/petern/git/security/src/main/java/org/opensearch/security/tools/SecurityAdmin.java:1267: Usage should be switched to an allow* based pattern [RegexpSingleline]
[ant:checkstyle] [WARN] /local/home/petern/git/security/src/main/java/org/opensearch/security/tools/SecurityAdmin.java:1268: Usage should be switched to an allow* based …
```

Add checkstyle for non-inclusive terms

---

securityconfig/opensearch.yml.example

Since #1001, the `plugins.security.advanced_modules_enabled` configuration setting has been deprecated, so this PR removes this setting from the example configuration to avoid confusion and deprecation warnings.

Remove advanced_modules_enabled from example

---

src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java
tools/install_demo_configuration.sh

Previously the setting was `cluster.initial_master_nodes` and has since
changed to `cluster.initial_cluster_manager_nodes`.  This was causing
issues due to a bug in the fallback method that has been fixed in
OpenSearch, but getting ahead of this change before its needed.
See related https://github.com/opensearch-project/OpenSearch/pull/2779

Rename cluster settings following new 2.x convention

---

.github/workflows/ci.yml
build.gradle

This provides a more digestible version of the test results for
debugging/troubleshooting failures that occur in CI.
I moved the jacoco report to use the same location
See how this output looks from this GHA workflow summary https://github.com/opensearch-project/security/actions/runs/2204140083

Add archive of reports for test/coverage

---

securityconfig/roles.yml

Signed-off-by: Cam McKenzie <camAtGitHub@users.noreply.github.com>
Fix 'openserach' typo. 
This commit has not been tested, however I scanned 'security', 'security-dashboard-plugins, and 'opensearch' repos.
security and its dashboards are the only two occurrences of the word.

Fix 'openserach' typo in roles.yml

---

build.gradle

Fixes vulnerabilities reported by WhiteSource.
* Resolves #1802 

Updates dependency vulnerabilities versions

---

README.md

Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>
Documentation
N/A
Adding a section in the README with instructions on how to onboard/integrate new APIs with security.
For consistency and faster development of different plugins wanting to integrate new or existing APIs with security.
N/A
6. __Testing done:__ (_Please provide details of …

Add documentation about integrating APIs with security

---

build.sh

Add custom build script to ignore standalone admin.  This script is largely from the deleted version of https://github.com/opensearch-project/opensearch-build/pull/1927.  The standalone-admin zip is generated as a part of the 1.X builds and is picked up by the default build script.
This change only applies to the the 1.x line as in 2.0.0 that tool has been removed.
* Closes https://github.com/opensearch-project/security/issues/1809
Built locally with a custom manifest for 1.3.2 pointing to this change
```
% ./build.sh manifests/1.3.2/opensearch-1.3.2.yml --component security
Installing dependencies in . ...
Installing dependencies from Pipfile.lock (d422cd)...
🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/5 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a …
```

Add custom build script to ignore standalone admin

---

build.gradle

While addressing CVE-2020-36518 the security team updated to the latest
minor version of jackson-databind, whereas the OpenSearch team took the
CVE specific update.  Aligning with OpenSearch's version.
* Resolves the build break associated with https://github.com/opensearch-project/OpenSearch/issues/2597

Keep jackson-databind in alignment with OpenSearch

---

build.gradle
bwc-test/build.gradle
src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/test/java/org/opensearch/security/ccstest/RemoteReindexTests.java

Switch from RC1 to the GA of OpenSearch 2.0
* Resolves https://github.com/opensearch-project/security/issues/1823

Switch from RC1 to the GA of OpenSearch 2.0

---

securityconfig/roles.yml

Signed-off-by: Ashish Agrawal <ashisagr@amazon.com>
* Enhancement
* The Alerting plugin created a new api called getFindings and need to add its cluster permission, cluster:admin/opensearch/alerting/findings/get, as part of the default roles.
* The default `alerting_read_access` and `alerting_full_access` now has the cluster permission for getFindings
N/A
N/A
Builds fine
For more information on following …

Add Alerting getFindings cluster permission

---

src/main/java/org/opensearch/security/ssl/rest/SecuritySSLCertsInfoAction.java
src/test/java/org/opensearch/security/ssl/SecuritySSLCertsInfoActionTests.java

Introducing `_plugins/_security/ssl/certs` API path to be consistent with OpenSearch API path convention.
* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation) Enhancement
* Why these changes are required? Apply consistent API path convention.
#1827 
UTs

Introduce new API _plugins/_security/ssl/certs

---

securityconfig/roles.yml

Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>
Adding new full access and read-only roles for the Notifications plugin launching in 2.0.
There is also a `"cluster:admin/opensearch/notifications/feature/publish"` permission which is for the legacy Notification publish which only Alerting and ISM use as a fallback to their legacy behavior. This permission has been added to the Alerting and IM full access roles to ensure no disruption in functionality in the fallback case.
This PR isn't a backport but it should be backported to the `2.0` branch, I don't have permissions to add the label myself to trigger the workflow …

Add default roles for Notifications plugin

---

src/main/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticator.java
src/test/java/com/amazon/dlic/auth/http/jwt/HTTPJwtAuthenticatorTest.java

This PR adds an option to validate the issuer and/or audience claim
in a JWT per JWT authentication domain
Signed-off-by: Jochen Kressin <jkressin@floragunn.com>
The audience and issuer claim in a JWT is currently not validated by the JWT authentication domain. This PR adds a configuration option to enforce this validation per JWT authentication domain.
* Resolves #1780
* Resolves #1781
No
New unit tests added to HTTPJwtAuthenticatorTest
- [ x] New functionality includes testing …

JWT: validate issuer and audience (#1780, #1781)

---

.github/workflows/ci.yml
build.gradle
bwc-test/build.gradle
bwc-test/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties

* Bump security plugin version to 2.1.0.0 and OpenSearch core version to 2.1.0.
* Upgrading Gradle to [the version that OpenSearch core uses.](https://github.com/opensearch-project/OpenSearch/blob/main/gradle/wrapper/gradle-wrapper.properties#L14)
```
* What went wrong:
A problem occurred evaluating root project 'bwc-test'.
> Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.
> Gradle 7.4.1+ is required
```
UTs
For more information on following Developer Certificate of Origin and signing off …

Bump version to 2.1.0.0

---

.github/workflows/ci.yml
build.gradle
bwc-test/build.gradle
bwc-test/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties

Reverts opensearch-project/security#1855
Seeing new build failures after this was merged, main CI failure: https://github.com/opensearch-project/security/runs/6615546106?check_suite_focus=true
```
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.apache.lucene:lucene-core:9.2.0-snapshot-ba8c3a8.
Searched in the following locations:
```

Revert "Bump version to 2.1.0.0"

---

src/main/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/PatchableResourceApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiTest.java

* Prevent the following 3 cases that cause recursive action groups and result in `StackOverflowException` when resolving the security configurations in runtime:
1. Prevent creating an action group with a role name.
2. Prevent creating an action group with itself as an allowed_actions.
3. Prevent patching an action group with itself as an allowed_actions.
https://github.com/opensearch-project/security/issues/1389
UTs …

Prevent recursive action groups

---

src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
src/test/java/org/opensearch/security/ssl/transport/DualModeSSLHandlerTests.java
src/test/java/org/opensearch/security/ssl/util/TLSUtilTests.java

Enhancement
security plugin should rely on `NettyAllocator.getAllocator()` to get `ByteBufAllocator` based on configured settings and parameters. Hard-coding `DEFAULT` `PooledByteBufAllocator` may cause unexpected allocator to be used.
6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and …

Delegate to NettyAllocator.getAllocator() for ByteBufAllocator instead of hard-coding PooledByteBufAllocator.

---

build.gradle
bwc-test/build.gradle
src/test/java/org/opensearch/security/dlic/rest/api/AbstractRestApiUnitTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165 …

Incremented version to 2.0.1

---

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
src/test/resources/internal_users.yml
src/test/resources/roles.yml
src/test/resources/roles_mapping.yml

Title
* Category : Bug Fix
* Resolves #1884 
A test is written to evaluate this

Cluster permissions evaluation logic will now include `index_template` type action

---

src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
src/main/java/org/opensearch/security/privileges/SnapshotRestoreEvaluator.java
src/main/java/org/opensearch/security/resolver/IndexResolverReplacer.java
src/test/java/org/opensearch/node/PluginAwareNode.java
src/test/java/org/opensearch/security/AdvancedSecurityMigrationTests.java
src/test/java/org/opensearch/security/EncryptionInTransitMigrationTests.java
src/test/java/org/opensearch/security/auditlog/integration/BasicAuditlogTest.java
src/test/java/org/opensearch/security/test/SingleClusterTest.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterConfiguration.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterInfo.java
tools/install_demo_configuration.sh

* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation) Refactoring
https://github.com/opensearch-project/security/issues/1664
ITs

Remove master keywords

---

securityconfig/roles.yml

Signed-off-by: Clay Downs <downsrob@amazon.com>
Adds new full access and read-only roles for the Snapshot Management plugin launching in 2.1.
Depending on the security plugin's branching strategy, this PR may need to be ported to the 2.x branch so it may be included in the 2.1 branch once that is cut. 

Adds default roles for Snapshot Management plugin

---

src/main/java/org/opensearch/security/dlic/rest/api/MigrateApiAction.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java

Fix build break from cluster manager changes

Fix build break from cluster manager changes

---

build.gradle

Update `org.apache.zookeeper:zookeeper` to `3.7.1`
Fixes CVE-2021-4104, CVE-2020-9488, and more from dependency on log4j-1.2.17.jar
* Resolves #1904
* Resolves #1905
* Resolves #1906
* Resolves #1907
* Resolves #1908
* Resolves #1909
* Resolves #1910

Update `org.apache.zookeeper:zookeeper` to `3.7.1`

---

src/test/java/org/opensearch/security/auditlog/compliance/ComplianceAuditlogTest.java
src/test/java/org/opensearch/security/auditlog/integration/TestAuditlogImpl.java

Recently with the build changes we have been seeing some increased test
failures.  Look at the biggest contributors its been the audit tests.
By switching to the established `doThenWaitForMessage` this should
improve test reliability considerably.

ComplianceAuditlogTest to use signal/wait

---

config/roles.yml

Signed-off-by: Clay Downs <downsrob@amazon.com>
(cherry picked from commit 7f5ca536da4599e4ad2d22ba05af0e33bf107fee)
Backport 7f5ca536da4599e4ad2d22ba05af0e33bf107fee from #1897 

[Backport 2.x] Adds default roles for Snapshot Management plugin (#1897)

---

.github/workflows/ci.yml
build.gradle
bwc-test/build.gradle
release-notes/opensearch-security.release-notes-2.1.0.0.md
src/main/java/com/amazon/dlic/auth/http/kerberos/HTTPSpnegoAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/saml/SamlFilesystemMetadataResolver.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
src/main/java/org/opensearch/security/ssl/util/SSLRequestHelper.java
src/main/java/org/opensearch/security/support/PemKeyReader.java

Adds release notes for 2.1.0 and revert #1890

---

scripts/build.sh

Adds build script for publishing plugin zips to maven repo.
* Required as part of 2.1 release 
* Resolves #1922

Adds build script for publishing plugin zip

---

build.gradle

First PR! 🥇 This upgrades Netty to address a CVE in 4.1.73. This resolves [1831](https://github.com/opensearch-project/security/issues/1831)
- [1831](https://github.com/opensearch-project/security/issues/1831)
This passes CI
For …

Upgrade netty to 4.1.77

---

build.gradle

After the upgrade of Netty from 4.1.73.Final -> 4.1.79.Final, we added another netty jar for `netty-transport-native-unix-common` in core's `module/transport-netty4` which is a new transitive dependency on `netty-handler`. 
We are experiencing build issues for 2.1.1 since other dependencies that depend on netty may resolve to another version of the jar. This PR adds a resolution strategy to determine which version of the jar to ultimately use.
Maintenance
Our build system needs to know how to resolve version conflicts in dependencies. …

Force netty-transport-native-unix-common version

---

build.gradle
bwc-test/build.gradle

Coming from https://github.com/opensearch-project/opensearch-build/issues/1818 post release activities.

Incremented version to 2.1.1.

---

pom.xml
release-notes/opendistro-for-elasticsearch-security.release-notes-1.13.1.1.md

Fixes a plugin installation issue with conflicting versions of jackson-core causing jar hell.
* 
Bug fix

Revert jackson-databind back to 2.11.2

---

.github/workflows/ci.yml
build.gradle
bwc-test/build.gradle

Increment version to 2.2.0.0

---

src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/test/java/org/opensearch/security/RolesInjectorIntegTest.java
src/test/java/org/opensearch/security/RolesValidationIntegTest.java
src/test/java/org/opensearch/security/TransportUserInjectorIntegTest.java
src/test/java/org/opensearch/security/auditlog/integration/TestAuditlogImpl.java
src/test/java/org/opensearch/security/ccstest/CrossClusterSearchTests.java
src/test/java/org/opensearch/security/dlic/dlsfls/CCReplicationTest.java
src/test/java/org/opensearch/security/dlic/rest/api/TenantInfoActionTest.java
src/test/java/org/opensearch/security/test/AbstractSecurityUnitTest.java

`waitForInit` was copied in few different tests classes. This PR abstracts it into `SingleClusterTests` and changes it from being recursive to iterative with a `maxRetries` of 3. (i.e. waiting a max of 1.5 seconds for security plugin initialization).
While abstracting the function I noticed that some of the tests its applied to correctly identify that the plugin is initialized, but swallow an error that the user making the health request does not have the correct permissions. This PR keeps the same behavior.
This also adds `waitForInit` inside of tests in `TenantInfoActionTest`
Maintenance, Test Reliability
Reduce code duplication and improve reliability
* …

Tenant info action test

---

src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java

The recent upgrade to Lucene 9.3.0 in core caused a build failure when an abstract method signature changed inside of `SortedSetDocValues`. See [here](https://build.ci.opensearch.org/job/distribution-build-opensearch/5849/execution/node/263/log/) for the build failure: 
Before Lucene 9.3.0: `public abstract long docValueCount();`
https://github.com/apache/lucene/blob/branch_9_2/lucene/core/src/java/org/apache/lucene/index/SortedSetDocValues.java#L51
Lucene 9.3.0: `public abstract long docValueCount();`
https://github.com/apache/lucene/blob/branch_9_3/lucene/core/src/java/org/apache/lucene/index/SortedSetDocValues.java#L61
Maintenance
By …

Fix gradle build issue after upgrade to Lucene 9.3.0

---

src/main/java/com/amazon/opendistroforelasticsearch/security/privileges/PrivilegesEvaluator.java
src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
src/test/java/com/amazon/opendistroforelasticsearch/security/IndexTemplateClusterPermissionsCheckTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
src/test/resources/internal_users.yml
src/test/resources/roles.yml
src/test/resources/roles_mapping.yml

Backport of #1885 to opendistro-1.10

backport cluster evaluation permissions #1885 to `opendistro-1.10`

---

src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/test/java/org/opensearch/security/dlic/dlsfls/FlsIndexingTests.java
src/test/java/org/opensearch/security/securityconf/impl/v7/IndexPatternTests.java
src/test/resources/dlsfls/internal_users.yml
src/test/resources/dlsfls/roles_fls_indexing.yml
src/test/resources/dlsfls/roles_mapping_fls_indexing.yml

Resolving index patterns into concrete indices had some confusing logic
make it hard to verify its behavior.  Updated this code to be easier
to read and added test cases to confirm resolution patterns.  Also added
unit tests to ensure line/by line coverage was correct.

Update indices resolution to be clearer

---

MAINTAINERS.md

Following the process in https://github.com/opensearch-project/.github/pull/59, I had nominated Craig Perkins (@cwperks) as a co-maintainer. The maintainers have voted and agreed to this nomination.
Craig has been participating in creating pull requests in both the back-end and front-end security repositories, answering questions and engaging with issue along with providing pull request feedback to keep standards high.

Adding @cwperks to Security maintainers.

---

build.gradle

Upgrade of jackson-databind to address CVE-2020-36518. The version now matches the version in core's `version.properties`. This should be backported to 1.3.
Maintenance

Upgrade jackson databind to 2.13.2.2 to match core's version.properties

---

config/roles.yml
src/main/resources/static_config/static_action_groups.yml
src/main/resources/static_config/static_roles.yml

This adds point in time permissions to default action groups.
Point in time has 3 apis:
1. Create PIT
2. List all PITs
3. Delete PIT
The permission model is similar to scroll which is a similar pagination feature
Cluster_composite_ops_ro:
Adding 'create pit' and 'list all pits' API permission to cluster composite ops read only action group.
Cluster_composite_ops:
Adding 'delete' API permission + above permissions to cluster composite ops action group.
Kibana_server:
Kibana server has access to all operations.
API changes links : 
https://github.com/opensearch-project/OpenSearch/pull/4064 - create pit and delete pit api
https://github.com/opensearch-project/OpenSearch/pull/4016 - list all
New …

Point in time security changes

---

src/main/java/org/opensearch/security/auditlog/sink/Log4JSink.java

Revert some changes introduced by https://github.com/opensearch-project/security/pull/1563 to correct work with log4j.
Signed-off-by: Andrey Pustovetov <andrey.pustovetov@gmail.com>
When I execute `GET` request to `.opendistro_security` index, I see three audit messages in the logs instead of one.
#1995
I manually checked the changes by doing `GET` request to the index and checking the logs.
- [ X] Commits are signed per the DCO using --signoff …

Triple audit logging fix (#1995)

---

src/main/resources/static_config/static_action_groups.yml
src/main/resources/static_config/static_roles.yml

Signed-off-by: Bharathwaj G <bharath78910@gmail.com>
The existing model requires indices read access to 'pit delete' and 'list all pits' to all users. 
So changing the action names to 'cluster:admin/<action_name>".
Now , we can't add these cluster permissions to 'cluster_composite_ops' or 'ops_ro' since user has access to 'my_index' role which has access to 'cluster_composite_ops' which will make all users to access list and delete pit.
So changing the approach to new one below.
Add point in time permissions to 'manage_point_in_time' which is part of default static action groups.
Point in time apis - and associated action names :
1. Create PIT -     - "indices:data/read/point_in_time/create" ( indices:data/read is chosen because this will make sure users have read permission to the passed …

Add security changes for point in time API

---

src/main/java/org/opensearch/security/tools/SecurityAdmin.java

Add `allowlist.yml` to where it is not being handled in securityadmin tool.

---

src/main/java/org/opensearch/security/configuration/DlsFilterLevelActionHandler.java

Fixed the inconsistent variable with name "`documentWhitelist`" and changed it into "`documentAllowlist`" with all its references in `DlsFilterLevelActionHandler.java`.
Resolve https://github.com/opensearch-project/security/issues/1665

Fix the inconsistent variable for DLS

---

src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/SecurityAdminTests.java
tools/SECURITY_ADMIN_TESTS.md

Security Admin tool contains a check to see if the security index is in the legacy v6 format. It works by checking to see if the security index has a property called `security`. If the `security` property exists it is in legacy format, otherwise its in the v7 format. Since OS 2.0.0 the check for the `security` property was removed which made the security admin tool always think the index was in the legacy format. The regression was introduced in this PR: https://github.com/opensearch-project/security/commit/4581a3d76ae3287c0821cd9beb3734b9fdcc57e8#diff-84a766aa2dc8279bc00a6447b9de6d8918a41f6522b150071f3f7d969b8d83c0L719
Bug Fix
* Why these …

Fix legacy check in SecurityAdmin

---

.github/workflows/ci.yml
build.gradle
bwc-test/build.gradle

Increments version to 2.4.0.0
Maintenance
https://github.com/opensearch-project/security/issues/2063

Increment version to 2.4.0.0

---

DEVELOPER_GUIDE.md
checkstyle/sun_checks.xml
src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/main/java/org/opensearch/security/dlic/rest/api/MigrateApiAction.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/RolesInjectorIntegTest.java
src/test/java/org/opensearch/security/RolesValidationIntegTest.java
src/test/java/org/opensearch/security/SlowIntegrationTests.java
src/test/java/org/opensearch/security/TransportUserInjectorIntegTest.java
src/test/java/org/opensearch/security/ccstest/CrossClusterSearchTests.java
src/test/java/org/opensearch/security/dlic/dlsfls/CCReplicationTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsFlsCrossClusterSearchTest.java
src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
src/test/java/org/opensearch/security/ssl/SSLTest.java
src/test/java/org/opensearch/security/test/AbstractSecurityUnitTest.java
src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java

Enforce usage of ClusterManager terminology in the codebase
Include mechanism to disable checkstyle rule
* Related to https://github.com/opensearch-project/security/issues/2050
Added Checkstyle mechanism to prevent usage of non-inclusive terminology

Switch to ClusterManager terminology

---

src/main/java/com/amazon/dlic/auth/ldap/util/ConfigConstants.java
src/main/java/com/amazon/dlic/auth/ldap2/LDAPConnectionFactoryFactory.java

Configure ldap connection pool pruning period and idle time through config.yml. For example, currently you can enable pooling and set the min and max size. ideally pool.idle_time and pool.pruning_period should also be configurable. Like this:
```
pool.enabled: true
pool.min_size: 0
pool.max_size: 5
pool.idle_time: 2
pool.pruning_period: 1
```
* Category (Enhancement)
To comply with strict ldap providers.
Defaults are the same, this just makes things configurable.
https://github.com/opensearch-project/security/issues/2090
No
Manual testing locally.
By submitting this pull request, I confirm that my contribution is …

Make ldap pool period and idle time configurable

---

src/main/java/com/amazon/dlic/auth/ldap/backend/LDAPAuthenticationBackend.java
src/main/java/com/amazon/dlic/auth/ldap/backend/LDAPAuthorizationBackend.java
src/main/java/com/amazon/dlic/auth/ldap/util/ConfigConstants.java
src/main/java/com/amazon/dlic/auth/ldap/util/LdapHelper.java
src/main/java/com/amazon/dlic/auth/ldap2/LDAPAuthenticationBackend2.java
src/main/java/com/amazon/dlic/auth/ldap2/LDAPAuthorizationBackend2.java
src/main/java/com/amazon/dlic/auth/ldap2/LDAPUserSearcher.java
src/test/java/com/amazon/dlic/auth/ldap/LdapBackendTest.java
src/test/java/com/amazon/dlic/auth/ldap/LdapBackendTestNewStyleConfig.java
src/test/java/com/amazon/dlic/auth/ldap2/LdapBackendTestNewStyleConfig2.java
src/test/java/com/amazon/dlic/auth/ldap2/LdapBackendTestOldStyleConfig2.java

Signed-off-by: Martin Kemp <martin_leon.kemp@mercedes-benz.com>
Allows specifying which attributes to request from the ldap server.
* Category: New feature
It can be a security risk to request more attributes than needed from an ldap server.
All attributes are requested.
https://github.com/opensearch-project/security/issues/2032
No
Manual testing with local ldap server. I made sure default behavior remains the same.
Updated unit tests.
This functionality is not tested directly with unit test, I can add one if needed. …

Allow custom return attributes

---

THIRD-PARTY.txt

Documentation change to reflect use of GA JNA in THIRD-PARTY.txt document. No behavioral changes just documentation correctness. 
- resolves #1387 

Correct Java Native Access Description in THIRD-PARTY.txt

---

.github/workflows/ci.yml
build.gradle

Backport 235d25672139c0663b422c3f7a2354e0250f23b0 from #1932
Note; had to remove BWC related changes since they were not included until 2.0 of this codebase

[Backport 1.3] Staging for version increment automation

---

build.gradle

The last version increment automation to run against 1.3 picked up all files of the project since it did not include an explicit `include` directive in the block. These lines are not needed in this branch since the only reference to the version is in `build.gradle`. 
See relevant conversation on this PR: https://github.com/opensearch-project/security/pull/2119
Bug fix …

Scope updateVersion to only build.gradle in 1.3

---

build.gradle

Update Kafka version to fix security vulnerability(#2095)
[[List any issues this PR will resolve]
](https://github.com/opensearch-project/security/issues/2095)

[Backport 1.3] Update Kafka Client to 3.0.2

---

build.gradle

[1.3] Updates jackson version to be in sync with core

---

src/main/java/org/opensearch/security/ssl/http/netty/SecuritySSLNettyHttpServerTransport.java

Remove HTTP_CHANNEL_KEY attributes since it is now available from the base class (see please https://github.com/opensearch-project/OpenSearch/pull/4638)
N/A
N/A

Remove HTTP_CHANNEL_KEY attributes since it is now available from the base class

---

MAINTAINERS.md

Following up from discussion https://github.com/orgs/opensearch-project/teams/security/discussions/4

Document standard practice for squashing pull requests

---

src/integrationTest/java/org/opensearch/security/SecurityRolesTests.java
src/integrationTest/java/org/opensearch/security/http/AuthInfo.java
src/integrationTest/java/org/opensearch/security/http/BasicAuthTests.java
src/integrationTest/java/org/opensearch/security/http/BasicAuthWithoutChallengeTests.java
src/integrationTest/java/org/opensearch/security/http/DisabledBasicAuthTests.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/integrationTest/resources/log4j2-test.properties

* Category (New feature [Tests])
The feature introduces integration tests related to basic authentication. The tests are implemented with the usage of a newly developed test framework.
Production code can be treated as a test for tests

Tests related basic authentication.

---

src/main/java/org/opensearch/security/action/configupdate/TransportConfigUpdateAction.java
src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
src/main/java/org/opensearch/security/configuration/ConfigurationLoaderSecurity7.java
src/main/java/org/opensearch/security/dlic/rest/api/MigrateApiAction.java

Removes all 7.x constants and logic that is no longer supported in 3.0. 
See: https://github.com/opensearch-project/OpenSearch/issues/2747
Related distribution build failure due to removal of these constants in core: 
- Resolves https://github.com/opensearch-project/security/issues/2149
Maintenance

Remove references to LegacyESVersion.V_7x constants

---

src/integrationTest/java/org/opensearch/security/SslOnlyTests.java
src/integrationTest/java/org/opensearch/security/TlsTests.java
src/integrationTest/java/org/opensearch/test/framework/cluster/CloseableHttpClientFactory.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/MinimumSecuritySettingsSupplierFactory.java
src/integrationTest/java/org/opensearch/test/framework/cluster/OpenSearchClientProvider.java
src/integrationTest/java/org/opensearch/test/framework/cluster/RestClientException.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/integrationTest/java/org/opensearch/test/framework/matcher/ExceptionHasCauseMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/ExceptionMatcherAssert.java
src/integrationTest/java/org/opensearch/test/framework/matcher/OpenSearchExceptionMatchers.java

Almost all integration tests use TLS so this feature is already pretty well tested. This PR introduced negative test cases related to TLS. Some extensions related to audit logs are required but can be introduced when another PR https://github.com/opensearch-project/security/pull/2153 is merged.
By submitting this pull request, I confirm that my …

TLS related tests.

---

.github/workflows/ci.yml
src/main/java/org/opensearch/security/auditlog/impl/AuditMessage.java
src/test/java/org/opensearch/security/auditlog/compliance/ComplianceAuditlogTest.java
src/test/java/org/opensearch/security/auditlog/integration/BasicAuditlogTest.java
src/test/java/org/opensearch/security/auditlog/integration/TestAuditlogImpl.java

Prevent message collection from being updated after message count has been received
Also added mechanism to detect if messages were missed so tests can be updated to appropriate counts
Saw a failure for PR https://github.com/opensearch-project/security/pull/2167 which had no code impact, saw the test `testSSLPlainText` was failing, looks like it was exiting early because the test was only looking for a smaller number of messages.
Tested locally, CI should confirm things are working as expected.  Also ran the bulk integration test workflow [1], 18 runs with no issues
[1] https://github.com/peternied/security/actions/runs/3291303445/jobs/5425278205
For more information on …

Prevent message collection from being updated after message count has been received

---

.github/workflows/ci.yml
src/main/java/org/opensearch/security/support/SecurityUtils.java
src/test/java/org/opensearch/security/IntegrationTests.java
src/test/java/org/opensearch/security/auth/limiting/HeapBasedRateTrackerTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java
src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
src/test/java/org/opensearch/security/support/SecurityUtilsTest.java

[Backport 2.x] Add CI for Windows and MacOS platforms
Due to the increase in the number of platforms, I've separated the newer integration tests into their own workflow.  Until retries have been enabled they will automatically pass - but still run and report logs.  As soon as we have full confidence we will allow them to start blocking pull requests from merging.  https://github.com/opensearch-project/security/issues/2184
Switch the gradle commands to be platform agnostic via the `gradle/gradle-build-action@v2`, dropping the 'clean' step to the build which allows us to reuse the gradle cache - if we see any problems pulling in more recent snapshots we can disable this setting quickly.
Found and fixed an issued with config value replacement via environment variables, long story short …

[Backport 2.x] Add CI for Windows and MacOS platforms (#2190)

---

.github/workflows/ci.yml
.github/workflows/code-hygiene.yml
build.gradle
spotbugs-include.xml
src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/org/opensearch/security/configuration/ConfigurationLoaderSecurity7.java
src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
src/main/java/org/opensearch/security/support/ConfigHelper.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/IntegrationTests.java

Adds spotbugs [1] to detect internalization before they are added to the codebase, also fixed several encoding bugs that impact windows users.
[1] https://spotbugs.readthedocs.io/en/stable/index.html
Closes https://github.com/opensearch-project/security/issues/2194
(cherry picked from commit a040b86a48eebcbe2791ba6371772fb9d386d6f2)

[Backport 2.x] Fix windows encoding issues (#2206)

---

.github/workflows/ci.yml
.github/workflows/code-hygiene.yml
build.gradle
spotbugs-include.xml
src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java
src/main/java/org/opensearch/security/auditlog/impl/AbstractAuditLog.java
src/main/java/org/opensearch/security/configuration/ConfigurationLoaderSecurity7.java
src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
src/main/java/org/opensearch/security/support/ConfigHelper.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/IntegrationTests.java

Adds spotbugs [1] to detect internalization before they are added to the codebase, also fixed several encoding bugs that impact windows users.
[1] https://spotbugs.readthedocs.io/en/stable/index.html
Closes https://github.com/opensearch-project/security/issues/2194
(cherry picked from commit a040b86a48eebcbe2791ba6371772fb9d386d6f2)

[Backport 2.4] Fix windows encoding issues (#2206)

---

config/roles.yml

* roles yml changes for security-analytics plugin
Signed-off-by: Raj Chakravarthi <raj@icedome.ca>
Signed-off-by: Raj Chakravarthi <49325334+raj-chak@users.noreply.github.com>
(cherry picked from commit 89a11c5a165d9fc1a5412a3c2369d3b27869b305) …

[Backport 2.4] roles yml changes for security-analytics plugin (#2192)

---

src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/test/java/org/opensearch/security/DataStreamIntegrationTests.java
src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java
src/test/java/org/opensearch/security/PitIntegrationTests.java
src/test/java/org/opensearch/security/securityconf/impl/v7/IndexPatternTests.java
src/test/resources/internal_users.yml
src/test/resources/roles.yml
src/test/resources/roles_mapping.yml

Backport of https://github.com/opensearch-project/security/commit/f7cc569c9d3fa5d5432c76c854eed280d45ce6f4 to 2.4

[Backport 2.4] Fix issues with datastream backing indexes 

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/2177/commits/8d2e309380e0b07fe3c803d1e19bb9aaef0ac321 to 1.3

[Backport] [1.3] Address CVE-2022-42889 by updating commons-text

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/2177/commits/8d2e309380e0b07fe3c803d1e19bb9aaef0ac321 to 1.x

[Backport] [1.x] Address CVE-2022-42889 by updating commons-text

---

src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
src/test/java/org/opensearch/security/DataStreamIntegrationTests.java
src/test/java/org/opensearch/security/IndexTemplateClusterPermissionsCheckTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/FlsIndexingTests.java
src/test/java/org/opensearch/security/securityconf/impl/v7/IndexPatternTests.java
src/test/resources/dlsfls/internal_users.yml
src/test/resources/dlsfls/roles_fls_indexing.yml
src/test/resources/dlsfls/roles_mapping_fls_indexing.yml
src/test/resources/internal_users.yml
src/test/resources/roles.yml
src/test/resources/roles_mapping.yml

Backport of https://github.com/opensearch-project/security/commit/f7cc569c9d3fa5d5432c76c854eed280d45ce6f4 to 2.x
Also includes changes from:
- https://github.com/opensearch-project/security/pull/2002
- https://github.com/opensearch-project/security/pull/1735 - Adds `appendUnresolved` from here

[Backport 1.3] Fix issues with datastream backing indexes

---

src/integrationTest/java/org/opensearch/security/CrossClusterSearchTests.java
src/integrationTest/java/org/opensearch/security/Song.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/certificate/TestCertificates.java
src/integrationTest/java/org/opensearch/test/framework/cluster/ClusterManager.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/NodeRole.java
src/integrationTest/java/org/opensearch/test/framework/cluster/SearchRequestFactory.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/integrationTest/java/org/opensearch/test/framework/matcher/GetResponseDocumentFieldValueMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/GetResponseDocumentIdMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/SearchHitDoesNotContainFieldMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/SearchHitsContainDocumentsInAnyOrderMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/SearchResponseMatchers.java

Integration tests related to the cross-cluster search feature created

Cross cluster search integration tests

---

src/integrationTest/java/org/opensearch/security/DoNotFailOnForbiddenTests.java
src/integrationTest/java/org/opensearch/security/SearchOperationTest.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/SearchRequestFactory.java
src/integrationTest/java/org/opensearch/test/framework/matcher/GetResponseContainOnlyDocumentIdMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/GetResponseMatchers.java

* Category (Integration test)
Integration tests with enabled configuration option "do not fail on forbidden" …

Test cases with flag do not fail on forbidden enabled.

---

.github/workflows/ci.yml
.github/workflows/plugin_install.yml
build.gradle
bwc-test/build.gradle

Bumps version to 2.5.0-SNAPSHOT
Created manually as auto-cut PR: https://github.com/opensearch-project/security/pull/2210 doesn't contain all changes.

Bump version 2.5.0

---

.github/actions/create-bwc-build/action.yaml
.github/actions/run-bwc-suite/action.yaml
.github/workflows/bwc-tests.yml
.github/workflows/ci.yml
bwc-test/build.gradle
bwc-test/src/test/java/SecurityBackwardsCompatibilityIT.java

With an issue reported indicating that there are serialization issue between 1.3 and 2.X, making sure that we can reproduce the errors.  This new workflow(s) will make sure that we aren't breaking BWC with changes we are adding to 2.X and will give us the flexibility to test certain migration workflows.
Fixing an issue where the BWC tests were not actually building or executing causing the clusters to spin up and then immediately spin down.  We will need to invest more energy into running multiple kinds of  security plugin specific scenarios through the test system.
- Resolves https://github.com/opensearch-project/security/issues/2250
- Resolves https://github.com/opensearch-project/security/issues/2232
- Resolves https://github.com/opensearch-project/security/issues/1474
- Related …

Generalize Backwards Compatibility tests so we can test from any version to any version

---

src/integrationTest/java/org/opensearch/security/IpBruteForceAttacksPreventionTests.java
src/integrationTest/java/org/opensearch/security/TlsTests.java
src/integrationTest/java/org/opensearch/security/UserBruteForceAttacksPreventionTests.java
src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationTests.java
src/integrationTest/java/org/opensearch/test/framework/AuthFailureListeners.java
src/integrationTest/java/org/opensearch/test/framework/RateLimiting.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/cluster/CloseableHttpClientFactory.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalAddressRoutePlanner.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/OpenSearchClientProvider.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClientConfiguration.java
src/integrationTest/java/org/opensearch/test/framework/log/LogsRule.java
src/integrationTest/resources/log4j2-test.properties

Test related to brute-force attack prevention and a minor correction for TlsTests. …

Tests related to brute force attack prevention.

---

src/integrationTest/java/org/opensearch/security/http/CertificateAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/RolesMapping.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/certificate/CertificateData.java
src/integrationTest/java/org/opensearch/test/framework/certificate/TestCertificates.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/OpenSearchClientProvider.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java

Integration tests related to user authentication with X.509 certificates.

Test related to authentication with x.509 certificates.

---

README.md

Adds a new section in the README on System Index protection under the section for onboarding new APIs. When new plugins are added that create system indices, the `install_demo_configuration` scripts need to be updated to register the new system indices.
Documentation
Related to: https://github.com/opensearch-project/security/issues/2265
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#develope …

Add sub-section on System Index protection under Onboarding new APIs to README

---

build.gradle
src/integrationTest/java/org/opensearch/security/http/DirectoryInformationTrees.java
src/integrationTest/java/org/opensearch/security/http/LdapAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/http/LdapStartTlsAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/http/LdapTlsAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/http/UntrustedLdapServerCertificateTest.java
src/integrationTest/java/org/opensearch/test/framework/AuthorizationBackend.java
src/integrationTest/java/org/opensearch/test/framework/AuthzDomain.java
src/integrationTest/java/org/opensearch/test/framework/LdapAuthenticationConfigBuilder.java
src/integrationTest/java/org/opensearch/test/framework/LdapAuthorizationConfigBuilder.java
src/integrationTest/java/org/opensearch/test/framework/RolesMapping.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/certificate/TestCertificates.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/OpenSearchClientProvider.java
src/integrationTest/java/org/opensearch/test/framework/ldap/EmbeddedLDAPServer.java
src/integrationTest/java/org/opensearch/test/framework/ldap/LdapServer.java
src/integrationTest/java/org/opensearch/test/framework/ldap/LdifBuilder.java
src/integrationTest/java/org/opensearch/test/framework/ldap/LdifData.java
src/integrationTest/java/org/opensearch/test/framework/ldap/Record.java
src/integrationTest/java/org/opensearch/test/framework/ldap/RecordBuilder.java
src/integrationTest/java/org/opensearch/test/framework/log/LogCapturingAppender.java
src/integrationTest/java/org/opensearch/test/framework/log/LogMessage.java
src/integrationTest/java/org/opensearch/test/framework/log/LogsRule.java
src/integrationTest/resources/log4j2-test.properties

Integration tests related to LDAP authentication.

Ldap authentication

---

src/integrationTest/java/org/opensearch/security/Song.java
src/integrationTest/java/org/opensearch/security/http/CommonProxyAuthenticationTests.java
src/integrationTest/java/org/opensearch/security/http/ExtendedProxyAuthenticationTest.java
src/integrationTest/java/org/opensearch/security/http/ProxyAuthenticationTest.java
src/integrationTest/java/org/opensearch/test/framework/RolesMapping.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/XffConfig.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java

Integration tests related to proxy authentication added
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTI …

Proxy authentication tests

---

src/integrationTest/java/org/opensearch/security/SearchOperationTest.java
src/integrationTest/java/org/opensearch/test/framework/matcher/AliasExistsMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/ClusterMatchers.java

Two additional test cases associated with
1. index deletion with IndicesAliasesRequest
2. Alias creation with CreateIndexRequest …

Additional two integration tests IndicesAliasesRequest,CreateIndexRequest

---

build.gradle

[CVE Fix] Fixes CVE-2022-42920 by forcing bcel version to resovle to 6.6

---

build.gradle

Increment the version of jackson to match with core
Maintenance
* Related https://github.com/opensearch-project/OpenSearch/pull/5346

1.3 branch version increment of for jackson to match with core

---

.github/actions/start-opensearch-with-one-plugin/action.yml

There was a release to download-file that cleans up the amount of log output during the download and also added logging if there was an issue during the installation. 
I'll do a comparison between the plugin-install workflows previous number of lines of output and the new number with this change
| Workflow | Link | Lines | Delta|
|-----------|------|--------|------|
| Plugin install ubuntu-latest |  [link](https://github.com/opensearch-project/security/actions/runs/3604084983/jobs/6073047571) |4977| - |
| Plugin install ubuntu-latest |  [link](https://github.com/opensearch-project/security/actions/runs/3605488561/jobs/6075937034) | 407 |  12.2x reduction |
```
Length: 234472457 (224M) [application/x-gzip]
Saving to: ‘opensearch-min-3.0.0-SNAPSHOT-linux-x64-latest.tar.gz’
0K .......... …
```

Cleanup download file output and improved error logging

---

.github/actions/start-opensearch-with-one-plugin/action.yml
.github/workflows/plugin_install.yml

Backport the plugin install workflow and github action to 1.3. The backport got missed when everything else was merged into one branch. 
Backports merged PR #2271 to 1.3 branch. 
Tested for functionality on Java and Windows with JDK 8, 11, 14. It is worth noting that the plugin install workflow seems slightly flaky on jdk 11 alone. I encountered this issue first when I was originally merging PR #2271. For whatever reason the setup.bat file does not always echo the  'yes' response into the install script as expected. It passes over 50% of the time though. 
For more information on following Developer Certificate of Origin …

[Backport 1.3] Add plugin install workflow and action 

---

config/roles.yml
tools/install_demo_configuration.bat
tools/install_demo_configuration.sh

Adds 2 k-NN related roles to the plugin: read only and fully access.
Adds k-NN system index to demo scripts as well.
#2265 
Pending

Integrate k-NN functionality with security plugin

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/2275 to 2.x

[Backport 2.x] Fixes CVE-2022-42920 by forcing bcel version to resovle to 6.6

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/2275 to 2.4

[Backport 2.4] Fixes CVE-2022-42920 by forcing bcel version to resovle to 6.6

---

.github/actions/start-opensearch-with-one-plugin/action.yml
.github/workflows/plugin_install.yml

Backport the plugin install workflow and github action to 2.x. 
Backports merged PR #2271 to 2.x branch. 
Tested for functionality on Java and Windows with JDK 11 and 17.

[Backport 2.x] Backports plugin install workflow and action to 2.x

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/2275 to 1.3

[Backport 1.3] Fixes CVE-2022-42920 by forcing bcel version to resovle to 6.6

---

CONTRIBUTING.md
TRIAGING.md

Split the Contributing Document to allow for further fine-tuning down the road. Created a separate Triaging document with previous info and also added a basic outline for the meeting structure. 

[Feature] Agenda

---

.github/actions/start-opensearch-with-one-plugin/action.yml
.github/workflows/bwc-tests.yml
.github/workflows/plugin_install.yml
tools/install_demo_configuration.bat
tools/install_demo_configuration.sh

This fix resolves the issue with the Windows install. The -y flag in the demo scripts was not actually setting the config settings correctly. 
Resolves issue #2305 
I ran the full workflow suite and everything worked. 

Windows Install Action Fix

---

.github/actions/start-opensearch-with-one-plugin/action.yml
.github/workflows/plugin_install.yml
tools/install_demo_configuration.bat
tools/install_demo_configuration.sh

Backports correction for install demo config.
Backports: PR #2308 

[2.x Backport] Install Demo Config Fix

---

.github/workflows/ci.yml

The upgrade check tests were a great idea that ultimately exposes some problems with build compabtility between versions.  While we could upgrade the test to re-install gradle after the upgrade since we are effectively 'down grading' this is a really complex way to confirm that code we don't often mess with works.
- Resolves https://github.com/opensearch-project/security/issues/2314 

Remove updateVersion tests that keeps breaking on env issues

---

src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

Signed-off-by: Rutuja Surve [rutuja@amazon.com](mailto:rutuja@amazon.com)
Signed-off-by: Rutuja Surve [110013621+rutuja-amazon@users.noreply.github.com](mailto:110013621+rutuja-amazon@users.noreply.github.com) 
Signed-off-by: Peter Nied [petern@amazon.com](mailto:petern@amazon.com) 
Co-authored-by: Peter Nied [petern@amazon.com](mailto:petern@amazon.com) (cherry picked from commit [efbc48b](https://github.com/opensearch-project/security/commit/efbc48b405ff6ff372c4821aa15c53fc50a409a3)) …

[Backport 1.2] Username validation for special characters (#2277)

---

src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

Signed-off-by: Rutuja Surve [rutuja@amazon.com](mailto:rutuja@amazon.com)
Signed-off-by: Rutuja Surve [110013621+rutuja-amazon@users.noreply.github.com](mailto:110013621+rutuja-amazon@users.noreply.github.com) 
Signed-off-by: Peter Nied [petern@amazon.com](mailto:petern@amazon.com) 
Co-authored-by: Peter Nied [petern@amazon.com](mailto:petern@amazon.com) (cherry picked from commit [efbc48b](https://github.com/opensearch-project/security/commit/efbc48b405ff6ff372c4821aa15c53fc50a409a3))

[Backport 2.3] Username validation for special characters (#2277)

---

.github/actions/start-opensearch-with-one-plugin/action.yml
.github/workflows/plugin_install.yml
tools/install_demo_configuration.bat
tools/install_demo_configuration.sh

Backports PR #2308 to 1.3 
The -y flag in the demo scripts was not actually setting the config settings correctly.

[Backport 1.3] Backport Demo Config Script -y Function

---

src/integrationTest/java/org/opensearch/security/ConfigurationFiles.java
src/integrationTest/java/org/opensearch/security/DefaultConfigurationTests.java
src/integrationTest/java/org/opensearch/security/IpBruteForceAttacksPreventionTests.java
src/integrationTest/java/org/opensearch/security/SecurityAdminLauncher.java
src/integrationTest/java/org/opensearch/security/SecurityConfigurationTests.java
src/integrationTest/java/org/opensearch/security/UserBruteForceAttacksPreventionTests.java
src/integrationTest/java/org/opensearch/test/framework/TestSecurityConfig.java
src/integrationTest/java/org/opensearch/test/framework/certificate/TestCertificates.java
src/integrationTest/java/org/opensearch/test/framework/cluster/LocalCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/MinimumSecuritySettingsSupplierFactory.java
src/integrationTest/resources/action_groups.yml
src/integrationTest/resources/allowlist.yml
src/integrationTest/resources/config.yml
src/integrationTest/resources/internal_users.yml
src/integrationTest/resources/nodes_dn.yml
src/integrationTest/resources/roles.yml
src/integrationTest/resources/roles_mapping.yml
src/integrationTest/resources/security_tenants.yml
src/integrationTest/resources/tenants.yml
src/integrationTest/resources/whitelist.yml

Integration tests which verify security plugin behaviour after the configuration update …

Test related to security plugin configuration updates.

---

.github/workflows/ci.yml
build.gradle

jackson-databind and jackson-annotations were added as api dependencies in `server` of opensearch core. The security plugin now gets these dependencies transitively and does not need direct dependencies on the jars.
PR in core where the dependencies are added: https://github.com/opensearch-project/OpenSearch/pull/5366
Maintenance 
https://github.com/opensearch-project/security/issues/2324 …

Remove jackson-databind and jackson-annotations dependency now coming from core

---

MAINTAINERS.md

Add @RyanL1997 to maintainers
Note this was an oversight as it should have happened at the same time as https://github.com/opensearch-project/security-dashboards-plugin/pull/1130
Signed-off-by: Peter Nied <peternied@hotmail.com>

Add @RyanL1997 to maintainers

---

README.md
build.gradle

Updates the cxf-core dependency tree to use cxf-core version 3.5.5. 

[1.x] Fixes CVE-2022-46363

---

src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

Signed-off-by: Rutuja Surve <rutuja@amazon.com>
Signed-off-by: Rutuja Surve <110013621+rutuja-amazon@users.noreply.github.com>
Co-authored-by: Peter Nied <petern@amazon.com>
(cherry picked from commit efbc48b405ff6ff372c4821aa15c53fc50a409a3)

[Backport 1.3] Username validation for special characters (#2277)

---

build.gradle
src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
src/test/java/org/opensearch/security/ssl/SSLTest.java

OpenSSLTest should be using the OpenSSL Provider. There are few issues with `netty-tcnative` and OpenSSL:
- it uses OpenSSL 1.0 and needs `compat-openssl10` 
- https://github.com/netty/netty-tcnative/issues/746
- https://github.com/netty/netty-tcnative/issues/742
- https://github.com/netty/netty-tcnative/issues/703
Closes https://github.com/opensearch-project/security/issues/2208
For more information on following Developer Certificate of Origin and signing off …

OpenSSLTest is not using the OpenSSL Provider

---

src/main/java/org/opensearch/security/securityconf/DynamicConfigFactory.java

While going through the code to understand how the security plugin persists data in a system index, I came across a duplicate block of code where the constructor of DynamicConfigFactory is performing `loadStaticConfig` twice. This PR removes the duplicate block so that it only loads static config once from `static_roles.yml`, `static_action_groups.yml` and `static_tenants.yml`
Maintenance …

Remove duplicate block of code in DynamicConfigFactory

---

src/main/java/org/opensearch/security/auth/BackendRegistry.java

Signed-off-by: Abhi Kalra <abhivka@amazon.com>
* Category 
Bug Fix
Changing logging type to give warning for basic auth with no creds.
When using basic auth without credentials, users just get a message telling "Unauthorized" which is not very descriptive. As an admin, I don't have any visibility into why my users are not able to login without enabling this log which is currently at trace level. Hence, changing log level to warn.
https://github.com/opensearch-project/security/issues/2346
We want to backport it to latest OS versions.
Signed-off-by: Abhi Kalra <abhivka@amazon.com> …

Changing logging type to give warning for basic auth with no creds

---

.github/actions/create-bwc-build/action.yaml
.github/workflows/ci.yml
src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java

Uses the changes from the PR's branch when running `backwards-compatibility` check during CI. The current `backwards-compatibility` check checks out branches from the main repo and ignores changes introduced in a PR.
Bug fix
https://github.com/opensearch-project/security/issues/2365

Incorporate changes introduced in PR branch when running BWC check for CI

---

src/test/java/org/opensearch/security/InitializationIntegrationTests.java
src/test/java/org/opensearch/security/auditlog/integration/BasicAuditlogTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsFlsCrossClusterSearchTest.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java
src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java
src/test/java/org/opensearch/security/test/AbstractSecurityUnitTest.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java

Add functional test cases for HTTP/2
Closes https://github.com/opensearch-project/security/issues/2125
Added new test cases

[HTTP/2] Functional Test cases

---

src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

Signed-off-by: Rutuja Surve <rutuja@amazon.com>
Signed-off-by: Rutuja Surve <110013621+rutuja-amazon@users.noreply.github.com>
Co-authored-by: Peter Nied <petern@amazon.com>
(cherry picked from commit efbc48b405ff6ff372c4821aa15c53fc50a409a3)

[Backport 1.x] Username validation for special characters (#2277)

---

src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/test/java/org/opensearch/security/dlic/dlsfls/FlsKeywordTests.java
src/test/resources/dlsfls/roles_keyword.yml
src/test/resources/dlsfls/roles_mappings_keyword.yml

When excluding fields also exclude the term + `.keyword`

When excluding fields also exclude the term + `.keyword`

---

tools/audit_config_migrater.bat
tools/hash.bat
tools/securityadmin.bat

Update tool scripts to run in windows.  They were missed during support for Windows, will backport this to 1.3.X as well
- Resolves #2368
Manually tested on my windows machine
```
...\opensearch-2.4.1\plugins\opensearch-security\tools>hash.bat test
OPENSEARCH_JAVA_HOME or JAVA_HOME must be defined
```
```
.\opensearch-2.4.1\plugins\opensearch-security\tools>set OPENSEARCH_JAVA_HOME="...\opensearch-2.4.1-windows-x64\opensearch-2.4.1\jdk"
.\opensearch-2.4.1-windows-x64\opensearch-2.4.1\plugins\opensearch-security\tools>hash.bat test
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
[Password:]
$2y$12$KjgWovKVps84wOMlwOQtu.b8TRL9uFrqv5eZ3/N4RgcHnOImln5aG
```
For more …

Update tool scripts to run in windows

---

src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java

Remove trimming of whitespace when extracting SAML backend roles
New unit test has been added to verify the functionality

Remove trimming of whitespace when extracting SAML backend roles

---

build.gradle

Add script for workflow version increment
* Category (Enhancement)
* Relate: #2352 
* Relate: #2372 
2.x, 2.4

Add script for workflow version increment

---

build.gradle

Reverts https://github.com/opensearch-project/security/pull/2325 and adds jackson-annotations and jackson-databind back as direct dependencies.
Maintenance
https://github.com/opensearch-project/OpenSearch/issues/5504

Re-add jackson-annotations and jackson-databind

---

release-notes/opensearch-security.release-notes-2.5.0.0.md

Add release note for 2.5.0
* Category (Maintenance)
* Relate https://github.com/opensearch-project/security/issues/2373
2.x, 2.5

Add release note for 2.5.0

---

.github/workflows/plugin_install.yml
tools/install_demo_configuration.bat
tools/install_demo_configuration.sh

Reverts https://github.com/opensearch-project/security/pull/2308 and uses `-i -c` as arguments to the windows program to make it equivalent to `-y`
Maintenance

Revert "Windows Install Action Fix"

---

.github/workflows/plugin_install.yml
tools/install_demo_configuration.bat
tools/install_demo_configuration.sh

Backport https://github.com/opensearch-project/security/pull/2401 to 1.3

[Backport 1.3] Revert "Windows Install Action Fix"

---

MAINTAINERS.md

Stephen Crawford (@scrawfor99) has been an avid contributor to Security plugin & Security Dashboard plugin since October '22, clocking in with 137 contributions in the OpenSearch project.  He has earned his place as a maintainer with the following valuable contributions.
- Created [41](https://github.com/search?q=repo%3Aopensearch-project%2Fsecurity+repo%3Aopensearch-project%2Fsecurity-dashboards-plugin+author%3Ascrawfor99&type=pullrequests&ref=advsearch) pull requests.
- Involved in [55 & 31](https://github.com/search?q=repo%3Aopensearch-project%2Fsecurity+repo%3Aopensearch-project%2Fsecurity-dashboards-plugin+-author%3Ascrawfor99+involves%3Ascrawfor99+&type=pullrequests&ref=advsearch) issues and pull requests respectively.
- Mentioned in …

Adding `@scrawfor99` to the maintainers

---

src/integrationTest/java/org/opensearch/test/framework/cluster/LocalOpenSearchCluster.java
src/integrationTest/java/org/opensearch/test/framework/cluster/TestRestClient.java
src/main/java/org/opensearch/security/action/whoami/WhoAmIResponse.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/ConfigTests.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java

Fixes broken CI
* Category: Maintenance
* Why these changes are required? To get CI working again
- #2417 
- #2420
Manual testing

Changes affected String.toString() method calls to reflect correct signature

---

build.gradle

This bumps bouncycastle to match core's version.properties (https://github.com/opensearch-project/OpenSearch/blob/1.3/buildSrc/version.properties#L31). 
I will file a separate issue to create a mechanism for tracking when 1.3 version of bouncycastle is mismatched from core.
Maintenance
Should resolve https://github.com/opensearch-project/security/issues/2419
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CO …

[1.3] Bump org.bouncycastle:bcprov-jdk15on from 1.67 to 1.70

---

release-notes/opensearch-security.release-notes-1.3.8.0.md

Add release note for 1.3.8
* Maintenance
* Relate: https://github.com/opensearch-project/opensearch-build/issues/3012

[Backport 1.3] Add release note for 1.3.8

---

src/test/java/org/opensearch/security/setting/DeprecatedSettingsTest.java

We've seen failures with this mock test cases seeing different parameters.  This failure was completely blocking https://github.com/opensearch-project/security/pull/2427
I don't see an obvious change that could cause this, it could be changes in compiler settings of how the 'params' argument was treated differently, or a shift in Mockito version from core.
Reproduced locally, and then with this fix it has been resolved

Fix testCheckForDeprecatedSettingFoundLegacy was broken with changes in calling patterns

---

src/main/java/org/opensearch/security/configuration/DlsFlsFilterLeafReader.java
src/test/java/org/opensearch/security/setting/DeprecatedSettingsTest.java

Backport https://github.com/opensearch-project/security/commit/7a6909f6912e888caa500a281bd7fe5d7e6c1ecf from https://github.com/opensearch-project/security/pull/2362 - Updates DlsFlsFilterLeafReader to use new Lucene document() instead of visitDocument()
Backport https://github.com/opensearch-project/security/commit/710baecff933f5e6bb936abbfa758daf7f26e7e2 from https://github.com/opensearch-project/security/pull/2428 - Fix testCheckForDeprecatedSettingFoundLegacy was broken with changes in calling patterns
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/mai …

[Backport 2.x] Updates DlsFlsFilterLeafReader with Lucene change and fix broken deprecation logger test

---

.github/workflows/maven-publish.yml

Maven doesn't have a way to filter published artifacts by platform build for and since our plugin zip works in both platforms switching to a single publishing leg.

Remove unneeded jdk and platform from publishing workflow

---

release-notes/opensearch-security.release-notes-1.3.8.0.md

Add release note for 1.3.8
* Maintenance
* Relate: https://github.com/opensearch-project/opensearch-build/issues/3012

Add release note for 1.3.8

---

src/main/java/org/opensearch/security/action/whoami/WhoAmIResponse.java
src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/configuration/DlsFlsValveImpl.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/test/java/org/opensearch/security/ConfigTests.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java

Manual backport of f808b2ae207442b5f18dc47bfb67c5a71e75e8b8 from https://github.com/opensearch-project/security/pull/2418

[Backport 2.x] Updates toString calls affected by change in method signature

---

release-notes/opensearch-security.release-notes-2.6.0.0.md

Manual backport of https://github.com/opensearch-project/security/pull/2456

[Backport 2.x] Add release notes for 2.6.0.0

---

.github/workflows/ci.yml

Remove MacOS platform from CI checks, they take a long time and have been more unreliable than other platforms.  
- Resolves https://github.com/opensearch-project/security/issues/2467

Remove MacOS platform from CI checks

---

.github/CODEOWNERS

Fix the format of the codeowners file
All maintainers are considered code-owners instead of only @scrawfor99 :D

Fix the format of the codeowners file

---

src/main/java/org/opensearch/security/auth/internal/InternalAuthenticationBackend.java
src/test/java/org/opensearch/security/auth/InternalAuthBackendTests.java

Manually backport reponse time flattening for 2.6 release 
Includes InternalAuthBackendTests.java test file. 

[Backport 2.6] Flatten response times

---

.github/workflows/maven-publish.yml

Use correct format for push trigger
Builds were not being automatically published, after reviewing the documentation
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs branches is an object, not an array.

Use correct format for push trigger

---

src/main/java/org/opensearch/security/auth/internal/InternalAuthenticationBackend.java
src/test/java/org/opensearch/security/auth/InternalAuthBackendTests.java

Flattens response times in InternalAuthBackend 
Adds a new set of tests in InternalAuthBackendTests.java

Flatten response times

---

src/main/java/org/opensearch/security/auth/BackendRegistry.java
src/test/java/org/opensearch/security/multitenancy/test/MultitenancyTests.java
src/test/resources/multitenancy/config_anonymous.yml
src/test/resources/multitenancy/roles.yml
src/test/resources/multitenancy/roles_mapping.yml
src/test/resources/multitenancy/roles_tenants.yml

* Category Bug fix
Multitenancy for the anonymous user is not supported. It's implied in Opensearch-Dashboards that this isn't the expected behaviour. From the UI, anonymous users can switch between tenants but in the end all the operations are run on the
Global tenant (even when the UI says the user is in a different tenant).
The current version of the plugin supports multitenancy for all the users but not for the anonymous user.
The header 'securitytenant' is ignored when this user is authorized. Therefore, all the operations run
with it, use the default tenant - normally the 'Global' tenant -.
This patch fixes this issue assigning the selected tenant - defined by the …

Support multitenancy for the anonymous user

---

build.gradle

[Backport 1.3] fix kafka CVE-2023-25194, update kafka client to 3.4.0 (#2484)

---

build.gradle

[Backport 1.x] fix kafka CVE-2023-25194, update kafka client to 3.4.0 (#2484)

---

build.gradle

[Backport 2.x] fix kafka CVE-2023-25194, update kafka client to 3.4.0 (#2484)

---

.github/CODEOWNERS

Backport https://github.com/opensearch-project/security/commit/8c506fa675036851d360563bec56e144597ebf67 from https://github.com/opensearch-project/security/pull/2469

[Backport 1.3] Fix the format of the codeowners file

---

src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java

Fix a test issue  in HTTPJwtKeyByOpenIdConnectAuthenticatorTest  discovered in PR #2482 ,
* Category Test fix
Fix the  "testExp" test
The "testExp" test was missing the "Bearer" auth-scheme in the request, so the token expiration test was not actually being executed
Thi is a follow-up PR no Issue has been opened
Is this a backport? 
No
unit testing
- [  ] New functionality includes testing
- [  ] New functionality has been documented …

Fix a test issue discovered in PR #2482

---

src/main/resources/static_config/static_roles.yml

* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation) Enhancement
**This change is required by https://github.com/opensearch-project/security-dashboards-plugin/pull/1359. So this PR needs to be merged before https://github.com/opensearch-project/security-dashboards-plugin/pull/1359**
https://github.com/opensearch-project/security-dashboards-plugin/issues/1222
No
MT …

Adding index template permissions to kibana_server role

---

src/main/java/org/opensearch/security/configuration/ConfigurationRepository.java
src/main/java/org/opensearch/security/support/ConfigHelper.java

If `plugins.security.allow_default_init_securityindex` set to `true`, the cluster should initialize the configuration index. Since reading of configuration files was done without `AccessController` in the diff thread on `JDK17` (not sure about `JDK11`) it fails randomly for the different file (for at least 3 nodes cluster) as result the configuration could be lost partially and the security configuration could be in the inconsistent state.
Beside that a check for the cluster global state lock was added, so index will be created after lead elation has been finished.  The main idea is do not bother cluster and reduce global state block exceptions in the log file. 
For more …

Fix lost privileges during auto initializing of the index

---

src/main/java/org/opensearch/security/privileges/SecurityIndexAccessEvaluator.java
src/test/java/org/opensearch/security/privileges/SecurityIndexAccessEvaluatorTest.java

There was a bug in the error message when interacting with a system index causing it to always return the security index instead of the index(es) that were blocked.
Also includes unit test cases to verify the SecurityIndexAccessEvaluator
- Resolves https://github.com/opensearch-project/security/issues/2483

Fix error message when system index is blocked

---

build.gradle
src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
src/test/java/org/opensearch/security/ssl/SSLTest.java

[Backport] [2.x] OpenSSLTest is not using the OpenSSL Provider (#2301)

---

src/test/java/org/opensearch/security/SnapshotRestoreTests.java

Manual backport of https://github.com/opensearch-project/security/pull/2384 to 2.x.

[Backport 2.x] Add a test in order to catch incorrect handling of index parsing during Snapshot Restoration

---

tools/install_demo_configuration.sh

Adds commands to change the permissions of the newly created demo certificates in the install_demo_configuration.sh script.
This PR only changes the certificate permissions, the other issue with the `config/` folder permissions should be addressed in opensearch-build:
```
... Directory /home/ec2-user/opensearch-1.1.0/config has insecure file permissions (should be 0700)
```
Bug fix
- https://github.com/opensearch-project/opensearch-build/issues/3262
- https://github.com/opensearch-project/security/issues/1465
Tested a local distribution before and after the change and verified that the `...has insecure file permissions (should be 0600)` errors were not logged.
By submitting this pull request, …

Add chmod 0600 to install_demo_configuration bash script

---

build.gradle

Backport of https://github.com/opensearch-project/security/pull/2564 to `2.x`

[Backport] [2.x] [BUG] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder" (#2564)

---

pom.xml

When the OpenSearch project was first starting out the unified build system was new. Mistakes were made and the snapshot artifacts for OpenSearch-1.1.0 were deleted.
Luckily the release artifacts are still around, so by switching from snapshot to the release artifacts builds can function again.
See missing snapshot artifacts: https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/plugin/transport-netty4-client/
See release artifacts: https://repo1.maven.org/maven2/org/opensearch/plugin/transport-netty4-client/
- Related https://github.com/opensearch-project/security/pull/2331
It build the package locally
For more information on following Developer …

Fix broken maven build v1.1.0

---

src/main/java/org/opensearch/security/dlic/rest/api/InternalUsersApiAction.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

Signed-off-by: Rutuja Surve [rutuja@amazon.com](mailto:rutuja@amazon.com)
Signed-off-by: Rutuja Surve [110013621+rutuja-amazon@users.noreply.github.com](mailto:110013621+rutuja-amazon@users.noreply.github.com) 
Signed-off-by: Peter Nied [petern@amazon.com](mailto:petern@amazon.com) 
Co-authored-by: Peter Nied [petern@amazon.com](mailto:petern@amazon.com) (cherry picked from commit [efbc48b](https://github.com/opensearch-project/security/commit/efbc48b405ff6ff372c4821aa15c53fc50a409a3)) …

[Backport 1.1] Username validation for special characters (#2277) 

---

DEVELOPER_GUIDE.md

* Category
Documentation
These changes keep the documentation up-to-date according to the changes which were introduced in earlier contributions. 
Before the changes, when clicking on the "here" link in the "Native platforms" section of [DEVELOPER_GUIDE.md](https://github.com/opensearch-project/security/blob/main/DEVELOPER_GUIDE.md) the user was redirected to a page with 404 error and a message `The 'opensearch-project/security' repository doesn't contain the 'plugin-descriptor.properties' path in 'main'.`
After the changes, the "Worth noting" paragraph was put after building code snippet, so that the user will be able to access the `plugin-descriptor.properties` file, which is …

Remove broken link from DEVELOPER_GUIDE.md

---

.github/CODEOWNERS
MAINTAINERS.md

I nominated Andriy Redko (@reta) to be a co-maintainer for Security through our [nomination process](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#nomination). The maintainers have agreed, and Andriy has kindly accepted.
Andriy’s involvement has taken many shapes, here are some highlights:
* Code
* Features work such as support for HTTP/2
* Manual Backports for CVEs
* Build infrastructure such as Gradle changes
* Test infrastructure such as fixes to OpenSSLTests
* Particpation in issues
* Adding contributors
* @reta
* Active participate in triage meeting / process
* Passion for quality
Thank you
For more information on following Developer Certificate …

Add Andriy Redko as a co-maintainer

---

build.gradle

Bumps JSON-Smart to version 2.4.10 to address CVE-2023-1370. 
Bumps Spring-core to version 5.3.26 to address CVE-2023-20861. 

Remediate CVE-2023-1370 and CVE-2023-20861 via version bumps

---

src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java
src/test/java/org/opensearch/security/dlic/dlsfls/DlsTest.java

This PR takes the Dls tests that were part of FlsDlsAndFieldMaskingTest.java and copies them out into a new test file DlsTest.java. The purpose of this change is to make it easier to verify that Dls works as expected. Previously, it was not abundantly clear what types of tests were being used to check Dls functionality. This new file has only Dls tests and also expands a fair deal on the types of checks it does.  

Expand Dls Tests for easier verification of functionality 

---

build.gradle

Bumps JSON-Smart to version 2.4.10 to address https://github.com/advisories/GHSA-493p-pfq6-5258.
Bumps Spring-core to version 5.3.26 to address https://github.com/advisories/GHSA-564r-hj7v-mcr5.
Backports #2606

[Backport 2.x] Remediate CVE-2023-1370 and CVE-2023-20861 via version bumps

---

build.gradle

Bumps JSON-Smart to version 2.4.10 to address https://github.com/advisories/GHSA-493p-pfq6-5258.
Bumps Spring-core to version 5.3.26 to address https://github.com/advisories/GHSA-564r-hj7v-mcr5.
Backport of #2606 

[Backport 1.3] Remediate CVE-2023-1370 and CVE-2023-20861 via version bumps

---

src/integrationTest/java/org/opensearch/security/DlsIntegrationTests.java

Adds an integration test class for testing Dls specific workflows. This PR bases off of the Dls tests that were part of FlsDlsAndFieldMaskingTest.java. 
Backports #2585

[Backport 2.x] Expand Dls Tests for easier verification of functionality 

---

build.gradle

Bumps JSON-Smart to version 2.4.10 to address https://github.com/advisories/GHSA-493p-pfq6-5258.
Bumps Spring-core to version 5.3.26 to address https://github.com/advisories/GHSA-564r-hj7v-mcr5.
Backports https://github.com/opensearch-project/security/pull/2606

 [Backport 2.6] Remediate CVE-2023-1370 and CVE-2023-20861 via version bumps

---

build.gradle

Bumps JSON-Smart to version 2.4.10 to address https://github.com/advisories/GHSA-493p-pfq6-5258.
Bumps Spring-core to version 5.3.26 to address https://github.com/advisories/GHSA-564r-hj7v-mcr5.
Backport of #2606 

[Backport 1.x] Remediate CVE-2023-1370 and CVE-2023-20861 via version bumps 

---

src/integrationTest/java/org/opensearch/security/FlsAndFieldMaskingTests.java

Turned the FlsDlsAndFieldMaskingTest class into just FlsAndFieldMasking. This avoid duplication and makes it easier to track breaks. 

Remove DLS from FlsDlsAndFieldMasking to avoid duplicates

---

build.gradle
src/main/java/org/opensearch/security/authtoken/jwt/EncryptionDecryptionUtil.java
src/main/java/org/opensearch/security/authtoken/jwt/JwtVendor.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java

_*This idea is coming from @cwperks 's [comment](https://github.com/opensearch-project/security/pull/2567#discussion_r1153350018)*_
Including encrypted `roles` in JIT token as payload for privilege validation.
* Relate: #2573 
* Relate: https://github.com/opensearch-project/security/issues/2619

[Security/Extension] Role encryption/decryption

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsAction.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/AllowlistApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/NodesDnApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SslCertsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

Added config settings `plugins.security.restapi.admin.enabled` which enables/disables `:resapi` permissions.
Default is `false`
- Resolves https://github.com/opensearch-project/security/issues/2571

Separate config option to enable restapi: permissions

---

tools/install_demo_configuration.bat
tools/install_demo_configuration.sh

* Enhancement
* These changes are required to mark ppl/sql datasource metadata index as a system index.
* It is a new additon.
https://github.com/opensearch-project/sql/issues/1477
manual testing.

New system index[.ql-datasources] for ppl/sql datasource configurations

---

release-notes/opensearch-security.release-notes-2.6.0.0.md
release-notes/opensearch-security.release-notes-2.7.0.0.md

Add release notes for 2.7.0
Maintenance
* Relate https://github.com/opensearch-project/security/issues/2635

Add release notes for 2.7.0

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/support/GuardedSearchOperationWrapper.java
src/test/java/org/opensearch/security/support/GuardedSearchOperationWrapperTest.java

Backport of https://github.com/opensearch-project/security/pull/2687 to 1.x
This PR adds graceful error handling in a cache miss scenario where the error is swallowed. Additional tests have been added to verify the new functionality.
See associated unit tests added

[Backport 1.x] Fix NPE and add additional graceful error handling

---

build.gradle

Corrects CVE-2023-20863 by forcing spring-expression up to a corrected version. 

Corrects CVE-2023-20863 by forcing spring-expression version

---

src/integrationTest/java/org/opensearch/test/framework/matcher/AliasExistsMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/ClusterContainTemplateWithAliasMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/GetSettingsResponseContainsIndicesMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/IndexMappingIsEqualToMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/IndexStateIsEqualToMatcher.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java

Removes use of the ImmutableOpenMap from Security code to resolve issue #2714. 

Resolve ImmutableOpenMap issue from core refactor

---

src/integrationTest/java/org/opensearch/test/framework/matcher/AliasExistsMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/ClusterContainTemplateWithAliasMatcher.java
src/integrationTest/java/org/opensearch/test/framework/matcher/GetSettingsResponseContainsIndicesMatcher.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java

Addresses comments raised here: https://github.com/opensearch-project/security/pull/2715#discussion_r1177857146
There is a compilation error in AliasExistsMatcher and this fixes the issue.
Maintenance

Switch from ImmutableOpenMap to Map in AliasExistsMatcher

---

src/integrationTest/java/org/opensearch/test/framework/matcher/GetSettingsResponseContainsIndicesMatcher.java

Removes all ImmutableOpenMap references

---

config/roles.yml

update security-analytics roles to add correlation engine apis
* Category (Enhancement)

update security-analytics roles to add correlation engine apis

---

src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java

Change method to lookup extension based on unique id after change to access modifiers in ExtensionsManager: https://github.com/opensearch-project/OpenSearch/pull/7374
Maintenance

Use updated method to lookup extension by unique id

---

build.gradle

Upgrade spring-core from 5.3.26 to 5.3.27 to fix [CVE-2023-20863](https://spring.io/security/cve-2023-20863)
[CVE-2023-20863](https://spring.io/security/cve-2023-20863)

Upgrade spring-core from 5.3.26 to 5.3.27.

---

checkstyle/sun_checks.xml
src/integrationTest/java/org/opensearch/security/SnapshotSteps.java
src/integrationTest/java/org/opensearch/test/framework/certificate/CertificateMetadata.java
src/integrationTest/java/org/opensearch/test/framework/certificate/CertificatesIssuer.java
src/integrationTest/java/org/opensearch/test/framework/certificate/PublicKeyUsage.java
src/integrationTest/java/org/opensearch/test/framework/certificate/TestCertificates.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/configuration/DlsFilterLevelActionHandler.java
src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java
src/main/java/org/opensearch/security/ssl/util/CertificateValidator.java
src/main/java/org/opensearch/security/ssl/util/TLSUtil.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/main/java/org/opensearch/security/support/HeaderHelper.java
src/main/java/org/opensearch/security/tools/SecurityAdmin.java
src/main/java/org/opensearch/security/transport/OIDClusterRequestEvaluator.java
src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java

Extensions are a big part of what we are building into OpenSearch and Security.  While we need these features we should try to build them as generically as possible, this checkstyle scan will help enforce this and also allow for working around the term usage with comments as we do have places where extensions need to be treated differently.

Limit the use of extensions term in the codebase

---

src/main/java/org/opensearch/security/transport/SecurityRequestHandler.java

The current method being used to permit handshake requests from extensions is failing because an extension with the unique id is not present in the map of initialized extensions. Since the handshake is the first request performed to initialize an extension, the extension will not be available in the map of initialized extensions. This PR consumes a new method defined in core to get extension settings by unique id which checks to see if the extension unique id is present in the list of extensions in `extensions/extensions.yml`
Associated PR in core: https://github.com/opensearch-project/OpenSearch/pull/7466
Bug fix
https://github.com/opensearch-project/security/issues/2747
By submitting this …

Use ExtensionsManager.lookupExtensionSettingsById when verifying extension unique id

---

config/roles.yml

1. Add a new full access role for ppl so that sql plugin users can query with piped processing language.
2. Add a new role for cross-cluster search.
User docs for these roles([ppl security](https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/security.rst), [cross-cluster search](https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/cross_cluster_search.rst#authentication-and-permission))
https://github.com/opensearch-project/sql/issues/789
We predefine the roles for easier use of the new feature. …

Add default roles for SQL plugin: PPL and cross-cluster search

---

src/main/java/org/opensearch/security/support/HeaderHelper.java

**Description**
Category:  Performance Bug Fix
**Why these changes are required?**
`HeaderHelper.deserializeSafeFromHeader` is invoked O(segment) times during every search request and introduced a huge overhead. This optimisation has resulted in good gains with respect to search throughput and latency in our experiments.
**Issues Resolved**
* Resolves #2757 
* Current test suite should pass.

`deserializeSafeFromHeader` uses `context.getHeader(headerName)` instead of `context.getHeaders()`

---

build.gradle

Backport https://github.com/opensearch-project/security/commit/54d47ab181c4c782af37c96521238f7dbaf50cb2 from https://github.com/opensearch-project/security/pull/2717

[Backport 2.x] Upgrade spring-core from 5.3.26 to 5.3.27

---

build.gradle
src/integrationTest/java/org/opensearch/security/SecurityConfigurationTests.java
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/validation/AbstractConfigurationValidator.java
src/main/java/org/opensearch/security/dlic/rest/validation/CredentialsValidator.java
src/main/java/org/opensearch/security/dlic/rest/validation/PasswordValidator.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/auditlog/compliance/RestApiComplianceAuditlogTest.java
src/test/java/org/opensearch/security/dlic/rest/api/AbstractRestApiUnitTest.java
src/test/java/org/opensearch/security/dlic/rest/api/AccountApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
src/test/java/org/opensearch/security/dlic/rest/validation/PasswordValidatorTest.java

The aim of this PR is to add support for a score-based password verification using  `zxcvbn` library.
For that 2 new settings were added to the plugin configuration:
- `plugins.security.restapi.password_min_length` - minimum password length, default and minimum is `8` 
- `plugins.security.restapi.password_score_based_validation_strength` - the strength of the valid password
Possible values:
- `fair` - very guessable password: protection from throttled online attacks
- `good` - somewhat guessable password: protection from unthrottled online attacks
- `strong` - safely unguessable password: moderate protection from offline slow-hash scenario
- `very_strong` - very unguessable password: strong protection from offline slow-hash scenario
By default the plugin always checks strength of the …

Add score based password verification

---

src/integrationTest/java/org/opensearch/security/SecurityConfigurationTests.java
src/integrationTest/resources/config.yml
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModel.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV6.java
src/main/java/org/opensearch/security/securityconf/DynamicConfigModelV7.java
src/main/java/org/opensearch/security/securityconf/impl/v6/ConfigV6.java
src/main/java/org/opensearch/security/securityconf/impl/v7/ConfigV7.java
src/test/java/org/opensearch/security/authtoken/jwt/JwtVendorTest.java
src/test/resources/config.yml
src/test/resources/restapi/securityconfig.json
src/test/resources/restapi/securityconfig_nondefault.json

Rename the term 'extension' into 'on_behalf_of'.
Bug fix
* Resolve https://github.com/opensearch-project/security/issues/2760
* Relate https://github.com/opensearch-project/security/pull/2671
* Relate https://github.com/opensearch-project/security/pull/2567

[Feature/Extension] Rename the term 'extension' into 'on_behalf_of'

---

release-notes/opensearch-security.release-notes-1.3.10.0.md

Add release notes for 1.3.10
Maintenance

Add release notes for 1.3.10

---

build.gradle
src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/validation/AbstractConfigurationValidator.java
src/main/java/org/opensearch/security/dlic/rest/validation/CredentialsValidator.java
src/main/java/org/opensearch/security/dlic/rest/validation/PasswordValidator.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/auditlog/compliance/RestApiComplianceAuditlogTest.java
src/test/java/org/opensearch/security/dlic/rest/api/AbstractRestApiUnitTest.java
src/test/java/org/opensearch/security/dlic/rest/api/AccountApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java
src/test/java/org/opensearch/security/dlic/rest/validation/PasswordValidatorTest.java

Backport 15860b65f33861f875b62ed57b6d8b7ab3c8a65d from https://github.com/opensearch-project/security/pull/2557

[Backport 2.x] Add score based password verification

---

tools/install_demo_configuration.sh

* Category (Enhancement)
We are going to add model group in 2.8.
Old: we don't have model group, user just create model
New: user need to create model in a model group, and we will use model group to control access.
Related issue: https://github.com/opensearch-project/ml-commons/issues/815
For more information on following Developer Certificate of Origin and signing off …

add ml model group system index

---

config/roles.yml

In **2.8**, index-management will have a new feature of sending notifications for long-running index operations(https://github.com/opensearch-project/OpenSearch/issues/5479). And to build this feature, index-management plugin introduce 3 new backend API(https://github.com/opensearch-project/index-management/issues/700). We want to add cluster permissions of these APIs to existing `index_management_full_access` role. It will also include list notification channels cluster permission.
https://github.com/opensearch-project/OpenSearch/issues/5479
https://github.com/opensearch-project/index-management/issues/700
https://github.com/opensearch-project/index-management/issues/703
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/618 …

Changes in role.yml for long-running operation notification feature in Index-Management repo

---

build.gradle

Removes the dependency on `jakarta.annotation` an implementation of `javax.annotation`, as OpenSearch now itself takes a dependency on an implementation of `javax.annotation`.
* Why these changes are required? OpenSearch now has a dependency on an implementation of `javax.annotation` causing a JAR hell error when installing the plugin.
* What is the old behavior before changes and new behavior after changes? install failed previously, now succeeds.
Also requires backporting to 2.x
Resolves #2799
Manual testing of repro steps in #2799 but using local build of plugin rather than published snapshot.
For more information on following Developer Certificate of …

Remove dependency on javax.annotation implementation as OpenSearch now has one.

---

src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticator.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/JwtVerifier.java
src/main/java/com/amazon/dlic/auth/http/jwt/keybyoidc/KeySetRetriever.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/HTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/MockIpdServer.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/SingleKeyHTTPJwtKeyByOpenIdConnectAuthenticatorTest.java
src/test/java/com/amazon/dlic/auth/http/jwt/keybyoidc/TestJwts.java

Re-creating https://github.com/opensearch-project/security/pull/2708 with the jar hell fix merged into main and addressing 2 minor comments from the PR. 
Extending auth with jwks_uri parameter to omit passing openid_connect_url with openid-configuration
* Category: feature
* Why these changes are required?  To add possibility to define a JWKS endpoint for JWT-based authentication
* What is the old behavior before changes and new behavior after changes? Old behavior remains the same, new one omits the part with calling openid-configuration endpoint of IdP
https://github.com/opensearch-project/security/issues/1858
For more information on following Developer Certificate of …

[FEATURE] usage of JWKS with JWT (w/o OpenID connect)

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsAction.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/AllowlistApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/NodesDnApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SslCertsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

[Backport 2.x] Separate config option to enable restapi: permissions (#2605)

---

src/main/java/org/opensearch/security/OpenSearchSecurityPlugin.java
src/main/java/org/opensearch/security/dlic/rest/api/AbstractApiAction.java
src/main/java/org/opensearch/security/dlic/rest/api/RestApiAdminPrivilegesEvaluator.java
src/main/java/org/opensearch/security/dlic/rest/api/SecuritySSLCertsAction.java
src/main/java/org/opensearch/security/support/ConfigConstants.java
src/test/java/org/opensearch/security/dlic/rest/api/ActionGroupsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/AllowlistApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/NodesDnApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/RolesMappingApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/SslCertsApiTest.java
src/test/java/org/opensearch/security/dlic/rest/api/UserApiTest.java

[Backport 2.8] Separate config option to enable restapi: permissions (#2605)

---

build.gradle

Re-adds jakarta dependency that was removed due to stale artifact issue with CI for 2.8 branch.
Category: Maintenance

Re-adds jakarta dep that was removed due to stale artifact issue with CI

---

build.gradle

Currently `./gradlew assemble` is failing for the security plugin due to the addition of `zstd-jni` in core which the security plugin already has a runtime dependency on. This PR uses the version from core's version.properties to ensure there is a matching version.
Related PR: https://github.com/opensearch-project/OpenSearch/pull/2996
`./gradlew assemble` is failing with the following error:
```
Execution failed for task ':bundlePlugin'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
> Conflict(s) found for the following module(s):
- com.github.luben:zstd-jni between versions 1.5.5-3 and ${versions.zstd}
Run with:
--scan or
:dependencyInsight --configuration runtimeClasspath --dependency com.github.luben:zstd-jni
to get more insight on how to solve the …
```

Match version of zstd-jni from core

---

build.gradle
src/test/java/org/opensearch/security/multitenancy/test/MultitenancyTests.java
src/test/java/org/opensearch/security/multitenancy/test/TenancyMultitenancyEnabledTests.java
src/test/java/org/opensearch/security/multitenancy/test/TenancyPrivateTenantEnabledTests.java

Follows #2823
Updates all java files under security/auth to security/filter.

Updates all java files under security/* and test/security/a* -> test/security/m*

---

build.gradle
src/test/java/org/opensearch/security/sanity/tests/SecurityRestTestCase.java
src/test/java/org/opensearch/security/sanity/tests/SingleClusterSanityIT.java
src/test/java/org/opensearch/security/securityconf/SecurityRolesPermissionsTest.java
src/test/java/org/opensearch/security/securityconf/impl/v7/IndexPatternTests.java
src/test/java/org/opensearch/security/ssl/CertificateValidatorTest.java
src/test/java/org/opensearch/security/ssl/OpenSSLTest.java
src/test/java/org/opensearch/security/ssl/SSLTest.java
src/test/java/org/opensearch/security/ssl/SecureSSLSettingsTest.java
src/test/java/org/opensearch/security/ssl/SecuritySSLReloadCertsActionTests.java
src/test/java/org/opensearch/security/ssl/TestPrincipalExtractor.java
src/test/java/org/opensearch/security/ssl/transport/DualModeSSLHandlerTests.java
src/test/java/org/opensearch/security/ssl/util/CertFromFileTests.java
src/test/java/org/opensearch/security/ssl/util/CertFromKeystoreTests.java
src/test/java/org/opensearch/security/ssl/util/CertFromTruststoreTests.java
src/test/java/org/opensearch/security/ssl/util/SSLConnectionTestUtilTests.java
src/test/java/org/opensearch/security/ssl/util/TLSUtilTests.java
src/test/java/org/opensearch/security/support/GuardedSearchOperationWrapperTest.java
src/test/java/org/opensearch/security/support/SecurityUtilsTest.java
src/test/java/org/opensearch/security/system_indices/SystemIndicesTests.java

Updates all the *.java files under `**/test/security/`

Update test/security/s* java files

---

.github/workflows/plugin_install.yml
build.gradle
bwc-test/build.gradle

Backport #2832 to 2.x
Depends on https://github.com/opensearch-project/OpenSearch/pull/7906

[Backport 2.x] Match version of zstd-jni from core

---

src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationTests.java

Changes an assertion in `JwtAuthenticationTests.shouldAuthenticateWithJwtToken_positive` that was not testing the code correctly. It was checking if a variable was equal to itself instead of the actual expected value.
Test fix
```
./gradlew integrationTest --tests JwtAuthenticationTests -i
```

Fix JwtAuthenticationTests.shouldAuthenticateWithJwtToken_positive assertion

---

.github/CODEOWNERS
MAINTAINERS.md

* Add Andrey to Maintainers
- Backports #2843

[Backport 1.3] Add Andrey Pleskach (Willyborankin) to Maintainers (#2843)

---

.github/CODEOWNERS
MAINTAINERS.md

* Add Andrey to Maintainers
- Backports #2843

[Backport 2.x] Add Andrey Pleskach (Willyborankin) to Maintainers (#2843)

---

config/roles.yml

Enhancement
ML-commons has a new index "model group" added in 2.8 release. This PR adds the search model group permission to the "ml_read_access" role.
We want a user with "ml_read_access" role to be able to search the model group index.  Before this change, user is not given that permission which is contrary to the expected behaviour. 
This change allows any user with "ml_read_access" role to search the model group index.
[Please provide details of testing done: unit testing, …

add search model group permission to ml_read_access role

---

build.gradle

This mirrors the changes in main (#2717) and 2.x (#2763). The backport workflow was not used because there have been major changes to the build file between 1.x and 2.x
N/A
N/A

Bumping spring-core and spring-expression from 5.3.26 to 5.3.28 to patch CVE vulnerabilities

---

build.gradle

Manual backport to 1.3 as the auto-backport in #2870 failed
Bump spring-core to 5.3.28
Also bumping spring-expression to 5.3.28

[Backport 1.3] Bumping spring-core from 5.3.26 to 5.3.27 to patch CVE vulnerabilities

---

src/main/java/org/opensearch/security/support/PemKeyReader.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java

Use BouncyCastle PEMReader instead of
regular expression to read and parse private key pem files.

Use boucycastle PEM reader instead of reg expression

---

src/main/java/com/amazon/opendistroforelasticsearch/security/resolver/IndexResolverReplacer.java
src/test/java/com/amazon/opendistroforelasticsearch/security/IndexTemplateClusterPermissionsCheckTest.java
src/test/java/com/amazon/opendistroforelasticsearch/security/test/helper/rest/RestHelper.java
src/test/resources/internal_users.yml
src/test/resources/roles.yml

One of the [PRs into opendistro-1.13](https://github.com/opensearch-project/security/commit/0b772a8089160372db1abfc4056f0fd18b318f11) introduced imports to org.opensearch which does not exist on the branch. This PR replaces the imports with their respective classnames in elasticsearch or the correct package name for opendistro-1.13
Tested by running `mvn compile`.

[opendistro-1.13] Fix compilation errors on opendistro-1.13

---

src/main/java/org/opensearch/security/support/PemKeyReader.java
src/test/java/com/amazon/dlic/auth/http/saml/HTTPSamlAuthenticatorTest.java

Backpor 3c9f7c298e35ea94250c921e2c65f5682b63fe80 from #2864

[Backport 2.x] Use boucycastle PEM reader instead of reg expression (#2864) 

---

src/test/java/org/opensearch/security/dlic/dlsfls/FlsFlatTests.java
src/test/resources/dlsfls/roles_fls_flat.yml

Making sure that FLS rules are tested on flattened fields, following the index fls test format
- Related https://github.com/opensearch-project/OpenSearch/issues/1018

Adding field level security test cases for FlatFields

---

build.gradle

Upgrades snappt to 1.1.10.1 and guava to 32.0.1-jre
Maintenance
- https://github.com/opensearch-project/security/issues/2885
- https://github.com/opensearch-project/security/issues/2882
- https://github.com/opensearch-project/security/issues/2884
- https://github.com/opensearch-project/security/issues/2883

Update snappy to 1.1.10.1 and guava to 32.0.1-jre

---

build.gradle

[Backport 2.x] Update snappy to 1.1.10.1 and guava to 32.0.1-jre (#2886)

---

.github/workflows/code-hygiene.yml
.gitignore
check-permissions-order.js
config/roles.yml
src/integrationTest/resources/roles.yml
src/main/resources/static_config/static_roles.yml
src/test/java/org/opensearch/security/dlic/rest/api/RoleBasedAccessTest.java
src/test/java/org/opensearch/security/test/helper/rest/RestHelper.java
src/test/resources/cache/roles.yml
src/test/resources/multitenancy/roles.yml
src/test/resources/restapi/roles.yml
src/test/resources/roles.yml
src/test/resources/roles_bs.yml
src/test/resources/roles_bulk.yml
src/test/resources/roles_ccs.yml
src/test/resources/security_passive/roles.yml

Adds a NodeJS tool that can inspect yaml role definitions, check if they are in alphabetical order, correct them if required.  Seems pretty useful to prevent manual inspection of changes to the roles definitions, but curious what other folks think.
- Related #2732

Role permissions order tool and workflow

---

src/main/java/org/opensearch/security/configuration/ClusterInfoHolder.java
src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java

Backport #2715 , #2725 , #2726 to 2.x

[Backport 2.x] Resolve ImmutableOpenMap issue from core refactor

---

src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java
src/test/java/org/opensearch/security/privileges/PrivilegesEvaluatorTest.java
src/test/java/org/opensearch/security/privileges/PrivilegesEvaluatorUnitTest.java

Changes classification of 'indices:data/read/msearch/template' to be a cluster permission instead of an index permission. It seems that this should have the same classification as  'indices:data/read/msearch', since it is a msearch but just with a template.
https://github.com/opensearch-project/OpenSearch/blob/63dc6aa795f8ec78597c7f93e732b979b6963d8f/modules/lang-mustache/src/main/java/org/opensearch/script/mustache/MultiSearchTemplateAction.java#L40
For more information on …

fix cluster perm classification for msearch template

---

.github/workflows/ci.yml
build.gradle

Currently "build" job in Github Actions runs for around 60-80 minutes on average. Long time for tests to be done can slow down development process. Easiest way to make this situation little better is to split tests into separate task and reconfigure Github Actions to run tests in parallel. This change allows to cut run of CI from 60-80 minutes to around 28-30 minutes.
We've determined which tests run are the longest and moved them into separate tasks (defined in `build.gradle` file). We do not want to break test on Developers side so running `gradle test` command would run full test suite (`test` task depends on new ones). This also allows new test to be added run automatically.
#2798 
There's no changes in test themselves.
By submitting this pull request, I confirm that my contribution …

[Enhancement] Parallel test jobs for CI

---

build.gradle
plugin-security.policy
src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java

Bump BouncyCastle to jdk15to18on since jsk15on is not supported anymore. I'm waiting for https://github.com/opensearch-project/OpenSearch/pull/8247 in OpenSearch to move forward with it.
https://github.com/opensearch-project/security/issues/2888

Bump BouncyCastle from jdk15on to jdk15to18

---

build.gradle
plugin-security.policy
src/main/java/org/opensearch/security/ssl/DefaultSecurityKeyStore.java

Backport 9a72355cbf37972ce1b9d12918e2a3e7c5023d80 from #2901

[Backport 2.x] Bump BouncyCastle from jdk15on to jdk15to18 (#2901)

---

build.gradle

Resolve any possible issues related to CVE-2023-2976 by forcing use of Guava 32.0.1

Resolve CVE-2023-2976 by forcing use of Guava 32.0.1
